### ISSUE TITLE
autoscroll is pernickety

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1014]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 06, 2010 02:22:14_

autoscroll doesn't always kick in smoothly, sometimes you have to keep 
wiggling the mouse to keep autoscroll going.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1014_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
