### ISSUE TITLE
Advanced preferences dialog

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1020]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 09, 2010 13:27:38_

The number of useful program settings are growing (and meandering into the 
menus), so it would be good to make the central preferences dialog more 
convenient and collect all the settings.

UI-wise, it seems to be modern to have a list of topics in a left column 
and then the related settings on the right. Examples can be found in:
- Qt Creator: Extras > Settings
- Eclipse: Window > Preferences
  I'm not a big fan of this UI, but neither do I know a better one.

Is there any good Qt support for this? Maybe the code from Qt Creator can 
be learned from.

For the exact settings that are needed, I will come up with a scheme.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1020_

**Comment by failiz** [comment]
There is a preferences menu for the general preferences and the grid size can be changed independently for each view in the view menu. From the discussion above, this suggestion seems controversial.

**Comment by KjellMorgenstern** [comment]
I think there is no point in 'banning' all settings into the preferences dialog. Each setting can have a different scope. Some are highly local, like the compression factor to use for exporting png images. Some are project wise. And some global, like the UI language. I think the UI should reflect
this scope.

We have the preferences dialog, new settings should always be challenged for their need, proper location and default values. Existing ones can be challenged, too.
