### ISSUE TITLE
enable rotation when dragging a part from a bin

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1024]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 22, 2010 13:45:12_

use a modifier key

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1024_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
