### ISSUE TITLE
Images with indexed color tables break the website

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1031]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 29, 2010 04:56:16_

What steps will reproduce the problem? 1. Create an image with an indexed color table (a png or a gif)
2. Upload it to a project description
3. Try to the view the project page What is the expected output? What do you see instead? The site throws up, showing the error message "cannot filter palette images".
The reason is that the PIL (Python Image Library) tries to scale the image 
using a smoothen filter. This filter however does not support this type of 
images.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1031_

**Comment by failiz** [comment]
Is this outdated? I did not try it, but this is the old website. Are we using the PIL (Python Image Library)?
