### ISSUE TITLE
Translate the website

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1040]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 06, 2010 12:34:26_

We might want to apply for some grant eventually to pay for translation of 
our website to German, and maybe French and Spanish as well.
In the meantime, we could also add a link to a Google translation of it, like 
this: http://translate.google.de/translate?js=y&prev=_t&hl=en&ie=UTF- 8&layout=1&eotf=1&u=http://fritzing.org&sl=en&tl=de

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1040_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
