### ISSUE TITLE
Document our python scripts et al. on the website

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1045]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 09, 2010 06:33:47_

We've got a lot of powerful scripts now that people might find useful, which 
should be documented somewher on our site.
This could also be a place to include the ECI script from our Columbian 
contributors.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1045_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
