### ISSUE TITLE
On loading a sketch file, ignore the stored connection location

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1046]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 09, 2010 06:46:02_
- instead, use the semantic knowledge about the connection of parts to snap 
  them into place. What steps will reproduce the problem? 1. Modify a part's breadboard graphic so that it's connector locations are 
  moved, e.g. shorten the legs of the LED.
- Load a previously stored sketch, e.g. the Blink example What is the expected output? What do you see instead? The part seems to be disconnected, but they aren't. Once you move e.g. the 
  breadboard that the LED is connected to, it automatically snaps back.

This makes the modifcation of part graphics a big usability problem!

So if we ignored the physical location of connected connectors and just let 
them snap into place, we could alter the graphics at any time.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1046_

**Comment by KjellMorgenstern** [comment]
Outdated. Use the obsoletion mechanism: The part should marked with replacedby pointing to the modified part.
