### ISSUE TITLE
Category can't be null

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1059]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 25, 2010 07:56:22_

The project upload will result in an error if the user hasn't selected a 
category. 
It is not marked as a required field, and aynway shouldn't be.

It's particularly bad because when you go back to select a category, some of 
the edited fields (files and links) have been reset. :(

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1059_

**Comment by failiz** [comment]
Outdated?
