### ISSUE TITLE
dragging a part with the shift-key down doesn't seem to find any detents

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1080]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 25, 2010 11:47:05_

Connect some parts with wires and try dragging the parts with the shift-key 
down.  Notice that wires connected to the parts don't stay at 90 or 45 degree 
angles.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1080_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
