### ISSUE TITLE
core parts still using obsolete svgs?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1104]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 11, 2010 02:37:31_

This is not an exhaustive list:

all Generic female header parts use parts/svg/obsolete/icon/generic_female_header.svg

lm358.fzp:           parts/svg/obsolete/pcb/DIP8N.svg
optocoupler.fzp:     parts/svg/obsolete/pcb/DIP6N.svg
555timer.fzp:        parts/svg/obsolete/pcb/DIP8N.svg
74HC595.fzp:         parts/svg/obsolete/pcb/DIP16N.svg
atmega168.fzp:       parts/svg/obsolete/pcb/DIP28N.svg
h-bridge.fzp:        parts/svg/obsolete/pcb/DIP16N.svg

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1104_

**Comment by failiz** [comment]
I think this is outdated. For example, the part lm358.fzp uses pcb/dip_8_300mil_pcb.svg
I could not find the word "obsolete" in any of the part files (except in the obsolete ones).
