### ISSUE TITLE
mac: undocked dockwidgets obscure dialogs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1105]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 11, 2010 04:39:29_

On the mac: undocked dock widgets appear on top of windowmodal dialogs (like the 'do you want to save' dialog). 

The same problem is described in comment 2 of issue #1093 The fix is either to modify the changeActivation mechanism to hide the undocked dock windows, or to put a wrapper around each dialog call.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1105_

**Comment by failiz** [comment]
Is this outdated?
