### ISSUE TITLE
1.0 roadmap?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1122]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 15, 2010 04:31:41_

This is maybe not the right venue, but here's my opinion, items not necessarily in order:

-- double-sided boards
-- SMDs
-- tight view synchronization
-- gEDA/Kicad export
-- new autorouter
-- revised parts editor
-- part sharing (web and/or app-based)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1122_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
