### ISSUE TITLE
when saving, first save to a temporary file, then copy to the real destination

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1133]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 18, 2010 02:12:02_

in case of a crash during save, less likely to delete the original

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1133_

**Comment by failiz** [comment]
If this still valid? Are there any bugs related to the save process?

**Comment by KjellMorgenstern** [comment]
Important enough to review this, although the issue is quite old

**Comment by KjellMorgenstern** [comment]
This was already implemented, but hidden by bugs.
See commits 975b67cf7 to 491c8d031 for improvements in error detection.
See commit abe60fe6c for a the fix of the most severe bug: The file was overwritten anyways, so temp file and copy to destination was not effective in preventing errors.
