### ISSUE TITLE
autosave: instead of saving the whole file at intervals, save each undo command as it is executed

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1134]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 18, 2010 02:32:19_

In other words, save a representation of each undo stack command.  As you undo and redo, the file would be updated.  

Some of the more complex nested undo commands might be tricky to save. 

The advantages would be that a recovery would take you right back to the last command, that an incremental save would hardly be noticeable, prefs would be unnecessary, and the undo stack would be recovered as well.  

It might also be possible to make the whole undo stack file-based from the get-go, which could reduce RAM usage.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1134_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
