### ISSUE TITLE
Side-scrolling using a 2D mousewheel only does regular vertical scroll action

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1139]
_From [bryant.m...@gmail.com](https://code.google.com/u/100278494353872040962/) on June 21, 2010 13:58:28_

I have the Logitech G5 mouse. It has a 2D scroll wheel that can provide vertical and horizontal scrolling. Horizontal scrolling with this mouse doesn't work, and worse does regular scrolling instead of just nothing.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1139_

**Comment by rraallvv** [comment]
Using the 'Guess' or 'Pure' options for wheel behavior works well for two-finger drag (horizontal/vertical scroll) and pinch-to-zoom on a trackpad in macOS Monterey. I'm not sure why neither of these is the default setting in Fritzing (1.0.3).

**Comment by KjellMorgenstern** [comment]
Was this a first time install, or did you already have an older version of Fritzing installed before?

I added the 'Guess' and 'Pure' options in Version 1.0.0, so it is a relatively new feature, and after there were no severe issues, we made it a default on 1.0.2 or 1.0.3, but not overriding old settings. (if I remember correct, it might as well still be an open ticket somewhere.)

**Comment by rraallvv** [comment]
Thanks, @KjellMorgenstern. The install wasn't clean, but I'm glad to hear it will be the default setting.
