### ISSUE TITLE
Add functional testing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1140]
_From [bryant.m...@gmail.com](https://code.google.com/u/100278494353872040962/) on June 22, 2010 12:17:33_

We should have functional testing. Looks like QTestLib could work: http://doc.qt.nokia.com/4.6/qtestlib-manual.html

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1140_

**Comment by failiz** [comment]
Outdated?
