### ISSUE TITLE
Add support for touch events on Mac

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1146]
_From [bryant.m...@gmail.com](https://code.google.com/u/100278494353872040962/) on June 27, 2010 18:34:15_

Mac users have become used to touch events when using applications. I suggest this support be extended to Fritzing:

2-finger swipe vertical: move along Y-axis
2-finger swipe horizontal: move along X-axis
2-finger rotate: rotate an element in 45deg steps
2-finger pinch/unpinch: zoom in/out by a reasonable stepping, probably the same as used by the -/+ buttons next to the zoom slider

3-finger swipe (either horizontal or vertical or both): switch views

Right now the 2 finger swipe is being interpreted as a scroll and I'm not certain if that can be changed. This conflicts with the prefs setting for the scrollwheel.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1146_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to inactivity.
If you think this issue is still important for a reason, please open.
