### ISSUE TITLE
resistance/capacitance unit formatting preference

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1147]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 28, 2010 13:20:55_
- Resistors have values 4.7kohm where some prefer 4K7 etc
- Capacitors have values 0.1uF where some prefer 100nF etc

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1147_

**Comment by failiz** [comment]
Is this worth it?

**Comment by KjellMorgenstern** [comment]
For future reference, lets see if we can at least recommend a formatting for Fritzing.

My suggestion:
For anything targeted for the screen or paper or high resolution use UTF-8 for units. No "uF" or "kohm" , use µ and kΩ 
Use  0.1µF 

For anything target at really low resolution / tiny letters use 4K7 , 100nF  , ascii without dots

**Comment by failiz** [comment]
What would be a case for the low resolution?
I do not think we are forcing any standard. Resistance and capacitance values are not changed after the user introduces them. 
In the simulator branch, I always the same format for the capacitance if the value introduced is out of range. If so, the code puts it in range and transforms it into the standard by calling convertToPowerPrefix. However, if the value is valid, it is not changed. 
I think we should not confuse users and keep the introduced value (except if it is not valid).
