### ISSUE TITLE
syntax highlighting: highlight numbers, handle escape-string-delimiter in strings

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1158]
_From [bryant.m...@gmail.com](https://code.google.com/u/100278494353872040962/) on June 30, 2010 07:54:13_

Highlighting of languages isn't fully correct as of now.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1158_

**Comment by failiz** [comment]
It seems that the numbers are not highlighted and the single quotation marks either. See below:
![image](https://user-images.githubusercontent.com/5708642/149621193-ec26e1ed-2d0e-47b8-a238-beacdc5394f7.png)

**Comment by KjellMorgenstern** [comment]
Added matcher for float, decimal, octal, binary and char expressions
