### ISSUE TITLE
Pin Spacing does not work in breadboard view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1178]
_From [ad...@gummelgammel.de](https://code.google.com/u/111756886814166955693/) on July 12, 2010 17:58:58_

What steps will reproduce the problem? 1. Create a resistor
2. Change its pin spacing (beinabstand)
3. It won't do anything What is the expected output? What do you see instead? The pinspacing of the resistor in the breadboard view should change What version of the product are you using? On what operating system? 0.4.0(b4318) On Linux ubuntu lucid Please provide any additional information below. please fix this ;) This is a very important problem

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1178_

**Comment by ao2** [comment]
Hi, while it's true that legs can be stretched, the pin spacing option in the Inspector view has still no effect in Breadboard View.

In particular it is not possible to place the resistors standing up, or with very short leads.

My use case is to place a resistor diagonally to span only 3 horizontal pins and 3 vertical pins.
Should I open a new issue?

**Comment by ao2** [comment]
Ah, a workaround I found is to use the "resistor mini" part from http://forum.fritzing.org/t/300-mil-resistor-does-anyone-have-please/3344/5 and stretch the legs.
