### ISSUE TITLE
inkscape transforms and xml splitting

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1184]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 19, 2010 14:05:08_

If an inkscape image for pcb view has top level transforms, and we split the file at the <g id="layer"> element, then those transforms won't make it into the split xml image, and the subelements won't be offset correctly.

So it means when splitting files we should back up the tree from the <g id="layer"> element, collect the transforms, and apply them.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1184_

**Comment by KjellMorgenstern** [comment]
Information is not available anymore. There is still a problem with svg viewBoxes that don't use (0,0) as origin. Top level transforms however are taken into account in v0.9.10
