### ISSUE TITLE
crossview drag and drop issues

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1185]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 20, 2010 04:28:41_

-- weird placement if you drag parts from view A in window 1 into view B in window 2 (if A != B).

-- labels aren't situated correctly

-- it's not clear whether cross-view drag and drop should be a move or a copy.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1185_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
