### ISSUE TITLE
Jumper pads end up a bit too close to the pads sometimes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1192]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 21, 2010 08:11:28_

From Brendan: Jumper pads end up a bit too close to the pads sometimes or too close inside the part bounds.  This is a really nasty problem to solve.  Nothing to worry about for this version but we might want to warn people in the docs and think about some kind of reasonable solution.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1192_

**Comment by failiz** [comment]
Is this still relevant? I think jumper pads have been depreciated. If not, how do you have them?
