### ISSUE TITLE
0 ohm resistor connectors should have a bus

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1199]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 26, 2010 16:24:24_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1199_

**Comment by failiz** [comment]
I am not sure if this is the right approach. A 0ohm resistor should still work as a resistor. Usually, you use them to join two ground planes (for example to have different analogical/digital ground). Thus, the bus approach will merge the two grounds in the same net.

**Comment by failiz** [comment]
Remove imported label

**Comment by KjellMorgenstern** [comment]
So, we have one argument against doing this, and zero to do it. Seems like closing this?

**Comment by failiz** [comment]
I am up for closing this. In addition, the bus option would mean to code a if(resistance ==0) then use a special resistor with a bus. I think it is cleaner the current approach, whee the only thing modified is the resistance.
In the simulator, all 0 ohm resistors are treated as 0.001 ohm resistors. It should not make a huge difference in the output for most common circuits.
