### ISSUE TITLE
add -h option to fritzing to list the current command line options

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1209]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 06, 2010 06:29:28_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1209_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
