### ISSUE TITLE
enable "add bendpoint" on right-click menu for ratsnest wires

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1215]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 14, 2010 13:37:37_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1215_

**Comment by failiz** [comment]
I think that add bendpoints to ratsnets is not a good idea and the link with the info is done
