### ISSUE TITLE
Jumper wires causing fritzing to crash?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1216]
_From [martin.e...@gmail.com](https://code.google.com/u/102040676821115196041/) on August 17, 2010 12:05:42_

What steps will reproduce the problem? 1. Create your usual project with some wires and some things
2. Autoroute a lot of times (Hey, I'm indecisive :P)
3. Save and close.
4. Open
5. Try to change something. What is the expected output? What do you see instead? The application crashes. What version of the product are you using? On what operating system? Fritzing 0.4.2 on Mac OS X 10.5.8 Please provide any additional information below. Opening the file in a text editor reveals a huge amount of wires, that doesn't show up in the application. Deleting them fixes the problem, but the chance of deleting the wires you actually want is high.
I have attached the error report from OS X and the file.

**Attachment:** [error.txt LED-remote-permanent repair.fz](http://code.google.com/p/fritzing/issues/detail?id=1216)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1216_

**Comment by failiz** [comment]
The files are not available and the jumper wires are gone. I could not reproduce the issue with the steps of the first message.
