### ISSUE TITLE
gerbview problem with integers?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1219]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 05, 2010 12:54:19_

From the forum: http://fritzing.org/forum/thread/309/?page=all#post1245 .

"i had a problem with a drill file that wouldn't load in gerbview.  i discovered that drill locations at exactly 1 and 2 inches from the edge of the board were printed in the drill file as integers.

"i editted the file to change occurences of things like "X1Y" to "X1.0Y" and things like "Y2$" to "Y2.0".  (dollar sign represents end-of-line in a regular expression.)"

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1219_

**Comment by failiz** [comment]
Very old issue which can cause problems when manufacturing. As there are no more complaints since 2010, I would say that this has been fixed. @KjellMorgenstern or have you seen issues?
