### ISSUE TITLE
convert transitive closure and other graph theory functions to boost

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1224]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 08, 2010 02:26:00_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1224_

**Comment by failiz** [comment]
Is this still valid? It was set to partly done, but no idea what's missing out what code is related to this
