### ISSUE TITLE
QtCreator is now using Kate-based syntax highlighting.  Can we borrow the code for the programming window?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1228]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 19, 2010 03:35:01_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1228_

**Comment by failiz** [comment]
This issue was created 10 years ago.
 Is it still in the pipeline? Sounds like to much work for something that we already have implemented.
