### ISSUE TITLE
drag icon from parts bin list view is wrong when bin is scrolled

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1240]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 29, 2010 10:16:35_

change parts bin to list view.  Drag a part from the bin; the icon attached to the drag cursor is the entry itself.  If you scroll down a couple of steps and drag one of the newly visible parts, the drag icon is empty.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1240_

**Comment by KjellMorgenstern** [comment]
Can not reproduce this, but something similar, see #3929
