### ISSUE TITLE
icon attached to cursor when dragging from parts bin is kinda funky

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1242]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 29, 2010 15:19:10_

In icon view, under mac and pc, a dashed square is attached to the drag cursor; under linux the attached image doesn't seem to have transparency, so (just recently) no image is attached.  In list view, the actual list item is attached. 

When the cursor is over a sketch widget, then the actual part is dragged along with the cursor.

Anyway, maybe we should rethink this...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1242_

**Comment by failiz** [comment]
I cannot see the dashed square which attached to the drag cursor in 0.9.4 (Windows). outdated?

**Comment by KjellMorgenstern** [comment]
Seems this was already fixed in 2011 with r5271 (svn repo on google code)
