### ISSUE TITLE
smd parts not highlighting in pcb view when board is single sided

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1244]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 30, 2010 06:38:37_

swap a through-hole part for an smd part in pcb view; it doesn't highlight when you roll over it with the mouse, and the connectors don't respond to clicks

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1244_

**Comment by failiz** [comment]
No reproducible in 0.9.6
