### ISSUE TITLE
Go through all the design specs in our wiki and turn the undone ones into issues

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1247]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on October 01, 2010 06:54:41_

There's a couple of nice ones from Johannes that are covered by some dust.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1247_

**Comment by failiz** [comment]
Do we have design specs in our wiki? Or is this an outdated issue?

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
I think this is outdated, and unspecifc. Fritzings design? Part design? Coding style? -> Closing
