### ISSUE TITLE
Part not appearing in SVG export

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1252]
_From [mrichard...@gmail.com](https://code.google.com/u/109967616069135434926/) on October 04, 2010 20:23:18_
1. Open a new file.
2. Drop the part Infrared proximity sensor into breadboard view
3. File... Export... to SVG...
4. View the file in SVG application

You should see the Infrared proximity sensor in the SVG file, but nothing appears.  Other parts do appear, however.

Fritzing 0.4.2 on Mac OS X Snow Leopard.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1252_

**Comment by bartgrefte** [comment]
> 
> 
> _From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 04, 2010 22:05:11_
> 
> The breadboard svg for this part was missing a <g id="breadboard> element. 

Thanks for the tip, since this problem unfortunately still exists.

I'm running into the same problem with pin labels though, not sure what to change for that.

**Comment by sebastiankmilo** [comment]
i have the same problem, when i export a custom part :/

**Comment by nikeee** [comment]
Having the same issue. PNG and PDF exports work fine. As I need the drawing as a vector image, I need SVG. The PDF seems to contain a vector image aswell. Maybe converting the PDF to a SVG suffices as a workaround.

**Comment by failiz** [comment]
I also experienced this when trying to export to svg with a pololu stepper driver. The svg of the breadboard does not have the id="breadboard". A quick check in the images for the breadboard in the core parts shows that there are several that are missing the id. You can check it with grep:

`` grep -L "breadboard" breadboard/*

I would fix them as soon as we implement a mechanism that does not allow users to insert wrong parts in the parts repository.

**Comment by failiz** [comment]
remove imported label

**Comment by KjellMorgenstern** [comment]
Parts layer ids have been fixed, this issue should be resolved.
