### ISSUE TITLE
remove THT from certain parts (like breadboard)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1256]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 06, 2010 11:33:09_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1256_

**Comment by failiz** [comment]
I cannot find the THT property in breadboards.
