### ISSUE TITLE
sort the appearing order of properties

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1258]
_From [daniel.t...@ixds.de](https://code.google.com/u/109739317909807101336/) on October 07, 2010 08:38:20_

The order of the properties is random. It would be nice if there could be a specific order.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1258_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
