### ISSUE TITLE
free form property that can be added to any part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1266]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 08, 2010 06:34:47_

so user can type anything, it's saved and loaded with the part, and you can show/hide it in the part label

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1266_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
