### ISSUE TITLE
make datasheet comment part of the actual xml

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1283]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 04, 2010 05:12:24_

instead of 

this should be made into an xml chunk instead of a comment so that it can be searched.  Best would be to use some version of RDF format.  You can find an example in the contrib pcb svgs.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1283_

**Comment by failiz** [comment]
It does no seem like a bad idea, but the links will get outdated with the time. Is there any reliable source that will not change too often? How to treat generic devices?

**Comment by KjellMorgenstern** [comment]
Basic support for rich text and linking to datasheets is already implemented.
