### ISSUE TITLE
fritzing doesn't remember grid settings

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1295]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 18, 2010 07:02:49_

From the forum http://fritzing.org/forum/thread/357/?page=all#post1454 :

Fritzing does not seem to remember the grid settings. I have to enter the grid size and "snap to grid" every time I open the application. This happens for breadboard, circuit and PCB-view.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1295_

**Comment by failiz** [comment]
I tried this and I could not replicate it. Fritzing remembered the grid size and the align to grid options.
