### ISSUE TITLE
Bedpoints "lock" some times (they can´t move)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1310]
_From [pietrodo...@gmail.com](https://code.google.com/u/108333589149146503657/) on December 13, 2010 14:55:14_

What steps will reproduce the problem? Has no steps. Is only in a moment that happens the problem. I don´t know why this occurs. Maybe it happens cause the circuit have much parts and connections... And now it is happenning with frequency, and i can´t work. What is the expected output? What do you see instead? All bedpoints "lock" and i can´t move they. What version of the product are you using? On what operating system? The version is Frizting Alpha 0.4.3. I'm at windows Vista Home Basic. Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1310_

**Comment by failiz** [comment]
Not enough info. Really old bug
