### ISSUE TITLE
mac: fritzing disappears when the app loses focus

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1315]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 10, 2011 12:50:45_

If the viewswitcher is hidden or in the dock, fritzing no longer disappears.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1315_

**Comment by failiz** [comment]
This was set to unable to replicate. @KjellMorgenstern , could you check it?
