### ISSUE TITLE
highlighted wire isn't in focus in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1320]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 12, 2011 11:11:41_

in schematic view, set up a connector with two outgoing connections.  As you hover over the connector, move the mouse and see which wire is highlighted.  If you click down when a particular wire is highlighted, you may find yourself dragging the end of the wire that was not highlighted.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1320_

**Comment by failiz** [comment]
I could not replicate this in 0.9.4. In fact, the wire highlighted is always the same.
