### ISSUE TITLE
schematic bendpoint drag bug

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1321]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 12, 2011 14:02:47_

set up the schematic view with the connections as pictured.  When you drag one of the selected parts, the bendpoint stays fixed.  Instead what should stay fixed is the end of the wire connected to the unselected part--the bendpoint should move.

**Attachment:** [schematicbug.PNG](http://code.google.com/p/fritzing/issues/detail?id=1321)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1321_

**Comment by failiz** [comment]
There is no picture to reproduce the problem.

**Comment by KjellMorgenstern** [comment]
I don't agree that bendpoints should moved together with the part. Instead, they should be selectable, and only the selected bendpoints should be move along.

Closing this in favor of https://github.com/fritzing/fritzing-app/issues/3609
