### ISSUE TITLE
consider ktechlab for schematic view routing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1325]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 21, 2011 12:08:29_

ktechlab.org

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1325_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
