### ISSUE TITLE
Copy and Paste in breadboard view doesn't echo well in other views

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1352]
_From [lionel.m...@gmail.com](https://code.google.com/u/103475144724766856816/) on February 23, 2011 06:14:50_

When I copy and paste parts in the breadboard view, the new part get pasted exactly over the original part in the PCB and schematic views.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1352_

**Comment by failiz** [comment]
I could reproduce this in 0.9.4 with the rotary encoder (and only when copy/paste two of them), no with the resistors. It also happens the other way around, from schematics to bb.

**Comment by KjellMorgenstern** [comment]
I have also observed this. It looks as if the part was not created, until you grab one of the parts and see that there is and identical part underneath
