### ISSUE TITLE
need a way to distinguish read-only parts bins

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1356]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 27, 2011 05:18:50_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1356_

**Comment by failiz** [comment]
Is the core bin read only? You can modify three files in as text editor and then regenerate the database. 
Is the read only just in fritzing? In the parts editor?

**Comment by KjellMorgenstern** [comment]
I think we can close this as "Won't fix" for now. I have not heard about any issues with it.
