### ISSUE TITLE
the faq could use some attention

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1361]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 05, 2011 12:21:35_

There are probably a bunch of new questions that could be added, such as what if I can't find a part, what is 'save as shareable', how do I make a pcb, where can i donate...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1361_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
