### ISSUE TITLE
parts editor, mac, maximize window? then minimize, restore, reminimize, program hangs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1379]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 15, 2011 07:46:11_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1379_

**Comment by failiz** [comment]
This has been marked as unable to replicate before. Can be replicated in 0.9.6 in Mac?

**Comment by KjellMorgenstern** [comment]
Just tried on macOS Big Sur and Fritzing 0.9.6
No issues observed, however it is not possible to go directly from Maximized to Minimized with any program. I have to first press Maximize again to get the window from fullscreen to window mode, then Minimize is enabled.
