### ISSUE TITLE
LED icon import doesn't allow multiple selection (import under the part menu does)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1397]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 23, 2011 07:03:19_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1397_

**Comment by failiz** [comment]
Outdated? I could not find the import under the part menu. Or the LED icon import. 
Is there a way to import multiple parts at once?
