### ISSUE TITLE
More options for pin headers/plugs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1425]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 09, 2011 13:17:18_

We currently only have plugs with 2.54mm pitch (0.1").
There are lots of other ones, ranging from 1mm to 0.2". An extra option for this on the pin headers would be awesome.
This would only affect PCB view, as they should still fit into the breadboard.

This would be fairly easy to realize and comes in really handy, so I'm marking it high priority.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1425_

**Comment by failiz** [comment]
Most of these comments have been implemented. Close?
