### ISSUE TITLE
(Mac) vertical splitter handle too small

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1430]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 21, 2011 06:08:25_

The vertical splitter between the sketch view on the left and the panels on the right is very hard to grasp. In fact, it's only one pixel, and only if you move the mouse from left to right.

Please someone with a Mac have a look into the style sheet. There's also a Mac-specific qss that can be adapted (resources/styles/mac.qss).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1430_

**Comment by kittentronic** [comment]
Seems fine to me in Fritzing 0.9.4 under Mac OS Catalina on a non-retina iMac and a retina MacBook. The divider is easily operated and its grabbable area seems at least 5 pixels wide.

**Comment by KjellMorgenstern** [comment]
@kittentronic Thank you. Also confirmend with dev build on BigSur , still works fine -> closing
