### ISSUE TITLE
Change file ending of Gerber contour to ".oln"

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1448]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 23, 2011 11:52:56_

Currently it's ".gm1", and even though there is no standard it looks like ".oln" is quite common.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1448_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
