### ISSUE TITLE
Optimize context menus

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1451]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 24, 2011 13:00:35_

Just noticed that the context menus are kind of messy and inconsistent in many ways.
So here's a suggestion on how to optimize them, mostly reordering/renaming and not showing disabled actions:

== Breadboard View ==

=Wire=
## Color

Remove
## Add Bendpoint

Raise and Lower

=Part=
## Show label

Copy
Duplicate
## Remove

Edit...
## Add to bin

Lock
Rotate>
Flip>
Raise and Lower>

== Schematic View ==

=Ratsnest=
## Make Connection // or Make Trace?

Remove

=Wire=
## Ignore for Autorouting

Remove  
## Add Bendpoint

Raise and Lower>

=Part=
## Show label

Copy
Duplicate
## Remove

Edit...
## Add to bin

Lock
Rotate>
Flip>
Raise and Lower>

== PCB View ==

=Ratsnest=
## Make Trace

Remove

=Trace=
Move to other side of the board
## Ignore for Autorouting

Remove  
## Add Bendpoint

Raise and Lower>

=Part=
## Show label

Copy
Duplicate
## Remove

Edit...
## Add to bin

Lock
Rotate>
Flip>
Raise and Lower>

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1451_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
