### ISSUE TITLE
missing resistor values, only E6 series available

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1455]
_From [stl...@poczta.fm](https://code.google.com/u/103015841192184689122/) on May 24, 2011 17:14:19_

What steps will reproduce the problem? 1. Take a resistor
2. Try to find 2.7kΩ

What is the expected output?
No such value on the list.

What do you see instead?
2.2kΩ and 3.3kΩ are available What version of Fritzing are you using? On what operating system? 0.5.2 (b4756) for Linux Please provide any additional information below. It looks like only E6[1] series is available (20&#37; tolerance, no fourth strip). I think it isn't uncommon to use E12 (10&#37;, silver strip). What's more misleading is that there is a golden strip on resistors that suggests E24 (5&#37;) series is available.

[1] http://en.wikipedia.org/wiki/Preferred_number

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1455_

**Comment by failiz** [comment]
E12 will create the too many values in the combo box. The proposed solution of two combo boxes (one for the number and one for the multiplier) will make the selection more complex for beginners and more time consuming. I would keep the E6 values in the combo box. The E12 values can be typed in and they are added to the combo box automatically.

**Comment by KjellMorgenstern** [comment]
I also agree with typing in. There could be improvements for that, like remembering the last use values, or a 'custom' option in the combo box, that points user to the possibility to type in values.
