### ISSUE TITLE
autorouter and smd parts: upsizing traces not connected to SMDs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1467]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 28, 2011 01:53:04_

Need to deal with trace width. 

An easier first version of this would be to go through all the possible connectors that could be routed to find the smallest, and use this to determine the trace width which would then be used for all connections.

A second version would be to go through all the possible source/destination connections for a single attempt to route a connection, and use the smallest to the determine the trace width for just that.

I am inclined to take the easier course, maybe offering a quick way of changing trace thickness after the fact (i.e. select all traces and offer a menu item that would run through them all and try to upsize).

In fact, the upsizing could be done automatically. So I think this solves it.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1467_

**Comment by failiz** [comment]
I could not replicate this in 0.9.6
