### ISSUE TITLE
schematic view: autorouter not recognizing loaded traces

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1470]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 28, 2011 11:07:03_

Open the example from issue #1460 .  Go to schematic view and run the autorouter.  Autorouter reroutes connections that already had traces, so you see the old trace and new trace for the same connection side-by-side.  The old traces should either be respected or deleted depending on whether the doNotAutoroute flag was set.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1470_

**Comment by failiz** [comment]
The file of not available and the issue seems fixed
