### ISSUE TITLE
Autorouter dialog

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1475]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 30, 2011 06:00:46_

The various autorouter settings and feedback windows are currently quite distributed and confusing. Also given that this process is a bit "magic" and will receive more and more options in the future, it would be nice to streamline this a bit.

Attached is a pdf of what a simple new autorouter dialog/process could look like. It's meant as a wizard/step-wise dialog, with the options as a separate pop-up.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1475_

**Comment by failiz** [comment]
This has been implemented. Is there any thing missing?
