### ISSUE TITLE
after export, launch the resulting file

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1483]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 31, 2011 15:13:39_

Since it's so nice that Export-to-BOM launches the BOM.html file directly in a browser, maybe some or all of the other exports should also launch their output file.  My only hesitation is that for the other export types, it's not so clear what program the user would really want to launch (launching the default might be an annoyance).

Another possibility would be to "show file in folder".

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1483_

**Comment by failiz** [comment]
I do not think that this should be the  default behaviour. It is up to the person to decide what to do after the export. For example, if you export an image, you could want to insert that image in a Word document. Opening the image in a viewer will just give you more work as you have to close the viewer. 
I would close this issue.
