### ISSUE TITLE
after swap, in pcb view, part is not automatically placed on the board

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1490]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 04, 2011 06:41:11_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1490_

**Comment by failiz** [comment]
Still an issue. Steps to reproduce:
1. Add a resistor in BB view at the top left (columns 1 and 5, row J). 
2. change the resistor to 0805 package
3. Change to pcb view
The resistor is not in the board. If you do not change the package the resistor is at top left corner of the board. It looks like the position of the resistor in the bb view influences the position in the PCB view. if the resistor is placed at right corner, the resistors apperars at right of the board in the PCB. If it is in the middle of the BB view, then appears in the board in PCB view.
Remove imported label.

**Comment by failiz** [comment]
Remove imported label. Not sure if this is just a pcbview problem or a more general issue
