### ISSUE TITLE
Consider moving user folder into default sketch folder

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1494]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on June 14, 2011 09:18:01_

It's very hard to find the current user folder. Even though we do it the "correct" way by putting everything into hidden user system folders, it's painful when you want to modify your files.

Arduino and Processing moved to a model where this folder is now in one's sketch folder. So when your sketch folder is
C:\Users\andre\Documents\Processing
then the "user" folder is
C:\Users\andre\Documents\Processing\libraries

I find this very convenient to work with, and we could take some extra measures to protect it from being accidently deleted.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1494_

**Comment by KjellMorgenstern** [comment]
This issue is outdated and a bit unclear. 
Current approach already uses Documents/Fritzing folder for user data.
With the introduction of git for fritzing-parts management, this also became much more flexible.
