### ISSUE TITLE
Pasting parts should paste it in the center of your view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#150]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 07, 2008 12:15:42_

What steps will reproduce the problem? 1. Select one or more parts from the far right of your canvas
2. Copy them
3. Paste them in a new document What is the expected output? What do you see instead? The pasted parts should always appear in the center of your view. Now instead the original location 
of the parts is also copied. In the case of parts copied from e.g. the far right they will also be pasted 
at the far right, which means you might not see them anymore, you would just see the canvas 
grown, by the scrollbar. 

Pasting parts should paste them in the center of your view, i.e. where you happen to have the focus 
of your view.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=150_

**Comment by failiz** [comment]
It pastes at the center of the view. Do we want to modify this to paste a the cursor? 
One issue is that if you paste several copies, the new parts are always placed a the right bottom of the previous one. So, if you paste several, they go out of the current view.

**Comment by KjellMorgenstern** [comment]
Closing this in favor of #3799

**Comment by KjellMorgenstern** [comment]
And acutally, #3799 already existed as #3568
