### ISSUE TITLE
fritzing.SqlPasPlugin is not deregistered when deactivated

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1517]
_From [till.sav...@gmail.com](https://code.google.com/u/107738394355416705890/) on June 20, 2011 10:50:55_

via plone control panel. A clean uninstall should be possible.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1517_

**Comment by failiz** [comment]
Outdated?
