### ISSUE TITLE
Traces change layers themselves

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1525]
_From [lpfthi...@gmail.com](https://code.google.com/u/114254058204735509887/) on June 24, 2011 10:43:31_

Not sure what triggers this, but it has happened a few times now. Traces will just randomly switch layers. I believe it happens if you close Fritzing, then open the file again at a later date.

Fritzing 5.2b on Windows 7 64x

**Attachment:** [tracelayers.png laser harpv8traces.fzz](http://code.google.com/p/fritzing/issues/detail?id=1525)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1525_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
The file referenced is not available anymore.
