### ISSUE TITLE
replacing a label with a space doesn't "take"

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1526]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 24, 2011 14:47:08_

have a look at the file in issue #1525 .  Replace the label "via2" with a space and save the file.  On reloading, the "via2" is back.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1526_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
The file referenced is not available anymore.
