### ISSUE TITLE
Closing the last window shouldn't quit the application on mac

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#154]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 07, 2008 13:32:31_

What steps will reproduce the problem? 1. Have one or more document windows open
2. Close them all What is the expected output? What do you see instead? On a Mac the application should not quit after the last window closes.
Because Macs have a menu bar fixed to the screen (not to the document), the user can always still 
create a new document, and not necessarily have to wait for the application load up again.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=154_

**Comment by failiz** [comment]
If this in the pipeline?

**Comment by KjellMorgenstern** [comment]
When done properly, this would be a major refactoring, also affecting Linux and Windows platforms.
It's not standard on Mac, but there is no real problem with it. Closing
