### ISSUE TITLE
schematic frame: make descr 1 and descr 2 into a single descr field, and figure out how to word wrap

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1547]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 02, 2011 08:33:07_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1547_

**Comment by failiz** [comment]
both wrap is working too. So, the issue is fixed. 
However, the frame size cannot be changed and only two lines can be shown in the description. Maybe it could be expandable to allow more text. Is so, change title of the issue and remove imported label and add scematichview label
