### ISSUE TITLE
.fz files should be associated with Fritzing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#155]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 07, 2008 14:56:45_

What steps will reproduce the problem? 1. locate a saved .fz file on your computer
2. try to open it by double clicking or dragging it onto the Fritzing application icon What is the expected output? What do you see instead? Fritzing should accept the file and open it. Now nothing happens.

On Mac OS X, this is quite simple to accomplish by editing the Info.plist file and listening for 
apple events, as described here: http://doc.trolltech.com/qq/qq12-mac-events.html On Windows / Unix it might be a bit more work and might involve an installer or a first-run 
(singleton-like) application. All described in this thread: http://lists.trolltech.com/qt-interest/2007-09/thread00672-0.html

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=155_

**Comment by failiz** [comment]
Outdated?
