### ISSUE TITLE
when swapping from a breadboard to a half breadboard, some parts are unexpectedly disconnected

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1565]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 13, 2011 10:22:59_

start with a full breadboard, and well on the left side, connect a resistor indirectly by dragging a wire from each end to the breadboard.  

After the swap both wires should be connected to the new breadboard, but only one of them is.  If the resistor is directly connected to the original breadboard, the swap works fine.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1565_

**Comment by failiz** [comment]
Not sure, but maybe it's related to #2123
