### ISSUE TITLE
combo box with multiple copies of the same value

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1569]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 14, 2011 05:32:54_

Occasionally when a user types a value into the combo box in the inspector, or a part has a particular value when being loaded (so that gets added to the combo box), the combo box conversion code fails to recognize that two values are the same, and mistakenly adds a value that was already there.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1569_

**Comment by failiz** [comment]
I could not reproduce this in 0.9.4. Close?

**Comment by failiz** [comment]
@KjellMorgenstern  have you seen this error lately?
