### ISSUE TITLE
QApplication::startDragDistance()

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1573]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 15, 2011 01:38:44_

various drag functions could use this constant when deciding that some drag motion was big enough to be considered the start of a drag

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1573_

**Comment by failiz** [comment]
Close in favour of #976
