### ISSUE TITLE
scale schematic view before exporting or printing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1575]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 17, 2011 13:36:59_

these parts are scaled way too large, so directly printing them wastes a lot of paper

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1575_

**Comment by failiz** [comment]
This is the opposite as #338. Related to #2195 and #653

**Comment by KjellMorgenstern** [comment]
I think we can close this issue: Scaling before export seems like a bad idea.
Instead:
1. symbols should have a more or less uniform size. If symbols are oversized, it is likely an issue with the scaling of the part itself.
2. supporting different image sizes (e.g A3 or US Letter) would be a different issue
3. any additional scaling is left to the user during printing, after export. Fritzing exports should be uniform scale to avoid surprises.

Side note: We have prepared a DPI dialog for PNG exports, it will be included in Fritzing soon.
