### ISSUE TITLE
Fritzing not happy under openSUSE

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1587]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 25, 2011 15:22:24_

see forum post http://fritzing.org/forum/thread/556 for details

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1587_

**Comment by failiz** [comment]
Link not working, not detailed description of the issue and the issue is 9 years old (the openSUSE distribution probably has changed).
