### ISSUE TITLE
User preferences page is extremely slow

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1588]
_From [till.sav...@gmail.com](https://code.google.com/u/107738394355416705890/) on July 26, 2011 06:11:22_

@@usergroup-userprefs sometimes takes minutes to display user lists or update roles.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1588_

**Comment by failiz** [comment]
I think this is not valid now, userprefs  for the old website

**Comment by KjellMorgenstern** [comment]
Indeed
