### ISSUE TITLE
export vias as image

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1590]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 26, 2011 14:21:07_

either on their own layer, so other layers can be hidden, or as a special export function

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1590_

**Comment by failiz** [comment]
Not sure why this is needed. Drilling information is exported and contains more than vías. Close?
