### ISSUE TITLE
regularly add "const" for data-retrieval-only functions

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1608]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 04, 2011 05:04:51_

one small step toward more robust code

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1608_

**Comment by failiz** [comment]
If we keep this open, I would specify the parts of the code that need improvement. If not, move this to the wiki as general code practice.

**Comment by KjellMorgenstern** [comment]
Adding a rule for this isn't straightforward. For example, from the google cppguide, they sum it up with 

"In APIs, use const whenever it makes sense. constexpr is a better choice for some uses of const."
