### ISSUE TITLE
thinner wires in breadboard view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1617]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 07, 2011 17:06:10_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1617_

**Comment by failiz** [comment]
I think that this is just a case of a more general feature requested in #3594

**Comment by KjellMorgenstern** [comment]
Agree, and #3594 is much better described.
