### ISSUE TITLE
general purpose resizable mystery part 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1618]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 08, 2011 13:13:37_

http://fritzing.org/forum/thread/528/?page=all#post2369

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1618_

**Comment by failiz** [comment]
Not enough info. Is the mystery part still needed? There is also a generic IC. The mystery part has a bug and it cannot set the pins in dual row in schematic view (IC works). It also looks like the mystery part does not follow tthe same design as othr ICs in the breadboard view.
Close or remove imported label if accepted.

**Comment by failiz** [comment]
From the old forum (summary):
"And mystery parts which can go over 900mils spacing.

Author: 2695

I have a large 7-segment LED display (over 1 inch) which takes up a good portion of my breadboard. When trying to use a mystery part as a stand-in for it, I set the "spacing" field to its maximum (900mils) but the resulting mystery part is still not large enough to use as an accurate representation of the physical piece.

Author: 8

Ok, spoke too soon: a general purpose resizable mystery part is more of a challenge, not so much in the resizing, but where the pins should go. Adding that one to the issue tracker."

**Comment by failiz** [comment]
If it is just the resizing, I would opt to close this issue and add bigger spacing options in #2535. I think that we should not try to create ad hoc fottprints with the mystery or ICs parts. The part editor should be the way to go for more complex parts.
