### ISSUE TITLE
svg export not drawing bendpoints

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1626]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 16, 2011 16:46:12_

make a wire with a bendpoint, export to svg.  The bendpoint circle is not drawn.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1626_

**Comment by failiz** [comment]
Still an issue in 0.9.9. It happens in all the views (BB, SCH and PCB). Remove imported label.
Tested in MS Edge and Inkscape. Produced as  File->Export->as Image->SVG

[test_bendpoint_export.zip](https://github.com/fritzing/fritzing-app/files/7710838/test_bendpoint_export.zip)

**Comment by KjellMorgenstern** [comment]
Still missing in PCB.

:red_circle: Bendpoints in copper trace not shown. Plus, the silkscreen should be colored dark.
![image](https://github.com/fritzing/fritzing-app/assets/6494025/9c4c290c-74eb-4037-892d-5d0b52ff43d6)

Print (pdf) as reference, but we don't want to export the red and green connector highlights:
![image](https://github.com/fritzing/fritzing-app/assets/6494025/3a016249-11ea-4abe-80c5-50afd1ef4bf7)



:white_check_mark: Breadboard (see the bendpoint in the leg):
![image](https://github.com/fritzing/fritzing-app/assets/6494025/5c84d525-7321-4d01-b719-682817fa62eb)

:white_check_mark:  Schematic:
![image](https://github.com/fritzing/fritzing-app/assets/6494025/d450cf04-28e4-4ab0-86e6-6e89eb7ec00d)
