### ISSUE TITLE
allow part labels and logo items to be in any font

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1631]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 19, 2011 00:48:16_

The problem is that the font would have to travel with the sketch. This functionality seems to exist for pdf export--if so, can we adapt it when saving fzz files?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1631_

**Comment by failiz** [comment]
Remove imported label

**Comment by KjellMorgenstern** [comment]
Won't fix. Rasterized text would come with additional problems, and images to render text usually are a bad idea (e.g. we use the label for netlists, some users even use Fritzing together with a screenreader) So we would also have to implement an alt-text feature.

In any case, it is of course possible to include any SVG or Raster image in Fritzing via the logo items.

**Comment by failiz** [comment]
Could we add the option of selecting the included fonts (OCRA, Droid Sans and seven segments font) when using the text logo items. Net labels is probably not worth the effort, but in logo could be useful. Not sure if it too much work...
