### ISSUE TITLE
LED nanometers setting

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1660]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 22, 2011 08:57:47_

Go back to the old simple color drop down, but add a second combo box that allows free entry of nm

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1660_

**Comment by failiz** [comment]
To much work for a minor improvement?
Close the issue or remove the imported label if the enhancement is accepted.

**Comment by failiz** [comment]
Ping
