### ISSUE TITLE
panelizer: some text is too small

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1661]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 26, 2011 06:25:53_

2mil border comes back
some text is too small (we have 70 micrometers)
silkscreen on copper

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1661_

**Comment by KjellMorgenstern** [comment]
Panelizer will be removed.
