### ISSUE TITLE
Protect users from doing a "destructive" ground fill

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1665]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on September 27, 2011 12:40:29_

Some measures we could take:
- Offer a separate "copper fill" and "ground fill" function
- Add a check for "shorts" to DRC, that looks for connections between + and -
- Run that check also before "ground fill", and if it fails, suggest "copper fill" as an alternative

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1665_

**Comment by failiz** [comment]
Outdated?
