### ISSUE TITLE
figure out why these "duplicate module id" messages keep showing up

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1674]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 03, 2011 04:38:51_

especially after running the panelizer

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1674_

**Comment by failiz** [comment]
How do you run the panelizer? Is this still relevant?

**Comment by KjellMorgenstern** [comment]
How to run: https://forum.fritzing.org/t/v-cut-or-panelizer/5416

**Comment by KjellMorgenstern** [comment]
Panelizer will be removed
