### ISSUE TITLE
autorouter is treating resistors as polarized

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1678]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 17, 2011 04:26:11_

See forum thread http://fritzing.org/forum/thread/654

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1678_

**Comment by failiz** [comment]
There is no forum thread available. I guess that the autorouter was trying to connect to the the connector of the resistor that was chosen in the schematic. Close?
