### ISSUE TITLE
Checkbox für Mailingeinverständnis

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1680]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on October 24, 2011 04:08:15_

Ich hätte gern in der Registrierung noch eine Checkbox:

Fritzing.org has my permission, to inform me by Email

oder so etwas in der Art. :)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1680_

**Comment by failiz** [comment]
Outdated
