### ISSUE TITLE
mac and linux dynamic cursors not working very well

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1682]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 24, 2011 08:02:41_

Since the cursor-changing mechanism seems unreliable under both Linux and Mac, I wonder whether we could implement it instead by using a "sprite".  Most of these dynamic cursor changes occur within the QGraphicsScene, so the sprite could perhaps be implemented as a QGraphicsItem set to the top of the z order and which follows the mouse.  In that case we would keep the actual cursor as a pointer and merely switch sprite images.  Since the sprite is offset from the cursor position, we can hope it won't interfere with selection, dragging, etc.  If this works, it could be any 32-bit image, not limited to black-and-white or 32x32.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1682_

**Comment by failiz** [comment]
Is this still an issue in Mac and Linux? It was opened in 2011 but not activity since then
