### ISSUE TITLE
returning costomers

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1684]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on October 27, 2011 00:44:43_

It would be very helpful, if the clients list could indicate returning costomers.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1684_

**Comment by failiz** [comment]
Does this issue still apply?

**Comment by KjellMorgenstern** [comment]
Not really. The Fab is managed by Aisler now.
