### ISSUE TITLE
undo doesn't work when adding or removing a part from the parts bin

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1691]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 03, 2011 10:35:27_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1691_

**Comment by KjellMorgenstern** [comment]
Won't fix.
1. this is not important: You can simple "undo" this by removing or adding the part as wished.
2. undo and redo should affect the model, but not the editor
3. undo and redo are per window/project, while the parts bin is Fritzing wide.
