### ISSUE TITLE
smd with throughhole confuses fritzing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1692]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 03, 2011 20:24:42_

Connections don't stay connected if you save and load if you draw a trace between two of the custom usb parts.

If you remove the copper0 references from the fzp file, then the traces will stay put.

Another problem with this file is that when you do a plain copper fill, the fill bumps right up against the usb smd pads on the copper top layer.  This does not happen doing a fill using the polygon fill part or using a ground fill.

**Attachment:** [skeletec-smd-shield_svg.zip skeletec-smd-shield.fzz](http://code.google.com/p/fritzing/issues/detail?id=1692)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1692_

**Comment by KjellMorgenstern** [comment]
Example file not available.
