### ISSUE TITLE
view mode:show unconnected 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1695]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 04, 2011 10:35:40_

http://fritzing.org/forum/thread/669

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1695_

**Comment by failiz** [comment]
Is this not done by the ratsnets and the routing menu under the window? If you press this menu the unconnected connectors are highlighted.
