### ISSUE TITLE
unable to create a new project on old website

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1701]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 10, 2011 06:56:05_

http://fritzing.org/forum/thread/671 .  Using I.E. seemed to fix it.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1701_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
