### ISSUE TITLE
save for fritzing fab

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1705]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 17, 2011 04:12:38_

does drc, ground/copper fill, and finally save as shareable. A dialog or wizard displays the steps.  

If drc fails, give option to bail or continue.

Let user select between ground and copper fill (with some textual advice).  Is there some way to check for shorts after a ground fill?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1705_

**Comment by failiz** [comment]
outdated?
