### ISSUE TITLE
some svg and fzp files have the executable bit set

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1714]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 09, 2011 07:05:02_

this only gets reset when a file is added, so may have to do an svn rename workaround

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1714_

**Comment by failiz** [comment]
I guess that this is in the files that come with  the installer. Is this still an issue? I guess that the parts in the repository are not the problem, but I am not sure where the permissions are stored in Linux...

**Comment by KjellMorgenstern** [comment]
Outdated, i think this was related to svn.
