### ISSUE TITLE
Fritzing quit on right click

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1720]
_From [Ridezebi...@gmail.com](https://code.google.com/u/104126857282072623043/) on December 18, 2011 13:44:24_

What steps will reproduce the problem? 1. open my sketch
2. rigth click on a via/route/component
-> Fritz close suddenly... without saving :-(

this issue come quite often (several times per hour) Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? 0.6.4
Windows XP Please provide any additional information below.

**Attachment:** [Poele.fz](http://code.google.com/p/fritzing/issues/detail?id=1720)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1720_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
