### ISSUE TITLE
net nodes missing or duplicated in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1722]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 19, 2011 14:12:16_

http://minbiocabanon.free.fr/public/20111218_fritzing/Fritzing_no_nodes.png from forum post thread 705:

 I didn't suceed in putting a "dot" on each node between diodes and R1 net...

other example : Q3 -> Why two "dots" ? If i try to remove one of both, i have a disconnexion :-(

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1722_

**Comment by failiz** [comment]
There is no fritzing file to debug, just a PNG image. And the issue is really old (2011)
