### ISSUE TITLE
when exporting a sketch containing a hole part to etchable pcb, actual hole is filled in

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1731]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 25, 2011 12:20:34_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1731_

**Comment by KjellMorgenstern** [comment]
PCB:
![image](https://user-images.githubusercontent.com/6494025/148959617-830e0009-01ee-4b3d-ba87-0245bf88ce7f.png)

Copper PDF:
![image](https://user-images.githubusercontent.com/6494025/148959630-99491a39-6c4d-42f1-900f-83812d66d609.png)

**Comment by KjellMorgenstern** [comment]
Closing in favor of duplicate #2765
