### ISSUE TITLE
add a "share part" function to fritzing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1751]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 05, 2012 16:01:01_

What if you could select a custom part in Fritzing and press a button to share it with the rest of the community?  

It looks like we could almost implement this for our current issue-tracker-based part-sharing method.  There is a google issue tracker API: https://code.google.com/p/support/wiki/IssueTrackerAPI , and you can use it to add a comment to an existing issue.  Unfortunately, it looks like they have not implemented attaching a file to a comment (and the request has been open for two years: https://code.google.com/p/support/issues/detail?id=3213 ).  

So what about a plan B?  We could implement a simple server which accepts fzpz files uploaded from the Fritzing application.  It would send an email to whomever, and we would manually add the comment to the issue tracker.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1751_

**Comment by KjellMorgenstern** [comment]
The recommended method to share a proven and test part is to submit a pull request to the fritzing-parts nightlyParts branch. Of course it is also possible to post in the forum or use the github issue tracker.
