### ISSUE TITLE
menu color

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1752]
_From [jazzcomm...@gmail.com](https://code.google.com/u/102214720157054660916/) on January 05, 2012 22:39:28_

What steps will reproduce the problem? 1.linux version 2. 3. the menu bar is dark gray, and the menu's(file edit and so on) are black so there is too little contrast to see the menus.
please change menubar background to lighter shade of gray. 
that's all
thanks for the nice software

greetings from Saigon, Vietnam Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1752_

**Comment by jostidetosti** [comment]
Thought i'd give you some extra info.
On Kubuntu 18.04 with Breeze Dark theme. Fritzing 0.9.3.
Open file dialog looks like this:

![image](https://user-images.githubusercontent.com/18124323/58244105-3fa3cb00-7d52-11e9-8284-494a6eebd7d1.png)

Dark text on dark background, unreadable.

**Comment by KjellMorgenstern** [comment]
Thanks a lot, good to know that this is still an issue.

**Comment by KjellMorgenstern** [comment]
Tried with Budgie and "Adapta" theme on 0.9.5 . Readability is fine, but it looked like colors in the file open menu changed. 
TODO: Retry with Kubuntu , Breeze Dark theme

**Comment by KjellMorgenstern** [comment]
Kubuntu 19.10, Breeze Dark theme looks good:
![image](https://user-images.githubusercontent.com/6494025/74048145-f247b680-49d1-11ea-9bcb-468be48f1b22.png)
