### ISSUE TITLE
Update problem of the parts library with opengl

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1772]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on January 13, 2012 04:16:16_

What steps will reproduce the problem? 1. open Fritzing

at first all parts were on the right place and there was a colored noise in the background

resizing of the libary space produced the image attached

see the attached image

**Attachment:** [fritzing_library.png](http://code.google.com/p/fritzing/issues/detail?id=1772)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1772_

**Comment by failiz** [comment]
Are we uing opengl? A `grep -Ri "opengl" .` does not report any results. outdated?
