### ISSUE TITLE
Resistor spacing switching is not working

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1773]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on January 13, 2012 05:23:55_

Changing the spacing in the PCB view is not working any more

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1773_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.4 (Windows)
