### ISSUE TITLE
Colors for the layers in the PCB View

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#179]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 14, 2008 13:17:28_

The PCB view should get nicer colors.

In this PDF document I describe the colors we need for alpha.
And towards the bottom, there is a section about the future colors, with examples, problems, 
solutions and other discussions.

**Attachment:** [PCBColorStyle.pdf](http://code.google.com/p/fritzing/issues/detail?id=179)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=179_

**Comment by failiz** [comment]
The document is not available and this issue is really old. I think that the colours of the pcb have been changed since then. Close?
