### ISSUE TITLE
Pin highlighting sometimes doesn't update immediately

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1812]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on February 01, 2012 06:40:35_

I think there are several cases, here is one:

Open an example. In breadboard view, move a part off the breadboard. Then right-click to delete one of the ratsnest lines. Notice that the pin highlight stays green, and only changes to red once you move trigger a redraw of that area.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1812_

**Comment by failiz** [comment]
I could not reproduce this.
