### ISSUE TITLE
Ohm symbol not displayed in export PDF

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1821]
_From [deyrin...@gmail.com](https://code.google.com/u/111887613590675600774/) on February 02, 2012 17:44:23_

What steps will reproduce the problem? 1. Create a new sketch and select PCB view
2. Add a standard resistor from the parts library
3. Change the resistor label to show the resistor value (220 Ohms per default)
4. Export the current sketch as DIY PDF
5. Open the *_etch_silk_top.pdf
6. You will see that the resistor label is rendered as "220?"

I'm using the latest SVN (5815) on Ubuntu 11.10 x86_64, Qt 4.7.4.
I can provide any additional information when needed.

Attached is an example of the silk top PDF with the error.

I don't think this is related to my PDF viewer because I tested it with the Adobe Reader, Okular and Evince and all show the same result.

**Attachment:** [Untitled Sketch 2_etch_silk_top.pdf](http://code.google.com/p/fritzing/issues/detail?id=1821)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1821_

**Comment by KjellMorgenstern** [comment]
This is fixed
