### ISSUE TITLE
Price calculator

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1827]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on February 03, 2012 12:00:55_

Several people have emailed us to get a quote for their PCBs.
So it would be really useful to have a price calculator separate of the order process, where you can either upload a sketch or just type in the size of your board.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1827_

**Comment by failiz** [comment]
When the mouse is over the fabricate button, the price is already displayed
