### ISSUE TITLE
min spanning tree ratsnest update problem

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1838]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 07, 2012 05:37:30_

start from the example in issue 1204 , comment #8.  Put a 2-pin pinheader between the offboard parts and the on board parts and connect them up. Note that the ratsnest redraw doesn't seem to include the new pinheaders.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1838_

**Comment by failiz** [comment]
No example´s file available.
