### ISSUE TITLE
fliphorizontal and flipvertical do not work on pcbView

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1851]
_From [tayl...@tinnov.net](https://code.google.com/u/107792761328206690703/) on February 15, 2012 23:31:18_

This is important for Ardunio-class modules as sometimes one wants to turn them upside down and plug them into a board. Without being able to flip the pins on the PCB view, there is no way to build this configuration.

And without the attributes working, there is no way to alter a part to work in this manor without major rework of the part file.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1851_

**Comment by failiz** [comment]
You can already select the layer (top or bottom) where they are placed, so the Arduino are flipped. Close
