### ISSUE TITLE
App Crashes When Deleting Vias

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1855]
_From [rick.win...@gmail.com](https://code.google.com/u/104098802778377434513/) on February 19, 2012 16:13:08_

What steps will reproduce the problem? 1. add a via to the pcb
2. route the via by hand
3. delete the via without deleting the wires first

expected: delete via without crash
actual: app crashes

Fritzing 0.7.0
Mac OS X 10.7

Stacktrace from crash attached.

**Attachment:** [stacktrace.txt](http://code.google.com/p/fritzing/issues/detail?id=1855)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1855_

**Comment by failiz** [comment]
The developers couldn't replicate it
