### ISSUE TITLE
hard to drag wires to connectors in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1859]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 26, 2012 02:19:08_

http://fritzing.org/forum/thread/801 . The suggested solution would be to make the connector target area larger when dragging a line. This could apply to the other views as well.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1859_

**Comment by failiz** [comment]
Not enough info, links outdated. 
Related to #678 and maybe #1386

**Comment by KjellMorgenstern** [comment]
Seems to work fine, see videos in #1386
