### ISSUE TITLE
When copying and pasting a part like "MAX7219" you have "MAX7220" as a result

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1866]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 02, 2012 06:36:52_

When copying and pasting a part like "MAX7219" you have "MAX7220" as a result, "MAX7219-2" would be more correct.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1866_

**Comment by failiz** [comment]
Unable to replicate this. The labels are U1 and U2.
