### ISSUE TITLE
osx lion crash on save

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1875]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 02, 2012 10:32:56_

When quitting fritzing with a complex layout, it asks to save (and does it 
successful), then shows the rainbow ball, then crashes.  It happens when you work with a big sketch for a longer time...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1875_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
