### ISSUE TITLE
implement a mini-drc as a trace is being drawn

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1877]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 03, 2012 01:55:46_

or moved, or as a part is being moved

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1877_

**Comment by failiz** [comment]
Not sure if this is too much for now. If accepted, remove imported label and add pcbview
