### ISSUE TITLE
autorouting 0mil traces

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1895]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 14, 2012 04:55:51_

in v0.7.1 (b5908 2012-03-10) [Qt4.8.0] selecting custom auto-routing and setting sized to 11 mils all traces shown/drawn in program show in Inspector as 0 mils

same thing happens with all trace settings when using auto-routing custom.

setting auto-routing to use professional, program over uses jumper wires instead of VIA's where as in custom it uses the VIA correctly. (would have included a pic but the interface only allows web/URL posted picks.)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1895_

**Comment by KjellMorgenstern** [comment]
We tried a few dozen autorouter runs, and could not observe (ArduinoISP.fzz and LED-Matrix.fzz from the examples) and not a single jumper wire was used. But also not many Vias. Maybe we need a more complex example. Closing this for now.
