### ISSUE TITLE
wire color menu: alphabetical order

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1899]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 16, 2012 02:43:30_

http://fritzing.org/forum/thread/826 .  Means a different order in each language, and not sure what it means for non-phonetic alphabets.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1899_

**Comment by failiz** [comment]
Too complex for the benefit? I would also argue that the first colours should be blue, black and red as they are the more used ones.
