### ISSUE TITLE
Allow re-ordering of previous fab submissions

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1901]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 19, 2012 10:17:43_

Use case:
1. Customer orders one test copy of his sketch
2. He's happy with it
3. He wants to order several more copies of the same sketch, but doesn't want to pay the "checking fee" again.

So it shold be possible to go to one's order history and order those uploads again.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1901_

**Comment by failiz** [comment]
Outdated. There is no checking fee in Aisler.
