### ISSUE TITLE
Order someone else's Fab or project submission

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1902]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 19, 2012 10:25:41_

This would be really cool -- we basically need a checkbox for that, and the submitter's PayPal mail address. Then they could get a percentage of the order and we could produce it with the next Fab run.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1902_

**Comment by failiz** [comment]
Remove imported label

**Comment by KjellMorgenstern** [comment]
Webpage issue, not about the fritzing app, but I have it on the issue list there, too.
