### ISSUE TITLE
silkscreen image elements with missing stroke-width not exported to svg

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1906]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 19, 2012 13:06:10_

load the attached into a logo image and export to svg; lots of lines (paths) will be missing because there is no stroke-width.

**Attachment:** [silkscreen.svg](http://code.google.com/p/fritzing/issues/detail?id=1906)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1906_

**Comment by failiz** [comment]
If this the same as #3843?

**Comment by KjellMorgenstern** [comment]
Hard to tell. If they literally mean there is no stroke-width, then it is a different issue, as this should then use the initial value of 1. Which might or might not be visible in the silkscreen, depending on the scale.

**Comment by failiz** [comment]
As there is no file to analyse, we cannot be sure.
I would close the issue if you think that is not common to produce the svg without the stroke-width element with Inkscape or illustrator. If it is accepted, remove the imported label.

**Comment by KjellMorgenstern** [comment]
Just tested with a part with missing stroke-width, and export renders a stroke-width of 1, as expected

[pcb.crystal_HC18.svg.zip](https://github.com/fritzing/fritzing-app/files/6712280/pcb.crystal_HC18.svg.zip)

**Comment by KjellMorgenstern** [comment]
During gerber export, the missing stroke-width causes some elements to be missing.

**Comment by KjellMorgenstern** [comment]
Stroke width works. The observed issue with the attached files is due to id="copper1" elements, which will not be exported to silkscreen gerber files.
