### ISSUE TITLE
include gerber files in the panelizer

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1914]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 29, 2012 01:53:09_

Could convert gerber back to svg. Use the contour layer for the board shape, the other layers to build a single custom part with a giant footprint that includes traces. Then this board could be panelized as usual. Possibly ignore the mask layers for a first pass.

The fab website would have to be changed to allow gerber uploading (presumably as a zip file). We would also have to make sure that only single or double layer gerber files got uploaded.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1914_

**Comment by failiz** [comment]
Panelizer will be removed, close?
