### ISSUE TITLE
export pdf copper fill gaps

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1915]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 29, 2012 05:06:45_

http://fritzing.org/forum/thread/859

**Attachment:** [Parachute.fzz](http://code.google.com/p/fritzing/issues/detail?id=1915)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1915_

**Comment by KjellMorgenstern** [comment]
From the old forum:

> Author: 3051
> Body:
> When I export PDF's for etching at home often the copper fill contains numerous horizontal gaps. I haven't found one that causes a real problem - it's just aesthetically displeasing. Eg:
> http://www.pocketscience.com.au/Parachute/Parachute_etch_copper_bottom.pdf
> 
> I can send a .fzz file to someone if they want to have a look - maybe I'm doing something wrong...?
> Cheers,
> 

![image](https://user-images.githubusercontent.com/6494025/178108661-d6cd5e07-6d3c-40dd-a7e9-c381e2c4901b.png)

**Comment by KjellMorgenstern** [comment]
Found more problems, removing from 1.0.0 again to not delay the release.

**Comment by KjellMorgenstern** [comment]
Issue was resolved with Fritzing 1.0.2
