### ISSUE TITLE
arrow keys not working when align to grid is on

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1917]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 31, 2012 17:51:11_

one small bug report.. when you change the grid size in pcb view to 0.01in and say align to grid (this is what i usually have..) then moving parts with the arrow keys will not work.. big jumps will work (arrow+shift works).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1917_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.6
