### ISSUE TITLE
parts wishlist should be directly accessible to users

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1920]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 01, 2012 02:02:19_

Let users submit these directly. A little form with a name field, url field, and datasheet field.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1920_

**Comment by failiz** [comment]
Not sure if it is a good idea. It creates expectations that we will not be able to fulfill. Better to work on the parts editor.
Move to the parts repository, if accepted

**Comment by KjellMorgenstern** [comment]
Something like that is on my mind, to suggest parts from the forum that could be integrated to core. On the other hand, that doesn't require a new feature, could be done within the forum or just by even creating PRs.
