### ISSUE TITLE
text rotation/sizing problem

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1923]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 02, 2012 01:25:44_
1. Insert Silscreen Text
2. Set Height to 1 mm
3. Uncheck Proportional
4. Rotate by 90° (Direction does not matter)
5. Resize Text -> Text is scaled to 4 mm by 4mm

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1923_

**Comment by failiz** [comment]
I could not replicate it in 0.9.6
