### ISSUE TITLE
logo text item with height = inf

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1930]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 02, 2012 11:00:18_

makes gerber crazy

**Attachment:** [buggy Breakout-Shield - Copy.fzz](http://code.google.com/p/fritzing/issues/detail?id=1930)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1930_

**Comment by failiz** [comment]
The cause of this issue is not described. A workaround measurement has been taken. It is not possible to add any letters in the Inspector´s width or height fields
