### ISSUE TITLE
panelizer rotation problem with custom part?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1931]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 02, 2012 11:02:39_

when board is part of panelizer? and rotated? and the custom part is on the board, gerber export creates a large rectangle covering the whole part.

**Attachment:** [RTD_Shield_V1.fzz](http://code.google.com/p/fritzing/issues/detail?id=1931)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1931_

**Comment by KjellMorgenstern** [comment]
Panelizer will be removed
