### ISSUE TITLE
single sided board, export to pdf, silkcreen is blank

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1942]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 10, 2012 18:13:28_

Attached file, for example.

**Attachment:** [Inverter_by_cosmolv.fzz](http://code.google.com/p/fritzing/issues/detail?id=1942)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1942_

**Comment by failiz** [comment]
I could not replicate this in 0.9.6.
