### ISSUE TITLE
trace is not reaching connector

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1946]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 11, 2012 05:29:35_

this may be a side-effect of other bugs in this sketch, but note the unattached trace at r6

**Attachment:** [Modulierte+Lichtschranke+2+April+2012+with+Ground+filling.fzz](http://code.google.com/p/fritzing/issues/detail?id=1946)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1946_

**Comment by failiz** [comment]
No file available and old issue.
