### ISSUE TITLE
replace tabs with spaces

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1954]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 14, 2012 07:02:37_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1954_

**Comment by failiz** [comment]
Is this still planned?

**Comment by KjellMorgenstern** [comment]
Tabs it is, so this issue is outdated.
We already have them, all relevant tools support them, and they resolve the discussion about 2,3,4 or 8 spaces for indentations. 
Should be a CI check, is there a github integration for C++ code for that?
