### ISSUE TITLE
Use Shift+Click for multiple selection instead of Ctrl+Click

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1971]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 11, 2012 09:10:48_

My bad, I originally pushed the Ctrl+Click version. But the Shift+Click really is the universal standard.
Since we don't use Shift+Click yet, we could also have both combinations work for some releases, before we phase Ctrl out.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1971_

**Comment by failiz** [comment]
Control click for selection is the standard in Windows. Shift is for a range of items. Maybe do this configurable it both ways but I don't think that we should disable the control click for selection.
Remove imported label

**Comment by KjellMorgenstern** [comment]
I am also not so sure if shift click is that universal. 

Ctrl - Click works fine in ununtu files 

On macos both fritzing and finder work with command-clic

So, we already follow the standard, nothing to do here.
