### ISSUE TITLE
Website says Multiple Boards Detected ... 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1976]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on May 14, 2012 08:55:52_

... even if there is only one in 

e.g. Fab Orders 00018 file: 
arduinoMega23.fzz

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1976_

**Comment by failiz** [comment]
This issue is very old and it seems that there was some work done to address it. Not sure if this can cause problems in the Aisler import process (and there is no file to be able to check it).

**Comment by KjellMorgenstern** [comment]
As this is an imported issue, there won't be anyone to provide that file. Closing.
