### ISSUE TITLE
Get rid of pcb board stickiness

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1978]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 21, 2012 11:17:25_

Stickiness is an ancient "feature" that we put in because people would often accidentally move the board. But it's causing a lot of usability problems with custom shapes these days.
Since we now have the "part lock" mechanism, we should get rid of stickiness and instead the user can lock the pcb shape.

I'm undecided whether we should lock the shape by default. I'm tempted to say no, for reasons of consistency, but then people might not find that feature and get frustrated. What do you think?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1978_

**Comment by failiz** [comment]
Are we considering this?

**Comment by KjellMorgenstern** [comment]
It would be usefull to check r5993 before closing this, to see if the mentioned remains are still left in the code. However, I didn't yet find an old SVN archive, seems this all got deleted with google code.
