### ISSUE TITLE
when deleting and restoring a pcb, also restore the active layers (i.e. top, bottom, both)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1982]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 24, 2012 09:39:38_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1982_

**Comment by failiz** [comment]
Not sure what the issue is? What does restoring mean? Undo?

**Comment by KjellMorgenstern** [comment]
Also not sure. Deleting a pcb does not have an effect on the active layer, and so doesn't restoring via undo. Seems like expected unsurprising behavior.
