### ISSUE TITLE
autorouter removes connections

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1989]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 27, 2012 08:15:55_

from an email (originally from the forum):

I'm attaching the schematic from which the autorouter sometimes removes
connections. If you switch to PCB view and click Autoroute a few times,
there's a high chance that one of the wires from either the top left or
bottom right header is removed at some point.

**Attachment:** [transmitter-o.fzz](http://code.google.com/p/fritzing/issues/detail?id=1989)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1989_

**Comment by failiz** [comment]
The file is not available. I think that there were several fixes in the autorouter.
