### ISSUE TITLE
 Restoring a component does not restore label properties

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#1997]
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on June 01, 2012 03:41:41_

When restoring a deleted component: displayed values, label position, orientation, font size and position are reset to default (although the text itself of the label is preserved). Also, when restoring a component that had a label, this label will be displayed upon restoring, even if the silkscreen layer is deactivated in the layer selector.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=1997_

**Comment by failiz** [comment]
Still an issue in 0.9.4 . It happens in all the views.

**Comment by KjellMorgenstern** [comment]
![image](https://user-images.githubusercontent.com/6494025/147461622-7a047087-5e7a-437e-b8e1-8b566e09e0a4.png)
Display/Flip/Rotate parameters are lost when using Undo
