### ISSUE TITLE
support square holes?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2006]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 03, 2012 12:04:54_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2006_

**Comment by failiz** [comment]
I would call them slots. Remove imported label

**Comment by failiz** [comment]
Related to #3320

**Comment by KjellMorgenstern** [comment]
Closing in favor of #3320

**Comment by failiz** [comment]
Did you forget to close it?
