### ISSUE TITLE
if a part connector overlaps multiple boards, it will appear in multiple export for production filesets 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2012]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 05, 2012 04:03:33_

should only occur very rarely. notify the user in this case and stop export? What is the fastest way to determine the condition?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2012_

**Comment by KjellMorgenstern** [comment]
![image](https://github.com/fritzing/fritzing-app/assets/6494025/f0788c7a-07f5-41f9-bf46-38fe23ae64cf)

When exporting each board to Gerber, the result looks as expected.

![image](https://github.com/fritzing/fritzing-app/assets/6494025/d6b5c6b9-6730-4a18-8f1e-7754e73bc687)

![image](https://github.com/fritzing/fritzing-app/assets/6494025/56dddd17-5aa0-462d-86c8-df4a583653b9)

Note that both boards miss the drill info for the split connector, but this is a different issue.
Can not reproduce.
