### ISSUE TITLE
Traces ending befor the pad

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2026]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on June 11, 2012 03:17:22_

just open the file

**Attachment:** [Bildschirmfoto 2012-06-11 um 09.16.06 – 11.06.2012.png Extruder+Layout+v0-1.fzz](http://code.google.com/p/fritzing/issues/detail?id=2026)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2026_

**Comment by failiz** [comment]
Not enough info to be reproduced. The issue was only reproducible with a custom part. Probably fixed by #3379. Close?
