### ISSUE TITLE
could we replace "do not autoroute" with part-locking?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2033]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 13, 2012 16:05:16_

Is there a reason to have both a part-locking mechanism and a "do not autoroute" setting?

-- currently locking doesn't apply to wires. what happens for example, if a wire is locked, but the part it's attached to isn't and you move or delete the part?

-- currently the default state for a part is not-locked, but the default for hand-positioned traces, jumpers, and vias is "do not autoroute".  In other words in the new scheme they would be locked by default.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2033_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
