### ISSUE TITLE
fritzing version update script at release time?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2034]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 14, 2012 07:29:19_

need to regularly update info.plist, fritzing.rc, version.cpp

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2034_

**Comment by failiz** [comment]
outdated?

**Comment by KjellMorgenstern** [comment]
I think the script would break about as often as it is used.
