### ISSUE TITLE
nested scaling confuses fritzing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2035]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 16, 2012 02:22:34_

when trying to flip this part going to a one-sided board fritzing gets confused.

**Attachment:** [SO20W_wide_pcb.svg SO20W_wide.fzpz](http://code.google.com/p/fritzing/issues/detail?id=2035)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2035_

**Comment by failiz** [comment]
The file is not available anymore.  Does anyone have a file to test the nested scaling to test this?

**Comment by KjellMorgenstern** [comment]
In ac93ed7, i made the following fix for nested scaling:
```
--- a/src/utils/textutils.cpp
+++ b/src/utils/textutils.cpp
@@ -903,7 +903,12 @@ QMatrix TextUtils::transformStringToMatrix(const QString & transform) {
                return QMatrix(floats[0], floats[1], floats[2], floats[3], floats[4], floats[5]);
        }
        else if (transform.startsWith("scale")) {
-               return QMatrix().scale(floats[0], floats[1]);
+               if (floats.size() == 2) {
+                       return QMatrix().scale(floats[0], floats[1]);
+               } else {
+                       Q_ASSERT(floats.size() == 1);
+                       return QMatrix().scale(floats[0], floats[0]);
+               }
        }

```

**Comment by KjellMorgenstern** [comment]
Might or might not be related. Without further information, we can close this.
