### ISSUE TITLE
SMD pads are rendered too large in PCB view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2039]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on June 17, 2012 07:07:33_

I just built a custom part with quite tiny pads in Illustrator. When opening it in Fritzing, all pads run into one another, creating one big blob. I checked in various views (see screenshots), and it turns out that it's only happening in PCB view. Gerber output and even the parts editor's pcb view are fine.

**Attachment:** [microsd-fritzing.PNG microsd-illustrator.PNG microsd-gerber.PNG microsd-partseditor.PNG microsd-socket-molex-502774-0891-pcb.svg](http://code.google.com/p/fritzing/issues/detail?id=2039)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2039_

**Comment by KjellMorgenstern** [comment]
Can not reproduce this issue (edgy motor example looks fine)
