### ISSUE TITLE
breadboard connection highlighting colors

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2041]
_From [orgfritz...@gmail.com](https://code.google.com/u/115834879217412145280/) on June 18, 2012 05:20:04_

As mentioned, it would be nice to have colored ratsnests.

Rules:
1. Don't highlight anything on a breadboard, before two components are connected.
1. If two components are connected, pick a color for the highlights.
2. If a cable is connected onto the bus, highlight with the cable color.

**Attachment:** [Bildschirmfoto 2012-06-17 um 08.45.03 – 17.06.2012 Kopie.png](http://code.google.com/p/fritzing/issues/detail?id=2041)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2041_

**Comment by KjellMorgenstern** [comment]
Highlights are configurable via the preferences, closing this issue.

Other related issues to think about:
- Ratsnest lines colors should be defined better, they appear to be random
- Make it somewhat easy to sync colors between schematic and breadboard, but the default to blue and black should stay.
