### ISSUE TITLE
logoitem sometimes doesn't let you shrink it beyond a certain point

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2049]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 20, 2012 08:16:11_

could it have to do with the aspect ratio calculation?  Try it with aspect-ratio turned off.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2049_

**Comment by failiz** [comment]
I could not reproduce it in 0.9.4 and it was (at least partially) fixed
