### ISSUE TITLE
enable swapping between bendpoints and vias in pcb view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2054]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 21, 2012 13:39:03_

this goes with some other suggestions about making it easier to draw vias when drawing traces.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2054_

**Comment by failiz** [comment]
I could not replicate the last comments in 0.9.6

**Comment by KjellMorgenstern** [comment]
Did you try a bendpoint with four connections?

**Comment by failiz** [comment]
I tried with three points  before. Now I tried with four points and no error either. Ae you able to replicate this? The only problem I found is the issue when connecting four traces to a bendpoint (when you move a bendpoint, only three of them move and the four one doesn't), but this is fixes after you convert it to a via. And this gets fixed when changing to a via or bendpoint later.

**Comment by KjellMorgenstern** [comment]
Ok, just wanted to rule out that this is a related issue. So
we can close this.
