### ISSUE TITLE
Placing an SMD part in breadboard view doesn't change board to double-sided

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2059]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on June 22, 2012 14:24:40_

What steps will reproduce the problem? 1. Blank sketch, breadboard view
2. Drag an SMD part onto the sketch (not via swap, so it has to be one from the new sets)
3. Go to PCB view

The PCB will still be single-sided, with the SMD part grayed out.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2059_

**Comment by failiz** [comment]
I think by default is double sided.
If change it to single sided, the Pcb does not change to double sided when added a SMD part. But it does not allow to move the smd parts to the top layer, so I do not see an issue. After changing the pcb to 2 sided, then you can move the parts to top layer.
