### ISSUE TITLE
make holes look different from vias

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2068]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 24, 2012 09:05:42_

users are confused by the two types, and having them appear different would help a little.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2068_

**Comment by failiz** [comment]
Not sure what the issue was exactly, the vias and holes look different in the icons. In addittion, the holes do not have a copper ring by default and thy are much bigger.
