### ISSUE TITLE
gerber silkscreen on copper that is not a connector

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2072]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on June 27, 2012 06:06:43_

No production stop, but strange anyway: The Panel 0 from order 00021 has got a pcb with a custom part where silkscreen still runs over copper pads. It is at the right edge in the middle on the panel and called RGB DMX V1 – the part is centered. Screenshot attached.

**Attachment:** [Bildschirmfoto 2012-06-27 um 12.03.09 – 27.06.2012.png](http://code.google.com/p/fritzing/issues/detail?id=2072)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2072_

**Comment by KjellMorgenstern** [comment]
If copper is not declared as a connector, then we want to allow silkscreen on it.
