### ISSUE TITLE
Make Fritzing more useful for textile/Lilypad projects

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2081]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on July 02, 2012 06:38:07_

Some things that would probably help:

Breadboard view:
- its own wire type "conductive thread", with a little texture on it
- a piece of cloth, much like a pcb shape: sticky, and maybe also a possibility to change color and/or shape

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2081_

**Comment by failiz** [comment]
I think that it is a very specific enhancement for a a few users. Not sure if it is worth the work.
Is this still in the pipeline? If so, remove the imported label. If not, close the issue.

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
Inactive issue since a long time. We didn't receive any requests about textile elements in the last year. Although that would be a nice-to-have, closing this now. 

If you can provide a use case or specific requirements for a similar feature, please be welcome to open a new issue.
