### ISSUE TITLE
Distributing Fritzing for RaspberryPi

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2082]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on July 02, 2012 07:02:38_

It seems like it's best to go with Qt5 beta. There's a lot of work done already, and Qt4 seems to be not efficient enough: http://qt-project.org/wiki/RaspberryPi http://qt-project.org/wiki/Qt-RaspberryPi On the other hand, there's a tutorial on how to build Qt4 apps for it, but it also looks quite complex: http://www.meegoexperts.com/2012/03/raspberry-pi-case-study-deploying-qt-apps-generic-linux-devices/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2082_

**Comment by failiz** [comment]
Is this still in the pipeline? I guess that it is more up to the package managers of the RP distributions.

**Comment by KjellMorgenstern** [comment]
I made some quick tests with cross compiling for the PI. Its on the todo for packaging, but there are some other distros we want to cover first
