### ISSUE TITLE
.fp import from the parts editor not working under 10.6.8

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2083]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 02, 2012 22:52:11_

perhaps the file extension string isn't properly formatted for mac?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2083_

**Comment by failiz** [comment]
This issue is very old and it was found to be unable to replicate
