### ISSUE TITLE
one command to convert all ratsnests in a given view to wires

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2084]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 03, 2012 00:12:29_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2084_

**Comment by failiz** [comment]
I do not think that this is a good idea. What is the user case for this command? 
If there are ratsnets, the circuit has been wired in other views. If this command is used, the view would be wired but it still needs to be cleaned. The components appear at "random" positions and the view would be very messy. Fritzing is well known to produce ugly schematics if you are not careful. This command will just make them even worse. Specially, beginners will use it and think that the work is done.

**Comment by KjellMorgenstern** [comment]
Sounds like adding an autorouter in breadboard view. Won't fix unless someone comes up with a really good reason. The schematics view already has an autorouter, which would result in this conversion.
