### ISSUE TITLE
make screwterminals swappable with pinheaders

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2087]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 03, 2012 10:23:39_

perhaps combine classes?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2087_

**Comment by failiz** [comment]
Not sure if this is worth the effort. You can always delete the part and add a new one
