### ISSUE TITLE
Ground fill does not (always) connect vias to ground planes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2095]
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on July 06, 2012 08:59:24_

In the attached example, the parts on the right are set to ground seed (one pad and two vias). Still, when generating the ground planes, the via on the bottom right corner is not connected to ground, neither top or bottom planes.

Vias are used to bind ground planes together (top and bottom planes) and sending signals to ground, so the two vias on the right should be connected to both generated ground planes, since they were set to ground seed.

Or maybe I completely misunderstood the way this should be used.

**Attachment:** [ground_test.fzz](http://code.google.com/p/fritzing/issues/detail?id=2095)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2095_

**Comment by KjellMorgenstern** [comment]
None of the reference images from google code are available anymore. Closing this in favor of #3794
