### ISSUE TITLE
Groundfill gets confused about rectifier circuit, shortens Vcc/GND

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2096]
_From [casch...@mac.com](https://code.google.com/u/116291006804426827631/) on July 07, 2012 06:26:29_

What steps will reproduce the problem? 1. Open attached sketch
2. Go to pcb view
3. Look at middle bottom, where the rectifying circuit is
4. Groundfill shortens Vcc/GND Attach your sketch file and/or custom part files to the bug report. Done. What is the expected output? What do you see instead? I expect that groundfill will not shorten Vcc/GND, but I think thats hard in a circuit like the attached. Maybe groundfill should show a warning about this. What version of Fritzing are you using? On what operating system? 0.7.5b; Mac OS X 10.7.4 Please provide any additional information below. -

**Attachment:** [QlockThreePcb_v04.fzz](http://code.google.com/p/fritzing/issues/detail?id=2096)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2096_

**Comment by failiz** [comment]
The file is not available. I do not understand why "I expect that groundfill will not shorten Vcc/GND, but I think thats hard in a circuit like the attached"

**Comment by failiz** [comment]
With the recent changes to the ground-fill algorithm, we can probably close this issue. Again no file to debug and probably the previous version was shortcircuiting wrong pads.
