### ISSUE TITLE
createZipAndSaveTo needs list of extensions to save (or ignore)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2099]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 08, 2012 04:44:01_

fzz files sometimes include junk

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2099_

**Comment by failiz** [comment]
Outdated? I have never seen the createZipAndSaveTo option

**Comment by failiz** [comment]
Ping
