### ISSUE TITLE
frtizing crashes instead of giving an error message when searching for a part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2120]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 17, 2012 05:18:18_

remove the file sparkfun-connectors_usb-a-h_breadboard.svg from svg/user/breadboard and search for "usb"

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2120_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.4 (windows). The program searches well. When trying to use the part, the program informs that there was a problem finding a file and do not crash.
