### ISSUE TITLE
peppermill power board: pins not on grid.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2125]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 20, 2012 08:21:17_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2125_

**Comment by failiz** [comment]
I cannot find that part. In any case, this should go to the parts repository.

**Comment by KjellMorgenstern** [comment]
Issue only visible in breadboard view, but spacing is correct (100mil) in PCB view. Very old part. Closing this for now.
