### ISSUE TITLE
Fritzing crashes after rotating 45° and changing layer of copper blocker

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2127]
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on July 21, 2012 18:11:17_
1. Open a new sketch.
2. Drag a copper blocker from the core parts and release it on top of a PCB (this is important)
3. Change its size, either with the mouse or in the inspector (this is important).
4. Rotate it by 45° (either clockwise or anti clockwise).
5. In the inspector, change it from copper0 to copper1.

Result: the copper blocker moved. This is already a bug. To evidence it better you can choose to resize the copper blocker to a smaller size (it is important to resize it, either bigger or smaller, but you can choose to make it smaller to see better the effect). It also can happen when changing back from copper1 to copper0, but you need to change the size of the copper blocker in between. It is possible to rotate several times successively 45°, or rotate back to initial value, with varied results (sometimes moves, sometimes not).

Now, by repeating these operations several times successively on several copper blockers, or by rotating them several times 45°, it is possible to crash, although I did not find a systematic way to reproduce the crash.

I could obtain a crash with current 0.7.5b release binary under windows, and using master ( r6195 ) under linux amd64. Attached two gdb backtraces taken on the linux system for two crash events. 

I used “make debug” of Fritzing, please tell me if I can make it more verbose. (If needed, I can also recompile Qt to get Qt debugging symbols.)

**Attachment:** [crash1.txt crash2.txt](http://code.google.com/p/fritzing/issues/detail?id=2127)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2127_

**Comment by failiz** [comment]
I could not replicate the crash in 0.9.6, but the copper block or logo or pad moves when switching from top to bottom (specially when they are rotated 45 degrees).
Change title to be more representative of the issue. Remove imported label, add pcbview

**Comment by KjellMorgenstern** [comment]
Looks like this was fixed, no offset when switching logos, pads or blockers from top to bottom layer (copper and silkscreen)
In 0.9.10 the label position jumps/resets when switching the layer. There will be several improvements for label positioning in v1.0.0,
