### ISSUE TITLE
export for production: multiple copies on a page

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2130]
_From [uscatu...@gmail.com](https://code.google.com/u/113011850106126045779/) on July 22, 2012 17:44:03_

is possible to ad function in export for production to select how many pcb to export on same pdf page 1, 2, 4..10

idea..
chose position of pcb in the page left up, right up, left down, center.... on export for production 

Best Regards 
Sebastian Uscatu

P.S.
Great Job..
Thank you guys... What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2130_

**Comment by failiz** [comment]
Is this the same as the panelizer? I think there is a panelizer tool that can be used

**Comment by failiz** [comment]
Panelizer will be removed, close?
