### ISSUE TITLE
Rotating a non-sticky PCB also rotates the part labels

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2132]
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on July 23, 2012 07:37:04_
1. Drop a component on the PCB. Make sure the PCB is not set to sticky (nor locked).
2. Rotate the PCB by any angle.

Result: the part labels rotated together with the PCB.

Regarding the picture below :
- The label stay quite close from the component because the board is very small. If the board is large, the rotation makes them go far away.
- It seems silly to rotate a square board without setting the sticky property, but it does make sense if the board is a shield or has a custom shape.
- I set the “lock” icon only for the picture (to enhance visibility of the orientation). The board was not locked when it was rotated.

**Attachment:** [bug-rotation-3.png](http://code.google.com/p/fritzing/issues/detail?id=2132)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2132_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.9
