### ISSUE TITLE
Custom Shrouded header display issues

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2139]
_From [mightybm...@gmail.com](https://code.google.com/u/101725927284918787532/) on July 27, 2012 00:35:25_

What steps will reproduce the problem? 1. I copied a generic 6 pin shrouded header to my bin.
2. I deleted the connections and made six new connections to match the programmer pin out specifications. I updated a 3 views.
3. When I apply my new part, no icon image is displayed. The pin order in the schematic is out of order but beadboard and pcb are correct. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I wanted the generic icon display in the parts bin. I wanted the pin order to be listed 1-6 in order on schematic view. Other two views are correct. What version of Fritzing are you using? On what operating system? 0.7.5 on Windows 7 Please provide any additional information below.

**Attachment:** [Atmel ISP connector.fzpz](http://code.google.com/p/fritzing/issues/detail?id=2139)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2139_

**Comment by failiz** [comment]
Not enough info to try to replicate it.

**Comment by KjellMorgenstern** [comment]
Those kind of issues might be mitigated by Fritzing checking parts for errors. There is an open ticket about that feature.
