### ISSUE TITLE
more lbr issues

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2143]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 30, 2012 07:21:54_

fill in all closed polygons in schematic view, not just rectangles?  Also deal with the cases where there are more than 4 wires, but still a rectangle.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2143_

**Comment by failiz** [comment]
Move to parts repository?

**Comment by KjellMorgenstern** [comment]
.
I think most of the issues described here would have been about code in the application, although it's about parts.

Anyway, closing: at least partly fixed, outdated and some information seems missing.
