### ISSUE TITLE
crash when swapping from single-sided to double-sided

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2147]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 04, 2012 02:45:39_

start with attached file. Drop an smd part (I searched for "jack" and took the first part from the search parts bin). When the message comes up that says "swap to double-sided" say "yes". Boom.

**Attachment:** [holetest (1).fzz](http://code.google.com/p/fritzing/issues/detail?id=2147)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2147_

**Comment by failiz** [comment]
The author of the issue was unable to replicate the bug after a full rebuild. Old issue, unable to replicate and the file o test is not available. Close.
