### ISSUE TITLE
differentiate between file not found, and file is broken in panelizer

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2152]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 06, 2012 10:34:05_

in 00024 in file SH_SE_SMDvQuadrov2-1.fzz, the custom part svg for pcb has no copper and the panelizer rightly puts up an error. However, it would be nice if the error said "the svg is messed up" rather than "the svg is missing".

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2152_

**Comment by failiz** [comment]
Panelizer will be removed,  close?
