### ISSUE TITLE
crowdsourced regression testing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2153]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 07, 2012 05:53:27_

A really nice suggestion from Till--outsourcing testing. Basically, we could set up a web infrastructure to enable any Fritzing user to test a new release candidate against one issue. We collate the results (plus any new issues that turn up).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2153_

**Comment by failiz** [comment]
Nice idea, but maybe it is too complex to setup with the current work force...

**Comment by KjellMorgenstern** [comment]
A setup like described here would be a big organizational effort, with uncertain outcome. 

Some github plug-ins / tools or dedicated testing services might help, but that are different issues.
