### ISSUE TITLE
deal with comma instead of period as decimal point in svgs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2171]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 20, 2012 06:49:17_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2171_

**Comment by failiz** [comment]
Not sure if this has been implemented yet. Any idea?

**Comment by KjellMorgenstern** [comment]
Close for now. Should be quite easy to identify in case it poses a problem.
