### ISSUE TITLE
when I right click in a component add the option "Open inspector" in the menu

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2172]
_From [c.marin....@gmail.com](https://code.google.com/u/111573134106332776943/) on August 20, 2012 17:20:59_

What steps will reproduce the problem? 1. go to schematic view
2. select one component you have in the schematic view (for example a resistor)
3. right click int hat component, you will get a menu.
In that menu it will be fine it would appear an option "open inspector view" to open the inspector menu (the same window that appears when you click at Window -> Inspector)

I had closed that windows and I did not know how to edit some components.

I am using Fritzing 0.7.5 in Windows 7 64 bits.

Fixing this issue, it will improve the usability of the software.

Thanks,

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2172_

**Comment by failiz** [comment]
Mmm, this option is in view. Not sure if it is worth it to implement in the contextual menu
