### ISSUE TITLE
breadboard is not aligned to grid

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2176]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 21, 2012 04:45:29_

This seems to cause connection problems under linux.  default pcb is not aligned to grid either.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2176_

**Comment by KjellMorgenstern** [comment]
Closing in favor of #3077
