### ISSUE TITLE
folder share/ not found in version 0.7.7

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2184]
_From [alanc...@gmail.com](https://code.google.com/u/111787383127216024467/) on September 01, 2012 17:56:45_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? 0.7.7. linuxmint 13 xfce x64 kernel 3.5 Please provide any additional information below. not present folder share in version.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2184_

**Comment by failiz** [comment]
The issue is not clear and it cannot be debugged.
