### ISSUE TITLE
ground fill is connected only to the lower side

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2186]
_From [th.gauwe...@googlemail.com](https://code.google.com/u/114319454448349078647/) on September 03, 2012 05:52:49_

What steps will reproduce the problem? 1. define a pin hole
2. set ground fill seeds
3. fill up with gnd

The pins are only connected to GND on the lower side, but not to the upper side of the pcb.

The file contains the connector for an antenna at the bottom right.
The four pins around the middle pin are connected to GND.

**Attachment:** [RFM12 breakout masse.fzz Screenshot gc viewer antenna.png](http://code.google.com/p/fritzing/issues/detail?id=2186)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2186_

**Comment by KjellMorgenstern** [comment]
Created PR #3555 for this

**Comment by ElectricRCAircraftGuy** [comment]
Glad you fixed this problem finally (after 5 yrs)! Unfortunately, I have long-ago moved to a much more professional free and open source program, [KiCad](http://www.kicad-pcb.org/) as a result of my problems with Fritzing, and I very strongly recommend KiCad to anyone looking to make professional PCB and circuit diagram products.
