### ISSUE TITLE
ratsnest in schematic view not updated after labeling a IC pin and IC changes size

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2194]
_From [boo...@nc.rr.com](https://code.google.com/u/108888894911553875363/) on September 04, 2012 09:49:37_

What steps will reproduce the problem? 1. In breadboard, add generic IC and resistor. Add one wire from resistor to IC pin 1.
2. Switch to schematic view and move components if you wish.
3. Edit label of IC pin 1 from "1" to "groundfoobar".  (I really just want "ground" but a longer name better illustrates.) Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? Expected to see the ratsnest updated.  The IC changes size in the schematic view but the ratsnest to IC pin 1 does not update, is left NOT at the end of the IC pin, but for example in the middle of the IC. What version of Fritzing are you using? On what operating system? 7.7 on Ubuntu 12.04 Please provide any additional information below. I did not include a sketch because the view corrects itself when you open the sketch file.

Workaround: switch to PCB view.  Autoroute.  Now the schematic view shows correct ratsnest.

Autoroute in schematic view sometimes workarounds (painting black lines instead of ratsnest), depending on how you have rotated or positioned the IC in schematic view before changing the pin 1 label.

This is frustrating since it is hard to know what particular sequence of view changes and autoroutes will update the schematic view ratsnest correctly.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2194_

**Comment by failiz** [comment]
Still an issue in 0.9.9. Before changing the name of pin 1:
![image](https://user-images.githubusercontent.com/5708642/147709454-094c94b0-9e40-40e4-ae91-e1dc04464e6e.png)
After changing the name of pin 1:
![image](https://user-images.githubusercontent.com/5708642/147709496-128f0d0c-0e19-4a37-bec5-4f9bc224ef56.png)

This also happens in the mystery part:
![image](https://user-images.githubusercontent.com/5708642/147709534-790a8c4e-a92a-437c-9a9f-d101623eefdf.png)

**Comment by failiz** [comment]
This is the same problem that I had in #1326. It can be fixed by forcing a updateRoutingStatus. See 
https://github.com/fritzing/fritzing-app/issues/1326#issuecomment-950145724
