### ISSUE TITLE
printing preview

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2195]
_From [uscatu...@gmail.com](https://code.google.com/u/113011850106126045779/) on September 04, 2012 15:45:15_

print preview can be greath

Best Regards 
Sebastian Uscatu

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2195_

**Comment by failiz** [comment]
Related to #653

**Comment by KjellMorgenstern** [comment]
We have a print option in the file menu, also we have the PDF export. 
I think we can close this issue.
