### ISSUE TITLE
File not loadable

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2198]
_From [smur...@gmail.com](https://code.google.com/u/100994285043858694248/) on September 06, 2012 03:15:32_
1. try to load the attached file
2. get an error: unable to load '' at ''
3. get an empty Fritzing view
4. run around in circles and tear out hair
   because I need that damn schematic!

This is 0.7.7b from Debian testing.

**Attachment:** [Power.fzz](http://code.google.com/p/fritzing/issues/detail?id=2198)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2198_

**Comment by failiz** [comment]
No file to debug and it was unable to replicate.
