### ISSUE TITLE
on startup, fritzing should detect whether there's a newer version available, and notify the user

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#220]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 12, 2008 06:45:51_

For the first implementation, Fritzing will send a query to the website
asking for the version string of the latest release.  Fritzing will compare
its version to the one it gets from the website, and if Fritzing's version
is older, Fritzing will launch the default browser to a Fritzing site for
downloading a new version.

Eventually, Fritzing could skip launching to the website, and instead,
directly notify the user that a new version is available, and if the user
grants permission, Fritzing will download the new version, and install the
new binary.  We may need a small secondary executable to handle this.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=220_

**Comment by failiz** [comment]
Has this not been implemented ?
