### ISSUE TITLE
Breadboard full+ should have all pins on 1/10 grid

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2201]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on September 07, 2012 02:57:08_

The power row holes are slightly off the grid so that wires from the outer row holes to the inner row holes are always looking wrily.

**Attachment:** [screenshot.png](http://code.google.com/p/fritzing/issues/detail?id=2201)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2201_

**Comment by failiz** [comment]
I cannot reproduce this in 0.9.6
