### ISSUE TITLE
Fritzing is blurry when using a retina display

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2204]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 09, 2012 23:41:03_

See forum post: http://fritzing.org/forum/thread/1080 For a potential solution see http://www.qtcentre.org/threads/50130-Qt-Creator-on-MacBook-Pro-Retina . Does adding this to info.plist mess anything up for non-retina displays?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2204_

**Comment by failiz** [comment]
Qt5 is in use now. I think that we are handling retina displays. Is this outdated?

**Comment by KjellMorgenstern** [comment]
Looks good on Big Sur with retina. There might still be issues, but not as generic as this issue suggests. Closing
