### ISSUE TITLE
change linux instructions on download page?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2211]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 15, 2012 05:36:09_

does sudo apt-get install Fritzing work under ubuntu?

also update the one-click debian script from Bruno

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2211_

**Comment by failiz** [comment]
outdated?
