### ISSUE TITLE
custom board shape confuses collectBorderPoints

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2219]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 24, 2012 08:32:10_

when the shape is upright collectBorderPoints works fine; when the board is rotated right so that the 'crack' is uppermost, collectBorderPoints gets very confused

**Attachment:** [custom board.svg](http://code.google.com/p/fritzing/issues/detail?id=2219)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2219_

**Comment by failiz** [comment]
File not available. If we keep it, remove imported label.

**Comment by KjellMorgenstern** [comment]
Several related issues have been fixed in 0.9.6, without a file to recheck, we can just close this one.
