### ISSUE TITLE
suggesting new default colors for background and breadboard

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2220]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on September 24, 2012 08:32:57_

like in the image to brighten things up :)

**Attachment:** [newColors.jpg](http://code.google.com/p/fritzing/issues/detail?id=2220)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2220_

**Comment by failiz** [comment]
Not enough info and link is gone
