### ISSUE TITLE
More standard hole / screw sizes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2223]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on September 25, 2012 12:04:36_

Currently it's just M2, M3, M4.

The standard screw sizes also include:
M1.6    M2  M2.5    M3  M4  M5  M6  M8  M10 M12 M16 M20 M24 M30 M36 M42 M48 M56 M64

From: http://en.wikipedia.org/wiki/Screw

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2223_

**Comment by failiz** [comment]
Add PCB View and remove imported label. Check comment Kjell´s comment in https://github.com/fritzing/fritzing-app/pull/3349#pullrequestreview-235224292
I guess that M8 is probably the maximum that we should include...
