### ISSUE TITLE
support tabbing + spacebar to dismiss a dialog

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2224]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 25, 2012 22:40:03_

this is a windows shortcut. not sure about the other platforms

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2224_

**Comment by failiz** [comment]
This works in the preferences dialog and in the autorouter settings dialog

**Comment by KjellMorgenstern** [comment]
Also checked file open dialog on ubuntu, works fine
