### ISSUE TITLE
export SPICE netlist

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2228]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 30, 2012 09:04:42_

See the comment by Chipmuenk in http://fritzing.org/forum/thread/413

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2228_

**Comment by angelopolotto** [comment]
Something new about this issue? I thinking to write a fritzing to SPICE netlist converter in Python. I tried search something like that but I din't have success. I don't know if already exists something like that in the Github.

**Comment by aknoerig** [comment]
There was already some groundwork done with a [spice section in the file format](https://github.com/fritzing/fritzing-app/wiki/2.1-Part-file-format#spice-modeling-optional). There's also an export that collects all spice info from the parts in the sketch. Take a look at the [spice-related code](https://github.com/fritzing/fritzing-app/search?q=spice&unscoped_q=spice).

Not knowing spice well, I assume it's more about providing spice models for all the parts in the parts library than anything else.

**Comment by WimberleyTech** [comment]
Every time a new part is added, a SPICE model for that part would also need to be included.  Trivial for a resistor,  but completely unrealistic for an Arduino Nano.  My view on SPICE netlist is the same as for the code tab--bad idea--a distraction.

**Comment by angelopolotto** [comment]
I will read the link resources. Thank you @aknoerig !

**Comment by failiz** [comment]
I think this issue should be closed. I tested the export to SPICE netlist and it works correctly. Of course, just a few parts have filled the spice field, but they can be added editing the parts in a text editor and regenerating the database afterwards. However, this is a different problem related to the parts, not the the code of the application.

**Comment by KjellMorgenstern** [comment]
Thanks @failiz , I agreee. Just before closing this, can you upload the file you used for testing, as a future reference?

**Comment by failiz** [comment]
Here you go. This is a voltage divider circuit and the generated spice netlist.
[voltage_divider.zip](https://github.com/fritzing/fritzing-app/files/5348869/voltage_divider.zip)
