### ISSUE TITLE
how to make a release needs updating

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2233]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 02, 2012 05:37:43_

1. remove it from the fritzing site

2. add it to the ixds wiki

3. instructions are out-of-date for all three platforms

for example:

-- dmg wrapper for mac
-- custom build QtSDK for three platforms, probably requires 10.6

-- need to update plist and version resource

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2233_

**Comment by aknoerig** [comment]
now in the github wiki
