### ISSUE TITLE
trace wire connected to (hidden) normal wire

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2236]
_From [pet...@esdm.co.uk](https://code.google.com/u/110394238758319246204/) on October 04, 2012 16:34:17_

Just run the DRC using my sketch and it crashes and burns

Windows XP SP3 fully updated 
Fritzing 0.7.7 (b6329 2012-08-14)[Qtr 4.8.2]

My Visual Studio JIT debugger kicks in but no useful information is to be had.

**Attachment:** [PhoenixV3.fzz](http://code.google.com/p/fritzing/issues/detail?id=2236)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2236_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
