### ISSUE TITLE
Colorize copper traces belonging to different nets

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2244]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on October 09, 2012 05:02:48_

We do this for ratsnests already, so why not for traces? This would make it much easier to do manual routing, and also easier to understand.

Of course we would need to visually differentiate them from ratsnests. This might be done by choosing a different color set that's closer to the copper color that we already have, or by making ratsnests different types of lines, stippled or something.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2244_

**Comment by failiz** [comment]
I think it would be too confusing, specially for two sided boards
