### ISSUE TITLE
The controls on the connectors editor in the new parts editor are not showing correctly

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2249]
_From [pet...@esdm.co.uk](https://code.google.com/u/110394238758319246204/) on October 10, 2012 03:06:03_

Edit a part with the new parts editor

The controls on the connectors editor in the new parts editor are not showing correctly, They appear to be too short and the contents is not visible.

Running Windows XP Pro Fully Updated.

Screen shot attached.

**Attachment:** [PE_Screenshot.png](http://code.google.com/p/fritzing/issues/detail?id=2249)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2249_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
