### ISSUE TITLE
Part>Add to bin>Search after clean start crashes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2255]
_From [boo...@nc.rr.com](https://code.google.com/u/108888894911553875363/) on October 11, 2012 08:25:56_

What steps will reproduce the problem? 1.start Fritzing
2.Choose Part>Add to bin>Search 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I dont' know what to expect, I was just learning.

I saw a crash and this output in console (from debug build.)

"after palette model" 
"open progress /home/bootch/.config/Fritzing/bins/search.fzb" 
"loading bin 'Search'" 
"done loading bin 'Search'" 
"close progress /home/bootch/.config/Fritzing/bins/search.fzb" 
QGraphicsLinearLayout::itemAt: invalid index -1
Segmentation fault (core dumped) What version of Fritzing are you using? On what operating system? Ubuntu 12.04
fritzing-0.7.6b.source is what I downloaded and built using "make -f Makefile.debug" Please provide any additional information below. The sketch was empty.  No part was selected.

Probably not a high priority. Most users will probably do a search before trying to examine the search bin?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2255_

**Comment by failiz** [comment]
Unable to reproduce it. Add to bin is disable at startup.
