### ISSUE TITLE
Arduino Pins should snap onto Arduino Shield PCB.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2275]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on October 23, 2012 06:04:23_

Arduino Pins should snap onto Arduino Shield PCB that they match perfectly.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2275_

**Comment by failiz** [comment]
Not sure what is the purpose of this is. Not enough info.

**Comment by KjellMorgenstern** [comment]
Maybe one of the shield / arduino uno pcbs did not match a real arduino, producing broken shields? If that was the problem, it seems solved.
