### ISSUE TITLE
swap 5mm tht LED for a 3mm tht LED, but cannot swap back

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2278]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 23, 2012 07:51:06_

if you swap from the 3mm based on the package property, choosing 5mm tht gets you the 5mm rgb led, and from there you can't swap back to the original led

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2278_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.5 (dev). You can swap them and everything works as expected in the PCB and bb views.
