### ISSUE TITLE
Exception in drag move event 61

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2279]
_From [casch...@mac.com](https://code.google.com/u/116291006804426827631/) on October 23, 2012 09:01:23_

What steps will reproduce the problem? I don't know Attach your sketch file and/or custom part files to the bug report. Done. What is the expected output? What do you see instead? O don't know. What version of Fritzing are you using? On what operating system? Version 0.7.10 (b6551 2012-10-12) Cocoa (Qt 4.8.2) on Mac OS X 10.8.2 Please provide any additional information below. -

**Attachment:** [Atari Punk Console.fzz exception.png](http://code.google.com/p/fritzing/issues/detail?id=2279)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2279_

**Comment by failiz** [comment]
File is gone and nobody could replicate it
