### ISSUE TITLE
Autorouter should respect wire size specified on schematic.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2281]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on October 25, 2012 21:08:29_

What steps will reproduce the problem? =====================================================
1. Create schematic and specify different wire sizes.
2. Switch to PCB, place components and auto-route.
3. Observe that the traces the autorouter makes are all the same width and do not relate to the wire size specified in the schematic. What is the expected output? What do you see instead? =====================================================

The autorouter should create traces that are consistent with the wire sizes on the schematic. What version of Fritzing are you using? On what operating system? =================================================================
0.7.10 b6551 2012-10-12, Ubuntu 64 Bit

**Attachment:** [sizes.fzz](http://code.google.com/p/fritzing/issues/detail?id=2281)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2281_

**Comment by failiz** [comment]
It is not possible to set the width of a line in the schematic view, see #2734. Close.
