### ISSUE TITLE
smd pinheader layer swap doesn't work

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2282]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 26, 2012 02:13:56_

http://fritzing.org/forum/thread/1200

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2282_

**Comment by failiz** [comment]
From the old forum: "I'm working with version 0.7.10 and wanting to mount smd pin header on copper0, currently on copper1. Each time I change this in the inspector it just automatically changes back.
Looks like the work around it to set the layer that you want to have the pin header on before you place it. This works but is not so flexible."
I could not replicate this in 0.9.6 (I guess copper0 and 1 are now top and bottom, or did I understand something wrong?)

**Comment by KjellMorgenstern** [comment]
Yes, copper0 and copper1 is how the to and bottom copper layers are called in parts format and in the code
