### ISSUE TITLE
Connections are not updating

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2285]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on October 31, 2012 13:35:07_

In the attached sketch, two of the FSRs in the lower left (J24 and J26) are displayed differently from how they are actually connected.
It will become apparent when you pick one of them up and move it.

So far we don't know any of the steps the user has gone through. From looking at the sketch, it could have been a copy/paste.

**Attachment:** [2709_pcb_print_test_am(1)_16sensors_routing_complete.fzz](http://code.google.com/p/fritzing/issues/detail?id=2285)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2285_

**Comment by failiz** [comment]
The file is not available
