### ISSUE TITLE
layer property (backplane SMDs) stopped working

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2287]
_From [jerome.b...@gmail.com](https://code.google.com/u/109375043177863169589/) on November 02, 2012 05:15:37_

In latest svn ( r6610 ), the "layer" property in the Inspector is greyed out and does not allow to set new parts to the bottom plane. Existing designs saved with components on the bottom plane work fine, and it's possible to get more components on the bottom plane by copy-paste.

On the attached image, you can see the "layer" property is greyed out while a copper0 SMD is selected (taken from an existing design).

Using linux 64 bits.

**Attachment:** [bug-SMD-copper0.png](http://code.google.com/p/fritzing/issues/detail?id=2287)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2287_

**Comment by failiz** [comment]
Not enough information to replicate the issue.
