### ISSUE TITLE
use opencl for autorouting, ground plane generation, etc

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2288]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 05, 2012 08:00:04_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2288_

**Comment by KjellMorgenstern** [comment]
This issue is closed due to inactivity.
If you think this issue is still important, please reopen and provide additional information.
