### ISSUE TITLE
since fzz is now standard, rethink the location of part svg files?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2290]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 06, 2012 01:26:29_

could part svg files be whereever the user wants them, since the files get saved as part of the fzz?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2290_

**Comment by failiz** [comment]
outdated?
