### ISSUE TITLE
add routing to breadboard view?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2291]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 06, 2012 07:22:30_

http://fritzing.org/forum/thread/1213

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2291_

**Comment by failiz** [comment]
I think this is not feasible with the current developers time and not very useful either. It will not generate professional breadboard and for teaching you want that they do not use shortcuts.
