### ISSUE TITLE
Problem editing a part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2295]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on November 09, 2012 08:50:19_

From the forum: http://fritzing.org/forum/thread/1032/?page=all#post5729 "I did not modify an ULN2003 to ULN2803 !  I renamed the part, made some modifications, tried to save them, the program crashed, when opening again I found an ULN2803 and assumed it was the part I was trying to make!! It is not so; an ULN2803 is included in Fritzing from the beginning, I just did not find it immediately, then tried to make one and apparently failed."

I can't replicate it yet, but asked the author to add details.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2295_

**Comment by failiz** [comment]
I did not manage to reproduce this. In the old forum , one of the developers also did not manged to reproduce it and asked for precise steps. There was no answer. Close
