### ISSUE TITLE
Fritzing crashes while DRC

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2297]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on November 13, 2012 05:00:23_

Fritzing crashes if I design rule check the attached file.

**Attachment:** [19786534_BatFrizzingV3.fzz](http://code.google.com/p/fritzing/issues/detail?id=2297)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2297_

**Comment by failiz** [comment]
A fix has been implemented to avoid the crash and the file is not available
