### ISSUE TITLE
5mm LEDtht And 3mm LEDtht have same footprint.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2298]
_From [kimk_...@hotmail.com](https://code.google.com/u/106273365127507070939/) on November 13, 2012 06:02:47_

What steps will reproduce the problem? 1.Put a 5mm LEDtht on the pcb.
2.Change value to a 3mm LEDtht.
3.Nothing Changes What version of Fritzing are you using? On what operating system? 0.70.10

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2298_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.5 (dev). The silkscreen changes in the pcb view.
