### ISSUE TITLE
Fritzing Crash on Mouse Hover

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2301]
_From [dta1160...@gmail.com](https://code.google.com/u/101018307322424384636/) on November 14, 2012 09:19:32_

What steps will reproduce the problem? 1. Open Fritzing, then hover over a few parts, then hover over the vertical scroll bar and Fritzing will crash. 
2.none 
3.Version 7.10 b6551 Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below. This problem does not occur with version 7.5 b6130

I am running a HP Laptop Win7 Pro 64bit.

I would love to contribute, It seems like a fine program, but I will need to see it more stable before I commit.

Dave

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2301_

**Comment by failiz** [comment]
Unable to replicate this in 0.9.5 (dev) in Windows 10. Maybe related to #2522

**Comment by KjellMorgenstern** [comment]
Outdated and can not reproduce, closing
