### ISSUE TITLE
Fritzing Crashes on Mac every time I print

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2302]
_From [okach...@gmail.com](https://code.google.com/u/106148137825627474816/) on November 15, 2012 17:08:21_

What steps will reproduce the problem? 1. Open the attached project with Fritzing 0.7.10 b6551 on OSX 10.6.8
2. Select Print 
3. Observe crash...

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Application Specific Information:
abort() called

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   libSystem.B.dylib               0x00007fff832880b6 __kill + 10
1   libSystem.B.dylib               0x00007fff833289f6 abort + 83
2   libSystem.B.dylib               0x00007fff83240195 free + 128
3   QtGui                           0x0000000100ad9f58 QPixmap::fromMacCGImageRef(CGImage_) + 520
4   com.apple.CoreGraphics          0x00007fff843f5fbb dataReleaseInfo + 34
5   com.apple.CoreGraphics          0x00007fff843f5f63 data_provider_finalize + 54
6   com.apple.CoreFoundation        0x00007fff83c42a73 _CFRelease + 179
7   com.apple.CoreGraphics          0x00007fff843f5ea1 image_finalize + 97
8   com.apple.CoreFoundation        0x00007fff83c42a73 _CFRelease + 179
9   libPDFRIP.A.dylib               0x000000011d0e1478 PDFImageEmitDefinition + 1517
10  com.apple.CoreFoundation        0x00007fff83c6e5a2 __CFSetApplyFunction_block_invoke_1 + 18
11  com.apple.CoreFoundation        0x00007fff83c62ad5 CFBasicHashApply + 213
12  com.apple.CoreFoundation        0x00007fff83c6e55f CFSetApplyFunction + 191
13  libPDFRIP.A.dylib               0x000000011d0e14d4 PDFImageSetEmitDefinitions + 47
14  libPDFRIP.A.dylib               0x000000011d0d5af0 emit_page_resources + 104
15  libPDFRIP.A.dylib               0x000000011d0d6a44 PDFDocumentEndPage + 79
16  libPDFRIP.A.dylib               0x000000011d0d52b0 pdf_EndPage + 17
17  ...e.print.framework.PrintCore  0x00007fff89352b29 pdfSpoolingEndPage(void_, void_) + 336
18  ...e.print.framework.PrintCore  0x00007fff8934a65b PJCEndPage(OpaquePMPrintSession_) + 46
19  ...e.print.framework.PrintCore  0x00007fff89326aa4 PMSessionEndPageNoDialog + 75
20  QtGui                           0x00000001009dcca8 QDesktopWidget::resizeEvent(QResizeEvent_) + 32008
21  QtGui                           0x00000001009dd638 QDesktopWidget::resizeEvent(QResizeEvent_) + 34456
22  QtGui                           0x0000000100b54846 QPainter::end() + 374
23  org.fritzing.Fritzing           0x000000010006d1ed MainWindow::printAux(QPrinter&, bool, bool) + 5037
24  org.fritzing.Fritzing           0x000000010006f161 MainWindow::print() + 209
25  org.fritzing.Fritzing           0x00000001003c66c2 MainWindow::qt_static_metacall(QObject_, QMetaObject::Call, int, void__) + 1314
26  QtCore                          0x000000010162e29e QMetaObject::activate(QObject_, QMetaObject const_, int, void__) + 1566
27  QtGui                           0x0000000100a192b1 QAction::triggered(bool) + 49
28  QtGui                           0x0000000100a1a644 QAction::activate(QAction::ActionEvent) + 180
29  QtGui                           0x00000001009cc38a QMacInputContext::reset() + 42442
30  com.apple.AppKit                0x00007fff85586eda -[NSApplication sendAction:to:from:] + 95
31  com.apple.AppKit                0x00007fff855ab46a -[NSMenuItem _corePerformAction] + 365
32  com.apple.AppKit                0x00007fff855ab1d4 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 121
33  com.apple.AppKit                0x00007fff85830cf4 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
34  com.apple.AppKit                0x00007fff856e29e9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 136
35  com.apple.AppKit                0x00007fff8558d99c NSSLMMenuEventHandler + 321
36  com.apple.HIToolbox             0x00007fff89bbd7f7 DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) + 1002
37  com.apple.HIToolbox             0x00007fff89bbcd46 SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) + 395
38  com.apple.HIToolbox             0x00007fff89bdaa81 SendEventToEventTarget + 45
39  com.apple.HIToolbox             0x00007fff89c09c35 SendHICommandEvent(unsigned int, HICommand const_, unsigned int, unsigned int, unsigned char, void const_, OpaqueEventTargetRef_, OpaqueEventTargetRef_, OpaqueEventRef__) + 387
40  com.apple.HIToolbox             0x00007fff89c36a0a SendMenuCommandWithContextAndModifiers + 56
41  com.apple.HIToolbox             0x00007fff89c369c2 SendMenuItemSelectedEvent + 101
42  com.apple.HIToolbox             0x00007fff89c368d2 FinishMenuSelection(SelectionData_, MenuResult_, MenuResult_) + 150
43  com.apple.HIToolbox             0x00007fff89c17c27 MenuSelectCore(MenuData_, Point, double, unsigned int, OpaqueMenuRef__, unsigned short_) + 467
44  com.apple.HIToolbox             0x00007fff89c1737c _HandleMenuSelection2 + 453
45  com.apple.AppKit                0x00007fff8545e851 _NSHandleCarbonMenuEvent + 236
46  com.apple.AppKit                0x00007fff85432362 _DPSNextEvent + 1908
47  com.apple.AppKit                0x00007fff85431801 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 155
48  com.apple.AppKit                0x00007fff853f768f -[NSApplication run] + 395
49  QtGui                           0x00000001009d8310 QDesktopWidget::resizeEvent(QResizeEvent*) + 13168
50  QtCore                          0x0000000101615d14 QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag) + 68
51  QtCore                          0x00000001016160c4 QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag) + 324
52  QtCore                          0x000000010161802a QCoreApplication::exec() + 186
53  org.fritzing.Fritzing           0x0000000100040a78 main + 408
54  org.fritzing.Fritzing           0x0000000100004c14 start + 52

**Attachment:** [MicroDrum.fzz](http://code.google.com/p/fritzing/issues/detail?id=2302)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2302_

**Comment by failiz** [comment]
Not file available. Not sure how we can test this. Close?

**Comment by KjellMorgenstern** [comment]
The backtrace hints that it is not really the print routines fault. It looks like object instance ownership is not properly handled by the caller, or simply that corrupted data is passed for printing. 
Without the file, we can not confirm or deny the problem. It seems similar crashes have not been observed in a long time. Closing.
