### ISSUE TITLE
Cannot create as straight wire

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2305]
_From [edmandie...@dlsu.ph](https://code.google.com/u/112362466218558873453/) on November 18, 2012 09:47:17_

I've tried to use the "Align to Grid" option but the grid gaps is too big so I chose not to use it. Unfortunately, the wires/trace that I control/move without using the "Align to Grid" option is not snapping and does not produce a straight wire.

I suggest for the future version that when zooming inside the PCB view (or even in Schematic view), the grid does not zoom so users can still use the "Align to Grid" option but with finer trace movement.

I am hoping that this will be added to the future versions.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2305_

**Comment by failiz** [comment]
Not enough info

**Comment by KjellMorgenstern** [comment]
Also, by holding "shift" wire can be aligned in 45 degree angles, without using the grid.
