### ISSUE TITLE
net label copy bug?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2308]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 20, 2012 07:50:08_

See comment 9 of issue #1526 Not sure if this is one of the bugs above, but using 7.10b6551 there is some funky business with net labels.  It may be because I copy-paste-rename a label, but not sure.

See the video: http://www.youtube.com/watch?v=zHoM_BBprxQ Hopefully it is clear enough to show the problem, but the steps are

  New project
  Place two screw terminals in schematic view
  Place a net label, called MOT-A and connect to one pin of first terminal
  Copy net label and rename copy to MOT-B, connect to other pin of first terminal
  Paste net label again leave as MOT-A and connect to one pin of second terminal
  Paste net label again, rename to MOT-B, connect to other pin of second terminal
  Switch to PCB view and see that the rats-nest is incorrect.

Expected result: PCB should show the two screw terminals with two rats-nest wires between them ( in ascii art something like :=: )

Actual result: PCB shows all 4 pins of the terminals are part of same net (in ascii art something like |_| )

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2308_

**Comment by bdenney99** [comment]
I'm running into this same issue on fritzing.0.9.2b.  Here is the simplest way I've found to reproduce it.

New project
Place a screw terminal in schematic view
Place a net label, called MOT-A and connect to one pin of it
Copy/paste net label and rename copy to MOT-B, connect to other pin of terminal
Switch to either breadboard or PCB view, and see that the rats-nest is incorrect.  
It thinks the two pins are connected, even though the net labels have different names!

Here are a few workarounds that appear to fix the rats nest for me:

1. Save the file and reload it.
or
2. In schematic view, cut MOT-B net label and paste it back.  Wire it up again.  Now in schematic/pcb views, the rats nest is correct.
or
3. In schematic view, cut EVERYTHING and paste it back.  Now in schematic/pcb views, the rats nest is correct. (careful, you might lose connections to other stuff?)

It would be great if this can be fixed.
Thanks!
Bryce

**Comment by failiz** [comment]
Still reproducible in 0.9.6. Remove imported label, add priority-High
