### ISSUE TITLE
solderless breadboard support

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2310]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 22, 2012 01:56:00_

An interesting alternative approach. See http://fritzing.org/forum/thread/1239 .

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2310_

**Comment by failiz** [comment]
Link is gone. I do not get the issue. there are solderless breadboards in the breadboard view...

**Comment by KjellMorgenstern** [comment]
I was curious and extracted that from the original database:

> <p>Hello everyone...&nbsp; I just found Fritzing and really like the concept and development.&nbsp; I haven't had the opportunity to use Fritzing yet so I have a couple of questions if you don't mind.&nbsp; If these questions have already been asked, I do apologize.</p>
> <p>1)&nbsp; Let's say that you have your project laid out on the solderless breadboard in Fritzing.&nbsp; Due to the cost of having a custom printed circuit board produced, you would like to be able to use a solderable breadboard instead. Can Fritzing transfer your solderless breadboard project layout to a solderable breadboard for you?&nbsp; Fritzing could use a layout/template that the user could design (single or double sided) or a standard template/layout of a solderable board you would find at your local electronics store or electronics website.&nbsp; This would be much like Fritzing designing the printed circuit board for you, but as an alternative, design the solderable breadboard alleviating any mistakes that you could potentially make in the component placement yourself.</p>
> <p>2)&nbsp; Does Fritzing have the ability to take an electronics schematic, drawn by the user or by importing a file of the schematic, and with a high level of confidence layout the parts on a solderable breadboard?</p>
> 

So, as I understand, the idea is to get from an existing breadboard to a perfboard. This could be achieved in the breadboard view, by adding a perfboard. Route all connections in schematic view, so they are fixed. Then, in breadboard view, move all elements from the breadboard to new positions at the perfboard. Ratsnest lines should indicated which parts need to be connected on the perfboard.
