### ISSUE TITLE
project update bug

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2311]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 23, 2012 06:21:12_

users are unable to update projects on the current website

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2311_

**Comment by failiz** [comment]
While this is still an issue, it is caused by the new website being uptaded. The issues described here are for the old website. Close?
