### ISSUE TITLE
blog entries copied to wordpress lost comments

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2318]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 27, 2012 02:14:39_

When the old Fritzing blog entries were copied to the wordpress blog, the comments to those blogs did not get copied.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2319_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
