### ISSUE TITLE
Labeling pins on Mystery part causes part label to be reset to "?"

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2328]
_From [gadgetde...@gmail.com](https://code.google.com/u/113639225049314860609/) on December 05, 2012 14:26:40_

What steps will reproduce the problem? 1. Create a mystery part, I used 16 pins
2. Change the label of the mystery part
3. Edit Pin Labels and change the names of all the pins and save
The label on the part is reset to "?" Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I expect the part label to remain the same What version of Fritzing are you using? On what operating system? 0.7.10 on Windows 8 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2329_

**Comment by failiz** [comment]
I could not replicate this in 0.9.6 (Windows)
