### ISSUE TITLE
Copy and paste of parts doesn't preserve line thickness

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2331]
_From [instantr...@gmail.com](https://code.google.com/u/103465596371088469371/) on December 07, 2012 12:11:07_

Similar problem has been reported, but when copying between 2 fritzing files instead.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2332_

**Comment by failiz** [comment]
I could not replicate it in 0.9.6. And it was not reproducible in 2013...
