### ISSUE TITLE
Help viewer broken on Kubuntu 10.0.4

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2332]
_From [snhir...@gmail.com](https://code.google.com/u/111342528238225234411/) on December 08, 2012 09:38:32_

What steps will reproduce the problem? 1. Start fritzing
2. Select Help --> Online Tutorials 3. Attach your sketch file and/or custom part files to the bug report. n/a What is the expected output? What do you see instead? Expect URL to be opened in system browser, but nothing happens.

This appears on stderr:

kfmclient: symbol lookup error: /usr/lib/libQtDBus.so.4: undefined symbol: _ZN14QObjectPrivate15checkWindowRoleEv What version of Fritzing are you using? On what operating system? 0.7.10 on Kubuntu 10.0.4 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2333_

**Comment by failiz** [comment]
This issue is very old and the libraries have changed since then. Can we close it?
