### ISSUE TITLE
certain prefs settings are saved in a language-dependent fashion

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2350]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 31, 2012 16:16:24_

for instance we have both "LeiterplattenansichtAlignToGrid" and "PCB ViewAlignToGrid" so if the language is changed, the prefs are lost

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2351_

**Comment by failiz** [comment]
Not sure how to check this, @KjellMorgenstern  could you check if this is still relevant?

**Comment by KjellMorgenstern** [comment]
At least the mentioned settings are now independent from language configuration
