### ISSUE TITLE
copper fill progress does nothing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2351]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 01, 2013 15:52:23_

the progress bar comes up but never increments. either come up with some measure or use a barber pole

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2352_

**Comment by failiz** [comment]
There is a barber pole in 0.9.9.
