### ISSUE TITLE
Permit toggling of auto-update mechanism at build time

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2365]
_From [e...@logic.net](https://code.google.com/u/100101134696154118651/) on January 08, 2013 20:15:13_

Hi guys,

I've been applying (and updating) the attached patch with each Fritzing release to remove the auto-update functionality, since it doesn't (and can't) work when installed as an RPM via Fedora, so it just irritates the poor user. :)

Is there a way that a form of this could make it's way into a build option, so that Fritzing could be specifically built for situations like this? I suspect I'm not the only packager who's dealing with this today; perhaps I've just missed an option?

**Attachment:** [fritzing-disable-autoupdate.patch](http://code.google.com/p/fritzing/issues/detail?id=2366)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2366_

**Comment by failiz** [comment]
Close?
