### ISSUE TITLE
having a hard time connecting breadboard with cables

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2380]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on January 15, 2013 10:54:43_

dont know how to redo it

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2381_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
