### ISSUE TITLE
Cannot always move track to other side of board

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2383]
_From [pet...@esdm.co.uk](https://code.google.com/u/110394238758319246204/) on January 16, 2013 17:47:47_

Cannot always move tracks to other side of board in version 0.7.11 but if i revert to an older version it allows me to do so.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2384_

**Comment by failiz** [comment]
Not enough information and a related bug has been solved.

**Comment by failiz** [comment]
This issue was that the board changed to single side. But there are issues that reporte that. So, let's close this one
