### ISSUE TITLE
PCB Terminal weirdness SMD

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2391]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on January 19, 2013 01:44:18_

Attached part.

When you import the part and place it, it appears as the attached image.

It appears fritzing is not reading the svgId in the fzp file.  But I don't know why.

If I open the placed part in the Parts Editor, the pcb view shows no pad assignments (it thinks the center of the IC should be a big pad, not the actual pads).

I then assign them all and save, the terminal assignments are correct, but only for that session.  Close fritzing (saving the Contrib bin) and then restart fritzing, and the pad assigments are gone again.

**Attachment:** [AZ324 Quad Op-Amp.fzpz edge12.png](http://code.google.com/p/fritzing/issues/detail?id=2392)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2392_

**Comment by failiz** [comment]
I think that this issue is solved and should be closed.
