### ISSUE TITLE
crashes windows 7 (when not running as administrator)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2397]
_From [garybur...@gmail.com](https://code.google.com/u/108707710390956734418/) on January 22, 2013 18:56:18_

What steps will reproduce the problem? 1. random get message fritzing stoped working every time i boot only can move a couple resistors to bb then crash
2.i move a resistor to bb and it will crash sometimes only one other times i may have 6 there 
3. crashes usually in a few mins Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). don't have one What is the expected output? What do you see instead? never finish don't get far enough worth saving my work What version of Fritzing are you using? On what operating system? newest version on windows 7 Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2398_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
