### ISSUE TITLE
Copper and Silkscreen Layer SVG Fill Oddness

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2404]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on January 28, 2013 04:31:44_

I am (trying to) making some parts which can be used as alignment/registration marks when doing DIY pcb etching, set around the outside 4 corners of a board so that you can align all the images precisely.

Anyway, the idea is that the svg has the same image for copper0,1 and silkscreen, the issues I have are when exporting the pcb to PDF or SVG...

  a) The silk and silk top are very strange, the label for the item (A1, A2) comes out black in the export (as you'd expect), but the part "footprint" itself is white.  Perhaps there is a flood-fill operation which is necessitating contiguous regions or something?

  b) The paste mask only seems to export the part's image IF there is an SMD part on the same layer.   In the attached example, I have an SMD part on the top layer and the alignment part appears in the top side paste mask, but not the bottom side (if you flip the SMD to the other side, you now get the alignment in the bottom but not the top).  Strangely, if you move that token SMD part off the board, the new part still appears in the corresponding paste mask export, but the SMD part doesn't, weird!

  c) The solder mask exports of course have a setback, this is not optimal for alignment marks, it would be better to be able to set some sort of "no setback" for a given part, or to be able to have a "soldermask" layer in the part's svg (overriding the automatically generated one).

I have attached a zip containing test fzz, the part's fzpz, and exported svgs.

**Attachment:** [testmarks.zip](http://code.google.com/p/fritzing/issues/detail?id=2405)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2405_

**Comment by failiz** [comment]
The files are not available

**Comment by KjellMorgenstern** [comment]
Closing, and i think the topics here are mostly covered in other issues or solved.
