### ISSUE TITLE
Win32 exception fritzing.exe [4824]

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2411]
_From [swan...@gmail.com](https://code.google.com/u/106761681753217590173/) on January 30, 2013 13:26:47_

What steps will reproduce the problem? 1. start Fritzing.
2. crashes when I select a part to place on the breadboard, everytime. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Windows XP and Windows 7 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2412_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
