### ISSUE TITLE
128 x 64 Graphic LCD: Pins are reversed in Breadboard view.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2416]
_From [yuri.pla...@gmail.com](https://code.google.com/u/104695304552290329726/) on February 01, 2013 04:18:51_

What steps will reproduce the problem? 1. Place 126x64 GLCD on the Breadboard view
2. Connect pins 1 (Vss) and 2 (Vdd)
3. Switch to Schematic view
4. Notice that pins 19 (A+) and 20 (K-) actually connected. 

Fritzing version is 0.7.11beta (most recent, updated before submitting the bug) under OS X 10.8.2

**Attachment:** [GLCD.fzz](http://code.google.com/p/fritzing/issues/detail?id=2417)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2417_

**Comment by KjellMorgenstern** [comment]
Issue was commented as done, but not closed? Closing now.
