### ISSUE TITLE
Circuit Simulation

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2418]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on February 03, 2013 05:49:16_

This is a place to collect ideas around our top feature request.
We are currently thinking of doing ERC as a first step (see issue 658 ).

The classical way to do this is to integrate SPICE: http://en.wikipedia.org/wiki/SPICE This would do basic simulation of electronic components.

The other part is the simulation of the microcontroller. There are now a couple of projects that try to do this for the Arduino: http://www.arduino.com.au/Simulator-for-Arduino.php http://web.simuino.com/ http://www.virtualbreadboard.com/Main.aspx?TAB=3&doc=Features/ArduinoToolkit/Overview https://github.com/ghewgill/emulino

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2419_

**Comment by q2dg** [comment]
Well...I think it's time to update this issue. Today, with tools like circuits.io, the explanation given by Fritzing folks is not believable. A simulator is a key tool for learning basic electronics in schools where buying several real Arduinos for several students is beyond institution economical possibilities. Meanwhile, Fritzing is losing its opportunity.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.

**Comment by wraybowling** [comment]
Bump.

**Comment by wraybowling** [comment]
The biggest drawback is a lack of simulation. I'd like to get a development branch going on this. Now. It's never too late. Other EDAs have made a lot of progress, but they're all also very fragmented. Fritzing is still relevant; it's the best EDA for beginners; it's the only EDA with a breadboard view. Let's start on a simulator, y'all.

**Comment by WimberleyTech** [comment]
I disagree.  There are good simulators already available--most notably LTSPICE.  No reason to duplicate that effort.  Having Fritzing output a SPICE-compatible netlist should be very easy to do, however.  There is the problem of how to describe the subcircuits of non-standard (i.e., non SPICE) components.  For example, an Arduino Nano.  Moreover, there needs to be a SPICE model for such a thing--a challenging affair.  So, it seems like a distraction to me.  Lets get the three views (bb, schematic, layout) in excellent shape before even considering such a thing.

**Comment by KjellMorgenstern** [comment]
TL;TR : Yes, but we would need a full time developer focused on this. Just throwing in a feature is not enough.

I would welcome such improvements. Adding such a functionality would be a much more motivating endeavour to many people than, let's say, fixing ten year old bugs or adding TLS, so I could imagine that there are new developers who want to work in this. But there is a catch: Cherry picking a new feature, hacking it together, throwing it on top and then leaving that pile of code rot would not be welcome. The aim should be well designed, state of the art code, with automated tests from start on, that integrates nicely with the rest of the application. 
With 'nice integration' I'd imagine something like LEDs blinking and capacitors smoking on the breadboard. Showing oscilloscopes would then be done in the schematics view, and electric fields can be shown on the PCB... and then simulating Arduinos, the links above are all outdated/dead, but maybe qemu ... I think we are talking about several full time developers by now ;-)

**Comment by WimberleyTech** [comment]
Ditto.

**Comment by failiz** [comment]
I made a basic simulator for Fritzing. The main idea is to use it to teach electronics to my CS students. You are welcome to try it. 

The documentation to use it and install it is here:
https://github.com/failiz/fritzing-app/blob/simulator/src/simulation/SIMULATOR_README.MD

The code is in my repository in a branch called simulator:
https://github.com/failiz/fritzing-app/tree/simulator

And you also need the pull requests that I made to the Fritzing-parts repository (basically adding spice fields to the parts and adding a multimeter part).

The idea is to integrate this code in Fritzing in the future. If you can help to achieve that, please, test it and give me (constructive) feedback. Is anything missing? How can it be improved?

Please, note that I will not add more new features until the code is integrated in Fritzing. It is time to fix bugs and consolidate the code.

**Comment by KjellMorgenstern** [comment]
Thanks a lot for this amazing improvement. Also for your help in reviewing the numerous open tickets!
In the last weeks, most important legal issues have been resolved, so I can finally release 0.9.5 now (before christmas). 
After that, we could pull the simulator to the development branch. I am optimistic that it will be stable enough. But as this is a major change there is some risk. Do you think we can make this configurable, so we can easily enable/disable it without changing the code base, to avoid long open branches? This way, we can take the simulator code in, and even if it turns out to not yet be stable, it could stay in without blocking further releases.

**Comment by failiz** [comment]
Excellent news Kjell! Looking forward to the new release.
Yes, I think that should be possible. However, are you thinking in adding defines to be able to compile it with or without the simulator or just in a way to enable/disable it from the program? The latest solution is (almost) implemented. Now, you need to activate the simulator in View->Enable the simulator. The only problem is that I tried to hide/show the simulate button based on the status of the simulator (enabled/disabled), but for some reason it does not work as expected. The show() or hide() functions do not work when they are called in MainWindow::enableSimulator() in mainwindow_menu.cpp. If we fix that, the simulator will be hidden for the users and it needs to be activated to use it.

**Comment by KjellMorgenstern** [comment]
I don't favor using defines, as that tends break the code for people working on the new feature.
I think of it more like hiding it, unless the user really wants to try, and is aware that this is a "beta" feature. Simply removing it from the menu would also do it. In a similar way, I had disabled the auto-router, until it was fixed. But I think having a setting might be worth it, since I guess there are quite some people who want to try it.

**Comment by failiz** [comment]
Haha, regarding the defines, I guess I spend too much time programming microcontrollers...
Yes, I can maybe create a new "beta features" tab in the preferences window to activate the simulator. I do think  that it should not be very difficult. I prefer that people use it, so we can find the bugs.

**Comment by WimberleyTech** [comment]
Great news about the upcoming release!!  Good work guys!
    
    On 12/10/2020 9:32 AM, Kjell wrote:
    
    
      
      Thanks a lot for this amazing improvement. Also for your help
        in reviewing the numerous open tickets!
        In the last weeks, most important legal issues have been
        resolved, so I can finally release 0.9.5 now (before christmas).
        After that, we could pull the simulator to the development
        branch. I am optimistic that it will be stable enough. But as
        this is a major change there is some risk. Do you think we can
        make this configurable, so we can easily enable/disable it
        without changing the code base, to avoid long open branches?
        This way, we can take the simulator code in, and even if it
        turns out to not yet be stable, it could stay in without
        blocking further releases.
      —
        You are receiving this because you commented.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/fritzing/fritzing-app/issues/2418#issuecomment-742594403",
"url": "https://github.com/fritzing/fritzing-app/issues/2418#issuecomment-742594403",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wraybowling** [comment]
This is such wonderful news! Thank you thank you thank you! Having a bit of a computer issue at home right now; I'll download the branch and start testing as soon as I get that sorted out.

**Comment by failiz** [comment]
Ok, the simulator is hidden by default now. To use it, you need to activate it in preferences->beta features. This setting is store with the other settings and once enabled stays enabled even after closing Fritzing (unless your disable it, of course).
Once enabled, the simulate button appears. There is also a reset simulation to remove the results of the simulation too.
So, I think is ready to get merged into the development branch after the 0.9.6 is released.
