### ISSUE TITLE
independently movable schematic subparts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2425]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 12, 2013 12:00:34_

http://fritzing.org/forum/thread/1363

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2427_

**Comment by KjellMorgenstern** [comment]
Subparts are independently movable. If any specific problems remain, they should be raised in new issues
