### ISSUE TITLE
Fritzing is crashing while drawing or doubleclicking ratsnets lines

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2427]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on February 14, 2013 04:16:58_

file is attached – is not happening every time but pretty often

klick and drag a ratsnest line > crash
doubleclick on ratsnest line > crash

file is attached

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2429_

**Comment by failiz** [comment]
No file available and the issue was tagged as  UnableToReplicate.
