### ISSUE TITLE
Mousing over Order PCB de-focuses main window

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2433]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on February 19, 2013 22:27:26_

Fritzing slows to a crawl, the windows are never closed until Fritzing quits, they just seem to hide behind it. Subsequent mouseovers create yet more windows. Perhaps using the OS's built in tooltip would be better? (OS X.8.2)

**Attachment:** [Screen Shot 2013-02-20 at 03.22.27.png](http://code.google.com/p/fritzing/issues/detail?id=2435)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2435_

**Comment by failiz** [comment]
Still reproducible in 0.9.9. Remove imported label.

**Comment by KjellMorgenstern** [comment]
Probably solved for 1.0.0 , retest after the release.
