### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2448]
_From [ferriema...@howard-winn.k12.ia.us](https://code.google.com/u/115750847685196679355/) on March 05, 2013 17:38:39_

What steps will reproduce the problem? 1.Open on Windows 7 Home Premium
2.Create a sketch (I did a 555 astable oscillator and it crashed within 10 minutes)Attach your sketch file and/or custom part files to the bug report.
Fritzing somehow deleted my sketch when it crashed... What is the expected output? What do you see instead? The expected output was a breadboard circuit. What I got was a "Fritzing has encountered a problem and needs to close" error.

What version of Fritzing are you using?
The latest release.

On what operating system?
Windows 7 Home Premium Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2450_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
