### ISSUE TITLE
Copper fill clearance violations

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2449]
_From [terryle...@gmail.com](https://code.google.com/u/115427266638150861454/) on March 06, 2013 15:40:52_

What steps will reproduce the problem? 1.Produce a PCB with various SMD pads
2. Ask for copper fill/ground fill
3. File>Export>For Production > Extended Gerber files (RS-247X)... to produce gerber files.  In the gerber files, the clearance between the fill areas and the SMD pads is too small causing PCB MFR to reject the gerbers as containing clearance violations.  These small clearances are shown in the Fritzing PCB view, but there is no way to edit the file polygons. Attach your sketch file and/or custom part files to the bug report. DONE!  I Have also attached the produced gerber files and the PNG annotated with the clearance violations.

What is the expected output? 
I expect the fill areas to clear the SMD pads at least at much as the through hole rings or to clear the SMD pads with at least as much clearance at the DRC parameters.  There is no way to edit the fill area.

What do you see instead?
A very tiny clearance causing the PCB MFR to reject the gerbers.

What version of Fritzing are you using? 0.7.12 On what operating system? Vista Please provide any additional information below.

**Attachment:** [DC Valve Assy V1c.fzz APCircuits.zip 255275_1.png](http://code.google.com/p/fritzing/issues/detail?id=2451)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2451_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
