### ISSUE TITLE
Custom part SVG Font Size missmatch between Inkscape/IE and Fritzing  

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2451]
_From [terryle...@gmail.com](https://code.google.com/u/115427266638150861454/) on March 06, 2013 22:18:16_

What steps will reproduce the problem? 1. Created a custom part from the standard IC part
2. Use Inkscape to update the IC schematic layout  
3. Import schmatic SVG into New Part editor, and while the drawing appears perfectly in Inkscape and IE it has blown up letters in Frizing.  Inspecting the XML Font size shows a very large (200PX) font is transformed down by Inkscape/IE but it not transformed/changed by Fritzing.  Can change the XML font size to 12/10 to be readable in  Fritzing, but then they are in Inkscape or IE. Attach your sketch file and/or custom part files to the bug report. DONE.  

What is the expected output? see What do you see instead?
Below see attached screen captures that show the inconsistent font size rendering/handling of Inkscape/IE/Chrome and Fritzing.

What version of Fritzing are you using? 0.7.12 On what operating system? Windows Vista Please provide any additional information below.

**Attachment:** [DC Valve Assy V1d.fzz SC70.fzpz Fritzing_view.JPG Inkscape_IE_font_presentation.JPG](http://code.google.com/p/fritzing/issues/detail?id=2453)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2453_

**Comment by failiz** [comment]
the files are gone and one of the developers said that the behaviors was correct. The last comment it is related to inkscape related bugs and I think that there are other issues reporting it. Close?

**Comment by bereldhuin** [comment]
Quite old post but I got the same problem.

To solve this, simply replace font-size="35px" by font-size="35" (remove px)

This can be done by using regular expression.
For example, in Visual Studio Code:
* open the search and replace popup
* set the search to regexp (.* button on the right of search)
* In search : type `font-size="(.*)px"`
* In replace : type `font-size="$1"`
