### ISSUE TITLE
pin spacing for stripboard

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2456]
_From [djrichar...@googlemail.com](https://code.google.com/u/117825441102055752227/) on March 07, 2013 09:58:00_

What steps will reproduce the problem? 1.on stripboard view you cant increse or decreece the pin spacing 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2458_

**Comment by failiz** [comment]
Not sure what the issue is. Are there perfboards that are not 0.1 inch???

**Comment by KjellMorgenstern** [comment]
A quick search for "metric perfboard" and "perfboard spacing" did not reveal anything, all seem to be 2.54mm.
