### ISSUE TITLE
copper fill layering bug

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2457]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 08, 2013 02:21:43_

make an individual copper fill on the top layer so that the whole board is not covered. Then lock it. Then do a normal copper fill. The bottom copper layer will visually cover the individual top copper layer.

This fixes itself when the file is saved and reloaded.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2459_

**Comment by KjellMorgenstern** [comment]
This seems to be outdated or fixed.
