### ISSUE TITLE
generic ic: connector item locations are off (again)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2463]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 10, 2013 01:02:56_

drop a generic ic, and switch to one of the smd packages: the connectorItem locations don't match the pins.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2465_

**Comment by KjellMorgenstern** [comment]
Neither attachment nor screencast are available anymore, closing due to lack of information.
