### ISSUE TITLE
pin label editor is losing it with HTSSOP28

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2465]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 10, 2013 12:37:12_

http://fritzing.org/forum/thread/1421

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2467_

**Comment by KjellMorgenstern** [comment]
Neither the thread nor the original issue are available anymore. Closing due to lack of information.
