### ISSUE TITLE
Board reverts to double sided with tracks on wrong side

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2468]
_From [iansav...@gmail.com](https://code.google.com/u/107358368552087388521/) on March 13, 2013 05:57:56_

Using Fritzing 0.7.12 2013-02-13 qt4.8.3

See attached design and gerber files

A single sided board when saved and re-opened becomes double sided with confusion as to which side the tracks are on.

Starting with a new board design I set the PCB to single sided and laid out the board. Exported Gerbers (attached) and noticed there was a top copper layer, but the bottom copper layer was correct. At various points in the design process odd things happened which may be related to a single-sided/double sided bug (e.g. side selection button appeared, moved a track and left a ghost on the wrong side) but the board always showed single sided in the inspector and printed as single sided.

Saved and reopened the board before sending it for fab and found it was now double sided. Not only that but when I set it back to single sided the tracks disappeared with the top copper fill, leaving the bottom copper fill and the outline of the tracks. So the copper fill routine thinks the tracks are on the bottom but the side selection thinks they are on the top!

A workaround would be good, this was a tricky board to lay out and I don't want to do it again!

**Attachment:** [Lamp Driver Opto RJ45 v2.1.fzz Lamp Driver Opto RJ45 v2.1 gerbers.zip](http://code.google.com/p/fritzing/issues/detail?id=2470)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2470_

**Comment by failiz** [comment]
Not file available and do not enough data to replicate it.
