### ISSUE TITLE
uploaded projects should automatically display .fzz view images

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2474]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 17, 2013 04:46:21_

this is a little tricky because often only one or two views are worth showing. Perhaps one could select the view that was most fully routed.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2476_

**Comment by failiz** [comment]
outdated?
