### ISSUE TITLE
support sieb&meyer 3000 drill format

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2482]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 20, 2013 16:40:00_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

**Attachment:** [10_Supplement.pdf 12_CommandDescription.pdf 12_SM_CommandDescription.pdf 12_FormatOverview_1000_3000_5000.pdf Sieb&Meyer.pdf SM-Format-5000.pdf](http://code.google.com/p/fritzing/issues/detail?id=2484)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2484_

**Comment by failiz** [comment]
If this in the pipeline?

**Comment by KjellMorgenstern** [comment]
Without knowledge about how often this is needed, I think we can close it.
@Libermentix I am closing this, or could this feature improve your process?

**Comment by Libermentix** [comment]
yep. The export should be more than sufficient at least when it comes to drills.
