### ISSUE TITLE
more control over solder mask

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2488]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 26, 2013 01:33:13_

http://fritzing.org/forum/thread/1447

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2490_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
