### ISSUE TITLE
power "label" part needs to integrate with new dcpower part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2491]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 31, 2013 13:43:43_

also new acpower part?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2493_

**Comment by failiz** [comment]
Is power "label" part the generic power symbol?
I am not sure what needs to be integrated. Regarding a AC power supply, there is one there (add dc power supply and change it to ac).

**Comment by KjellMorgenstern** [comment]
Not enough information, closing
