### ISSUE TITLE
provide an installer

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2496]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 03, 2013 00:56:52_

qt installer framework docs: http://doc-snapshot.qt-project.org/qtifw-1.3/ifw-overview.html installer framework binary: http://releases.qt-project.org/qt-installer-framework/1.3.0/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2498_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
