### ISSUE TITLE
text not visible in schematic and breadboard

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2501]
_From [kamilaal...@gmail.com](https://code.google.com/u/101052479957330810423/) on April 08, 2013 11:18:06_

Hi :)
I make new component in Coreldraw x5 and export the component in svg file.
But in new parts editor, the text (in Droid Sans) is not visible in either schematic and breadboard. The problem still occur when I use OCRA font. I use fritzing v0.7.12 and windows 7. Any suggestion to fix this are welcomed
thanks

**Attachment:** [Untitled Sketch 6_bb.jpg Untitled Sketch 6_schem.jpg](http://code.google.com/p/fritzing/issues/detail?id=2503)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2503_

**Comment by failiz** [comment]
I think this issue can be closed. The files are no longer available, one issue was fixed in version 0.7.13 and the other issue looks like a bug in the part.
