### ISSUE TITLE
DRC not complaining but pads are touching each other

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2502]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on April 09, 2013 09:03:08_

attached file

**Attachment:** [Bildschirmfoto 2013-04-09 um 15.02.29 – 09.04.2013.png 95168203_robot.fzz](http://code.google.com/p/fritzing/issues/detail?id=2504)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2504_

**Comment by failiz** [comment]
Not sure if I get the issue (the file is gone). The DRC  can detect overlaps between pad-pad, pad, track and pad-through hole. Not sure what "escaping donuts" means...

**Comment by KjellMorgenstern** [comment]
Not enough information
