### ISSUE TITLE
Design ended up with unrouted wires, can't remove them.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2503]
_From [chris0yo...@gmail.com](https://code.google.com/u/110685069175823132786/) on April 09, 2013 15:31:08_

What steps will reproduce the problem? 1. Open design, see unrouted wires, try to remove them. 2. 3. Attach your sketch file and/or custom part files to the bug report. OK What is the expected output? What do you see instead? I built my design, and it ended up with undesired wires between pins 2/3 of my IC, and across C1. This shows up in schematic view, breadboard view, and they even get routed by the autorouter. I don't want these wires, but I could not delete them... What version of Fritzing are you using? On what operating system? 0.7.12, Win8-64 Please provide any additional information below.

**Attachment:** [USBLightController.fzz](http://code.google.com/p/fritzing/issues/detail?id=2505)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2505_

**Comment by failiz** [comment]
The file is no longer available and the error happened in a very old version which allowed to delete ratsnets. I would close this issue as there is no way of debugging it.
