### ISSUE TITLE
problems with pinheader part in current release version on win 7

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2506]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on April 11, 2013 05:06:21_

Yesterday, on of the workshop participants had a problem with the pin header part. Fritzing was saying "Fehler beim laden ... pinheader.fzp". I don't know, if it is a known or even solved issue. Otherwise, you can try to replicate it simply by draging the pinheader part onto a pcb in pcb view.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2508_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
