### ISSUE TITLE
real cables?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2514]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 17, 2013 04:00:34_

feature idea: off-board components like displays and speakers, connectable with "real" cables to the various jacks

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2516_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
