### ISSUE TITLE
0.156in pin spacing option?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2518]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 17, 2013 15:29:45_

Hello, I work with many connectors that use 0.156" pin spacing and I can't seem to find anything in the fritzing environment that uses that.  Also I can't seem to edit the existing parts to make them 0.156 is there a way to do it?  All I need are the holes the right space so I can put a connector in it so the actual part shouldn't matter much.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2520_

**Comment by failiz** [comment]
I think that this is very specialized. I think that we should close this. It will automatically solved when there is a new part editor. Thus, users could generate their own pcb layouts.
