### ISSUE TITLE
copper fill spacing to small

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2519]
_From [orgfritz...@gmail.com](https://code.google.com/u/115834879217412145280/) on April 18, 2013 06:27:28_

add more space to the default copper fill spacing

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2521_

**Comment by KjellMorgenstern** [comment]
Outdated, files not available anymore, spacing can be configured.
