### ISSUE TITLE
plain text or html netlist export

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2523]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 19, 2013 01:08:24_

might be easier to work with than the current xml netlist export

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2525_

**Comment by failiz** [comment]
What is the use case for this? Kicad does not export in Xml neither in plain text.

**Comment by failiz** [comment]
Close? I don't see the utility of this
