### ISSUE TITLE
Update example sketches

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2530]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 23, 2013 10:18:50_

Breadboard
- align all parts to the grid
- use the new breadboard (with blue/red stripes)

Schematic
- revise layout (many are really obscure..)
- align all parts to the grid

PCB
- show part labels
- align all parts to the grid
- add "Made with Fritzing" logo

More examples
- for the new starter kit
- for other microcontrollers
  ...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2532_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
