### ISSUE TITLE
wires along the border not sticking to board during rotation

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2532]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 24, 2013 00:45:57_

order 000056 42971386_LEDUINO.22.4.fzz

Two thin wires making a long snaky trail along the edge of an arduino shield were not sticking to the board when the board was rotated.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2534_

**Comment by failiz** [comment]
Still an issue in 0.9.6. Remove imported label.

**Comment by KjellMorgenstern** [comment]
![image](https://user-images.githubusercontent.com/6494025/145414404-ecbad445-21a7-4550-9188-578a2f7fea0e.png)

![image](https://user-images.githubusercontent.com/6494025/145414495-a2bf3b7d-8dac-48d6-84a9-ca7087a9f253.png)

**Comment by KjellMorgenstern** [comment]
Workaround:
1. Select all <kbd>Ctrl-A</kbd>
2. Press <kbd>[</kbd> or <kbd>]</kbd> or <kbd>Ctrl-R</kbd>

**Comment by KjellMorgenstern** [comment]
The OP did not mention if the board is sticky or not. If the board is set to be sticky, then resistors are rotated and moved along with the board as expected. Tested with 0.9.9.
One could demand that the sticky flag should be enabled as a default for all PCBs. But that would be a different issue.
