### ISSUE TITLE
silkscreen gerber export missing sides of rectangular pcb

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2533]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 26, 2013 04:21:27_

unable to replicate using 0.7.12 or 0.7.13 under windows. try mac.

file schele-mixer8.fzz, under gijs

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2535_

**Comment by failiz** [comment]
not enough info.
