### ISSUE TITLE
save last drc update for fab

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2536]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on April 26, 2013 11:55:07_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2538_

**Comment by failiz** [comment]
Seems a reasonable feature to implement. Remove imported. Not sure what the comment is suggesting

**Comment by KjellMorgenstern** [comment]
We are working on a better integration with the fab. Closing this issue because it is not specific enough.
