### ISSUE TITLE
Strange sketch behavior

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2538]
_From [casch...@mac.com](https://code.google.com/u/116291006804426827631/) on April 27, 2013 15:43:50_

What steps will reproduce the problem? 1. Open the attached sketch 
2. Klick on the breadboard line shown in the screen shot
3. Another line will lit up, indicating equal electric potential. But I don't know why. Attach your sketch file and/or custom part files to the bug report. Done. What is the expected output? What do you see instead? Pin 13 and pin 3 of a generic ic with 20 pins should nor be electrically equal. What version of Fritzing are you using? On what operating system? OS X 10.8.3 with Fritzing 0.7.12

**Attachment:** [tpic595.png tpic595.fzz](http://code.google.com/p/fritzing/issues/detail?id=2540)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2540_

**Comment by failiz** [comment]
There is not enough information to debug and it was made with an old version of Fritzing. Probably that version had the issue and has been fixed since then . I haven't seen more errors like this one reported. Close?
