### ISSUE TITLE
change logo in image exporte once the redesign takes place

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2543]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on April 30, 2013 09:12:38_

change logo in image exporte once the redesign takes place

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2545_

**Comment by failiz** [comment]
Is a  redesign of the logo taking place?

**Comment by KjellMorgenstern** [comment]
I think the redesign finished, including the logo export
