### ISSUE TITLE
Copy from one fzz to another fzz

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2553]
_From [viableve...@googlemail.com](https://code.google.com/u/101250619270702583897/) on May 03, 2013 18:06:03_

It would be extremely useful if you could copy an object, component from one open project to another open project.  Or duplicate a whole section including components and wires.  So can duplicate multiple mux switches for example.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2555_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
