### ISSUE TITLE
lock flag is preserved when parts are duplicated

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2554]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 04, 2013 06:11:24_

but chances are you will want to move the duplicated parts, so maybe the lock flag should always be set to false after copy or duplicate?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2556_

**Comment by KjellMorgenstern** [comment]
Can see any reason to copy that flag. I think copies should have this flag unset.

**Comment by KjellMorgenstern** [comment]
Lock flag will not be copied when a part is copied. 
However, when changing the package, the lock is also removed.
