### ISSUE TITLE
debug mode for parts editing

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2555]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 06, 2013 04:24:20_

so you can edit core parts in place

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2557_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
