### ISSUE TITLE
get Apple certification for application

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2561]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 08, 2013 02:20:52_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2563_

**Comment by szippy** [comment]
Hey guys, This issue has been opened for a while, but I believe you could request a free developer program membership waiver as an educational institution, which would let you sign the app. 

https://developer.apple.com/support/membership-fee-waiver/

**Comment by KjellMorgenstern** [comment]
> Eligible countries: Brazil, China, Japan, United Kingdom, United States.

Fritzing UG (the organization that has all the legal properties to interact with Apple) is based in Germany.

**Comment by failiz** [comment]
Now Germany is included:
 Eligible countries or regions: Australia, Brazil, Canada, China mainland, France, Germany, Israel, Italy, Japan, Mexico, South Korea, United Kingdom, United States.
But the app needs to be free:
Fee waivers are not available for:

    Organizations distributing paid apps or apps with in-app purchase on the App Store
