### ISSUE TITLE
Some THT parts have issues when moved to the bottom

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2568]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 11, 2013 10:58:33_

Some parts have some of their layers not correctly rotated/flipped when moving to the bottom of the PCB. It looks  like the silkscreen is flipping, but the copper is not (or not completely).

Examples:
* Trimmer Potentiometer (rotate it to see the effect)
* LCD screen
* Triple Axis Accelerometer
These are easy to spot because they are not symmetrical, but the symmetrical ones could have the same issue.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2570_

**Comment by mMerlin** [comment]
Likely this was a symptom of  #2961. Where duplicate parts, one on top, the other on the bottom triggered DRC (and gerber export) issues.
