### ISSUE TITLE
Autoroute crashes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2579]
_From [georgeko...@gmail.com](https://code.google.com/u/107656141387250685553/) on May 19, 2013 19:08:10_

What steps will reproduce the problem? 1. Deleted all traces that were autorouted before
2. Run autorouter for 100 rounds
3. Autorouter crashes after the 100th round is run and next phase of autorouting starts (not sure what's its name)

I believe the problem started once I deleted all the pre-autorouted traces and vias and tried to re-run autoroute. I could be wrong. I have been working on this file for some days before and autorouting was not crashing fritzing Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? ...(loads of similar debugging msgs before)
"routing net 16, subnets 2, traces 1, routed 1" 
"routing net 17, subnets 2, traces 1, routed 1" 
"routing net 18, subnets 3, traces 1, routed 1" 
"routing net 20, subnets 5, traces 0, routed 0" 
"routing net 21, subnets 2, traces 0, routed 0" 
"routing net 22, subnets 5, traces 0, routed 0" 
"traceback zero points" 
"traceback zero points" 
"overlap not found" 
"overlap not found" 
"missing source connector" 
Segmentation fault What version of Fritzing are you using? On what operating system? 0.7.12 (b6882 2013-02-13) [Qt 4.8.3] on Linux Mint 13
also tried it
fritzing.2013.02.25.pc.zip on WinXP 32bit
and confirmed same issue is present Please provide any additional information below.

**Attachment:** [v1.fzz](http://code.google.com/p/fritzing/issues/detail?id=2581)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2581_

**Comment by failiz** [comment]
The issue was not replicable and the file is not available any more. I tried to autoroute something, delete all the traces and autoroute again in 0.9.4 and did not crash.
