### ISSUE TITLE
smd flip for custom smd misses transform

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2580]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 21, 2013 23:39:29_

probably because the transform is "outside" the copper1 layer rather than within it.  Look for the file called 90238716_Beta_test_skrek-3514.fzz.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2582_

**Comment by KjellMorgenstern** [comment]
Information not available anymore. Also, similar issues have been fixed.
