### ISSUE TITLE
fab: mask layer for connector comes out circle rather than square

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2583]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 23, 2013 17:36:51_

see Startlicht+shiftplate+wide+final+v20130422.fzz

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2585_

**Comment by KjellMorgenstern** [comment]
I think this image shows the issue:
![image](https://user-images.githubusercontent.com/6494025/130811297-a0896f9a-81ed-4889-8c75-06093ce888c4.png)

**Comment by KjellMorgenstern** [comment]
Fixed for upcoming release:
![image](https://user-images.githubusercontent.com/6494025/130811989-8a25f074-1029-401d-8669-a4af6d093990.png)
