### ISSUE TITLE
logo part filled up

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2589]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on May 28, 2013 08:40:28_

export attached file to gerber produces a filled rectangle on top of the logo drawing

**Attachment:** [Bildschirmfoto 2013-05-28 um 14.35.58 – 28.05.2013.png Bildschirmfoto 2013-05-28 um 14.38.21 – 28.05.2013.png double_ac-sens_v2alt-multi_v2.fzz](http://code.google.com/p/fritzing/issues/detail?id=2591)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2591_

**Comment by failiz** [comment]
The files are not available and the error was produced by a xml structure in the original file.  Close?
