### ISSUE TITLE
breadboard view: create a wire only if fully dragged out

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2594]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 29, 2013 19:00:46_

http://fritzing.org/forum/thread/1551

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2596_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
