### ISSUE TITLE
Single sided board chosen but Fritzing treats it as double sided

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2611]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on June 08, 2013 13:06:40_

I think this may be a corrupted fzz, but I have chosen "one layer" in the PCB inspector, and the board is treated in most cases like a two sided board. Drawing wires results on them appearing on the top of the board. Also a ground fill is rendered for the top side, and I am able to move SMDs to the top side too. 

I've attached the offending file.

**Attachment:** [Heating HV Board.fzz](http://code.google.com/p/fritzing/issues/detail?id=2613)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2613_

**Comment by failiz** [comment]
The file is not avalaible and they had, at least, partially fix the issue. 
I could not replicate this in 0.9.6. In single boards, the traces (or "wires") and copper fill are placed on the bottom layer.
