### ISSUE TITLE
generate ground fill unit should merge results into one svg

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2615]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 10, 2013 06:24:33_

generate ground fill unit seems to correctly generate a bunch of svgs, but only uses the first one. The svgs should be merged to create a single combined svg.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2617_

**Comment by failiz** [comment]
Still relevant after the improvements in Fritzing 1.0.2?

**Comment by KjellMorgenstern** [comment]
I think the mechanism is still the same. The method makeCopperFillFromPolygon (called from generateGroundPlaneUnit , not "generate ground fill unit") still creates an SVG for each polygon.

PCBSketchWidget::generateCopperFillUnit (again, there is no "Generate Ground Fill Unit") returns `gpg.newSVGs()[0]` , so only the first SVG .

However, in PCBSketchWidget::groundFill , you can see that all the SVGs are used to create Items. My guess is that this second context was overlooked when the initial issue was created.
