### ISSUE TITLE
when switching from two layer board to 1 layer board, traces no longer select easily

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2617]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 10, 2013 07:35:13_

view from below will work, as will saving the file and reloading. One issue is ground plane from the top (which should probably just be deleted).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2619_

**Comment by failiz** [comment]
I could not replicate this in 0.9.6
