### ISSUE TITLE
 cannot draw bottom traces when viewing from above, and no top traces when viewing from below

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2618]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 10, 2013 14:02:26_

r13b7fc49568d

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2620_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
