### ISSUE TITLE
getting rid of the rectangular footprints

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2619]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on June 11, 2013 08:07:25_

We often have parts with one rectangular pin. We dit it to let people easier find out the orientation of their parts, but I think it is causing more problems. Let's throw them out. 

(Sometimes like on the resistor part it is even not making sense ...)

**Attachment:** [Bildschirmfoto 2013-06-11 um 14.05.11 – 11.06.2013.png](http://code.google.com/p/fritzing/issues/detail?id=2621)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2621_

**Comment by failiz** [comment]
There are still some rectangular footprints at the first pad. I think they are ok and not sure way they caused issues. The resistor, capacitor (except the electrolytic one) and inductors all have round pads. The single side row connector has all rounded parts, and the double row connectors have a square pad at pin1. 
I would keep the square pin (it is nice to see which one is pin one without silkscreen), but maybe homogenize this, but not very high priority.
