### ISSUE TITLE
schematic wires are not black

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2620]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on June 11, 2013 11:59:35_

in schematic view the wires are just black if they are new and be auto routed. the inspector identified the color as "blue". if you switch to black the wires get a dark grey. real black isn't possible.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2622_

**Comment by failiz** [comment]
The wires are black and they can be changed without problems in the inspector
