### ISSUE TITLE
layer selector doesn't work for generic DIP IC

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2623]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on June 14, 2013 08:27:22_
1. Select PCB view and choose to view Bottom Layer
2. Drag generic IC onto PCB view
3. Try to change layer selector in Placement section of inspector

Generic IC does not change layer (silkscreen does not reverse).

Other components (including specific ICs and SMD generics) do so it must be something specifically about the generic IC.

I've also noted that dragging the ULN2003A DIP IC onto the workspace causes Fritzing to do a lot of work at something, takes about 5-8 seconds!

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2625_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
