### ISSUE TITLE
Fritzing doesn't compile on Debian 7.0 Wheezy

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2624]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on June 14, 2013 11:40:50_

reported through Twitter from drogon: https://twitter.com/drogon/status/345562746978451456 The build fails due to a missing version of GLIB_C:
/home/gordon/fritz/0.8.0b/lib/Fritzing: /lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.15' not found (required by /home/gordon/fritz/0.8.0b/lib/libQtGui.so.4)
/home/gordon/fritz/0.8.0b/lib/Fritzing: /lib/i386-linux-gnu/i686/cmov/libc.so.6: version`GLIBC_2.15' not found (required by /home/gordon/fritz/0.8.0b/lib/libQtNetwork.so.4)
/home/gordon/fritz/0.8.0b/lib/Fritzing: /lib/i386-linux-gnu/i686/cmov/libc.so.6: version `GLIBC_2.15' not found (required by /home/gordon/fritz/0.8.0b/lib/libQtCore.so.4)

It seems that others also have this issue, for example: http://steamcommunity.com/app/221410/discussions/0/864959810027507793/ Ideally, we would find a way to tweak the build script. Maybe some of our Linux distro gurus can help. On the other hand, it could also be that the issue will be solved by Debian. The new 7.0 is only from mid-May.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2626_

**Comment by KjellMorgenstern** [comment]
Closing outdated issue, please re-open if this is still a problem.
