### ISSUE TITLE
Autoroute crashes after 100 iterations

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2627]
_From [melbourn...@gmail.com](https://code.google.com/u/117859318928309083699/) on June 16, 2013 22:50:50_

What steps will reproduce the problem? 1. Load attached .fzz
2. Switch to PCB view
3. Select Routing | Autoroute

See Attached: .fzz file What is the expected output? What do you see instead? Uncontrolled program termination. What version of Fritzing are you using? On what operating system? 0.8.0 (b08d5 2013-06-12) [Qt 4.8.3] - It would be nice if I could cut-n-paste that from the about box rather than transcribing it.
Running on Linux Mint Maya 64-bit on an i3 with 8Gb RAM Please provide any additional information below. There's a component hanging off the PCB, but moving it doesn't make the crash go away.

**Attachment:** [Pedestrian light.fzz](http://code.google.com/p/fritzing/issues/detail?id=2629)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2629_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
