### ISSUE TITLE
Cannot find a component HC-SR04 after loading and it will not re-import

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2635]
_From [petergui...@gmail.com](https://code.google.com/u/104347556436441090856/) on June 23, 2013 07:18:58_

What steps will reproduce the problem? 1. Downloaded the file https://fritzing.googlecode.com/issues/attachment?aid=-6306772637015161054&name=HC-SR04.fzpz&token=48s8tfGIPzLC6kQKG038ra6qMAs&#37;3A1371984850298 from https://code.google.com/p/fritzing/issues/detail?id=875 It opened up a fresh copy of the Fritzing software, ignoring the project I already had open. I closed the instance, but didn't take much notice of the warning messages about saving etc. I thought I'd go to the open project where I wanted the new component to be used but it reported an error message - "There is already a part with id '75255e2f65c7e5f385f1565cd28977a1' loaded into Fritzing".

I then shut all instances of Fritzing down and tried to open my project fresh, then looking for the new component in the list of components on the right. Couldn't find it.

Shut down all instances of Fritzing.
1. Tried to double click the item in the download directory, and it opened Fritzing but reported the following "There is already a part with id '75255e2f65c7e5f385f1565cd28977a1' loaded into Fritzing"
2. I have also tried going to the 'Import...' option from the components menu but it also reports the same.

I have tried searching in the components menu for HC-SR04, 75255e2f65c, sonic, hc-, SR04 but nothing is reported which matches the item I'm trying to find.

I have tried deleting the Fritzing software files from the directory and then copying them in again from a freshly downloaded zip file, but no change to the reported error.

I cannot find a file in the software directory structure which matches the id in the error, so cannot even delete that to see if it will help.

Is there any way that the software would ask if you wish to over-write, or delete the installed file. If you're going to present a button for the user to press to acknowledge the situation then another button could be added to try again? What is the expected output? What do you see instead? I thought I'd see the component listed in the components under 'Contributed' or 'Mine' What version of Fritzing are you using? On what operating system? Fritzing version 0.8.0 (b08d5 2013-06-12)[Qt4.8.3](see attachment) 
Installed on a Samsung NC-10 running Windows XP HE (see attachment) Please provide any additional information below.

**Attachment:** [2013-06-23 13_06_42-About Windows.png 2013-06-23 13_07_36-fritzing.png HC-SR04.fzpz](http://code.google.com/p/fritzing/issues/detail?id=2637)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2637_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
