### ISSUE TITLE
BitDefender shows virus warning for Fritzing on Win8

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2637]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on June 27, 2013 10:51:01_

See attachment. BitDefender seems to detect the signature for MIDAS3 in fritzing.exe.
This is a common issue with BitDefender, there are a lot of Google hits on false positives.

I will contact them directly to find out about the problem.

**Attachment:** [Fritzing.exe_Viruswarnung.jpg](http://code.google.com/p/fritzing/issues/detail?id=2639)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2639_

**Comment by KjellMorgenstern** [comment]
This issue is closed because it is outdated.
If you think this issue is still important, please reopen.
