### ISSUE TITLE
ground fill border setting

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2638]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 27, 2013 17:32:03_

At present it is hard-coded. Really the only implementation issue is overloading the UI.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2640_

**Comment by KjellMorgenstern** [comment]
A keepout can be set. If "border setting" was the same as "keepout" then, this issue is already solved.
![image](https://github.com/fritzing/fritzing-app/assets/6494025/e3c5d98c-804a-44fa-adf8-69cfb03b347b)

Link to google code is dead -> Closing.
