### ISSUE TITLE
reinstate the old "doesn't need to end in /" fritzing web addresses

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2640]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 30, 2013 14:30:27_

There many links to the Fritzing website which used to bring up a legitimate web page, but now bring up a 404 page with a stack trace. Since links of this form are all over the place, the old functionality should be restored.

For example, the Fritzing software currently accesses this location, which now brings up the 404 + stacktrace: http://fritzing.org/projects/create The new address is http://fritzing.org/projects/create/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2642_

**Comment by failiz** [comment]
outdated?
