### ISSUE TITLE
make drc give better hints for common problems

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2641]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 01, 2013 05:43:35_

for example, if routing a trace between pins on the same part, tell user to make the trace thinner, or make the connectors smaller

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2643_

**Comment by failiz** [comment]
Not sure if it is going to be a good idea, you could aslo trace the track differently and not always the same solution is the best.

**Comment by KjellMorgenstern** [comment]
If the trace gets to close to the pins, DRC will highlight the issue. I think it is up to the user how to resolve this.
