### ISSUE TITLE
what happened to these part fzp files

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2645]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 03, 2013 07:28:55_

"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-SMD not found in database" 
"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-PTH not found in database" 
"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-RA_LOCK not found in database" 
"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-LONGPADS not found in database" 
"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-LOCK not found in database" 
"module id SparkFun-Connectors-ARDUINO_SERIAL_PROGRAM-PTH-KIT not found in database"

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2647_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
