### ISSUE TITLE
PCB-View, fast flickering selection

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2646]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on July 03, 2013 08:09:28_

the new function in pcb-view makes you able to select parts behind other parts. it's realy great. But it is very hard to use it longer time because of the "flickering" selection-rects. a short delay or a smoother come in could be better to reduce noise for the user eyes. 

other ideas?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2648_

**Comment by failiz** [comment]
I do not observe this behavior in 0.9.6

**Comment by failiz** [comment]
Related to  #3584

**Comment by KjellMorgenstern** [comment]
Seems this is solved, can not reproduce, too
