### ISSUE TITLE
Special characters in file names cause trouble in Fab

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2648]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on July 03, 2013 17:08:36_

Trying to upload fzz files with special characters in the name are causing an error (see log below). This error is not visible to the user, even worse, he gets no feedback, and no file is uploaded.

This error is different from the one we had before. We solved it previously by only allowing certain characters (using  regexp "^[a-zA-Z0-9 _.-+]+$" in constraint.py), but now the file isn't even stored when there's just a '+' in the filename--this worked fine before.
This might be related to an update in Plone, possibly this one:

plone.app.blob: 1.5.5 → 1.5.6
- Don't fail on obscure chars in filename [tomgross]

Log:
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 46, in call_object
  Module plone.z3cform.layout, line 70, in **call**
  Module plone.z3cform.layout, line 54, in update
  Module plone.dexterity.browser.add, line 112, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 138, in update
  Module z3c.form.action, line 99, in execute
  Module z3c.form.button, line 315, in **call**
  Module z3c.form.button, line 170, in **call**
  Module plone.dexterity.browser.add, line 99, in handleAdd
  Module z3c.form.form, line 247, in createAndAdd
  Module fritzing.fab.faborder, line 241, in add
  Module Products.BTreeFolder2.BTreeFolder2, line 426, in _setObject
  Module plone.folder.ordered, line 239, in _checkId
  Module Products.CMFCore.PortalFolder, line 310, in _checkId
  Module OFS.ObjectManager, line 97, in checkValidId
BadRequest: The id "7 Segme+ntdirect.fzz" contains characters illegal in URLs.

> /Users/andre/Plone/zinstance/eggs/Zope2-2.13.19-py2.7.egg/OFS/ObjectManager.py(97)checkValidId()
> -> 'The id "&#37;s" contains characters illegal in URLs.' &#37; escape(id))

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2650_

**Comment by failiz** [comment]
Outdated?
