### ISSUE TITLE
groundfill taking shortcuts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2650]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 04, 2013 05:23:06_

originally from comment 2 issue #2649 (and see attached file there)

Also while you are looking at the fzz, note that the ground fill on the top seems to "take a short cut" across some inside curves on curved traces, would be nice if that was fixed sometime would be more aesthetically pleasing to follow the curve all the way around :)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2652_

**Comment by failiz** [comment]
I don't think that there is enough info to debug
