### ISSUE TITLE
mac OSX 10.8 default compiler causing lots of overload warnings

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2652]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 04, 2013 09:40:51_

In file included from ../fritzing/src/fapplication.cpp:68:

../fritzing/src/sketch/pcbsketchwidget.h:204:7: warning: 'PCBSketchWidget::wireSplitSlot' hides overloaded virtual function [-Woverloaded-virtual]

void wireSplitSlot(class Wire*, QPointF newPos, QPointF oldPos, QLineF oldLine);

../fritzing/src/sketch/sketchwidget.h:575:15: note: hidden overloaded virtual function 'SketchWidget::wireSplitSlot' declared here

virtual void wireSplitSlot(class Wire*, QPointF newPos, QPointF oldPos, const QLineF & oldLine);

---

see http://stackoverflow.com/questions/9995421/gcc-woverloaded-virtual-warnings

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2654_

**Comment by failiz** [comment]
Is a warning during compilation a bug? Does still happen in 2020? What is the default compiler?

**Comment by KjellMorgenstern** [comment]
While i think that warnings from the compiler should not be ignored, tracking them with github seems not so useful. Especially when the ticket is old. Lots of warnings have been fixed since then.
