### ISSUE TITLE
curved traces cover through holes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2653]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on July 04, 2013 21:35:00_

If you draw a curved trace, the ends cover the holes they extend from.

A workaround is you can add a bendpoint at each end very close to the hole to create a straight segment from the hole to the start of the curve (and other hole to the other end of the curve), but it's quite annoying to do so.

See attached.

**Attachment:** [holes.png](http://code.google.com/p/fritzing/issues/detail?id=2655)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2655_

**Comment by failiz** [comment]
Still an issue in 0.9.6, but  #3120 is basically the same issue. I would close this and write this case in the other one.

**Comment by KjellMorgenstern** [comment]
Closing in favor of #3120
