### ISSUE TITLE
Version 0.8.0 to 0.7.11

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2654]
_From [Thetinkerer101](https://code.google.com/u/Thetinkerer101/) on July 04, 2013 23:02:18_

What steps will reproduce the problem? 1. Loading the attached file from 0.8.0 into 0.7.11 What is the expected output? What do you see instead? The traces should be where I put them in 0.8.0, however, in 0.7.11, the copper rendering is all skewed, but the mouse-over outlines are all correct. What version of Fritzing are you using? On what operating system? 0.8.0 and 0.7.11 on MACOSX 10.7.5

**Attachment:** [OLEDWATCH.fzz](http://code.google.com/p/fritzing/issues/detail?id=2656)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2656_

**Comment by failiz** [comment]
This is not a bug, you cannot open a file created in 0.8.0 into 0.7.11.
