### ISSUE TITLE
Strange silkscreen shapes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2658]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on July 10, 2013 06:28:41_

attached file is creating a strange silkscreen in the gerber export – maybe something that can be automaticaly solved next time

(top right)

**Attachment:** [Bildschirmfoto 2013-07-10 um 12.27.43 – 10.07.2013.png 41793208_PCB-decop-2.fzz](http://code.google.com/p/fritzing/issues/detail?id=2660)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2660_

**Comment by failiz** [comment]
I would close this and maybe create a new issue for "warn the user that the Fritzing is unable to completely deal with it."
