### ISSUE TITLE
Part editor cannot properly load new image for view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2659]
_From [ckel...@ca-cycleworks.com](https://code.google.com/u/114158986152099077944/) on July 10, 2013 17:55:40_

What steps will reproduce the problem? 1. Edit any part, core or otherwise
2. Click Schematic tab
3. File / Load image for view What is the expected output? What do you see instead? A warning dialog opens saying OCRA or Droid fonts expected and will be substituted.

Expecting to see the pin labels nicely, instead they're HUGE. This happens with my SVG files and also the CORE files' schematic SVGs, specifically M5450_LED_Driver_schematic.svg

What version of Fritzing are you using? 
Version 0.8.0 

On what operating system?
Windows 7 Professional SP1 64 bit

**Attachment:** [font_subs.jpg bad_font.jpg](http://code.google.com/p/fritzing/issues/detail?id=2661)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2661_

**Comment by failiz** [comment]
The issue was addressed and it was not ab bug

**Comment by failiz** [comment]
Any reason to keep this open?
