### ISSUE TITLE
Frustration in PCB design when moving components - ratsnest wires get turned into traces. 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2663]
_From [SharmanJF](https://code.google.com/u/SharmanJF/) on July 15, 2013 01:08:26_

What steps will reproduce the problem? 1. Accidental click on ratsnest wire that runs through a small component when trying to select the component, e.g. a SMT capacitor (very little visibility even at large magnifications).
2. The ratsnest wire gets turned into a trace obscuring even more of the small component etc.
3. The only way out is to Undo (ctrl-Z).

Attach your sketch file and/or custom part files to the bug report. N/A

What is the expected output? THIS IS A CHANGE REQUEST. What do you see instead? I would like:
1) Escape key press to abandon the grab of the ratsnest wire (or any other for that matter);
2) Components to have a higher priority than ratsnest or traces so that components get picked instead.  [Only if that does not prevent trace pick-up from a connection point when required.  Should not be an issue if design is done in the schematic.]

What version of Fritzing are you using? Fritzing v0.8b. On what operating system? Windows 7 Professional 64-bit - very fast machine. Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2665_

**Comment by cashpipeplusplus** [comment]
This is going to drive me back to Eagle.  It is damn-near impossible to do a board layout because the ratsnest is in the way.  I have to zoom WAY in, and then click on exactly the right pixel to avoid the ratsnest wires.

**Comment by Intrinsically-Sublime** [comment]
> This is going to drive me back to Eagle. It is damn-near impossible to do a board layout because the ratsnest is in the way. I have to zoom WAY in, and then click on exactly the right pixel to avoid the ratsnest wires.

Go to view and turn off ratsnest. Problem solved.

**Comment by cashpipeplusplus** [comment]
Thanks!

**Comment by failiz** [comment]
Remove imported label

**Comment by failiz** [comment]
Add pcbview and ui

**Comment by KjellMorgenstern** [comment]
How can we make the solution more intuitive to find? Turning of the ratsnest might also be not always the best way.
Maybe right click the ratsnest and move to back? 
Or a dedicated button to enable disable it?

**Comment by failiz** [comment]
I like the second idea of the first message: "Components to have a higher priority than ratsnest or traces so that components get picked instead. " I am not sure about the traces though. But rastnests can still be double click to be placed and usually there is some gap between components. And traces can still be placed by dragging from the connectors. Probably we could also fine tune the selection algorithm.
A button could help, but it should make the rastnets not selectable but still visible. But that is #1400.

**Comment by KjellMorgenstern** [comment]
This was solved along with https://github.com/fritzing/fritzing-app/issues/4012
