### ISSUE TITLE
Incomplete set of IC generic pin & shape preventing PCB layout

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2665]
_From [SharmanJF](https://code.google.com/u/SharmanJF/) on July 15, 2013 03:15:22_

What steps will reproduce the problem? 1. QFN shapes do not include 6 through to 18 pins, and 16 is a popular size
2. XTAL and silicon oscillators come in 6 pin QFN type packaging but with pins 2 and 5 missing (see TXC 7 series and ABRACON ASVMP range from Element 14 (formerly Farnell) - next to impossible to create from existing shapes).
3. The MAX6966 LED driver comes in Thin QFN16 (Element14 supply this version) and QSOP16 packages but the pin to signal designations are different, e.g. TQFN pin 1 is P0, but the QSOP pin 1 is SCLK - this suggests that it should be possible to have two pin lists for a device in case a substitution is needed. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I would like to see comprehensive guide to developing new devices as quite a lot of what I have been doing has required me to modify existing templates in ignorance.

What version of Fritzing are you using? 0.8b On what operating system? Windows 7 Professional 64-bit. Please provide any additional information below.

**Attachment:** [TXC 7w.pdf ABRACON  ASVMP.pdf MAX6966-MAX6967.pdf](http://code.google.com/p/fritzing/issues/detail?id=2667)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2667_

**Comment by failiz** [comment]
Regarding 1, I would move this to #1935.
Regarding 2, I do not think it should be implemented. Too much work for a special case. I would focus on the part editor instead.
Regarding 3, I also do not think that it should be implemented. The solution is just to create to different parts (as they are different). Some devices could have 8 different implementations.

**Comment by KjellMorgenstern** [comment]
Closing in favor of #1935 .
