### ISSUE TITLE
gerber export missing contour for hole in lower left corner

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2666]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 16, 2013 05:02:46_

see file in 000068: 84712963

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2668_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
