### ISSUE TITLE
ubuntu software center, app store, etc

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2667]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 17, 2013 03:26:06_

make releases compatible with these venues

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2669_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
