### ISSUE TITLE
Feature Request: Autorouter option to only use vias to cross sides

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2668]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on July 17, 2013 04:04:55_

Presently the auto router can use through hole component holes as a cross point to go from one side to the other.  

If using a board with plated through holes that's fine, but when home-etching a PCB you don't typically have that luxury.

An option to the auto router to only be permitted to use vias to cross planes would be useful.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2670_

**Comment by failiz** [comment]
I think this is not a very interesting enhancement. A few reasons: 
1) the costs of a manufactured PCB have dropped a lot in the las years and it is much more common to order the PCB than etch it or mill it at home. 
2) in most TH components, you can solder at the bottom and at the top and then there is collection between both layers. This does not work for connectors.
3) The autorouter does not know if a via is under a component. DIY vías need to be soldered on both sides and they are a small protrusion that does not allow to have a component on top. Si, the implementation of the feature is found to be complex (there is no a courtyard around each component)
Work around: autoroute the board and fix the problematic connections by hand

I would recommend to choose the issue. There are more important issues to fix.
