### ISSUE TITLE
Changing Net Label name deletes wires

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2669]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on July 17, 2013 23:19:52_

What steps will reproduce the problem? 1. Drag label onto schematic
2. Connect it to a bend point on some wire between a couple of components
3. Change the label name
4. Observe that the complete wire you connected it to including through bendpoints is deleted and the label and components are not connected to anything anymore.

This occurs not just with new labels, renaming any label deletes the wire(s) connected to it right though bendpoints.

It is not be undo-able either, so rather annoying if you rename a label connected to a complicated wiring, and poof, all gone :-(

I don't think renaming the label should delete any wires, doesn't make sense to me to do that.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2671_

**Comment by failiz** [comment]
Still reproducible in 0.9.6. It is the same problem as in #1326 (wires disconnect when changing power symbol´s text). I would merge both issues here (and change the title).
