### ISSUE TITLE
hard to select the shield underneath the part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2674]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 23, 2013 03:23:21_

select the arduino in a sketch with multiple boards--the drc doesn't think it's a board.

**Attachment:** [Melody3.fzz](http://code.google.com/p/fritzing/issues/detail?id=2676)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2676_

**Comment by failiz** [comment]
No file available. Duplicate of #3569 and others
