### ISSUE TITLE
View From Below, Ruler, Silk Problems

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2678]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on July 25, 2013 04:16:36_

Switch to View from Below (incidentally, the button label is cut off too, see images)

Notice that the ruler is mirrored.

Notice that the silk screen on the bottom is:

  a) still grey and hard to see - my personal expectation would be that the silkscreen on the "current" side would be white, the grey is more appropriate to indicate that you are looking "through" the board, which you're not when you've flipped it over.  This could perhaps be mitigated if we could choose the colours for silkscreen, so I could make it brighter.

  b) obscured by traces etc which are on the top layer, stuff on the "other" side of the board should not be able to appear above stuff on the current side of the board.

**Attachment:** [view-below.png](http://code.google.com/p/fritzing/issues/detail?id=2680)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2680_

**Comment by KjellMorgenstern** [comment]
Grey: Checked with 0.9.4, the rendering is consistent.
The grey becomes only hard to see if the view is from top layer, and clickable elements are top layer, and silkscreen is bottom layer.

Ruler: Won't fix for now, but it would make sense to at least give the option to flip a ruler.
