### ISSUE TITLE
when fritzing starts up with a non-sketch file, default parts are not created

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2680]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 25, 2013 11:03:25_

for example, double-click a bin file to start up

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2682_

**Comment by failiz** [comment]
The core parts are created. Are there other default parts?
