### ISSUE TITLE
New objects show up extremely small in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2683]
_From [zeldarul...@gmail.com](https://code.google.com/u/117826949897414446584/) on July 25, 2013 19:58:15_

What steps will reproduce the problem? 1. Open Fritzing
2. Get a part from any of Sparkfun's newly created parts
3. View in schematic view What is the expected output? What do you see instead? The schematic part should show up normal sized (e.g. An Arduino UNO R3 ), but shows up in a size that's only readable in 200&#37; zoon What version of Fritzing are you using? On what operating system? Fritzing 0.8.1 on Ubuntu 13.04

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2685_

**Comment by failiz** [comment]
Not able to replicate in 0.9.6, but not sure which parts are the newly created...
The five parts that I tried, all had the connectors set to 0.1 in.
