### ISSUE TITLE
raspberry pi connectors are not female or male, but pad doesn't seem to do the trick

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2684]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 26, 2013 06:38:53_

allow wires to connect but not other parts, and not to the breadboard. Either pad is not working, or a new classification is needed

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2686_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.

**Comment by failiz** [comment]
@KjellMorgenstern, you forgot to close the issue...
