### ISSUE TITLE
button example is not fully routed in bb view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2685]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 26, 2013 08:10:20_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2687_

**Comment by failiz** [comment]
This is a related to issue #3616. Same behaviour than connecting two components through a breadboard.

**Comment by failiz** [comment]
The fix for the issue #3616 did not fix this. Working on a fix for this,

**Comment by failiz** [comment]
already released, close
