### ISSUE TITLE
Perhaps my newly created part ( LM393 ) is defective ....  ratsnest lines ( RNL ) appear by magic

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2686]
_From [ags...@gmail.com](https://code.google.com/u/102396176247280453443/) on July 27, 2013 11:15:45_

What steps will reproduce the problem? 1.Delete a rat's nest line attached to LM393
2.More RNLs appear magically 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? 082  OS X 10.6.8 Please provide any additional information below.

**Attachment:** [dual temperature switch LM393 v5 .fzz Fritzing log.txt](http://code.google.com/p/fritzing/issues/detail?id=2688)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2688_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
