### ISSUE TITLE
open source part libraries to import?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2690]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 30, 2013 02:13:14_

Adafuit - http://www.ladyada.net/library/pcb/eaglelibrary.html Seeed Studio - https://github.com/Seeed-Studio/EagleLib-of-Seeedstudio Dangerous Prototypes - http://dangerousprototypes.com/docs/Dangerous_Prototypes_Cadsoft_Eagle_parts_library

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2692_

**Comment by KjellMorgenstern** [comment]
@PatrickFranken

**Comment by KjellMorgenstern** [comment]
Outdated issue, broken links. Some of the parts we already have.
