### ISSUE TITLE
a handful of UI bugs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2691]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on July 30, 2013 22:41:31_

http://fritzing.org/forum/thread/1628/?page=last

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2693_

**Comment by KjellMorgenstern** [comment]
Could not reproduce the capacitance settings issue.

**Comment by KjellMorgenstern** [comment]
Comment 4 does not have enough detailed desciption / can not be reproduced.

Ctrl- select bendpoint toggles the grid reliably
Shift- select bendpoint enables smart guidance, e.g. moving the bendpoint along a straight line with 90,45  degree or 1/3 slopes.

**Comment by KjellMorgenstern** [comment]
Comment 2: "In any view, when box-selecting (say) the left half of my circuit, when I drag-move the selection, most of the wire bend points stay where they are, resulting in a big mess of bend points that I have to manually straighten out. It seems like the components themselves, and any wires directly between them, are moved OK, but unconnected wire segments can't be moved on their own."

Bendpoints of unconnected wires and bendpoints of a wire partly selected are not moved together with the selection. 

Creating a seprate issue for this remaining comment.

**Comment by KjellMorgenstern** [comment]
Created issue #3609 for the remaining comment.
