### ISSUE TITLE
change connector highlighting in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2694]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 01, 2013 05:31:01_

Maybe just highlight the terminal point instead of the entire connector.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2696_

**Comment by failiz** [comment]
What is the reason? I do not mind that the entire connector is highlighted. In fact, in the BB view, some connectors are so small that are sometimes difficult to find, even when they are highlighted.
