### ISSUE TITLE
caught exception on 3 pins in one net

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2696]
_From [marcel.a...@gmail.com](https://code.google.com/u/101626057898779081415/) on August 02, 2013 09:08:50_

Fritzing 0.8.2b-1 and 0.8.3b-1 built from source tarball on Arch Linux. 

In any view (breadboard, schema, pcb) when 3-pins of different components are connected together into a single net Fritzing fails with following message:

"Fritzing caught exception from '' in event 157"

seldomly 

"Fritzing caught exception from '' in event 3"

Not always on the first net made, but always on the second/third.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2698_

**Comment by failiz** [comment]
This is a really old issue caused by the boost library version 1.54. Since 1.55 this problem has been fixed and the latest version is 1.75. Close?
