### ISSUE TITLE
SVG Export of schematic with IC contains incorrectly sized IC

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2698]
_From [ta...@lightup.io](https://code.google.com/u/106495197084350430972/) on August 03, 2013 18:41:08_

What steps will reproduce the problem? 1. Open attached file in schematic view
2. Export SVG for schematic
3. Open exported SVG in Inkscape

Using Fritzing 0.8.0 on Ubuntu 13.04.

**Attachment:** [Light Theremin.fzz](http://code.google.com/p/fritzing/issues/detail?id=2700)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2700_

**Comment by failiz** [comment]
No file available.
