### ISSUE TITLE
Arduino Pro Min V13 is not in grid in PCB

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2699]
_From [eero.ha...@gmail.com](https://code.google.com/u/109634745033994792479/) on August 04, 2013 04:47:38_

What steps will reproduce the problem? 1. I take Arduino Pro Mini V13 to PCB Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? - It shoulbe in the Grig 
  instead it is in between the grid meaning I can not draw straight lines to other components and I can nod design it to PCB that already have holes. What version of Fritzing are you using? On what operating system? Vesion 0.8.3 (b048f2013-07027) Qt4,8,3 Please provide any additional information below. - I could not find out how to correct this with Parts Editor

Thank You 
- Eero -

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2701_

**Comment by KjellMorgenstern** [comment]
If you think this issue is still important, please provide additional information.
  - What version of Fritzing are you using? 
  - Screenshots with error messages or rendering issues.  
  - Attach your sketch file and/or custom part files to the bug report.
