### ISSUE TITLE
Pressing enter in parts editor text fields often causes a crash

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2704]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on August 05, 2013 16:21:03_

When making or editing a part with the new parts editor, choose the PCB or schematic view and click on a connector. Try to edit the name or description, then press enter. Fritzing crashes.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2706_

**Comment by failiz** [comment]
I cannot replicate it in 0.9.4 in Windows (as before). This is an old issue and not reproducible, close?
