### ISSUE TITLE
Please add CFBundleShortVersionString and/or CFBundleVersion strings to Info.plist for OS X version

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2707]
_From [rustici...@gmail.com](https://code.google.com/u/117354857925856529956/) on August 06, 2013 13:31:52_

It would be greatly appreciated and exceedingly helpful for our software management and deployment system (Munki) if the Fritzing.app bundle had useful and correct "CFBundleShortVersionString" and/or "CFBundleVersion" key-value pairs added to the Info.plist file.

The deployment system compares these values to what it finds on disk to make decision whether update is available/required and act accordingly. Without those keys/values it defaults to version "0.0.0.0.0" which is, obviously, unhelpful. (It's also a bit of pain to manually add this every time I deploy an update.

So, if it's easy to add to your workflow, it would be GREATLY appreciated by sysadmins! Thank you. No rush.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2709_

**Comment by failiz** [comment]
This seems fixed. If this mechanism still being used and if so, is this automated in the CI?

**Comment by failiz** [comment]
Ping
