### ISSUE TITLE
gmake install illegal -D option

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2710]
_From [patrick....@gmail.com](https://code.google.com/u/102826629042216635344/) on August 12, 2013 06:51:29_

Hello,

I've just installed Fritzing last version (0.8.3b) on FreeBSD 9.1-RELEASE-p5.

Gmake gave me the following error : 
"install -D -m 0644 resources/images/fritzing_icon.png /usr/share/icons/fritzing.png
install: illegal option -- D"

I've solved the problem by deleting the -D option in the file Makefile.Release (see modified file in attachment). The command must be changed as following :
install -m 0644 resources/images/fritzing_icon.png /usr/share/icons/fritzing.png

Then everything went fine !

Thanks a lot for your work !

**Attachment:** [Makefile.Release](http://code.google.com/p/fritzing/issues/detail?id=2712)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2712_

**Comment by failiz** [comment]
Outdated?
