### ISSUE TITLE
Stripboard rotated between 0.7.11 and 0.8.3

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2713]
_From [l...@lukewoodbury.co.uk](https://code.google.com/u/108713730900152555932/) on August 15, 2013 05:37:28_

What steps will reproduce the problem? 1. Create a square piece of stripboard (10x10) in Fritzing 0.7.11 with horizontal running strips and save
2. Open in Fritzing 0.8.3
3. Strips are now running vertically

MBPro 10.6.8

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2715_

**Comment by failiz** [comment]
I would close this issue. These versions are old and there will not tool many migrating from 0.7.11 now. And we don't have the resources to do it soon, so it will become less and less a real issue
