### ISSUE TITLE
fritzing website search results ending in 404

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2714]
_From [stefanhermann79@googlemail.com](https://code.google.com/u/stefanhermann79@googlemail.com/) on August 16, 2013 02:34:43_

go to Fritzing website
search for »Zack Freedman«
klick the project link
you end up here: http://fritzing.org/projectstouch-my-piano you should end up here: http://fritzing.org/projects/touch-my-piano

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2716_

**Comment by failiz** [comment]
outdated?

**Comment by KjellMorgenstern** [comment]
Search and link work just as expected for this case, closing
