### ISSUE TITLE
Moving parts with arrow keys is reversed when viewing PCB from below.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2715]
_From [elija...@mac.com](https://code.google.com/u/100346973317850103324/) on August 17, 2013 12:39:45_

If you switch to viewing the PCB from below and try to move a part with the arrow keys, it moves in the opposite direction to the arrow key you press. The part should move the same direction as the pressed key.

OS X.8.4 latest Git build.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2717_

**Comment by failiz** [comment]
It is still present in 0.9.6. remove imported label, add pcbview
