### ISSUE TITLE
Can't bend wires in schematic after drawing pcb and turning rats nest into traces

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2732]
_From [TarunPon...@gmail.com](https://code.google.com/u/115247822706866350968/) on August 23, 2013 18:55:36_

What steps will reproduce the problem? Draw a PCB in Fritzing and connect traces
Go into schematic view and turn a rats nest connection into a trace. Try to drag the trace to create a bendpoint. It turns red but doesn't work.
File where the issue manifested is attach. Open the file and try to add a bendpoint to any of the traces.

Debugging output says:
dragging bendpoint
deleting connector drag wire What version of Fritzing are you using? On what operating system? 0.8.3 on Ubuntu (would be nice if you make the text in the about box copyable)

**Attachment:** [Microcontroller 32u4.fzz](http://code.google.com/p/fritzing/issues/detail?id=2734)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2734_

**Comment by failiz** [comment]
Not reproducible. Close
