### ISSUE TITLE
wire thickness option should not be available in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2734]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 25, 2013 14:29:28_

currently it is available, but does nothing

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2736_

**Comment by spassignat** [comment]
Here is how I do to make a little "sure" I'm not messing up the wires, but when I layout the PCB, I discover swapping wires simplifies and then forget to review the other card ... 
I thought to make my own header with "named" pin, tried to have all pcb in the same fritzing project ... but none are really satisfying...
Colors helps to quickly identify wires, reason why I was thinking about another visual "solution".

 
![image](https://user-images.githubusercontent.com/6451374/139631321-9dadf60d-2fb3-4408-8c88-0f514f0f6179.png)
![image](https://user-images.githubusercontent.com/6451374/139631400-098e0f41-9aa1-42ac-8ab1-ba59113bbd86.png)

**Comment by failiz** [comment]
When two netlabels have the same text, they are connected together. Thus, you only need the connector, a netlabel and a short wire connecting them together. The wire should not anywhere else.

Netlabels are not just labels. Try to connect a resistor to two netlabels on each end. When the text of the netlabels is the same, you will see a ratsnet on the pcb or breadboard view, indicating that they should be connected.

**Comment by spassignat** [comment]
So you're suggesting to have several pcb board in the same sketch.

I'll give it a new try, I don't remember why I had difficulties in the previous attempts.

**Comment by failiz** [comment]
I didn't know that you had two PCBs. I never tried two PCBs in the same sketch. I don't think you should change your approach.
I would only have the connector and the netlabels with short wires. I don't know why you have long wires going out the image. Instead of that, use netlabels in the other end of the wires.
