### ISSUE TITLE
more command-line export options

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2737]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 29, 2013 03:42:52_

http://fritzing.org/forum/thread/1686/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2739_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
