### ISSUE TITLE
log rotation on fritzing.org

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2738]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 29, 2013 22:31:06_

From Daniel:

I just had to empty some log files  in /var/log/apache2/. It seems like the logration does not work for those. I don't have the time to take care of that. Please have a look.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2740_

**Comment by KjellMorgenstern** [comment]
Won't fix.
