### ISSUE TITLE
fritzing downloads

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2739]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 29, 2013 22:32:38_

from Daniel:

I just found out that the releases of Fritzing in the media-folder seems to be in there twice. Once in the folder downloads/ and a  second time in uploads/downloads. Either the apps.downloads is awfully broken or these are stale files. Maybe you want to have a look.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2741_

**Comment by KjellMorgenstern** [comment]
This issue is closed because it is outdated.
If you think this issue is still important, please reopen.
