### ISSUE TITLE
breadboard logo image should allow full color jpgs

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2744]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 06, 2013 01:00:28_

and add a color option to the logo text image

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2746_

**Comment by failiz** [comment]
Mmm, not sure what the issue is. The logo text has an option to specify the color of the text. The image can load color jpg images.
