### ISSUE TITLE
wrong group description on Core part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2745]
_From [nathap...@gmail.com](https://code.google.com/u/110485011223932639843/) on September 08, 2013 14:27:37_

Language : french
Version : 0.8.3

In core parts box, the item group for the pcb view is called "Vue de la platine d'essai" (breakout board view).

I don't know if this problem appear with other languages. Attach your sketch file and/or custom part files to the bug report.

**Attachment:** [Capture du 2013-09-08 20:22:44.png](http://code.google.com/p/fritzing/issues/detail?id=2747)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2747_

**Comment by failiz** [comment]
I think this is outdated as the developer fixed the reported issue.
