### ISSUE TITLE
TLC5940 not found

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2748]
_From [helmer.m...@googlemail.com](https://code.google.com/u/101859101010070905752/) on September 13, 2013 07:10:47_

adding the TLC5940 PWM IC cant be found inside library,
leads to a loop of error messages:

"/Applications/Fritzing/pdb/user/sparkfun-digitalic-tlc5940--nt.fzp: file for Packages: SparkFun-DigitalIC-TLC5940--NT not found."

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2750_

**Comment by failiz** [comment]
I cannot reproduce this in 0.9.4 (windows) and there are four TLC5940  parts that appear in the search. All of them work correctly.
