### ISSUE TITLE
User-created parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2751]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on September 17, 2013 04:16:29_

This is a space for Fritzing users to upload and share their self-created 
parts with others.

Add your part by adding a comment to this issue and attach your part as a 
.fzpz file. 
(You can get this by right-clicking your part in the parts palette and then 
clicking "Export..")

Make sure you have quality-checked it, and add a description in the comments 
text. If you have any problems with your part, please try to fix it first by 
getting help in the fritzing.org forums.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2753_

**Comment by mcauser** [comment]
Micro Python pyboard:
https://github.com/mcauser/Fritzing-Part-Micro-Python-pyboard

**Comment by vfilby** [comment]
It seems like these all link back to code.google.com, and are no longer accessible due to a redirect.  Would it be possible to point the actual files over?  The one that I have been having difficulty is the AD9850 part.

**Comment by aknoerig** [comment]
Unfortunately, Google Code has gone from read-only mode to nirvana mode -- all entries are lost, I'm afraid!
But to get the AD9850, simply take the "generic IC" part (first part under ICs) and set it to 28 pins.

**Comment by aknoerig** [comment]
Closing this now, in favour of the new parts-sharing place in the forum: 
http://forum.fritzing.org/t/share-your-custom-made-parts-here/791

**Comment by PereGhis** [comment]
Hello Everyone,
I'm new and I need to find the ATTINY2313 part for Fritzing, I need explanations to "how to get it".
Sorry, but englsh is not my native language.
Best Regards,
Pascal
Belgium
