### ISSUE TITLE
Error in Routing with MCP23017

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2754]
_From [RainerOt...@googlemail.com](https://code.google.com/u/106453161197931540378/) on September 22, 2013 14:34:30_

What steps will reproduce the problem? 1. Load the sketchfile
2. Go to layout-Editor
3. Double-Click on one of the 2 wires

The wires swap, so why?

Actual Fritzing (0.8.3)

**Attachment:** [Routing Error.fzz](http://code.google.com/p/fritzing/issues/detail?id=2756)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2756_

**Comment by KjellMorgenstern** [comment]
Closing, as the pcb svg file is not available anymore.
