### ISSUE TITLE
Breadboard, Schematic, and PCB tabs overlap menu on custom UI size in windows

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2755]
_From [ChadHe...@gmail.com](https://code.google.com/u/111100767294542138280/) on September 22, 2013 16:31:04_

What steps will reproduce the problem? 1.In windows 8, right click on desktop and select Screen resolution
2. Click on the link that says "Make text and other items look larger or smaller"
3.Change size to anything other than 100&#37; 
4. Open Fritzing and notice tabs overlap menu.

What is the expected output? Expect to see tabs below menu.  What do you see instead?  Tabs overlap menu.

What version of Fritzing are you using? 0.8.3 On what operating system?  Windows 8 (But I suspect this can be reproduced on any version of windows)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2757_

**Comment by failiz** [comment]
They look well in 0.9.6 (Windows) with 150% scaling
