### ISSUE TITLE
copper blocker layer change is broken

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2756]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 30, 2013 23:10:54_

http://fritzing.org/forum/thread/1730 . But you can work around it by selecting the active layer.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2758_

**Comment by failiz** [comment]
From the old forum:
"Latest post time: 2013-10-01 03:09:51 UTC

Author: 12578

Body: I have been unable to move the "copper fill blocker" to the bottom layer. Every time I select the "copper bottom" button in the pcb layer window of the Inspector, the program immediately returns to "copper top". I am running version 0.8.3(2013-07-27)using Window's Vista. Is there a way to open a blocking window on the bottom layer?

Time: 2013-09-30 22:46:31 UTC

Edited at:

Author: 8

Body:

Hi KE6PI,

It appears that layer-changing is indeed broken for the copper blocker. However, there is an easy workaround. Toggle the Active Layer button in the toolbar at the bottom of the window until you have selected Bottom. At that point, when you drag a copper-blocker from the Parts Bin, it will default to the bottom layer. If the Active Layer button state is Both or Top, then when you drag a copper blocker, it will default to the top layer."

**Comment by failiz** [comment]
I cannot replicate this in 0.9.9. The copper fill blocker can be moved to the bottom layer without problems.
