### ISSUE TITLE
Parts-Bin swapping back to iconview when enter another bin

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2760]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on October 16, 2013 10:12:23_
1. switch to listview (partsbin-window)
2. change the bin
3. the view goes back to icon-view, the marker in the menu shows listview

to come back to list-view you have to reclick it again in the dropdown menu

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2762_

**Comment by failiz** [comment]
Not a bug. Related to #2692
