### ISSUE TITLE
holes without copper should not appear in copper top (or bottom) pdf

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2765]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 26, 2013 18:49:14_

and maybe not in solder mask. http://fritzing.org/forum/thread/1771/?page=last

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2767_

**Comment by jamievicary** [comment]
This is causing us quite a bit of pain, please fix!! :)

**Comment by KjellMorgenstern** [comment]
Fritzing 0.9.9

![image](https://user-images.githubusercontent.com/6494025/145443992-9514cace-e9b7-4c20-a3fa-e6b2b2cdd123.png)

Gerber looks good:
![image](https://user-images.githubusercontent.com/6494025/145444072-0d617308-6d91-4ae1-9e08-b3470a9d78e1.png)

Paste mask for pdf and svg are empty, which seems correct.

I think we can keep the default that holes should appear in solder mask, but maybe this can be made optional.

However, the hole is included in "copper top" when exporting SVG or PDF:
![image](https://user-images.githubusercontent.com/6494025/145450706-4afdd057-45f4-4ee9-911f-e76c3c50877e.png)

Although that will be drilled away, this behavior differs from Gerber export, which does not produce/leave copper at the holes.
