### ISSUE TITLE
parts editor confused when only child copper layer has transform

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2771]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 03, 2013 01:58:50_

http://fritzing.org/forum/thread/1769/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2773_

**Comment by failiz** [comment]
From the old forum. Not sure if it is still relevant:

False warning by parts editor?
Views: 0

Latest post time: 2014-01-21 20:31:12 UTC

Author: 8704

Body:

Hi,

I have a very simple (for demonstrating my issue) svg file. It looks like below.

Why do I get the "This version of the new Parts Editor can not deal with separate copper0 and copper1 layers..." warning in the parts editor.

It seems to be the transform="scale(1,-1)  of cooper1 g element which causes the issue. If I move it to copper0 it works.

Why is there a difference? A bug?

<?xml version="1.0" encoding="utf-8" ?>
<svg baseProfile="tiny" height="4.4400mm" version="1.2" viewBox="-2.2199999999999998,-2.2199999999999998,6.9799999999999995,4.4399999999999995" width="6.9800mm" xmlns="http://www.w3.org/2000/svg" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs />
<g id="pcb">
<g id="copper0" >
<g id="copper1" transform="scale(1,-1)" >
<circle cx="0" cy="0" fill="none" id="connector0pin" r="0.7" stroke="#F7BD13" stroke-width="0.5" transform="translate(-1.27,1.27) rotate(-90)" />
</g>
</g>
<g id="silkscreen" transform="scale(1,-1)">
<path d="M 0 0" fill="none" stroke="#CCCCCC" stroke-width="0.5mm" />
</g>
<g id="keepout" transform="scale(1,-1)" />
<g id="outline" transform="scale(1,-1)" />
</g>
</svg>

Time: 2013-10-22 18:57:40 UTC

Edited at:

Author: 8

Body:

Hi Markus,

Sorry, missed this post. 

It's a bug--adding this to the issue tracker.

For reasons having to do with how Qt processes SVGs, when the file is loaded, the transform is moved out of the copper1 element and a new <g> element is created with the transform added. Effectively that gives <g id="copper0"> <g transform="scale(1,-1)"><g id="copper1"> and that confuses the Parts Editor. which is looking for <g id="copper0"> <g id="copper1">.

Note that the scale transformation on the circle is redundant anyway.

- j

Time: 2013-11-03 06:57:54 UTC

Edited at:

Author: 8055

Body: I have the same error, and what is most interessting: Fritzing can't handle its own core parts SVGs. I have exported a svg from a part then I reimport it and get the "seperate copper0 and copper1 layers" - Error

Time: 2014-01-19 17:38:20 UTC

Edited at:

Author: 8

Body: Given that there are over 1600 parts, created at different times by many different people, and there is only one guy to deal with it all... The next update of the parts editor will remove the restriction, but I am not sure what the schedule for that is. - j

**Comment by KjellMorgenstern** [comment]
Would be good to have the exact structure of the problematic svg. SVG handling was improved since then. SVG file it is not available. Closing this for now.
