### ISSUE TITLE
Fail with multiple transforms

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2772]
_From [snoozerw...@gmail.com](https://code.google.com/u/103395736618623481413/) on November 04, 2013 12:45:54_

What steps will reproduce the problem? 1. Create svg file with a svg element having attribute transform="translate(...) rotate(...)"
2. Use the file in parts editor for pcb view. 
3. Make a gerber export. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? Fritsing shows the svg correctly but the transform is when exported to gerber files. What version of Fritzing are you using? On what operating system? Using Fritzing 0.8.3 build 2013-07-27 on Windows 7. Please provide any additional information below. Combining transforms into a matrix transform should be a workaround although not confirmed. However that may require manual work.
Unless resolved, there should at least a warning when importing the file to the parts editor may be a good idea.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2774_

**Comment by moritzmhmk** [comment]
Noticed this problem with the Wemos D1 which has multiple groups with translate and rotate in one transform. Looking through the code [this](https://github.com/fritzing/fritzing-app/blob/a3d8cab74c48a67795d71c199c378317fe3aa633/src/utils/textutils.cpp#L889) line seems related.

**Comment by KjellMorgenstern** [comment]
Yes, that is the line. Currently i think the svgpp library is a good fit to solve those problems, but i did not yet evaluate it in depth.

**Comment by failiz** [comment]
Remove imported label
