### ISSUE TITLE
Don't disconnect if connector terminals of moved part are still in connector areas of host part

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#278]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on November 19, 2008 16:26:41_

What steps will reproduce the problem? 1. Drag breadboard on the canvas
2. Drag (e.g.) a 8 pin 555 on the breadboard and connect it
3. Touch the 555 (i.e move it 1 pixel) What is the expected output? What do you see instead? It would feel more natural if the small move would not disconnect the part from the breadboard, 
but the part would snap back into its sockets.
If you move it again 1 pixel (even further from the sockets), it snaps back to the same socket as 
before, because the connector terminals of the 555 are still in the region of the connector pins.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=278_

**Comment by failiz** [comment]
I could not reproduce this in 0.9.4 (Windows)
