### ISSUE TITLE
Phantom ratsnest wires cannot be delted without corrupting the views

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2782]
_From [grateful...@gmail.com](https://code.google.com/u/100421332840703192744/) on November 19, 2013 12:35:13_

What steps will reproduce the problem? 1. I had a perfect PCB view.
2. I laid out the Breadboard view
3. I laid out the Schematic view.
4. At this point all views were ok.
5. I made some cosmetic improvement in the breadboard layout: The routing was ok!
6. In both the schematic and PCB views new INCORRECT ratsnest wires had appeared. If I tried to remove them, the breadboard view got screwed up. Some could not be deleted in any way that I could find. Attach your sketch file and/or custom part files to the bug report. - File is attached

What is the expected output? 
The breadboard view is correct as are the other views if the ratsnest could be eliminated.

What do you see instead?

The PCB and schematic views report routing as incomplete. The breadboard view shows routing complete. This is incoherent. All views should update in parallel. What version of Fritzing are you using? On what operating system? - fritzing-0.8.3b.linux.i386
- on Ubuntu 12.04
- on Asus 1201N EEEPC Please provide any additional information below. I am available and desperately need a solution to send my PCB to you for FAB....

Thanks,
Bob

**Attachment:** [ArduStompPCB03.fzz](http://code.google.com/p/fritzing/issues/detail?id=2784)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2784_

**Comment by failiz** [comment]
The file of gone and there are no steps to reproduce it.

**Comment by RadioFlakes** [comment]
I have the same problem! If I move a component on the breadboard it creates an erroneous ratsnest line on the schematic that cannot be deleted, if I delete the erroneous ratsnest on the schematic, then the component on the breadboard jumps out of position and when you place the component back into position on the breadboard, the erroneous ratsnest on the schematic reappears! It cannot be deleted for it recreates itself on the other environment, ad infinitum!!!

**The schematic is: TO BE UNTOUCHABLE! A CHISELED IN STONE REFERENCE THAT IS NEVER EVER TO BE TOUCHED BY THE SOFTWARE ALGORITHM! IT SHOULD ONLY BE EDITED MANUALLY BE THE CREATOR!!! WHY WOULD ANYONE CREATE A PROGRAM THAT EDITS THE SCHEMATIC AUTOMATICALLY FROM THE BREADBOARD ENVIRONMENT? THAT IS BATSHIT CRAZY!!!**
I paid money for this program SO, I WILL SHOUT IF I FEEL LIKE IT!

**Comment by failiz** [comment]
@RadioFlakes , first of all you should keep a civilized tone. You can shout if you feel like it, but not here. 
Second, this is a bug very difficult to reproduce. If you can share the file, please upload it here. If so, someone could take a look at it and try to find the issue.
