### ISSUE TITLE
Mini USB B selection of usb-micro causes Fritzing to crash.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2783]
_From [Rachelra...@gmail.com](https://code.google.com/u/103057294531300290787/) on November 22, 2013 18:39:38_

What steps will reproduce the problem? 1. Breadboard view.
2. Select Mini USB B
3. Try and pack package to usb-micro Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? 0.8.3, Mac OSX 10 Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2785_

**Comment by failiz** [comment]
This could not be replicated in 2013 (Windows and Mac) and I could not replicate the crash in 0.9.4 (Windows). Close?
