### ISSUE TITLE
Gerber exported files missing the .gm1 (outline) data

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2784]
_From [flud...@gmail.com](https://code.google.com/u/100926065562272054660/) on November 22, 2013 23:35:22_

To recreate the bug:
1. Create a new project
2. Add something to it (any random component will do)
3. Export the PCB to Gerber format
4. View the .gm1 file in gerbv - it has no contour.

Attached a sample file created with above steps and the .gm1 contour file as created by Fritzing.

Expected output would be the board outlines. What we get is NO outlines.

Two amd64 versions of Fritzing have the same bug on Ubuntu 13.10 (amd64).
- 0.8.0 (b08d5 2013-06-12) [Qt 4.8.4]
- 0.8.3 (b048f 2013-07-27) [Qt 4.8.3]

changing PCB type from Rectangle to anything else and back has no effect. Deleting the PCB element and creating a new one has no effect.

**Attachment:** [gerber_no_outline.fzz gerber_no_outline_contour.gm1](http://code.google.com/p/fritzing/issues/detail?id=2786)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2786_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
