### ISSUE TITLE
new creator kit examples need language selection

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2786]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 26, 2013 11:18:27_

modify sketches/index.xml and change code accordingly

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2788_

**Comment by failiz** [comment]
The sketches/index.xml supports the translation of the sketches. What is needed is to translate them. Are they included in the instructions to the translators?
Remove imported label, add examples and translations label

**Comment by KjellMorgenstern** [comment]
Adding en, de, fr, es, pl, zh, it, ja, pt, ko and id translations.

**Comment by KjellMorgenstern** [comment]
I don't think we should duplicate examples for each language. Instead, we need to add language support to fz files. So, this is only about the xml file.
