### ISSUE TITLE
grid color under custom background color

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2792]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 03, 2013 01:34:29_

use some kind of opposite color generator

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2794_

**Comment by Sigma-One** [comment]
This would definitely be useful.

**Comment by failiz** [comment]
Remove imported label

**Comment by failiz** [comment]
Duplicate of #3750
