### ISSUE TITLE
qss junk

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2797]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 07, 2013 02:19:46_

there is a lot of junk in the qss file, particularly around welcome view, that needs to be cleaned up

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2799_

**Comment by failiz** [comment]
still relevant?

**Comment by KjellMorgenstern** [comment]
Closing this for now. It's quite hard to debug this or test the effects. Cleaning up this would be done as a side effect of a different refactoring, but not on a purpose in its own.
