### ISSUE TITLE
DRC detecting PTH-parts with just one copper-site

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2799]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on December 10, 2013 08:13:44_

in some cases we get sketches with old or broken pth-parts. these parts have just one coppersite in the svg. so if the gerber gets exported they produce a short with the automatically created copperfill from the pcb-production-inscriper. 

the problem is that this gets not detected and don't show up as a "bug" in the panelizer-output-file. 

an example is the file "53807694" from fab-order 000085

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2801_

**Comment by failiz** [comment]
Seems that it was addressed and fixed.
