### ISSUE TITLE
curvy wires get stuck in mode if wire has bendpoint

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2802]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 11, 2013 06:11:02_

It doesn't happen every time but:

draw out a wire in pcb view
drag out a bendpoint
drag out the curve on one of the connected wires
try to modify the curve on the same wire

the bug also occurs in bb view, but not as often

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2804_

**Comment by failiz** [comment]
I could not replicate this. Did not try too much. Dis you observe this behavior before?

**Comment by KjellMorgenstern** [comment]
Did not observer this yet
