### ISSUE TITLE
PCB-view: change text with double click

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2808]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on December 13, 2013 04:56:30_

if you have a custom text-window on your pcb
it would be nice to change the text in the frame directly
by clicking or double clicking in the text-frame.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2810_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
