### ISSUE TITLE
Arduino Boards can oly placed on Top Side Shields can be placed on both

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2823]
_From [michaelj...@gmail.com](https://code.google.com/u/101102059201293781730/) on December 17, 2013 04:44:43_

What steps will reproduce the problem? 1.Put in an Arduino Board you want
2.Put in an Arduino Shield you want
3.Choose the placed Arduino Board and try to change PCB-layer
  it is not possible
4.Choose the placed Arduino Shield and change PCB-layer her you can.
5.Please implement this Funktion also on Arduino Board's (all :-() Attach your sketch file and/or custom part files to the bug report. Not needed. What is the expected output? What do you see instead? On any Arduino Board the choose abiliti for PCB-Layer is not given. What version of Fritzing are you using? On what operating system? Version 0.8.4 (b8b2c 2013-12-07) [Qt 4.8.5] Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2825_

**Comment by failiz** [comment]
This has already been implemented. It is working for all the Arduino boards in 0.9.4. Close.
