### ISSUE TITLE
Crash: Parts Editor can't deal with separate copper0 and copper1 layers in my (new created) USB-ISS device

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2825]
_From [cvds...@gmail.com](https://code.google.com/u/104710969572323170005/) on December 17, 2013 09:43:27_

What steps will reproduce the problem? 1. Fritzing version 2013.12.15.pc on windows7 system.
2. Opening of the new part editor with my current designed part.
3. Saving makes fritzing chrashing.

See my new created file. There is a problem with the PCB version of the device. I don't know how to correct this.

When I open the file and right-click on the USB-ISS and try to edit the PCB I get a SVG problem: "This version of the new Parts Editor can not deal with separate copper0 and copper1 layers in 'C:/Users/Casper/AppData/Roaming/Fritzing/parts/svg/user/pcb/USB-ISS_2773e765ed915925cfe202f827134152_2_pcb.svg'. So editing may produce an invalid PCB view image"

The component can be opened in the new part editor but then I cannot replace the SVG file without fritzing stops working.

The next message is that Fritzing may have crashed. And I can select a file to recover. (I don't know what to do with this)

How can I modify the footprint to see the direction of the USB-connector whitout these errors? (I'm new with fritzing and trying to construct my own components)

Regards,
Casper

**Attachment:** [USB-ISS Multifunction USB Communication Module.fzpz USB-ISS_pcb_modification.fzz](http://code.google.com/p/fritzing/issues/detail?id=2827)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2827_

**Comment by tcurdt** [comment]
I am trying to create a new part that needs to have a top and a bottom copper layer. I thought I would just need to create a new layer - but then I am also getting this. So what's the suggest way of creating such components?

**Comment by el-j** [comment]
in the attached file are 2 cooper0 groups. that is not possible. because an id have to be unique. 
if you need to have smd-pads in a part and tht-connectors. the correct svg structure has to be like:
 <g id="copper0">
 <rect id="connectorXXpad />

        <g id="copper1">

            <circle fill="none" id="connectorXXpin".../>
             ...
        </g>
    </g>

the parts fzp (xml) needs to have just the one defined copper-layer for the smd-pad-connectors. 
the tht-connectors need both defined layers. e.g.:

**Comment by tcurdt** [comment]
@el-j hold on - what's wrong with

    <g id="copper0">
        <circle fill="none" .../>
        ...
    </g>
    <g id="copper1">
        <circle fill="none" .../>
        ...
    </g>

There are no clashing ids then.

**Comment by el-j** [comment]
the problem with that structure is that you have to have the double amount of connectors in the end.
another thing is that a circle will have a drill-hole and if there is no circle on the other side of the pcb the part will end up with a short in the gerber output. so the only way is having <copper1> inside of <copper0>

because this is not possible:
```
<g id="copper0">
    <circle fill="none" id="connector1pin" .../>
    ...
</g>
<g id="copper1">
    <circle fill="none" id="connector1pin".../>
    ...
</g>
```

so, it has to be:
```
<g id="copper0">
  <g id="copper1">
    <circle fill="none" id="connector1pin".../>
    ...
</g>   
</g>
```

**Comment by tcurdt** [comment]
Thanks for the clarification.
But that also means one has to manually change the svg after every save - because this

    <g id="copper0">
        <circle fill="none" .../>
        ...
    </g>
    <g id="copper1">
        <circle fill="none" .../>
        ...
    </g>

is how layers are expressed (at least in the tool I am using).

**Comment by el-j** [comment]
i think there must be a way to have a group with id in another group in a svg editor. the word "layers" is maybe a bit confusing because it means layers for fritzing but group-elements in the svg-structure. so you do not really need a layer in a layer, you need a group in a group.

**Comment by tcurdt** [comment]
Well, it's called layers in Affinity Designer and Illustrator.

**Comment by el-j** [comment]
i do not use layers in AI for the design. there is just one layer. copper and silkscreen are just groups with ids as you can see in the screenshot. but anyway, it is important to have the svg structured as i motioned it.

![image](https://cloud.githubusercontent.com/assets/2795534/6305793/f757eb98-b92d-11e4-84e4-3eb6f81d58cb.png)

**Comment by tcurdt** [comment]
Ah I see now. Thanks for clarifying again.
