### ISSUE TITLE
FRQ: Support for Specctra Export/Import format ( to use freerouting.net, qautorouter ....)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2831]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on December 19, 2013 23:25:37_

freerouting.net ( http://www.freerouting.net/ ) is a free autorouter which produces very good results and can be used from many PCB layout software (kiCad,  gEDA, Diptrace, Eagle....) through the Specctra dsn (export from pcb software) and ses (import from router) files.

qautorouter ( http://sourceforge.net/projects/qautorouter/ ) is a free (GPL) autorouter which similarly uses dsn and ses files.

There are other routers which also use this same format, which is something of a de-facto industry standard for pcb routing.

If Fritzing had a basic dsn export and ses import function then Fritzing could also use these autorouters.

The dsn and ses files are text based files, following a fairly simple syntax, the specifications for the dsn and ses file are defined by http://sm-7.net/upload/PCB/Autorouters&#37;20and&#37;20autoplacers/Cadence_specctra/Design_Language_Reference.pdf I've also attached a dsn produced by diptrace, and an ses file produced from that by freerouting.net, and a screenshot from diptrace after importing the SES so you can get a feel for what it's all about.

Looking at these documents, essentially the steps involved in doing this for Fritzing would be to generate a dsn which incorporates the net list a crude outline of each component (just a bounding box) and the land patterns for the pads/holes.  This dsn can then be used with the external autorouters, which produce an ses file, importing the ses to Fritzing would be a matter of reading the component placements/rotations, and wires/vias for each route, then reproducing those in the fritzing data.

**Attachment:** [rt.dsn rt.ses dipt.png](http://code.google.com/p/fritzing/issues/detail?id=2833)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2833_

**Comment by failiz** [comment]
remove imported label, but not very relevant for most users as there is already a basic autorouter

**Comment by KjellMorgenstern** [comment]
All links in this issue are outdated, we might as well create a new issue with then updated external routing services, if this is still a thing.
