### ISSUE TITLE
SVG export skips image for custom part. PDF/PNG export are OK

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2833]
_From [stephen....@gmail.com](https://code.google.com/u/101715070573995136397/) on December 20, 2013 01:29:41_

What steps will reproduce the problem? 1. Load mosfet_not_final.fzz (attached)
2. View breadboard
3. File -> Export -> As Image -> SVG, pick filename, OK
4. View resultant SVG in an SVG viewer. I tried Inkscape, Firefox, Chrome, GIMP, ... What is the expected output? What do you see instead? Most of the breadboard appears in the SVG fine, but the button is missing. If I export to PNG or PDF, the button appears as expected.

The SVG I used for "load image for (breadboard) view" is attached as 'Button 0.2" x 0.2." breadboard.svg' What version of Fritzing are you using? On what operating system? Fritzing git commit 18564b3 "more updated examples" (the packaged version on Ubuntu crashes)
Linux Ubuntu 12.10.

**Attachment:** [mosfet_not_final.fzz Button 0.2&#37;22 x 0.2.&#37;22 breadboard.svg](http://code.google.com/p/fritzing/issues/detail?id=2835)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2835_

**Comment by failiz** [comment]
The original bug was a user mistake creating one part. The latest comment I do not get if this is a bug. If accepted, I would close this one and open a new one without all the noise
