### ISSUE TITLE
Silkscreen bottom SMD components not flipped.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2835]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on December 20, 2013 06:39:45_

See attached, PCB view.  All the components were put on the bottom layer, but notice that the silkscreen labels are not (or if they are, they have not been flipped, they should be mirrored when viewed from top).

**Attachment:** [7-seg-jumbo-digit-only.fzz](http://code.google.com/p/fritzing/issues/detail?id=2837)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2837_

**Comment by KjellMorgenstern** [comment]
This issue is similar to  #2961 and #3186, both which have more data.
