### ISSUE TITLE
Silkscreen on bottom side of board for pin header (can not be moved to other side)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2837]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on December 22, 2013 19:16:43_

See attached fzz, the headers J4 and J5 have their silkscreen somehow on the bottom of the board, as if the header has been moved to the other side - but as far as I can see there is no way to do that.

I have no idea how I managed it, but there you go, seems no way to move it back either.

**Attachment:** [7-seg-control-only.fzz cyb6.png](http://code.google.com/p/fritzing/issues/detail?id=2839)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2839_

**Comment by failiz** [comment]
This seems that has been fixed
