### ISSUE TITLE
alternate method for finding text bounds?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2838]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 24, 2013 08:06:46_

instead of using FontMetrics and/or vector-to-raster techniques, create a temporary QGraphicsItem and use its bounds.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2840_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
