### ISSUE TITLE
hole part with zero hole diameter should not have a drill hole when exported to gerber

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2842]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 30, 2013 02:54:11_

need to add a "nodrill" attribute in this case

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2844_

**Comment by KjellMorgenstern** [comment]
Is there a valid use case for zero diameter holes?
Enforcing a "nodrill" attribute seems to make sense.
I think Fritzing should also warn about this when running the DRC.

**Comment by KjellMorgenstern** [comment]
Zero diameter holes will not be drilled. If the hole does have a copper ring, the copper will still be set -> There will be a copper circle on the PCB.
