### ISSUE TITLE
Arduino Pro Mini v13 on the grid placement shift

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2847]
_From [tremb...@gmail.com](https://code.google.com/u/118197217170027525143/) on December 31, 2013 19:25:51_

What steps will reproduce the problem? 1. Place Arduino Pro Mini v13 component on breadboard
2. Rotate it 3. Fritzing 0.8.5 WIN XP 32

**Attachment:** [firtzingBUG.JPG](http://code.google.com/p/fritzing/issues/detail?id=2849)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2849_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
