### ISSUE TITLE
set color dialog could also use a qss update

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2850]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 02, 2014 13:12:47_

and maybe a complete revision--andre has always hated it.  Note that in the current dialog, there isn't enough room for the text in certain languages (French, for example).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2852_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
