### ISSUE TITLE
board shape gerber contour fails with transform

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2855]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 07, 2014 14:27:39_

<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<svg xmlns=" http://www.w3.org/2000/svg " width="2.38406in" version="1.1"  height="0.411427in" viewBox="0 0 215.125 37.125" id="svg9922">
   <g id="board">
    <g transform="translate(1294.6064,27.107517)">
    <path fill="#338040" stroke="none"  id="boardoutline" fill-opacity="0.50196078" d="m -1079.5439,-27.044988 0,20.0000008 -115,0 0,17.0000014 -85,0 0,-22.0000022 -15,0 0,-15 z"/>
   </g>
 </g>
</svg>

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2857_

**Comment by KjellMorgenstern** [comment]
Similar issues have been fixed, and there is no data to reproduce this one.
