### ISSUE TITLE
handle mac pinch gesture as zoom

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2861]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 09, 2014 09:39:04_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2863_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
