### ISSUE TITLE
generic dip with apostrophe in the pin label

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2865]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 12, 2014 01:30:23_

comes out as escape sequence

see example timer.fzz.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2867_

**Comment by failiz** [comment]
I can see the apostrophe in 0.8.3 but there is no apostrophe in 0.9.4. However, I can see it if I open the example that comes in  0.8.3 with 0.9.4. So, the example has been modified, but the problem is still there.

**Comment by KjellMorgenstern** [comment]
After loading 0.8.3 timer.fzz in 0.9.4, saving and then reverting it (reloading the saved fzz) see pin Q7
![image](https://user-images.githubusercontent.com/6494025/96084070-b5b44f00-0ebe-11eb-9a2c-ee3247f8a28d.png)
![image](https://user-images.githubusercontent.com/6494025/96084338-34a98780-0ebf-11eb-9cdc-8a6be9f37dd0.png)

**Comment by KjellMorgenstern** [comment]
0.8.3 version of timer.fzz:
[Timer.fzz.gz](https://github.com/fritzing/fritzing-app/files/5382796/Timer.fzz.gz)

**Comment by failiz** [comment]
remove imported label
