### ISSUE TITLE
text elements with internal transforms and no x and y coordinate may not flip or rotate correctly

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2869]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 13, 2014 07:21:09_

could write a script to fix all these

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2871_

**Comment by failiz** [comment]
Do you known how to test this? Is it still relevant?
