### ISSUE TITLE
delete ratsnest line does not pop an led off the arduino

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2872]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 15, 2014 00:47:20_

goes back at least to 0.8.3

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2874_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.4. When a LED is connected directly to the Arduino, I cannot delete the ratsnet in the schematic view.
