### ISSUE TITLE
breadboard pin spacing for generated parts: use a breakout

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2875]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 18, 2014 12:22:05_

Since this issue keeps coming up

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2877_

**Comment by failiz** [comment]
The link is not available and (I think) that the title is not descriptive enough.
