### ISSUE TITLE
make core parts files read-only

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2877]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 20, 2014 09:45:11_

Add this as part of the build script

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2879_

**Comment by failiz** [comment]
Is this in the pipeline? Does it go here or in the parts repository?

**Comment by KjellMorgenstern** [comment]
Outdated, this was before core parts had a version management system (git)
