### ISSUE TITLE
delete a recent fzz file, recent list on welcome page doesn't update

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2890]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 24, 2014 05:30:07_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. If the sketch uses custom parts, save the sketch as shareable (under the file menu). What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2892_

**Comment by failiz** [comment]
Not reproducible. 
The recent list updates when you create new files (adds the new files to the recent list).
When you delete a file, it is still in the recent list as the program does not know that you have delete it. When you try to open it, Fritzing states that it was not found. Then, after you open a new file, the deleted file is removed from the recent list. 
There is no option to manually delete a recent list. However, I dont remember that I have ever seen that option in other programs.
