### ISSUE TITLE
Cannot mix incompatible Qt library with this library

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2892]
_From [wapcaplet88](https://code.google.com/u/wapcaplet88/) on January 24, 2014 17:06:21_

In Fritzing versions 0.8.6b and 0.8.7b, the `Fritzing` executable script in the root directory of the Linux download does not work for me. I get:

  $ cd fritzing-0.8.7b.linux.AMD64
  $ ./Fritzing
  Cannot mix incompatible Qt library (version 0x40803) with this library (version 0x40805)
  Aborted

I've found a simple workaround, which is simply to comment out this line of the `Fritzing` script:

  export LD_LIBRARY_PATH

but I haven't dug into it further to figure out why it happens. I'm on LinuxMint 14 (Ubuntu-based) with a stock 3.5.0 kernel; there's various Qt stuff installed on my system, looks like 4:4.8.3. Please let me know if any other info is needed.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2894_

**Comment by failiz** [comment]
I think that we are using the system libraries in 0.9.4. At least, the installation instructions says:
Fritzing requires the Qt5 libaries. On Ubuntu, those can be installed with "sudo apt install libqt5printsupport5 libqt5xml5 libqt5sql5 libqt5serialport5 libqt5sql5-sqlite".
