### ISSUE TITLE
hybrid connectors are unnecessary?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2893]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 25, 2014 17:27:09_

this mechanism is used to make a connector visible in one view but not in the others. I think this could probably just as easily be accomplished by using layer IDs that aren't visible in the given view. This would be worth testing as it would clean up some unnecessary code, both in Fritzing and in brd2svg.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2895_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
