### ISSUE TITLE
wants a bunch of parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2894]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 26, 2014 01:17:50_

http://fritzing.org/forum/thread/1887/?page=last http://fritzing.org/forum/thread/1884/?page=last

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2896_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
