### ISSUE TITLE
Ratsnest gets confused after changing connections in one view that are routed in another view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2899]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on January 27, 2014 09:15:51_

What steps will reproduce the problem? 1. make a new sketch and put in a part. 
2. wire it up in breadboardview and route the traces from the ratsnest in pcb view
3. if you now go back to breadboard and change the connections and go back to pcb-view and delete the routed traces, the upcoming ratsnest isn't correct.

the only way to solve this issue is to delete the ratsnest (rightclick on ratsnest and delete) which will delete all connections in all view. or delete the part and put in a new one. What is the expected output? What do you see instead? the Ratsnest should be right after deleting the "old" pcb-traces. What version of Fritzing are you using? On what operating system? - win7 64bit nightly 0.8.7(1)-build

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2901_

**Comment by failiz** [comment]
I could not replicate this in 0.9.4 or 0.8.3b. And the file is not available.

**Comment by KjellMorgenstern** [comment]
Fritzing up to 0.9.4 has a error similar to that, it's mostly fixed in the dev version. And it's much better documented in more recent tickets, therefore we can close this one.
