### ISSUE TITLE
PCB-View: bendpoints cannot be added/deleted after a long working periode

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2900]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on January 27, 2014 09:18:57_

if i work on a complex board a very long time. i cannot delete or add bend-points on copper traces. unluckily i cannot rebuild the bug, but i happens everytime when i use fritzing 0.8.7 a longer time. 

i'm quite sure i had the same issue in older releases.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2902_

**Comment by failiz** [comment]
Old issue and nobody else has commented or reported this issue. Not enough info to replicate. Should we close it?
