### ISSUE TITLE
Opening old fzz in Read Only is bad (random ratlines all over, voltage references wrong...)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2901]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on January 27, 2014 20:46:13_

Current git da4e53f004b30c5530ffde81e083ac6e930c57d3 Open attached fzz "Read Only"
See PCB view has very strange ratlines
See that voltage references are incorrect, labels are all wrong, inspector values incorrect.
  The GREEN POWER one V8 has <property name="voltage" value="9.9"/> in the fz file, but comes up as voltage: 5 in the inspector, 
  RED POWER V9 should be 6.2 but in inspector is 5
  V12 and V11 should be 12v

There are also some various odd ratlines on the schematic (but some of these are correct - due to my 0-ohm resistor jumpers and other parts which I hadn't added to the schematic yet).

Selecting to convert the file on opening does work,although boy-howdy does it make a mess of the schematic :(

**Attachment:** [dipt9.jpeg dipt10.jpeg 7-seg-control-only-flipped.fzz](http://code.google.com/p/fritzing/issues/detail?id=2903)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2903_

**Comment by failiz** [comment]
There is no file to debug.
