### ISSUE TITLE
Multiple connections to bendpoint weirdness

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2908]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on January 31, 2014 02:46:48_

This problem has been existing for quite some time in Fritzing, but I don't actually remember seeing it reported.

When bendpoints have multiple connections, sometimes weird and undesirable things happen.

See this video for a brief example of the most common issue, one or more legs of a bendpoint intersection "separate", and snap back only when you try to move it. 

I'm sure pretty much everybody has come across these annoyances before. http://youtu.be/lQcWVcBC7r4

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2910_

**Comment by KjellMorgenstern** [comment]
Same problem also exists in breadboard view.

**Comment by KjellMorgenstern** [comment]
Duplicate of issue #3006 (and others)

**Comment by failiz** [comment]
Let's close this issue as it is a duplicate. I copied the link to #3006
