### ISSUE TITLE
Coper fill keep out failure

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2909]
_From [bitsybof...@gmail.com](https://code.google.com/u/112850805511005419452/) on February 01, 2014 05:44:06_

See video below which illustrates the problem. http://youtu.be/INWAAnXbUmk Shows keepout set to 15mil, run a copper fill, most of the board keepout is correct, but R18 and R12 have a far far reduced keepout, maybe only a mil or two.

These are a custom part, but in all other respects they seem to work fine, so not sure what's up with them and keepout.

Fzz attached

**Attachment:** [dummy-load.fzz](http://code.google.com/p/fritzing/issues/detail?id=2911)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2911_

**Comment by KjellMorgenstern** [comment]
Issue 0.9.4 did not see this issue, and 0.9.5 is likely robust against parts with this problem. Since  files from google code are not available anymore, I am closing this without verification.
