### ISSUE TITLE
no wire for connecting in schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2914]
_From [mahanthg...@gmail.com](https://code.google.com/u/103883738243869223282/) on February 08, 2014 01:37:13_

there is no way to make connections in schematic view

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2916_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
