### ISSUE TITLE
Wiring a sketch from the schematic view whole wires/connections get lost in autorouting

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2919]
_From [sven.kra...@googlemail.com](https://code.google.com/u/117458226116538687248/) on February 12, 2014 06:45:10_

What steps will reproduce the problem? in Schematic view:
1. Wire an Adafruit PWM Board with an Arduino Leonardo
2. Attaching external power supply
3. Wire Power supply & numerous servos
4. Ground of Power Supply connection lost after very long routing
5. Same happened for Sharp IR proximity sensors, here the connection to the Arduino got lost

"Attach your sketch file and/or custom part files to the bug report.": It's a client project & the file is subject of an NDA, but I attached a detail screenshot showing the broken power supply wiring

"What is the expected output?": the same wiring with tidied routes

"What do you see instead?": some wires were completely lost after the autorouting

Version 0.8.7 (b1bf5 2014-01-24) Cocoa [Qt 4.8.5]

**Attachment:** [12.02.14 12:43-Bildschirmkopie.jpeg](http://code.google.com/p/fritzing/issues/detail?id=2921)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2921_

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?
-- did the autorouter "complete" or did it stop at 100 tries
-- were the parts wired only in schematic view?
