### ISSUE TITLE
screw connectors size is not correct in breadboerd

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2923]
_From [eero.ha...@gmail.com](https://code.google.com/u/109634745033994792479/) on February 23, 2014 02:59:59_

What steps will reproduce the problem? 1. select screw terminal and take it to breadboard
2. In inspector window change the pin spacing Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I would expect the spacing should change in breadboard but it does not.
(it changes OK in PCB so I think this is not Fatal but it is confusing.) What version of Fritzing are you using? On what operating system? Version 0.8.7 (b1bf5 2014-01-24) [Qt 4.8.5]
in Linux Mint Please provide any additional information below.

**Attachment:** [Screenshot -screw terminal.png](http://code.google.com/p/fritzing/issues/detail?id=2925)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2925_

**Comment by chrisyokum** [comment]
The part in question is:
https://www.sparkfun.com/products/8432
How can we get this fixed?

**Comment by chrisyokum** [comment]
This still happens in 0.9.2b.

**Comment by Elspin** [comment]
Still happening in latest version for me too with the part @chrisyokum mentioned in the latest version (0.9.3) in the same way, it updates in PCB view but in breadboard view it remains static.

**Comment by failiz** [comment]
This bug is just a partial effect of issue #1597. Should we close it and leave #1597 with all the info or should be leave it open? If the later, remove imported label.

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
Closing in favor of #1597
