### ISSUE TITLE
Exporting PCB SVG of part has wrong colors for copper.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2924]
_From [jacob.fe...@gmail.com](https://code.google.com/u/111281479460336299364/) on February 24, 2014 20:12:49_

If you're editing a part in the PCB view and go File > Export > as Image > SVG and open the part in something like Inkscape the copper color comes out FFBF00, but according to http://fritzing.org/fritzings-graphic-standards/ it should be F7BD13.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2926_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
