### ISSUE TITLE
when selecting a variant with different label the label does not change with it

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2925]
_From [fda...@online.nl](https://code.google.com/u/107932673981941701484/) on February 26, 2014 10:16:52_

What steps will reproduce the problem? I make use of version 083 and windows7

1.I made new parts, metadata within same family, but different label
2.then I drag one of those parts into the working space
3.then select another part (variant) in the inspector with another label

When done so the label does not change with it.

F.Damen

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2927_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
