### ISSUE TITLE
Will not open complete .fzz file, many parts not found error

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2928]
_From [Hunter11...@gmail.com](https://code.google.com/u/113509229951006850643/) on March 05, 2014 23:01:25_

What steps will reproduce the problem? 1. Opening a recent file 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I expected to see my previous work but when it opens i only see the arduino lily pad that was used as a switch. What version of Fritzing are you using? On what operating system? the latest version on windows 8.1 Please provide any additional information below.

**Attachment:** [Diesel Wiring 1.fzz](http://code.google.com/p/fritzing/issues/detail?id=2930)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2930_

**Comment by failiz** [comment]
The file is not available to debug
