### ISSUE TITLE
4148 DIODE IS NOT CONNECTING

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2929]
_From [haddad.f...@gmail.com](https://code.google.com/u/102627340869691085045/) on March 08, 2014 11:14:25_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2931_

**Comment by failiz** [comment]
I could not find a diode 4148  in the core parts. Is this a custom part? Not enough info to debug.
