### ISSUE TITLE
All buttons were removed from sketch, putting one back in crashes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2932]
_From [btrout.d...@gmail.com](https://code.google.com/u/110128371775853098484/) on March 16, 2014 14:59:53_

What steps will reproduce the problem? 1. Opening the sketch
2. Drag-and-droppping a button to Schematic or PCB view
3. _BOOM_ crashes What version of Fritzing are you using? On what operating system? 0.8.7b

Windows 7 Ultimate x64

Here's the thing Windows gives me:

Problem Event Name: APPCRASH
  Application Name: Fritzing.exe
  Application Version:  0.8.7.0
  Application Timestamp:    52e2bc76
  Fault Module Name:    Fritzing.exe
  Fault Module Version: 0.8.7.0
  Fault Module Timestamp:   52e2bc76
  Exception Code:   c0000005
  Exception Offset: 00195462
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Attachment:** [Power Glove Final.fzz](http://code.google.com/p/fritzing/issues/detail?id=2934)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2934_

**Comment by failiz** [comment]
The file is not available and the old maintainer was unable to replicate it.
