### ISSUE TITLE
Autorute fault

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2933]
_From [ramon...@gmail.com](https://code.google.com/u/114477175868907958404/) on March 18, 2014 09:50:19_

What steps will reproduce the problem? 1.If you autorute the file "Tarjeta TEG sin rutear" some wires dissapear. I copy files before and after("Tarjeta TEG ruteada"), in the SMDs 20pins  some wires are missed after autorute.
2. I hope do not loose connectios when autorute.
3.fritzing.0.8.7b.pc Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please, let me know any way to go on, any advice will be great to finish, very close to do it.

Best regards,

Ramón Villanova. Please provide any additional information below.

**Attachment:** [Tarjeta TEG sin rutear.fzz Tarjeta TEG ruteada.fzz](http://code.google.com/p/fritzing/issues/detail?id=2935)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2935_

**Comment by KjellMorgenstern** [comment]
This issue is closed because the original information on google code was not be rescued before the service shut down. Some fixes have been done to the autorouter since then.
