### ISSUE TITLE
Hide individual connectors in PCB view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2934]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on March 19, 2014 09:51:47_

http://fritzing.org/forum/thread/2270/ from amundsen:

"I suppose I am not the only one using Fritzing to create PCBs with components connected with headers. With microcontrollers and breakout boards, one does not always use all the connections. It means unused connections could be left unconnected, which helps leaving some points to let traces go through.

However, Fritzing's current implementation doesn't allow to mask a connector's copper to be masked in the PCB view. One has to re-build a board's pinout using generic female header.

For instance, see on the linked picture what I have done for an Arduino Pro Mini in a situation where A4/SDA and A5/SCL pins were needed while RST and A3 were not. http://flic.kr/p/mcWr4r It would ne nice if Fritzing had an option to remove any pin from PCB view so to allow this without having to rebuild a component using headers."

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2936_

**Comment by failiz** [comment]
I think this is not a very useful feature to have. You can easily send a track between two connectors with pin headers of pitch  0.1in. Alternatively, and as you suggest, you can use generic pin headers to build it (using the grid should take very little time). I would suggest to close this issue.

**Comment by KjellMorgenstern** [comment]
It could be nice to have some kind of eraser, to quickly be able to mod some of the existing pcb views of parts, for example to remove a ICSP header. But the backlog is long, it won't be implemented anytime soon.
