### ISSUE TITLE
part rotation deletes copper-connector attribute in gerber export

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2939]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on March 31, 2014 07:30:34_

What steps will reproduce the problem? 1. copy a smd-part into an sketch
2. rotate the part (does not matter if it's left or right direction)
3. export in gerber, the pads will not be recognized as solder-pads

latest fritzing build

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2941_

**Comment by Intrinsically-Sublime** [comment]
This looks to be a very old bug that has been fixed for a long time now. This issue should most likely be closed.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
