### ISSUE TITLE
Larger hotspot area for thin wires

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2941]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on April 03, 2014 11:20:43_

esp. in schematic view: http://fritzing.org/forum/thread/2302/

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2943_

**Comment by failiz** [comment]
I do not understand the issue and the link is gone...

**Comment by failiz** [comment]
Happy New Year Kjell!
