### ISSUE TITLE
pin's jumpers in auto route are below other parts in pcb design

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2947]
_From [fernaand...@gmail.com](https://code.google.com/u/103843632457594732081/) on April 22, 2014 00:52:43_

What steps will reproduce the problem? 1.connect a IC with pin crossed to a generic header connector and auto route to get jumpers in pcb view
2.when fritzing generates jumper are below other parts
3.the jumpers are in a bad position Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? the jumpers pin out of the other parts What version of Fritzing are you using? On what operating system? Version 0.8.7 (b1bf5 2014-01-24) Cocoa [Qt 4.8.5] Please provide any additional information below.

**Attachment:** [jumpes-below-parts.fzz](http://code.google.com/p/fritzing/issues/detail?id=2949)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2949_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
