### ISSUE TITLE
Generic DIP goes 'wonky' in Schema view after changing IC name

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2952]
_From [jtigchel...@gmail.com](https://code.google.com/u/101804703692728909578/) on April 30, 2014 02:17:04_

What steps will reproduce the problem? 1. Create a breadboard/schema layout using a 8-pin generic DIP
2. Change the name of the DIP in the breadboard view
3. In schema view, the layout is suddenly 'wonky', for lack of a better word, multiple pin numbers are shown and alignment/layout is off by a large margin, changing the IC name again seems to make things worse.

Extra: When i press save in the schema view after trying my best to recenter the IC, it automatically opens the PCB view.

I have attached my project file, any help on how to fix this would be greatly appreciated. The design experience was very pleasant, and i was just thinking about ditching Designspark PCB for Fritzing, when this happened.

Version: Versie 0.8.7 (b1bf5 2014-01-24) [Qt 4.8.5]

Regards,
Jelle

**Attachment:** [Amplifier.fzz wonkyschema.png](http://code.google.com/p/fritzing/issues/detail?id=2954)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2954_

**Comment by failiz** [comment]
Not able to reproduce it in 0.9.6
