### ISSUE TITLE
convert dialogs and other views to QML

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2954]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 07, 2014 15:52:47_

QGraphicsView widgets are not compatible with QML widgets, but they can exist side-by-side as children of the same window.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2956_

**Comment by failiz** [comment]
Is this still being considered? Does QML provide any advantage?

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
We don't have dedicated UI developers, so I don't think we need this.
