### ISSUE TITLE
QCocoaMenu::insertNative() Menu item is already a menu

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2955]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 10, 2014 23:15:31_

Seems to be a qt 5 mac bug when inserting a QAction with a submenu in multiple menus. https://bugreports.qt-project.org/browse/QTBUG-34160 https://bugreports.qt-project.org/browse/QTBUG-31549 Haven't tracked down the exact cause in Fritzing

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2957_

**Comment by failiz** [comment]
This bug has been fixed in Qt. Is this still an issue?

**Comment by KjellMorgenstern** [comment]
Yes, seems it was closed with Qt5.6.1, and our oldest build uses Qt5.9
