### ISSUE TITLE
green resistors

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2956]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on May 20, 2014 04:06:09_

we should think about green resistor bodies too.
i guess it's not that complicated?!? isn't it?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2958_

**Comment by failiz** [comment]
I think that this feature is too much work for the benefits that gives.

**Comment by KjellMorgenstern** [comment]
I also don't see it happening. I would consider it if there was already a Pull Request, but for now it's just not needed. Different thing for the strip boards though, here the brown color is not ideal, bad visibility. And green boards are quite common.
