### ISSUE TITLE
Parts Editor <tab> in key word field does not select the new field for input

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2963]
_From [crje...@gmail.com](https://code.google.com/u/102335747725248175584/) on June 06, 2014 14:32:04_

What steps will reproduce the problem? 1. Open Parts <sic> Editor
2. Move cursor to the last Input Field
3. Enter some Text
4. Press <tab> to add a new Input Field
5. Start typing new text

The text does not appear in the newly generated input field since it is not selected (which would be the expected behaviour)

> What version of Fritzing are you using? On what operating system?

0.8.7 on Win 8.1

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2965_

**Comment by el-j** [comment]
closed. can not be reproduced.
