### ISSUE TITLE
keypad

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2966]
_From [mgarr...@grupomasenergia.com.ar](https://code.google.com/u/101440378511297803718/) on June 11, 2014 13:55:00_

What steps will reproduce the problem? 1. 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2968_

**Comment by el-j** [comment]
not enough information. closed
