### ISSUE TITLE
PCB View zoom and move at once while mouse middle button is pressed.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2967]
_From [sivicjar...@gmail.com](https://code.google.com/u/106554598869003629474/) on June 14, 2014 10:21:34_

What steps will reproduce the problem? 1. Switch to PCB tab (PCB View).
2. Put a lot of vias and other component on PCB
3. Press mouse middle button and move cursor. It will move PCB, but as well zoom in, which I think is an error and definitely it is not user friendly.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2969_

**Comment by failiz** [comment]
I cannot reproduce this in 0.9.4. The view pans (move the pcb around), not zooms.

**Comment by failiz** [comment]
I cannot reproduce this in 0.9.6 (Windows). The view pans (move the pcb around), not zooms. @KjellMorgenstern , did you leave this issue open on purpose? Do you think that it could be platform specific?

**Comment by KjellMorgenstern** [comment]
No example file is given, could not be reproduced for a longer time. Could as well be a mouse gesture form the operating system
