### ISSUE TITLE
cannot define connectors 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2970]
_From [tuna.cla...@gmail.com](https://code.google.com/u/105636943804389539598/) on June 23, 2014 17:26:01_

I cannot define connectors in the new parts editor. What steps will reproduce the problem? 1. Make a new IC. 
2. Go to inspector and change it to 16 pins and it's name to "create".
3. right click> edit (new) parts editor.
4. for any pin, click 'select graphic'
5. hover over the part of my sketch that I want to use. it turns pink
6. click, it turns dark blue and no cross hair is placed. "terminal point" is grey/inactive (not black) 

I tried this with my own file, as well as the spark fun example file for the barometer breakout. The first time i ran the new parts editor, it let me add crosshairs/connectors. Since then it won't be responsive. I tried downloading an older version of Fritzing. Once again, it worked the first time and then never again. What version of Fritzing are you using? On what operating system? I am using the newest version of fritzing on a mac running 10.9.3

**Attachment:** [SFE_T5403_Barometer_Breakout_breadboard.svg frontcopy.svg](http://code.google.com/p/fritzing/issues/detail?id=2972)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2972_

**Comment by el-j** [comment]
cannot verify this bug on win7 64bit. with fritzing 0.9.1b
