### ISSUE TITLE
wrong character encoding

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2974]
_From [Dietrich.Frank@gmail.com](https://code.google.com/u/Dietrich.Frank@gmail.com/) on July 14, 2014 16:58:56_

What steps will reproduce the problem? 1. start Fritzing
2. open the context menu on the breadboard to rotate any component
3. the degree sign is not correct displayed, it's a square with a question mark inside What version of Fritzing are you using? On what operating system? fritzing-0.9.0b.linux.i386 version packaged on 13. July
  The error does not occur with version fritzing-0.8.7b.linux.i386

On what operating system?
  Debian Jessie Please provide any additional information below. strace output of fonts loaded during application start

open("/usr/share/fonts/truetype/ttf-dejavu", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 11
open("/usr/share/fonts/truetype/ttf-liberation", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 11
open("/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf", O_RDONLY) = 16
open("/usr/share/fonts/truetype/droid/DroidSansThai.ttf", O_RDONLY) = 19
open("/usr/share/fonts/truetype/droid/DroidSansHebrew-Bold.ttf", O_RDONLY) = 23
open("/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf", O_RDONLY) = 23
open("/usr/share/fonts/truetype/dejavu/DejaVuSans-ExtraLight.ttf", O_RDONLY) = 23

All those fonts contain a the degree sign.

**Attachment:** [wrong_encoding.png](http://code.google.com/p/fritzing/issues/detail?id=2976)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2976_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.4 (Windows)

**Comment by failiz** [comment]
I cannot replicate this in 0.9.6 either (Windows). As someone reported that was replicable on Windows 8.1, it is probably fixed. But it would be nice to confirm it in Linux.

**Comment by KjellMorgenstern** [comment]
Neither in Linux
