### ISSUE TITLE
Via unsizeable

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2977]
_From [wallerro...@gmail.com](https://code.google.com/u/108015824139808103148/) on July 26, 2014 17:31:51_

What steps will reproduce the problem? 1. Create via
2. Click on via
3. Attempt to change size/scale of via

> What is the expected output? 
> 
> What do you see instead?
> Fritzing doesn't do anything and seems to have a critical problem handling decimals.
> 
> What version of Fritzing are you using? 
> 0.9.0b
> 
> On what operating system?
> Windows 7 (Swedish) Please provide any additional information below. I assumed that it was because some systems use a '.' as a decimal point, but it did not make any difference.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2979_

**Comment by failiz** [comment]
Yo can change the size of the via in the inspector. Select the via and change hole diameter and ring thickness.
