### ISSUE TITLE
DRC-check: drill-hole and via size 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2978]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on July 29, 2014 05:44:14_

drc does not yell on vias and drills smaller than the set radius in the drc-options. really need to include this check.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2980_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
