### ISSUE TITLE
"sparkfun battery holder" (AA/AAA battery) plus and minus pole mixed up

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2979]
_From [nicholas...@gmail.com](https://code.google.com/u/106351620986635116373/) on August 02, 2014 10:12:54_

1. Select part "sparkfun battery holder"
2. Connect "+" and "-" poles to rails in breadboard view.
3. Compare "+" and "-" poles of picture in breadboard view to those in schematic and PCB view.

The battery symbol in schematic or PCB view has the plus and minus poles mixed up compared to the breadboard view. This applies to ALL different battery holders based on "sparkfun battery holder".

See attached file for additional info...

(Fritzing Version 0.8.7 (b1bf5 2014-01-24) [Qt 4.8.5])

**Attachment:** [battery_poles.fzz](http://code.google.com/p/fritzing/issues/detail?id=2981)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2981_

**Comment by el-j** [comment]
fixed
