### ISSUE TITLE
drc - should know about smt-parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2980]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on August 03, 2014 17:41:13_

use an smt-part and run the drc. the drc yells because of a missing copper-layer.

in the svg of a smt part is just one copper-id specified. 
the drc looks for parts with just one copper-site because of 
tht-parts that otherwise will make a short in the gerber-export.

we need to make the drc know about smt parts that has just one copper site.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2982_

**Comment by mMerlin** [comment]
That "fix" may have broken another scenario. I created an edge connector part. That is not THT (no drill holes, no plating through), but it has pads on both sides of the board. Electrically, the part seems to work, but DRC complains that:

> Connector «n» on Parts «part description» '«part label»' should have both copper top and bottom layers, but the svg only specifies one layer.

for every connector on the bottom (copper0) layer. It does not complain about the connectors on the top (copper1) layer, although they also only exist on one layer. DRC (some parts of) seem to assume that if the views, pcbView, layers includes both copper1 and copper0, that the part is THT. Or at least that any connector in the part on copper0 is supposed to be THT, even though the fzp file specifies only copper0 for the connector pcbView layer.

Here is the failing part (renamed from .fzpz to .zip to be able to upload). Not a lot of testing done with that. I have not tried exporting it to gerber yet. The top and bottom layer copper looks good in pcb view, and traces to the pads match the side of the board the pads are on.

[db25_edge_connector.zip](https://github.com/fritzing/fritzing-app/files/6076734/db25_edge_connector.zip)
