### ISSUE TITLE
Export for PCB - Bottom Image Reversed

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2982]
_From [d...@cording.id.au](https://code.google.com/u/110988540499332484376/) on August 06, 2014 07:01:31_

What steps will reproduce the problem? 1.  Create a circuit
2.  Design PCB
3.  Export PCB design for DIY production (Export for PCB) Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? When exporting the PCB design for DIY production the bottom images are the wrong way around.  What is called the bottom_mirror image should be the normal image and vice versa.

Problem occurs for both PDF and SVG export What version of Fritzing are you using? On what operating system? 0.9b on Ubuntu Linux Please provide any additional information below.

**Attachment:** [Test.fzz Test_etch_copper_top.pdf Test_etch_mask_bottom.pdf Test_etch_mask_bottom_mirror.pdf](http://code.google.com/p/fritzing/issues/detail?id=2984)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2984_

**Comment by failiz** [comment]
I think they are ok in 0.9.4 Windows. The non mirror image corresponds to what you see in the screen (the bottom silkscreen text is flipped) and the mirror output is the flipped version of what you see on the screen (the bottom silkscreen text can be read normally).

**Comment by failiz** [comment]
Ping
