### ISSUE TITLE
"donut blocker"

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2983]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on August 08, 2014 08:01:47_

it would be very helpful to have a "donut blocker" that works quite similar to the copper-fill blocker. so the user can "block connectors" during the output as gerber/svg. 
or it could be like the "set gnd-fill-seed" option. so you right-click over a copper connector and choose something like: "exclude for export"

example scenario 1. - use an arduino mega but you want to make a smaller shield without 
any pinheaders breaking the "contour" of the pcb. 2. or you just want to "block" 2 headers to have multiple 
traces in this place.

**Attachment:** [donut-blocker.jpg](http://code.google.com/p/fritzing/issues/detail?id=2985)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2985_

**Comment by KjellMorgenstern** [comment]
Outdated and missing information.  If you think this is still relavant, please reopen and provide more information.
