### ISSUE TITLE
add "hide parts silkscreen"

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2984]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on August 11, 2014 09:37:52_

we need to add "hide part silkscreen" to the parts dropdown menu.
so you can press "strg+a" and hide the silkscreen for all parts on the board.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2986_

**Comment by KjellMorgenstern** [comment]
Feature is already implemented, outdated issue.
