### ISSUE TITLE
User Changes in schematic can ruin work in PCB view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2986]
_From [ferranpu...@gmail.com](https://code.google.com/u/107077687428382647039/) on August 20, 2014 10:23:46_

Symbols in schematic view are directly linked to components on the PCB view. Is easy to forget that, and for example, cut-paste a symbol in the schematic view just to reposition it easily, but later discover that the component was actually cut and paste also in the PCB view and now the components are out of place.

I suggest to separate components added to the project from their schematic representation and their "physical" situation. So, for example, if a symbol is removed from schematic view, the actual component is not removed from the rest of the project. A list of components added to the project and where they are implemented (schematic, breadboard or PCB) would be useful.

Fritzing 0.9.0 on Windows 8.1 x64

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2988_

**Comment by el-j** [comment]
this behavior would destroy the consistency of the 3 views. all 3 views are especially linked together because they are all meant as one representation of the same electrical circuit.
