### ISSUE TITLE
2010 and 2512 SMD resistors have fixed values

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2987]
_From [noisym...@gmail.com](https://code.google.com/u/113658753624401965336/) on August 21, 2014 22:39:39_

What steps will reproduce the problem? 1. Place a basic resistor from the core library
2. Change the package to 2010 or 2512
3. Attempt to change the resistance What is the expected output? What do you see instead? Resistor values should be user settable for 2010 and 2512 packages, just as they are for all other SMD and THT packages. What version of Fritzing are you using? On what operating system? 0.9.0 on OSX 10.9.4

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2989_

**Comment by el-j** [comment]
resistor package 0402 has the same behavior. now fixed
