### ISSUE TITLE
schematic and pcb connections dont match

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2988]
_From [emmanuel...@eeb1.eu](https://code.google.com/u/105686751521554569241/) on August 25, 2014 16:05:55_

I attach my sketch (you need the 2N7000 part also).

I also attach the pcb and schematic views where you can see the mismatch: on the PCB you can see the traces from ATMEGA's pins 15 to 19 connections to JP6 (top left) are well ordered whereas on the schematic the ATMEGA328's pins 15 to 19 connections to JP6 are mixed up.

Fritzing version is 0.8.7b on linux.

**Attachment:** [pcb-view.png schematic-view.png gps_ada_at328.fzz](http://code.google.com/p/fritzing/issues/detail?id=2990)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2990_

**Comment by el-j** [comment]
as i found out there are multiple files with this strange pinorder in schematic view. i fixed all of them at the moment.
