### ISSUE TITLE
On Welcome side Project view is not accessible.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#2989]
_From [michaelj...@gmail.com](https://code.google.com/u/101102059201293781730/) on August 26, 2014 08:44:46_

What steps will reproduce the problem? 1.Start Fritzing
2.try to choose Projects
3. no function!!!

This was a nice function :-(

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2991_

**Comment by el-j** [comment]
seems to be fixed. closed
