### ISSUE TITLE
Breadboard & Schematic Reverse Synching with Voltage Regulator and power plug

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#2994]
_From [drio...@gmail.com](https://code.google.com/u/108202091347179289396/) on August 29, 2014 21:56:36_

What steps will reproduce the problem? 1.  On the Breadboard view place the power plug with the lightning bolt graphic and the THT Voltage Regulator that reads V Reg.

2. Wire the VCC of the Power Plug to the "IN" pin of the Regulator

3. Wire the Ground of the Power Plug to the "GND" pin of the Regulator

4. Switch to the schematic view and the routes will be reversed.  VCC of the plug will connect to "GND" of the regulator and Ground of the Plug will route to "IN" on the regulator Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? I expect VCC to connect to IN and Ground to GND but instead and the routes are reversed.  VCC of the plug routes to "GND" of the regulator and Ground of the Plug routes to "IN" on the regulator What version of Fritzing are you using? On what operating system? Fritzing 0.9 running on Mac OS 10.9.3 Please provide any additional information below.

**Attachment:** [Screen Shot 2014-08-29 at 3.18.52 PM.png Screen Shot 2014-08-29 at 3.19.15 PM.png Screen Shot 2014-08-29 at 3.34.06 PM.png Screen Shot 2014-08-29 at 3.34.15 PM.png LabHighCurrentLoadFail.fzz](http://code.google.com/p/fritzing/issues/detail?id=2994)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2994_

**Comment by el-j** [comment]
seems to be fixed in 0.9.1
