### ISSUE TITLE
ds1307 

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#2995]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on September 02, 2014 17:49:51_

the ds1307 smd core-part has a wrong pinout. 
the sparkfun variant has the right pinout.

we should change the core-smd part to the sparkfun part.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2995_

**Comment by el-j** [comment]
seems to be fixed. closed
