### ISSUE TITLE
routing message untrue in breadboardview

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#2997]
_From [bluearc....@gmail.com](https://code.google.com/u/112158384960039030429/) on September 06, 2014 20:26:09_

What steps will reproduce the problem? 1. breadboardview: take a view parts and make connections between them with the breadboard between them 
2. the message in the bottom say: 0 of X nets routed. X connection still to be routed
3. use menu: show unrouted connection: message: there are no unrouted connections 

fritzing 0.9

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2997_

**Comment by el-j** [comment]
seem ok in 0.9.1b
