### ISSUE TITLE
Arduino Mega Proto Shield v6 - Without D27 Pin

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#2999]
_From [robson.e...@gmail.com](https://code.google.com/u/100929517148910823635/) on September 11, 2014 05:56:11_

What steps will reproduce the problem? 1. Arduino Mega Proto Shield v6 Without D27 Pin 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=2999_

**Comment by el-j** [comment]
#3000
fixed
