### ISSUE TITLE
 Arduino Mega Proto Shield v6 - PIN DEFECT: (D45/D46) & (D27/D28) UPON EACH OTHER

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#3000]
_From [robson.e...@gmail.com](https://code.google.com/u/100929517148910823635/) on September 11, 2014 06:14:07_

What steps will reproduce the problem? 1. Arduino Mega Proto Shield v6 - PIN DEFECT: (D45/D46) & (D27/D28) UPON EACH OTHER 2. 3. Attach your sketch file and/or custom part files to the bug report. What is the expected output? What do you see instead? What version of Fritzing are you using? On what operating system? Please provide any additional information below.

**Attachment:** [FRITZING-DEFECT.png](http://code.google.com/p/fritzing/issues/detail?id=3000)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=3000_

**Comment by el-j** [comment]
fixed
