### ISSUE TITLE
Common PIN of Rotary Encoder incorrect in Schematic View

### ISSUE THREAD

**Issue by aknoerig** [fritzing/fritzing-app#3001]
_From [julian.r...@gmail.com](https://code.google.com/u/112714071888307658325/) on September 14, 2014 01:27:08_

What steps will reproduce the problem? 1. Add a rotary encoder from Core parts, section Input.
2. Switch to Schematic View

I would expect the pins on the one side to be A and B and the one on the other side to be C(ommon). As you can see in the attached screenshot this is not the case.

I'm using Fritzing 0.9.0b built from source on Linux.

I attached a screenshot to illustrate the problem.

Thanks for fixing it.

**Attachment:** [encoder.png](http://code.google.com/p/fritzing/issues/detail?id=3001)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=3001_

**Comment by el-j** [comment]
fixed
