### ISSUE TITLE
3 Related Bugs: ground seed & copper fill problems (ground fill doesn't work properly in certain cases)

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [fritzing/fritzing-app#3005]
3 Related Bugs: 
-Work in PCB view for all the following:

Bug 1) Pins are not always isolated when ground fill added, depending on "View" selections.
Bug 2) Ground seed is cleared when you modify a part's hole size (or other parameters)
Bug 3) Ground fill does not work if there is a trace or object is nearby (even if it is easily far enough away for ground fill to be possible).

To duplicate the above three problems:

Bug 1: Pins are not always isolated when ground fill added, depending on "View" selections.
1) In a new sketch, insert a 2-pin screw terminal from the core parts under "Connection."  
2) Uncheck the "copper top layer" view under the "view" options.
3) Right click and set pin 2 (circle pin) as "ground fill seed".
4) Add the ground fill (top & bottom).
5) The bottom of the board is fine.
6) Add the check back to the "copper top layer" to view again the top of the board.  
7) The copper fill was botched.  It filled all the way up to the pins.

Bugs 2: Ground seed is cleared when you modify a part's hole size (or other parameters)
1) In a new sketch, insert a 2-pin screw terminal from the core parts under "Connection."
2) Right click and set pin 2 (circle pin) as "ground fill seed".
3) Add the ground fill (top & bottom).  You will see that the copper fill worked perfectly on both the top _and_ bottom of the board.
4) Select the screw terminal and change Ring Thickness from 0.508mm to 0.8mm.
5) BUG 2: you will see that the "ground fill seed" was cleared on pin 2.  Now, if you clear the copper fill and remake the ground fill, no seed is selected.  This causes mistakes in selecting all ground seeds when all you are doing is modifying part parameters.

Bug 3: Ground fill does not work if there is a trace or object is nearby (even if it is easily far enough away for ground fill to be possible).
1) In a new sketch, insert a 2-pin screw terminal from the core parts under "Connection."
2) Select the screw termial and set parameters as follows:
-Pin Spacing: 0.2in (5.08mm)
-Hole Diameter: 1.2mm
-Ring Thickness: 0.8mm
-Pins: 6
3) Connect a top trace from pin 1 to pin 6, and modify it to look as shown below.
4) Connect a top trace from pin 2 to pin 5, and modify it to look as shown below
![20140928 - screw terminal snapshot](https://cloud.githubusercontent.com/assets/6842199/4436593/d2a2e6fa-477b-11e4-94e4-ee826cde4f34.PNG)
.
5) make pin 4 a "ground fill seed"
6) Add a ground fill
7) BUG: you will see that the ground fill was NOT added on the top layer simply due to the traces being that close to the pins.  This should not be the case, as there is _easily_ plenty of room to allow the ground fill to work there in real life, as far as I can tell.  Note: if you look at the bottom layer you'll see the ground fill worked fine (so long as you had the "Copper Bottom Layer" checked in the view settings during ground fill creation--& Bug 1 didn't occur) since no bottom traces were that close to the pin.

**Comment by a-johansson** [comment]
I had bug 1 with my custom component, played around a bit and found that if my SVG uses matrix transformations for the pins, the copper fill goes all the way up to them, but if I change it so that they don't use matrix transformations, it works fine.

**Comment by noisymime** [comment]
Bug 3 is a huge problem for me. I find myself placing a lot of extra vias and then attaching them to a pin/pad just so it gets it's ground connection. If there's enough room to place a via, then there's definitely enough room to add the connection to the ground plane.

**Comment by ElectricRCAircraftGuy** [comment]
yeah, I have to move to Eagle instead. I need fewer bugs and more functionality. I'll just have to learn it.

**Comment by KjellMorgenstern** [comment]
Issue 3 is fixed in #3555

**Comment by ElectricRCAircraftGuy** [comment]
Update: Glad you fixed this problem finally (after 5 yrs)! Unfortunately, I have long-ago moved to a much more professional free and open source program, KiCad as a result of my problems with Fritzing, and I very strongly recommend KiCad to anyone looking to make professional PCB and circuit diagram products.

**Comment by KjellMorgenstern** [comment]
@ElectricRCAircraftGuy Yes, not sure why it wasn’t done. I started reviving Fritzing in spring this year, and after getting a minimum of infrastructure back i am now going for some of the bugs :-) Alignment with KiCad is  on the roadmap for 2020.

**Comment by ElectricRCAircraftGuy** [comment]
> Alignment with KiCad is on the roadmap for 2020.
Interesting! What does this mean exactly? How will Fritzing "align" with KiCad?

**Comment by KjellMorgenstern** [comment]
Align was probably a to big word choice. I don't know if anybody currently uses the kicadschematic2svg code in Fritzing, but working on parts compatibility would be an interesting topic.

**Comment by KjellMorgenstern** [comment]
What is mentioned here as "Bug 1" is fixed in issue #4081
So, I think we can consider all problems reported here as fixed or duplicates -> Closing
In case there are further issues, please open separate tickets, please only one bug per issue (e.g. bug 3 was fixed long ago, but bug 1 was overlooked for a long time in this case)

**Comment by KjellMorgenstern** [comment]
Note: Issue number two mentioned here is fixed in #4099
