### ISSUE TITLE
Connectors with with 4-Wires at node highlight but dont move together

### ISSUE THREAD

**Issue by dreamalligator** [fritzing/fritzing-app#3006]
Connectors with with 4-Wires at node highlight but dont move together. The disconnected portion "blips" between one side or the other when I move the node about.

![screenshot - 09282014 - 07 41 57 pm](https://cloud.githubusercontent.com/assets/2218331/4436795/5a499490-4782-11e4-96d2-18963c596aaa.png)

**Comment by failiz** [comment]
It can still be reproduced in 0.9.4 (Windows)

**Comment by failiz** [comment]
Video showing the issue from another bug report #2908:
http://youtu.be/lQcWVcBC7r4

**Comment by failiz** [comment]
The issue applies to all the views. Add bug label, UI pcbview and bbview

**Comment by Aclassifier** [comment]
It has been suggested at [https://forum.fritzing.org/t/gluing-wires-to-each-other-in-schematic-view/15420/17?u=aclassifier](url) that it may be the same error as the one reported here. By inspecting the above comments and movie, yes that may be correct. My file is available from that posting.

**Comment by failiz** [comment]
I think this has been solved in 1.0.0
