### ISSUE TITLE
Package drop-down does not highlight / change color in a readable way.

### ISSUE THREAD

**Issue by nebulousdog** [fritzing/fritzing-app#3007]
Package drop-down does not highlight / change color in a readable way. Text is white, or close-enough with the gray off-white as background.

To reproduce
1. Select package in Inspector
2. Move mouse to highlight options

Thanks.

Version 0.9.0 (bda4e 2014-06-11) 64 [Qt 5.2.1]

**Comment by KjellMorgenstern** [comment]
Looks like #3336

**Comment by KjellMorgenstern** [comment]
Checked with various settings (Ubuntu budgie, Kubuntu dark themes, Windows 10) looks like this is no longer an issue.
