### ISSUE TITLE
locking 2 connected parts in PCB view problem

### ISSUE THREAD

**Issue by WilfredRoeten** [fritzing/fritzing-app#3021]
On a "sticky" PCB you can move the board and all components, traces etc. move along with the board.
Thats OK.
When you lock 1 parts that is connected to another part moving the board still works fine.

But when you lock both parts things don't work as suspected.
Moving the bord now still moves all the components etc, but de connecting copper trace is not moving allong with the board but stays on a static place on your monitor screen.
Clicking the component or the copper trace gives still an "electrical connection" although on your screen there is no connection at all.

**Comment by failiz** [comment]
Add bug, easy to replicate.
Steps:
1. Set the PCB as sticky
2. Add two resistors to the pcb
3. Add a trace connecting the two resistors
4. Lock both resistors
5. Move the PCB
The resistors move with the PCB, but the trace does not move and gets disconnected from the resistors
