### ISSUE TITLE
much to big fonts from inkscape import

### ISSUE THREAD

**Issue by satsatt** [fritzing/fritzing-app#3022]
"Jonathan Cohen 1 Jahr, 11 Monate ago

The next version of Fritzing will deal with this "px" from Inkscape problem.
- j"

If importing a new breadboard.svg fritzing still says it is not the right font but it is and leaves it otherwise alone - ok, but when importing a new schematic it totally messes up the fontsize.
You have to delete all "px" references in the svg by yourself. 
This is an very old bug and you stole some of my lifetime and i guess not me alone.

**Comment by Nizhile** [comment]
I'm very new to fritzing and find this very annoying problem. For now I just use notepad++ search and replace with pattern (font-size:\d+.?\d+)px and replacing by \1.
Anyway, the font handling in #3343 seems to solve another problem. Trying other SVG renderers all are correct with px. Moreover SVG spec allow using units for fonts (px, pt, em). If somebody already know how to fix this, I can give it a try.

**Comment by KjellMorgenstern** [comment]
The assumption that px are allowed on fonts seems wrong. Even if they were, how big should px be? Do you really want to use 12px fonts on 1000dpi documents such as for PCBs?

https://www.w3.org/TR/SVGTiny12/coords.html

Especially section 7.11:

7.11 Units

Besides the exceptions listed below all coordinates and lengths in SVG must be specified in user units, which means that unit identifiers are not allowed.
Two exceptions exist:

Unit identifiers are allowed on the 'width' and 'height' XML attributes on the 'svg' element.

Object bounding box units are allowed on 'linearGradient' and 'radialGradient' elements.
