### ISSUE TITLE
Exporting the breadboard view for part   "8x8 LED Matrix 1588ASR.fzpz" yields an empty file  

### ISSUE THREAD

**Issue by davsmith2** [fritzing/fritzing-app#3027]
I've seen this on 2 computers.  Here are the repro steps:
1) Install the custom part for an 8x8 LED matrix from the link below.
2) From the bin where you imported the part, right click and choose Edit part (new parts editor)
3) When the parts editor launches, make sure you're on the Breadboard tab
4) Choose File | Export | As Image | SVG
5) Pick a location to store the file.

The output file shows an empty page when rendered in Inkscape, and viewing in a text editor shows only the page definition, no data.

Unzipping the part file yields a proper SVG file which can be edited in Inkscape.

Link to custom part:
http://fritzing.googlecode.com/issues/attachment?aid=8750528000&name=8x8+LED+Matrix+1588ASR.fzpz&token=ABZ6GAcBugQGyixZaoKD7Qd5WK7DnTzmGA%3A1415766320228

**Comment by el-j** [comment]
sorry, this is more a bug in the part than in fritzing. closed
