### ISSUE TITLE
Raspberry Pi A broken on linux 0.9.1b

### ISSUE THREAD

**Issue by dank101** [fritzing/fritzing-app#3033]
The part exactly named "Raspberry Pi A" is non-working on linux build as there is no part file

"~/fritzing-0.9.1b.linux.AMD64/pdb/core/Raspberry_PI_A: file for Raspberry Pi A Raspberry Pi A not found." <- is the message

**Comment by pciavald** [comment]
Same here, fresh install

fritzing `0.9.0` from the official repositories
```
Error reading file /usr/share/fritzing/pdb/core/Raspberry_Pi_A.fzp: file for Raspberry Pi A Raspberry Pi A not found.
```

fritzing `0.9.2b` from the website
```
Error reading file /home/pciavald/Downloads/fritzing-0.9.2b.linux.AMD64/pdb/core/Raspberry_Pi_A.fzp: file for Raspberry Pi A Raspberry Pi A not found.
```

the file is indeed present, has the same chmod/chown as others files and seems coherent

**Comment by aknoerig** [comment]
This issue was moved to fritzing/fritzing-parts#41
