### ISSUE TITLE
Raspberry PI Model B Rev 01 - WIN32 causes fritzing Version 0.9.1 to freeze

### ISSUE THREAD

**Issue by mikecjudge** [fritzing/fritzing-app#3035]
In breadboard view when changing from the default Raspberry PI B+ to the PI B Rev 01 Fritzing Version 0.9.1 (b8d2d5970658f0bed09c661c9ea9a5) becomes unresponsive and freezes.

It works if the Raspberry PI variant is changed in schematic view and then change back to breadboard view.

**Comment by el-j** [comment]
sorry but i cannot rebuild this behavior. switching between the raspi variants works perfect for me.

**Comment by aknoerig** [comment]
This issue was moved to fritzing/fritzing-parts#40
