### ISSUE TITLE
Menu layout fails on Dual screen OSX

### ISSUE THREAD

**Issue by linuxjet** [fritzing/fritzing-app#3036]
When opening Fritzing on macbook  OSX 10.9 with Thunderbolt screen attached the menu options are floating in the incorrect locations.  
![screen shot 2014-12-18 at 15 29 49](https://cloud.githubusercontent.com/assets/378474/5496237/cd1224ec-86ca-11e4-90a5-954263d7d8db.png)

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
Especially if this still happens on recent OS X and Fritzing 0.9.3
