### ISSUE TITLE
Change to component connections when moving components.

### ISSUE THREAD

**Issue by wrishel** [fritzing/fritzing-app#3038]
When I have a component on the breadboard connected as I want it and then I move the component it drags the connection points away from their current connection and reconnects them at the spot where the connection lands. This makes sense when the component has a rigid set of pins at fixed locations, but there are many cases where the component has pigtail or bendable leads (such as a resistor or speaker) I would really like to nudge the component around without generating a bunch of ratsnest lines. 

Is there a way to do that? Could there be?

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
