### ISSUE TITLE
Deleting Ratsnest in Schematic Perturbs Breadboard View

### ISSUE THREAD

**Issue by wrishel** [fritzing/fritzing-app#3039]
Often when I have edited the breadboard view of a project and switch to the schematic I find ratsnest lines that were not logically necessary. Other traces on the schematic already complete the connection filled in with the Ratsnest.

When I delete these ratsnest lines and switch back to the breadboard view I find that the component has been moved to a new position and a new wire is added; in moving the component Fritzing breaks the connection. It then adds another wire to complete the circuit it just broke.

If this is not an already-known problem I can provide before and after Fritzing files to demonstrate what happens.

Thanks for your attention in this matter.

**Comment by rh-galaxy** [comment]
I have the same problem, here very well explained. It is very annoying and the most important thing to fix. It really makes you avoid doing changes to not mess up the different views again and again.

**Comment by failiz** [comment]
Please, could you upload the problematic files or provide precise steps to reproduce the error? Without them, we cannot fix the bug. Thanks!

**Comment by wrishel** [comment]
I appreciate your response, but this work is from a few years ago and I no
longer have the info to upload.

You might consider just removing very old issues from consideration.

**Comment by KjellMorgenstern** [comment]
From the description it sound like this issue does not happen anymore, however I don't really see a chance of really verifying if it has been fixed.
It might also be related to any of
#3734
#3678
#3659
#3608
#3580
#3340
#3039
#2899
#2800
#2782
and probably more.
