### ISSUE TITLE
Leonardo And Yun

### ISSUE THREAD

**Issue by browsem** [fritzing/fritzing-app#3041]
I have just tryed to do some SPI in Leonardo.
it seems the ICSP pins arent connected

I then inserted the YUN instead, and that had the icsp in the right place.
Then i started messing around, an noticed that SDA and SCL are connected to A4 and A5, as on a normal arduino.They should be to D2 & 3 instead.

I think i know, how to create new models, by cutting, pasting and in general mocking around, but i dont know where to put them

**Comment by el-j** [comment]
close because already fixed with commit: 4f888e47b27cebdb99eb219ad19f5fb9c0b2c473
