### ISSUE TITLE
Adafruit MCP23017 VDD (Pin9) and VSS (pin10) interchanged 

### ISSUE THREAD

**Issue by ChristianThiel** [fritzing/fritzing-app#3042]
Reproduce: Drop MCP23017 and look at pin 9 and 10 and compare to data sheet.

**Comment by el-j** [comment]
i assume you talk about this part:
https://github.com/adafruit/Fritzing-Library/blob/master/parts/MCP23017.fzpz

it is not part of the fritzing parts. please contact them because of the bug.
thanks
