### ISSUE TITLE
Cannot resize to monitor - too big

### ISSUE THREAD

**Issue by simon-Br** [fritzing/fritzing-app#3044]
I cannot resize the window to fit my monitor which is 1024x768 resolution. The window sizes are too large. Is there a way to reduce these to fit correctly?

Thanks,
Simon.

**Comment by el-j** [comment]
hello simon, 
on this small resolution you could only release the pallets to solve this problem. just track them out and i should work. if you make fritzing full-screen it should work.

we know about the "minimal"-width problem but cannot fix it because we need to reserve space for the bottom-tool-bar. 

![image](https://cloud.githubusercontent.com/assets/2795534/5941918/6f7cce58-a714-11e4-98b6-4560432ae248.png)

**Comment by simon-Br** [comment]
el-j wrote:
> hello simon,
> on this small resolution you could only release the pallets to solve
> this problem. just track them out and i should work. if you make
> fritzing full-screen it should work.  
> 
> we know about the "minimal"-width problem but cannot fix it because
> we need to reserve space for the bottom-tool-bar. 
> 
> image
> <https://cloud.githubusercontent.com/assets/2795534/5941918/6f7cce58-a714-11e4-98b6-4560432ae248.png>
> 
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/fritzing/fritzing-app/issues/3044#issuecomment-71869040>
> .
> <https://github.com/notifications/beacon/AKCukbttOLntyrdxGr_jNLtBZSICaHPXks5nmQnKgaJpZM4DSPA9.gif>

Hi,

What do you mean by "small" resolution? This is the maximum that this monitor is capable of
and any higher, it would also be impossible to read anything.

Thanks,
Simon.

**Comment by chrisyokum** [comment]
1024x768 is low resolution, it is not very common especially in engineering. I think that's what he means.

**Comment by grince** [comment]
I have the same problem with Fritzing on my Debian Stable (9.x) with a Full-HD Resolution.
I am not sure what goes wrong, but this is a screenshot of the app as I start it and I'll have an xterm below to show the size of a "normal" xterm. I have no idea why this happens, is there a way to have a smaller fontsize or something similar?

![fritzing-desktop](https://user-images.githubusercontent.com/2045125/33936699-b14f5936-e000-11e7-81a5-810de56ac17c.png)

**Comment by juanmitaboada** [comment]
Having same problem here in Debian 9. My resolution is 1920x1080 and everything looks so big I can not fit the window either into my desktop.

**Comment by AugustoCiuffoletti** [comment]
@juanmitaboada your solution works on Ubuntu 20.04.3 LTS and Fritzing 0.9.3b.
Many thanks
