### ISSUE TITLE
Cannot export for PCB on Mac OSX

### ISSUE THREAD

**Issue by stannard-p** [fritzing/fritzing-app#3045]
After designing in the PCB view, I cannot export to PDF or SVG. 

I get a window asking to which folder to save the file, I select a folder and click Open - but it does nothing. The window stays there and does not respond. Click on Cancel and it does nothing. I have to resort to Force Quiting Fritzing.

I tried this for exporting as PDF and also as SVG. Both responded (or rather didn't respond) in the same way.

Any ideas?

**Comment by stannard-p** [comment]
Forgot to mention - I'm on Mac OS 10.6.8

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
