### ISSUE TITLE
Easy rotation (enhancement)

### ISSUE THREAD

**Issue by charlieb000** [fritzing/fritzing-app#3047]
i decided to try fzz,
the first thing that i found I needed is an easy rotation shortcut button! The first thing i tried was a right click while i was dragging the object, perhaps this can be your shortcut for it.

cb

**Comment by el-j** [comment]
there are multiple ways for rotation: 
1. rightclick -> rotate menu
2. at the bottom is a rotate tool-button
3. go close to the edge of a part rotation arrow indicates rotation
...  

![image](https://cloud.githubusercontent.com/assets/2795534/5940398/da34f676-a70a-11e4-8cf7-c7bac41cc1e6.png)
