### ISSUE TITLE
Save as in code view

### ISSUE THREAD

**Issue by jokohoko** [fritzing/fritzing-app#3049]
When working in the code view i can't save it at an other location.

Even saving the fritzing design does not copy the ino file along with it.

Also it would be great is the code would be saved inside a folder with the same name the way arduino likes it. So even if you have to use the code seperatly it still works.

**Comment by arvindpdmn** [comment]
In a related issue, I found that when creating code for first time and saving it as a new ino file works. But if that ino file already exists in folder, I cannot overwrite it. There is a prompt to overwrite but it doesn't work as expected.

**Comment by KjellMorgenstern** [comment]
The file can be renamed like this:
![image](https://user-images.githubusercontent.com/6494025/149160353-3e67076c-07f4-41a6-a31a-07f6aa535549.png)

The dialog then also allows saving the file to a different folder.

Closing because it seems the issue does not occur anymore.
