### ISSUE TITLE
Untranslated Labels are missing

### ISSUE THREAD

**Issue by htho** [fritzing/fritzing-app#3050]
Hi,

I wanted to be able to position parts using x/y coordinates in mm. I was neither able to see the unit, nor was I able to change it. Taking a look at the sourcecode I realized everything is there to show the unit, and allowing to change it. Then I found that there is a small area at the right side of the coordinates where the mouse cursor changed. Clicking there changes the unit.
Anyway, I fear that there are more features I am (and propably ohers are) missing, just because a label isn't rendered properly.
The Label for the rotation is missing too. Both have in common that they are not translated. Maybe there is a Problem with that. Well, but I am not an QT expert.

I found this behaviour for the German version in Linux64 and Windows 8.1 64 and for the English Version in Linux64 too. The Frech version has the same Problem (besides the translated words are too long) (https://github.com/fritzing/fritzing-app/issues/2953).
![fritzing_linux64_de](https://cloud.githubusercontent.com/assets/2182288/5898567/011ab4d0-a551-11e4-8faa-e412466b7eb2.png)
![fritzing_linux64_en](https://cloud.githubusercontent.com/assets/2182288/5898568/011b9b7a-a551-11e4-9186-a3e96feacc01.png)
![fritzing_windows64_de](https://cloud.githubusercontent.com/assets/2182288/5898569/01211fd2-a551-11e4-8c82-afe2c80eb1d4.png)

**Comment by el-j** [comment]
fixed with: e9660eff9642f7a208e6f4d533056e5082f39cb4
