### ISSUE TITLE
When using the parts editor, delete all of the pins on Connectors, and then edit graphics(Breadboard,Schematic..) software crashes.

### ISSUE THREAD

**Issue by shikongzhu** [fritzing/fritzing-app#3055]
In the case of ubuntu and windows are the same.

**Comment by illarion** [comment]
Not sure if it's the same issue but software seems to crash just when editing schematics

**Comment by aquilanorica** [comment]
Fritzing 0.9.1 part editor crashes when editing schematics, breadboard, Icon or pcb.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
