### ISSUE TITLE
fritzing 0.9.1b part editor crashes when saving new parts after editing pins or connections

### ISSUE THREAD

**Issue by aquilanorica** [fritzing/fritzing-app#3057]
Hi there,
I love fritzing, but when it comes to creating new parts with the editor, one wastes countless hours.
It is a pain ...
I am using win7 64bit, fritzing 0.9.1b and inkscape 0.91.
The part editor often crashes the whole program. The editor crashes when saving a new part after having edited some pins. 
Saving is not his strength, it crashes also after having edited some connections.

Please, keep on debugging the editor. 

Go on with your phantastic initiative.

Greetings

Aquila

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
