### ISSUE TITLE
fritzing 0.9.1b part editor crashes using mystery parts as new parts when saving after editing

### ISSUE THREAD

**Issue by aquilanorica** [fritzing/fritzing-app#3058]
Hi fritzing team,

sorry, I wasted nearly six hours creating only one new part with fritzing 0.9.1b part editor.
I am using win7 64bit, fritzing 0.9.1b and inkscape 0.91.
The Editor crashes every time when saving a new part after having edited something.
Even mystery parts do not ease the pain.
I have lost my editing at least 6 times today.

regards

Aquila

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
