### ISSUE TITLE
No easy way to tell which bin a part originally came from

### ISSUE THREAD

**Issue by JohnVeness** [fritzing/fritzing-app#3062]
When clicking on a part (e.g. in the schematic view, or after doing a search in the parts bin pane), there is currently no way to know for sure which bin the part originally came from. In the Inspector pane there is a "family" field and "Tags" field, but nothing that matches exactly or consistently with the parts bin tooltip text that comes up when you hover over the different parts bins.

It would be useful if this showed up in the Inspector, ideally clickable to view the entire relevant parts bin, with the particular part highlighted.

I'm using Windows version 0.9.1.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
