### ISSUE TITLE
Sparkfun's 10mm LED icon problem in Fritzing Breadboard view

### ISSUE THREAD

**Issue by Jasmohan-ThandaLe** [fritzing/fritzing-app#3066]
Sparkfun's 10mm LED icon problem in Fritzing Breadboard view

Here is a Red 3mm LED next to a 10mm LED (Sparkfun) in breadboard view

![breadboard view](https://cloud.githubusercontent.com/assets/11637422/6812596/e854bdb6-d295-11e4-8553-70efd9475cc4.JPG)

Before I explain my problem let's go over some basics:-

A diode has two terminals. The positive side is called the anode, and the negative one is called the cathode.
The diode circuit symbol, with the anode and cathode marked.
![518ac8c5ce395f5f50000000](https://cloud.githubusercontent.com/assets/11637422/6812663/485172e0-d296-11e4-873d-106c55cb2fc9.png)

LED stands for light-emitting diode, which means that much like their diode cousins, they’re polarized. There are a handful of identifiers for finding the positive and negative pins on an LED. You can try to find the longer leg, which should indicate the positive, anode pin.
(Source: https://learn.sparkfun.com/tutorials/polarity/diode-and-led-polarity)

Parts of an LED
![led _5mm _green_ en svg](https://cloud.githubusercontent.com/assets/11637422/6812736/c6e70db8-d296-11e4-9813-eec0a27ec148.png)
(Source: http://en.wikipedia.org/wiki/Light-emitting_diode)

We can identify the polarity of an LED by looking inside it's casing. The larger end inside the led is -ve and the shorter one is +ve, that is how we find out the polarity of a LED.
![ffkevnzgtiew09n medium 1](https://cloud.githubusercontent.com/assets/11637422/6812807/3707b6b0-d297-11e4-9b10-6d2b9411a72d.jpg)
(Source: http://www.instructables.com/id/IDENTIFY-THE-ANODECATHODE-of-LEDs/)

Now that you understand this much, I shall explain the problem.

If you look closely in the LED icons in the Breadboard view of Fritzing, we should be able to identify the positive and negative terminal easily by looking inside the casing.
i.e. Bigger element is Cathode and Smaller element is Anode.

![breadboard view](https://cloud.githubusercontent.com/assets/11637422/6812890/da28456c-d297-11e4-8068-2a318eaf3d64.JPG)

So, looking at the icons as reference, I have connected the (presumably) Anodes and Cathodes of the 2 LEDs together by wires. But if we see the schematic view, the problem becomes clear.

![schematic view](https://cloud.githubusercontent.com/assets/11637422/6812939/2655133e-d298-11e4-8785-d12c30ebe07d.JPG)

The anode and cathode pins on the 10mm LED from sparkfun are reversed.

Since this is a part in the default library of Fritzing, and all installations have the same icons; I request that this problem be rectified so that new comers and experienced users don't get confused.

Here is some more information about the 10mm LED part:-
![sparkfun led](https://cloud.githubusercontent.com/assets/11637422/6813058/a6502d6c-d298-11e4-90b6-f19ecfccee55.JPG)

I may also be wrong about this, so if anyone can confirm this then that will be great.

One solution for the time being is to create a new part with the corrections; but if it gets fixed by fritzing in a software update then it is even better. That way, the problem may be solved for all the users.

**Comment by el-j** [comment]
thanks for the bug report. you are right. the wrong part is now "obsolete". so the user get the hint to change to part to the new version.

**Comment by Jasmohan-ThandaLe** [comment]
el-j Thank you for your time.
