### ISSUE TITLE
No text color in code editor

### ISSUE THREAD

**Issue by tofugl** [fritzing/fritzing-app#3067]
I have fritzing installed on several PC's, but one of the installations is not showing text colors in the code editor. I really like the text color......so please help me here......
The installation is windows 7 Pro running as VM under MAC OS X Yosemite 10.10.2
(this combination is working fine on another MAC with windows).

I suspect that it is a window setup somehow or?

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
