### ISSUE TITLE
Duplicating Generic IC does not work

### ISSUE THREAD

**Issue by EeroKH** [fritzing/fritzing-app#3068]
How to get the fault:
1. Take a new Schema
2. Take a Generc IC in Schematic
3. Select the Generic IC 
4. Use Mouse rigt button and select Dublicate
-> in duplicated IC the labels are not in there correct place.

I use fritzing  Version 0.9.1 (b8d2d5970658f0bed09c661c9ea9a515b5f40f44c 2014-11-19) 64 [Qt 5.2.1] 
in Linux Mint.

Thankyou 
- Eero-

**Comment by failiz** [comment]
I cannot replicate this in 0.9.6
