### ISSUE TITLE
Tag/Relase for Version 0.9.2b

### ISSUE THREAD

**Issue by htho** [fritzing/fritzing-app#3069]
Currently there is no tag or "release" for version 0.9.2b here on github.
There also is no downloadable source-tarball on the website.

The package maintainer for my favourite distro won't update the package until a source release is available: https://aur.archlinux.org/packages/fritzing

btw. why is it named 0.9.2**b** anyway?

**Comment by htho** [comment]
Thanks for tagging! (https://github.com/fritzing/fritzing-app/releases/tag/0.9.2b)
Anyway, what about that "b"?

**Comment by aknoerig** [comment]
The "b" stands for "beta" and historically means no warranties. :)
