### ISSUE TITLE
I can't create a new account

### ISSUE THREAD

**Issue by futurebird** [fritzing/fritzing-app#3082]
It also says my email is "inactive"

**Comment by el-j** [comment]
hej futurebird,
this a known bug. i can activate your account but i need your email address. please write to support@fritzing.org

**Comment by futurebird** [comment]
me@futurebird.com thanks!

**Comment by noyelseth** [comment]
Same for me too, Account is **not yet activated**.

![image](https://user-images.githubusercontent.com/29272159/90346316-81025380-e045-11ea-8f03-03204620b572.png)
