### ISSUE TITLE
port settings incomplete

### ISSUE THREAD

**Issue by ulilaube** [fritzing/fritzing-app#3088]
Hi!

I'am running the Fritzing IDE version 0.9.2 with Arduino IDE 1.6.4 under OpenSuse 13.2 in 64 Bits.
When I plug in an Arduino Uno R3 the device /dev/ttyACM0 becomes available.
Starting the Fritzig IDE and selecting the code tab shows the correct platform and board as well as the port "ttyACM0" in the dropdown boxes at the bottom of the window.

When I load the Blink.fzz example from the examples in the file menu and try to upload it, **_the upload fails**_. The log looks like this:

```
Running /home/ausbildung/Downloads/arduino-1.6.4/arduino --board arduino:avr:uno --port ttyACM0 --upload /home/ausbildung/.config/Fritzing/fzz/ade9fe320a41691a48cc9e208fcedc32/Blink_TMP/Blink_TMP.ino
Loading configuration...
Initializing packages...
Preparing boards...
Verifying and uploading...
Der Sketch verwendet 1.068 Bytes (3%) des Programmspeicherplatzes. Das Maximum sind 32.256 Bytes.
Globale Variablen verwenden 11 Bytes (0%) des dynamischen Speichers, 2.037 Bytes für lokale Variablen verbleiben. Das Maximum sind 2.048 Bytes.

avrdude: ser_open(): can't open device "ttyACM0": No such file or directory

ioctl("TIOCMGET"): Inappropriate ioctl for device

Hochladen beendet.
```

The error text is: `can't open device "ttyACM0": No such file or directory`

which is correct since /dev/ttyACM0 is the complete path.

In fact taking the command line from the log:

```
/home/ausbildung/Downloads/arduino-1.6.4/arduino --board arduino:avr:uno --port ttyACM0 --upload /home/ausbildung/.config/Fritzing/fzz/ade9fe320a41691a48cc9e208fcedc32/Blink_TMP/Blink_TMP.inoAnd
```

and changing the option from

```
--port ttyACM0
```

into

```
--port /dev/ttyACM0
```

and executing  the command manually in the shell results in a succesfull upload.

Is this known?
Is there a config file for the Fritzing IDE to work around the incomplete port setting?

Regards
Uli

**Comment by ulul** [comment]
mh... just finished a build of the master branch... and it works fine. The path in the option is correct. The version with the bug is from the 1-Click-Installer rpm provided by

obs://build.opensuse.org/home:Heinervdm

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
