### ISSUE TITLE
Raspberry Pi 2 Pin numbers incorrect

### ISSUE THREAD

**Issue by chrisyokum** [fritzing/fritzing-app#3091]
The Raspberry Pi 2 header pin numbers are incorrect. Take a look at http://pi.gadgetoid.com/pinout. In the Fritzing the top-left pin (furthest from the Ethernet port) is listed as GND/pin40. On the official documentation it's GND/Pin2. It's confusing when trying to hook things up..

**Comment by aknoerig** [comment]
This issue was moved to fritzing/fritzing-parts#38
