### ISSUE TITLE
Cannot find the Softpot Membrane Potentiometer part in Fritzing?

### ISSUE THREAD

**Issue by eljacko** [fritzing/fritzing-app#3092]
Here is a link to evidence it has been used in Fritzing projects:

https://learn.sparkfun.com/tutorials/sik-experiment-guide-for-arduino---v32/experiment-10-reading-a-soft-potentiometer

Please tell me how I can find the Softpot Membrane Potentiometer part.

**Comment by aknoerig** [comment]
This issue was moved to fritzing/fritzing-parts#37
