### ISSUE TITLE
Impossible to type fractionals when locale determines that 'period' isn't fraction delimiter.

### ISSUE THREAD

**Issue by Zalewa** [fritzing/fritzing-app#3094]
OS: Ubuntu 14.04

In Polish locale the delimiter for fractionals is a comma ','. When I run Fritzing with locale set to pl_PL.UTF-8 I can't specify size for PCB holes in fractionals. The input box won't accept period character '.', and when I type in ',' the entire number gets parsed incorrectly.

Workaround: launch Fritzing with environment variable LC_NUMERIC set to en_US.UTF-8 like this:

`LC_NUMERIC="en_US.UTF-8" ./Fritzing`

When I do this I can type periods into input boxes.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
