### ISSUE TITLE
mouse wheel on parts tabs: unexpected/unusable bahviour

### ISSUE THREAD

**Issue by htho** [fritzing/fritzing-app#3104]
Scrolling using the mouse wheel on the list of parts-catecories (search, core, mine, etc.) makes the panel actually switch to the next category, which causes loading this category, which is awfully slow.

Although this list probably is/was a tab-panel, where this behaviour is appropriate, it obviously became a scrollable list. As such, the expected behaviour for the wheel is the same as for the arrows on the bottom of that list.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
