### ISSUE TITLE
IC rendering glitch in schematic view

### ISSUE THREAD

**Issue by tylerhunt** [fritzing/fritzing-app#3108]
I've added several 4-pin ICs to a schematic, and everything looked fine, but when I closed and reopened the app, it no looks like this:

<img width="260" alt="screen shot 2015-07-09 at 2 43 22 pm" src="https://cloud.githubusercontent.com/assets/6457/8624775/71ec304c-2708-11e5-88a0-e006eeb43c08.png">

The bounds of the IC are kind of duplicated and shifted to the right, and the pin labels are no longer properly aligned. This IC was rotated 180 degrees, in case that has something to do with it.

This is what those ICs should look like:

<img width="329" alt="screen shot 2015-07-10 at 1 38 35 pm" src="https://cloud.githubusercontent.com/assets/6457/8624857/02ff7d14-2709-11e5-8c20-d653f4923ade.png">

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important, especially if version 0.9.3b still has this issue, please open.

**Comment by oxygene** [comment]
I just started using Fritzing 0.9.4, created a generic IC with 16 pins, rotated it in schematic view by 90 degrees. Then I saved and reopened the project, and the pin labels seems to have shifted to the bottom right. Seems it keeps shifting on subsequent save/reload cycles.

![2020-01-27_22h52_14](https://user-images.githubusercontent.com/833417/73217204-c4ec4480-4157-11ea-9470-24c5d636d9ad.png)
