### ISSUE TITLE
Zooming with mouse wheel causes unexpected scrolling

### ISSUE THREAD

**Issue by tylerhunt** [fritzing/fritzing-app#3113]
Use the modifier key to zoom with the mouse wheel (the Command key under OS X) leads to a zoom event followed by a scroll event.

Expected behavior: using the modifier key to zoom with the mouse wheel should change the zoom level but not the scroll position.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
