### ISSUE TITLE
Bend points are broken after save / crash-restore

### ISSUE THREAD

**Issue by thijs** [fritzing/fritzing-app#3115]
![bend-points-broken](https://cloud.githubusercontent.com/assets/1750/8659019/007d3bb6-29a8-11e5-8da5-af58cb30ab2a.png)

Today I've twice returned to a project to find all the bend points in my traces broken. See the screenshot above. The problem is not just visual, see below:

![bend-points-broken-copper](https://cloud.githubusercontent.com/assets/1750/8659075/5cebad92-29a8-11e5-86fb-3eed0cf2bfac.png)

When I try to move the bend points the traces seem to have been doubled up multiple times on each other and everything gets even more screwy. So the only option is to delete all traces and start over.

I've now seen this twice, as I said. Once after choosing to restore after a crash, once after just a regular save and then opening the project again later in the day.

The version I'm using is 0.9.2 on linux.

**Comment by ubenedix** [comment]
Same problem.
Reopend files are scrap. 
Moving bend points leads to chaos. 
1: file reopend -> broken connections everywhere 
2: moved bend point at broken connection: bend point not common to 2 traces 
3: moved bend point at "C5" just a little bit to left -> "even more screwy":  
I only had to touch 2 point to get from 1 to the chaos in 3. 
This makes frizzing 0.9.2 ... well, unhelpful. 

![frizzing-fehler1](https://cloud.githubusercontent.com/assets/13620433/9080328/da5cb454-3b52-11e5-83cf-ca779d140ded.jpg)
![frizzing-fehler2](https://cloud.githubusercontent.com/assets/13620433/9080398/72c3c11a-3b53-11e5-8ce8-bbd1bacbd8cf.jpg)
![frizzing-fehler3](https://cloud.githubusercontent.com/assets/13620433/9080400/76222f7c-3b53-11e5-9d57-2f4329532383.jpg)

**Comment by OnkelDittmeyer** [comment]
Same issues with Fritzing 0.9.2 under OS X10.9.5

**Comment by gepd** [comment]
I'll let here this gif to undertstand better this problem.

![bug1](https://cloud.githubusercontent.com/assets/7091609/11460802/cc8e9762-96d2-11e5-9900-6d80a9d95077.gif)

**Comment by aknoerig** [comment]
A quick heads up to everyone experiencing this bug: Jonathan has made great progress on it in the "crossed" branch (https://github.com/fritzing/fritzing-app/tree/crossed). The bug will be fixed from 0.9.3 on, and will also fix 99% of all broken files created with earlier versions.
Thanks for all the insights you provided!

**Comment by gepd** [comment]
Excellent news, I've been waiting long for it! :)

**Comment by aknoerig** [comment]
Fixed and pushed in 12b7894

**Comment by crazymadprofessor** [comment]
Same issue using Maveriks, 
Yesterday I been doing a PCB project for 7 hours non-stop, Today morning when I opened my project I realized that my project was usefulness , and  if I try to rectify the wire routing, my project get chaotic.

Is it there any solution? 
Is there some way I can fix that problemt?

Thank you very much

**Comment by aknoerig** [comment]
Sorry that this nasty bug has hit you, too. Expect a release of the new fritzing version in the next few weeks. It has the bug fixed, and will also repair old broken files. 

If you don't want to wait, you can try building the latest version yourself, but that's a few hours work: https://github.com/fritzing/fritzing-app/wiki/1.-Building-Fritzing

**Comment by crazymadprofessor** [comment]
Hey thank you very much ,  just I read your mail . 

When my project on fritzing crashed I stopped for a while, and experimented with eagle and other softwares, but to be honest are not the same than fritzing, the workflow in fritzing is much faster and much more intuitive than other freewares . you done a really good job . Actually I don't have to much money , but definitely if I could start to work with fritzing again I will try donate some to this fantastic project.

Thank you so much for all the effort.

Regards

Date: Sun, 14 Feb 2016 11:37:21 -0800

**Comment by mearsy** [comment]
Any idea when 0.93 will be on the main site for download?

**Comment by aknoerig** [comment]
We're still refining a few things while we're waiting for the final release of Qt 5.6 (which brings High-DPI support). It's scheduled for sometime in March, expect our release shortly after.

**Comment by mearsy** [comment]
Now qt 5.6 is out any idea when fritzing 0.93 will be released. im kind of stuck until i can fix my bendpoint issue

**Comment by aknoerig** [comment]
Getting really close now.. Note that Fab is already using it, so pcb orders will be fine.
Which OS are you on? Maybe we can issue a pre-release.

**Comment by mearsy** [comment]
Osx
