### ISSUE TITLE
Too many crashes / hangs with version 0.9.2 on linux

### ISSUE THREAD

**Issue by thijs** [fritzing/fritzing-app#3116]
I've recently started using Fritzing again, and before I dove in I updated to the latest version. Maybe I shouldn't have, because the new version is very prone to crashes and problems.

Basically I'm working and then suddenly the whole window vanishes. Without warning or trace. So then the only option is to start it up again and hope that the recovery save has run recently enough not to have lost a substantial amount of work. 

I've also seen a couple of freezes of the program. It just stops reacting and hangs. The only option is to kill it and start over.

**Comment by jrobeson** [comment]
try running it from the terminal and so when it crashes, it might output useful and potentially actionable information.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
