### ISSUE TITLE
generic ic with longpads

### ISSUE THREAD

**Issue by syedubaid** [fritzing/fritzing-app#3118]
in fritzing 0.9.2b generic ic has no longpad footprint as generic headers have.
other pcb making programs have such options.
please make generic ic customisible for having longpad footprint.
![untitled sketch_pcb](https://cloud.githubusercontent.com/assets/13495573/8889063/fc00db40-327d-11e5-90c5-773ad41118ac.jpg)

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open
