### ISSUE TITLE
pcb footprint

### ISSUE THREAD

**Issue by syedubaid** [fritzing/fritzing-app#3119]
fritzing lacks 5 volt relay pcb footprint.
relay given in image.
![s-l1000](https://cloud.githubusercontent.com/assets/13495573/8889088/4476a282-327f-11e5-926a-3d910ee8828c.jpg)

**Comment by bootchk** [comment]
With all respect, please choose more specific wording of the title for issues, so that readers can quickly see what the issue is about.  I thank you for reporting issues.

**Comment by el-j** [comment]
this is more a fritzing-parts issue not fritzing. please make issues and wishes for parts in the specific repo. https://github.com/fritzing/fritzing-parts
thanks + closed
