### ISSUE TITLE
smt parts not selectable 

### ISSUE THREAD

**Issue by agokhale** [fritzing/fritzing-app#3121]
versions are  Fritzing 0.9.1 beta (binary d/l) on OSX 10.6
desc:
The PCB editor is unable to select smt resistors or sot-23 transistors. 
reproduce:
Select an NPN transistor and change it's package style to SOT-23 via the inspector. Now the PCB editor is unable to select the body of the device to change it's position or orientation. 
workaround:
Don't use SMT parts. 
Remove the underlying PCB; then parts are selectable.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open
