### ISSUE TITLE
Bottom margin is too small in the app Window

### ISSUE THREAD

**Issue by JohnRDOrazio** [fritzing/fritzing-app#3127]
When the Fritzing window is enlarged to full-screen mode, it overflows slightly the desktop screen area on the bottom and is slightly cut off.

![image](https://cloud.githubusercontent.com/assets/231298/9014981/266ec336-37c6-11e5-802b-d46ae6ccfe46.png)

In this screenshot the zoom icons are half cut off, and the zoom bar is at the very edge of the desktop screen area. It would make for a better user experience if there were a little more bottom margin so the zoom bar and icons wouldn't be so close to the edge.

This also happens when not in full-screen mode:

![image](https://cloud.githubusercontent.com/assets/231298/9015282/249d2e1a-37c8-11e5-8164-73b00bc31456.png)

Here again, the zoom bar is very close to the edge of the window and the icons are half cut off.

**Comment by KjellMorgenstern** [comment]
I think this issue was solved in 0.9.4 or earlier
