### ISSUE TITLE
Resistor 5.6 ohm and all Multiplier are missing!!!

### ISSUE THREAD

**Issue by rpretolesi** [fritzing/fritzing-app#3134]

**Comment by el-j** [comment]
it is possible to write any value into the resistance field. 
what do you mean be mulitplier?

**Comment by rpretolesi** [comment]
I mean that in the dropdown menu', on the value that you can choose, the
value of 5,6 ohm and all it's multipliers doesn't exist.
I did not found any other way to set the value of the resistance.
Il 31/Ago/2015 10:53, "el-j" <notifications@github.com> ha scritto:

**Comment by tiramiseb** [comment]
>  I did not found any other way to set the value of the resistance.

You can type it manually in the same field, which is manually editable.

**Comment by rpretolesi** [comment]
Ok, i will try. If i have some more issues i will let you know. Thank you
for your support.
Il 03/Set/2015 09:00, "Sébastien Maccagnoni-Munch" <notifications@github.com>
ha scritto:
