### ISSUE TITLE
Segmentation fault when loading scheme

### ISSUE THREAD

**Issue by lootr** [fritzing/fritzing-app#3136]
1. Steps you took that resulted in the problem
   - Clean start of Fritzing (after removing ~/.config/Fritzing and given the parts folder)
   - Open the [Hall-effect schema](http://fritzing.org/media/fritzing-repo/projects/h/hall-effect-sensor/fritzing/Hall-effect.fz)
   - Accept conversion to Fzz format
   - Accept component update proposal
   - Confirm update
2. What you expected should have happened instead
   New file saved and board ready
3. Your version of Fritzing and your operating system
   Gentoo/Linux x86_64 kernel-4.0.5
   Fritzing-0.9.2b
4. Any files that relate to this problem: sketches, parts, log files or screenshots
   ![gdb_fritzing](https://cloud.githubusercontent.com/assets/202670/10019164/0c0210d0-613c-11e5-9ca5-2dfdf39f2e7a.png)
   [core file](https://fizzy.lootr.net/~bloody/core.Fritzing) (~339 MiB)

**Comment by KjellMorgenstern** [comment]
Tried several variations with current develop branch (>0.9.3b), including a valgrind run. I don't think this is still an issue.
