### ISSUE TITLE
Breadboard vs Schematics not ok

### ISSUE THREAD

**Issue by b4ulook4me** [fritzing/fritzing-app#3137]
Hello,
 Breadboard view and connections are ok, but when autorouting in schematics it is making unwanted connections. Also, it crashes when auto routing in PCB view.
Regards,

**Comment by landracer** [comment]
You might want to check on the internal routing of the said parts in question. This could affect autorouting. Crashing could be due to your specific hardware. Did you try and compile the source code, or are you running a release package?

**Comment by b4ulook4me** [comment]
Will Try, Also I am using released package.

**Comment by aknoerig** [comment]
If you still have this problem, please provide an example or screenshots. For the time being I'm closing this issue.
