### ISSUE TITLE
Incorrect pinout for NPN EBC transistor

### ISSUE THREAD

**Issue by chrisspen** [fritzing/fritzing-app#3147]
Selecting "NPN-Transistor" with an EBC pinout type from Core/Basic parts renders with pin 1 showing as the base. However, since it's listed as "EBC", I would expect pin 1 to be emitter. Also, in every datasheet for NPN EBC transistors I've seen (e.g. [2N4401](https://www.fairchildsemi.com/.../2N4401.pdf)), pin 1 is the emitter and pin 2 is the base.

Searching for NPN transistor shows many similar parts but they all appear to render pin 1 as the base regardless of the EBC type selection.

Have I misconfigured something or am I misunderstanding how these parts are rendered?

**Comment by aknoerig** [comment]
This issue was moved to fritzing/fritzing-parts#35
