### ISSUE TITLE
When exporting file to .pdf the graphic elements get bloated

### ISSUE THREAD

**Issue by TeresaFalomir** [fritzing/fritzing-app#3155]
The board looks 100% ok at Fritzing, is only when it is exported into a PDF when it adds extra strokes.
There is a way to fix that?

![example](https://cloud.githubusercontent.com/assets/15727581/11032164/d1205828-86d9-11e5-9eb7-78e7f302f87a.jpg)

**Comment by aknoerig** [comment]
Hmm, try using export to SVG, and then save as PDF from Inkscape or Illustrator?
Not sure we have enough control over PDF export, as that is a Qt feature.

**Comment by KjellMorgenstern** [comment]
Closing, as 
* no file to reproduce is available 
* issue seems to be in Qt
* a workaround was suggested, but no feedback from original poster
