### ISSUE TITLE
Ruler: 1/10 millimeter scale

### ISSUE THREAD

**Issue by duff2013** [fritzing/fritzing-app#3163]
it would be nice to have a finer scale for the ruler. Is this something that would be considered for a pull?
![screen shot 2015-12-07 at 2 15 38 am](https://cloud.githubusercontent.com/assets/5598200/11622116/7ad3d7dc-9c88-11e5-8b5b-75653a15fe56.png)

**Comment by niclashoyer** [comment]
yes, please, pull requests are always welcome!

**Comment by duff2013** [comment]
Ok, I was also thinking of splitting the ruler into just metric or english depending on what width type property was selected. The ruler in my opinion is unruly in such that its too wide while displaying Inches and Centimeter together and if I choose cm from the properties drop down I would think users just want to use cm for the ruler not both, same goes for if I choose inches. 

In the long run I want to look at a proper measuring system maybe like a simplified SolidWorks measuring tool which can select edges and measure the distance between them. So for example I could click the edge of the pcb and the edge of part and get that distance. I know it won't be easy or even possible but would make placing components and such much more precise.

**Comment by duff2013** [comment]
here is what I have come up with for the Ruler Class:
![screen shot 2015-12-09 at 1 09 13 pm](https://cloud.githubusercontent.com/assets/5598200/11695689/2dfd3698-9e76-11e5-9748-be5fa80476ca.png)

As you can see it splits the ruler into its own unit type i.e. English or Metric. Also made switching these types dynamic so when you switch units the Ruler changes to reflect that change. I am looking into fixing that stupid ComboBox that Qt has becuase it is a real pain to select the option you want. I was thinking of changing it to simple Check Box type?

**Comment by aknoerig** [comment]
Nice work! Not sure about Check Box, but a radio button would also be appropriate here.

**Comment by duff2013** [comment]
Thanks! I'll have a pull I hope today, I'll do separate pull for the radio button, still learning the fritzing code flow so I want be sure I don't break anything. My changes to the Ruler Class should be localized to that class so hopefully its incapsulated correctly:)

**Comment by aknoerig** [comment]
Committed in PR #3166
