### ISSUE TITLE
a segfault occured when deleting all the pins of a part in the part editor

### ISSUE THREAD

**Issue by norcott381** [fritzing/fritzing-app#3171]
[ 4467.801161] show_signal_msg: 21 callbacks suppressed
[ 4467.801176] Fritzing[2355]: segfault at 0 ip 00007f06aece4700 sp 00007fff189a64d8 error 4 in libQt5Xml.so.5[7f06aecd2000+3b000]

lubuntu 15.10 desktop amd64

updated on 21/12/2015

**Comment by norcott381** [comment]
version fritzing-0.9.2b.linux.AMD64

**Comment by KjellMorgenstern** [comment]
Can not reproduce. If this is still an issue, please provide additional information (exact steps, screenshots,  part files)
