### ISSUE TITLE
Bendpoints (Glowing Green) break traces. (PCB View)

### ISSUE THREAD

**Issue by opensourcefan** [fritzing/fritzing-app#3176]
After Autorouting and when attempting to modify routes by bending a green glowing circle appears at each bend. I thought was normal since this was my first use. I went to OSH Park to submit my PCB and noticed the breaks in the traces at all glowing bendpoints on their PCB preview page.   

![untitled](https://cloud.githubusercontent.com/assets/10550038/12077223/84a1fc34-b18d-11e5-86d7-2538f6ef6697.png)

The exact same issue reported here: http://fritzing.org/forum/thread/7082/ and http://fritzing.org/forum/thread/71170/

I am using the latest 0.9.2 version on Ubuntu 14.04LTS.

I removed all the traces via the select traces and delete commands and re-autorouted and saved. After that I was able to bend points without getting the glowing green connection point.

**Comment by aknoerig** [comment]
Another instance of issue #3115, will be fixed in the next release.
