### ISSUE TITLE
Mouse handles should remain the same size across zoom levels

### ISSUE THREAD

**Issue by deshipu** [fritzing/fritzing-app#3177]
This is a usability observation, and I think following this could greatly improve the ease of use for Fritzing.

Currently, when we zoom into the PCB view (and possibly other views too), all the mouse handles (trace benpoints, footprint outlines, etc.) zoom too. This means that zooming doesn't help with working with very tight designs, where those handles overlap. If instead the handles remained a constant size (large enough to conveniently click, small enough to not obscure too much), then zooming in would result in them being displayed farther apart, and thus easier to manipulate accurately. You can see how GIMP and Inkscape handle that, and how that makes it much easier to work both at large and small zoom levels.

**Comment by idontusenumbers** [comment]
This times a hundred. I regularly find it absolutely impossible to select a wire end point, drop it on the appropriate connector, move a component, etc.

**Comment by KjellMorgenstern** [comment]
There are (or hopefully, were) multiple things to fix for this issue.

All screenshots taken at zoom level 3000% . Most show an RP2040 (QFN part) , wires are 8mil
Comparing 1.0.3 to the upcoming 1.0.4.

### 1. Ratsnest lines getting in the way. 

_Fritzing 1.0.3 ratsnest lines with way to big hitbox_
![image](https://github.com/user-attachments/assets/d925db7d-38f2-4fd9-89f9-d8bee8c27df7)
The Hitbox for ratsnest line obstructs wire end. Note: I modifed 1.0.3 to show the hitbox. A vanilla Fritzing would give no indication that a click will grab the ratsnest line. Annoying.

_Fritzing 1.0.4 ratsnest lines don't increase with zoom_
![image](https://github.com/user-attachments/assets/0e68fe4e-7820-4365-b3c2-96b8f0555de2)
The hitbox of the ratsnest line is only slightly bigger than the line itself. It is now shown with a hover shadow by default. Ratsnest and their hitbox keep the same absolute width across all zoom levels.


### 2. Dotted selection markers not helpful on zoom

_Fritzing 1.0.3 selection markers are irritating at best_
![image](https://github.com/user-attachments/assets/ee1b274f-33a8-4d10-8b6f-ff895dc853eb)

_Fritzing 1.0.4 selection markers are relative to the trace width_
![image](https://github.com/user-attachments/assets/5d610098-0353-4a3c-9760-f92064a5dc55)

### 3. Mouse handles clutter view.
Did you spot that there is a unnecessary bendpoint between the 6th and 7th connector of the row?
Overlapping mouse handles often mean that there are more hitbox candiates than useful. Of course it is always the wrong item that takes priority.

_Fritzing 1.0.3 bendpoint hard to spot, mouse needs to be at a seemingly random spot far away to hit it_
![image](https://github.com/user-attachments/assets/85fa3efb-2f0c-4068-9180-96a80599d193)

_Fritzing 1.0.4 directly hover over the bendpoint_
![image](https://github.com/user-attachments/assets/414aad17-0a80-4317-9380-78c50798d32b)

_and remove it with double click to get a straight wire. Fritzing 1.0.3_
![image](https://github.com/user-attachments/assets/d1acbb54-2b22-4705-a3ce-f9d6221c3351)

_1.0.4 ..._
![image](https://github.com/user-attachments/assets/5bc19f0e-9913-4e1f-93fa-d3061c7b34b9)

**Comment by KjellMorgenstern** [comment]
### 4a. Wires easily jump to nearby connectors

_Fritzing 1.0.3 detaching the wire from VDD (7th pad of the row)_
![image](https://github.com/user-attachments/assets/221a2200-e6dc-4f29-8e70-14b70463c61e)
_but it directly snaps to the nearby bendpoint_ :-1: 
![image](https://github.com/user-attachments/assets/d24f1888-ac1b-43c9-a605-7e3b7132e35e)


_Fritzing 1.0.4 grab the wire_
![image](https://github.com/user-attachments/assets/dad1ba27-918b-49d7-9baf-77d7315b3645)
_and drop it at an empty place to detach it_
![image](https://github.com/user-attachments/assets/614b2149-519c-4eda-a25b-392fca8bbcbb)

**Comment by KjellMorgenstern** [comment]
### 4b. Wires easily jump to nearby connectors

Same effect as 4a, but quite a different part of the code, so worth to mention. 
Connecting the lose wire to a connector.

_Fritzing 1.0.3. Where will it snap?_
![image](https://github.com/user-attachments/assets/6289b780-d412-45d1-a61e-34c20df0922b)
_adding insult to the damage, the hover text already told us it will use this connector_
![image](https://github.com/user-attachments/assets/a6b3b850-67ab-47dc-9596-fcaa0ec81e2f)

_Fritzing 1.0.4 even with shaky hands_
![image](https://github.com/user-attachments/assets/d5b0c3a2-82e0-40f0-896c-a2438b81411d)
_probably the correct connector. Using the distance to the candidates for a guess what the user wanted_
![image](https://github.com/user-attachments/assets/11e2418f-546f-4584-9107-72e963960e3e)

*) If there are multiple candidates, we still prioritize by layer, but we now also take the distance into account.
We don't need to rely on the layers as much anymore. This will probably enable some more improvements for edge cases, e.g in the breadboard view.
