### ISSUE TITLE
Can't open fritzing without error

### ISSUE THREAD

**Issue by FS-rcarroll** [fritzing/fritzing-app#3182]
This is the same as this archived problem:
http://fritzing.org/forum/thread/1375/

When I open I get this error: http://imgur.com/Rv3Benj

I'm running Mac El Capitan (but this happened in Mountain Lion, as well)

**Comment by aknoerig** [comment]
Hmm, still a weird problem. Did you try a fresh installation, also wiping your use folder at ~/.config/Fritzing ?

**Comment by FS-rcarroll** [comment]
I did try a fresh install. I took a look at the ~/.config folder in my user directory but it is empty. Am I looking in the right place?

**Comment by aknoerig** [comment]
Yes, but it could mean that Fritzing isn't able to create a user folder there. Maybe a permissions problem, as Jonathan describes in the last forum post. You could try the two ideas he mentions there.

**Comment by FS-rcarroll** [comment]
Would the /.config file be in my user directory or in the var or usr directory?
