### ISSUE TITLE
SVG export reverses/flips the text

### ISSUE THREAD

**Issue by zeehio** [fritzing/fritzing-app#3186]
When exporting as SVG, the text is flipped and or rotated when it should not be. 
Tested on Linux, Fritzing-0.9.2b. 
I can't test on git master due to build errors (related to wrong libboost first, and libgit2 issues later).

Here is a simple example that can be used for testing:
## SVG export (incorrect):

This has been converted later on to png with the GIMP so it can be viewed here:
![bug_export_label_rotated_schem2 svg](https://cloud.githubusercontent.com/assets/75441/12843373/2cad2c16-cbf9-11e5-9430-0e192089f87a.png)
## PNG export (correct):

![bug_export_label_rotated_schem](https://cloud.githubusercontent.com/assets/75441/12843260/7cd530cc-cbf8-11e5-97c1-49c7f3fd7c70.png)
## SVG figure to see the generated "svg code"

SVG figure (In a zip file, so it can be attached in a github issue)
[bug_export_label_rotated_schem.svg.zip](https://github.com/fritzing/fritzing-app/files/118922/bug_export_label_rotated_schem.svg.zip)
## Fritzing test

FZZ file (with zip extension added, so it can be attached in a github issue):
[bug_export_label_rotated.fzz.zip](https://github.com/fritzing/fritzing-app/files/118913/bug_export_label_rotated.fzz.zip)

**Comment by zeehio** [comment]
Additionally, the colors are not converted to the black silkscreen and "#F7BD13" standard copper colors. This makes some parts appear with white silkscreen, hard to distinguish if there is a white background (e.g  https://github.com/fritzing/fritzing-parts/blob/master/svg/core/pcb/connector_power_pj202ah.svg)

**Comment by KjellMorgenstern** [comment]
Easy to reproduce with current 0.9.5 develop (and probably all other versions)

**Comment by KjellMorgenstern** [comment]
Possibly related to #2772
