### ISSUE TITLE
Inspector properties dropdowns seem to be disabled (Wire/LED...) - Mac.

### ISSUE THREAD

**Issue by alpha1125** [fritzing/fritzing-app#3187]
After I select an object, and the inspector shows the item, I am unable to change most/some properties.

Examples:

Wire:
I _AM_ able to change banding.
I am NOT able to change the color.

LED:
I am _NOT_ able to change
- package
- color

Anyone else experiencing this?

Fritizing Version: 0.9.2b.11.19.8d2d5970658f0bed09c661c9ea9a515b5f40f44c
OS: OSX 10.11.3

**Comment by failiz** [comment]
I am not able to reproduce this in 0.9.4.
