### ISSUE TITLE
parts.db prevent fritzing from loading new parts

### ISSUE THREAD

**Issue by el-j** [fritzing/fritzing-app#3189]
1. add a new part to the fritzing-parts (fzp+all svgs in it's folders)
2. start fritzing
3. fritzing does not find the part

fritzing should check the parts-branch and folders and update the parts.db on load. otherwise the git-update function during fritzing loads needs to pull the new parts and a new parts.db (around 10mb at the moment.) is it possible to "attach" new parts at the end of the parts.db?

**Comment by aknoerig** [comment]
Not sure I understand.. 
The parts.db is no longer stored in the git repo. It only gets created by developers when doing a release. 

If you want to experiment with new parts or fix old ones, there is now a new command line option -ov, that points to an override folder. All parts stored there will be loaded after parts.db and extend/override it. 

See also https://github.com/fritzing/fritzing-app/wiki/3.-Command-Line-Options

**Comment by aknoerig** [comment]
Wait, now I get it.. 
This should be happening, and I think it works for me. I will check again.

**Comment by aknoerig** [comment]
The parts.db is completely regenerated after the user accepts the update, so that seems to work as expected.
 
What exactly did you do that didn't work, step by step?

**Comment by el-j** [comment]
ok step by step:

1. make a new part (fzp and svg in the parts-core-folderstructure/fritzing-parts-repository)
2. open fritzing
3. the part cannot be found in fritzing
4. move/delete parts.db
5. open fritzing again
6. fritzing starts with all parts
7. looking for the new part, shows the part via fritzing-parts-search
8. fritzing-parts folder has a new parts.db now with 0kb size
9. close fritzing
10. open fritzing again
![image](https://cloud.githubusercontent.com/assets/2795534/13034751/d586ede0-d33d-11e5-9461-cd0425b66e49.png)
![image](https://cloud.githubusercontent.com/assets/2795534/13034753/e985fc78-d33d-11e5-9cee-fecd272b183b.png)

the only way to solve the problem:
a) copy back parts.db -> fritzing starts but without the new part
b) write a new parts.db -> the complete new parts.db file has to be pushed/pulled (10mb)

the ov option did the job, but slows down the loading and search mechanism. it seams that it works without the parts.db completely. 

the question is now: how can new parts in the parts-repository, be used, without rewriting the hole db-file? otherwise the update-mechanism for users does not make sens from my point of view.

**Comment by aknoerig** [comment]
I think you are tricking yourself here, if you try to create a new part in the same fritzing-parts repo that the Fritzing app is using.
Instead, you should keep a separate clone of fritzing-parts (let's name it fritzing-parts-dev) for pushing changes.

So the new workflow for core parts contributors would go like this:
* Test all new parts or changes in the override folder 
* When working, copy these to your fritzing-parts-dev clone. Push from there.
* Run fritzing, which is using the not yet updated fritzing-parts clone. It will then update its clone and regenerate parts.db

**Comment by el-j** [comment]
ok, i got it. sorry. 
but when i now click on "update parts" fritzing crashes...

![image](https://cloud.githubusercontent.com/assets/2795534/13045697/25a68abe-d3d5-11e5-8e9f-ca2350cbcca9.png)

![image](https://cloud.githubusercontent.com/assets/2795534/13045706/3227f3a4-d3d5-11e5-81d1-354fa2079838.png)


next time i reopen fritzing, the update message is gone. it works normal but do not have the new part in the library and the new parts-files aren't cloned into my fritzing-parts-app folder.
![image](https://cloud.githubusercontent.com/assets/2795534/13045760/7e055352-d3d5-11e5-8a81-45ba5ce626aa.png)

what is wrong now? any idea?

**Comment by aknoerig** [comment]
Not really. ;) For me everything is working fine. Please try a clean new setup. If it crashes, the crash report / command line output / Qt Creator error messages would be helpful.

**Comment by el-j** [comment]
"http check new version no error" 
is the last message i get from qt. after that, i have to hit: "programm schließen"
and it ends up with "~\Fritzing\debug64\Fritzing.exe exited with code 255"
the windows error log on this:
```
Name der fehlerhaften Anwendung: Fritzing.exe, Version: 0.9.2.0, Zeitstempel: 0x56c1ae91
Name des fehlerhaften Moduls: git2.dll, Version: 0.23.0.0, Zeitstempel: 0x56610937
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000018b820
ID des fehlerhaften Prozesses: 0x858
Startzeit der fehlerhaften Anwendung: 0x01d167e1f914f6a8
Pfad der fehlerhaften Anwendung: ~\Fritzing\debug64\Fritzing.exe
Pfad des fehlerhaften Moduls: ~\libgit2\build64\git2.dll
Berichtskennung: f77f0806-e59b-497e-a8c9-a150e39cea7c
Vollständiger Name des fehlerhaften Pakets: 

```

i have found this libgit2 error on stackoverflow:
http://stackoverflow.com/questions/28978460/libgit2-write-tree-object-to-mysql-odb-backend

maybe that helps
