### ISSUE TITLE
svg export missing fritzing-logo

### ISSUE THREAD

**Issue by el-j** [fritzing/fritzing-app#3192]
1. make a sketch
2. export as image -> svg
3. a fritzing logo should sit in the right corner of the image

sadly there is no fritzing logo like in the pdf export. is that intended?
i think there was a logo in earlier versions.

**Comment by el-j** [comment]
unfortunately i cannot attach a svg file or a zip of it. github blocks the upload for some reason.--

**Comment by KjellMorgenstern** [comment]
This was fixed in 0.9.9 or earlier.
