### ISSUE TITLE
error library

### ISSUE THREAD

**Issue by yo3gsk** [fritzing/fritzing-app#3194]
adding layer kin 57341 3 25 10837b990
adding layer kin 57342 3 23 1153b3c50
after drop event
adding layer kin 57341 3 25 1153b3d50
adding layer kin 57342 3 23 11d82bee0
svgidlayer fail connector0 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/obsolete/Rotary_Encoder.fzp
svgidlayer fail connector1 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/obsolete/Rotary_Encoder.fzp
svgidlayer fail connector2 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/obsolete/Rotary_Encoder.fzp
adding layer kin 57341 2 10 10836d720
placing part with rotation:1 rect: x=-0.623 y=-36.45 w=585.921 h=225.45
addPartItem renderImage failed RevEd_24LC01 file for 24LC01 RevEd_24LC01 not found
after drop event
addPartItem renderImage failed RevEd_24LC01 file for 24LC01 RevEd_24LC01 not found
svgidlayer fail connector0 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector1 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector2 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector3 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector4 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector5 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector6 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
svgidlayer fail connector7 vid:2 vlid:10 /Applications/Fritzing.app/Contents/MacOS/pdb/core/24LC01.fzp
adding layer kin 57371 2 10 11af66f70
placing part with rotation:0 rect: x=82.45 y=-43.451 w=502.848 h=89.888

**Comment by aknoerig** [comment]
Thanks, but how did you end up with this error? Which steps did you take?
