### ISSUE TITLE
PCB trace width should remember the last used value

### ISSUE THREAD

**Issue by Kazade** [fritzing/fritzing-app#3195]
If you are laying down your traces in PCB view it's really annoying to after every trace to change the wire thickness. I suggest that the trace thickness should be "sticky" and the next trace you draw should inherit the thickness of the last trace.

**Comment by DrItanium** [comment]
I've been designing a ton of boards in the last two weeks and this issue kept coming up. As a addendum to this, there should be a way to denote a default width as well.

**Comment by cowboydaniel** [comment]
![Image 004](https://user-images.githubusercontent.com/107297413/173712199-6cd8c6fd-f93a-4151-b66f-8f5a1ba42012.png)
![Image 003](https://user-images.githubusercontent.com/107297413/173712202-dfe58770-a2a1-489f-b0c6-4a38faaff53b.png)
I don't know if this is new or something, but the autorouter trace width IS setable. I just found this setting, and by selecting custom, you can change the default trace width!!!

**Comment by KjellMorgenstern** [comment]
@cowboydaniel The issue is not about autorouter trace width, so it is still open. PS. Please avoid cross-posting.
