### ISSUE TITLE
It's really difficult to just move components in PCB view

### ISSUE THREAD

**Issue by Kazade** [fritzing/fritzing-app#3197]
If I just want to select a component in PCB view, I can't just click on it, I have to hover the mouse around until I hit just the right place and then click - and sometimes that's not possible because of other components getting in the way!

It would be great if there was a modifier key which basically meant "always select component/wire" rather than creating a new trace.

**Comment by Kazade** [comment]
See also #2663

**Comment by failiz** [comment]
Duplicate of  #2663. Close

**Comment by KjellMorgenstern** [comment]
Closing as duplicate.
