### ISSUE TITLE
half+ breadboard pin misalignment

### ISSUE THREAD

**Issue by chuank** [fritzing/fritzing-app#3199]
When **Align to Grid** is enabled, the **half+ breadboard** snaps itself to the alignment grid, with its power rail pins perfectly aligned on the grid.

The power rail pins, however, are not vertically aligned with the main breadboard pins, which causes all other 0.1" pitch parts attached to the main prototyping area to become offset vertically:

![image](https://cloud.githubusercontent.com/assets/1781911/13513441/0709c7f0-e1f5-11e5-8146-33b1f4095f3f.png)

The full+ or full/half breadboards do not have this problem, as all pins are aligned to the grid.

**Comment by KjellMorgenstern** [comment]
The alignment of parts and connector seems to be fixed.

The vertical mismatch of power rails and breadboard pins are common (physical modules I have on my desk show the same mismatch). 

Actually the full+ breadboard variant I have also has this mismatch. The power rails has just one row less than the breadboard, and is offset by half a row.
