### ISSUE TITLE
VERTER 5V USB Buck-Boost does not have a unique ID

### ISSUE THREAD

**Issue by joaoTrevizoli** [fritzing/fritzing-app#3204]
error when runnig fritzing with the adafruit parts library, the error message is "The part 'VERTER 5V USB Buck-Boost' at '/home/joao/.config/Fritzing/parts/user/verter_usb.fzp' does not have a unique module id 'verter-usb'."

the verter_usb.fzp attached

**Comment by aknoerig** [comment]
Thanks, but please report to https://github.com/adafruit/Fritzing-Library as we're not maintaining the Adafruit library.
