### ISSUE TITLE
Arduino Pro Mini gets not hidden if I hide the parts-layer

### ISSUE THREAD

**Issue by MikeMitterer** [fritzing/fritzing-app#3206]
Screenshot shows it better what I mean:

![screenshot-2003](https://cloud.githubusercontent.com/assets/116654/14914900/a707a282-0e0e-11e6-854c-5950437b22d8.png)

![screenshot-2004](https://cloud.githubusercontent.com/assets/116654/14914899/a706b55c-0e0e-11e6-8404-b32ffac38bf0.png)

**Comment by KjellMorgenstern** [comment]
It seems this affects the only the pro mini v13 part, and is fixed with the pro mini v14 part.
