### ISSUE TITLE
Unable to select "hole" part

### ISSUE THREAD

**Issue by chrisspen** [fritzing/fritzing-app#3208]
Searching for "hole" find a part simply labeled "hole". However, trying to click and drag shows the mouse cursor as the "not" symbol, and prevents placing of the part. No error message is shown to explain why this part can't be placed. How do you select and place a "hole"?

**Comment by aknoerig** [comment]
Hmm, are you trying this in PCB view? If yes, which version are you using, and on which platform?

**Comment by chrisspen** [comment]
No, that was it. It's only placeable in the PCB view. Sorry for the confusion.
