### ISSUE TITLE
Bend points become disconnected on load

### ISSUE THREAD

**Issue by jbsaige** [fritzing/fritzing-app#3215]
![frtz1](https://cloud.githubusercontent.com/assets/8528028/15679711/174e936a-2710-11e6-87d6-618e3b86d8c3.jpg)
This happened after a certain level of complexity, and only after I had a via with 3 traces attached.  Not sure if that has anything to do with the cause.

The first and last bend point on a trace become disconnected on load. (Highlighted by the green dots.)  All other bend points are fine.

This only happens on program load. Fixing the file and choosing revert does not cause the error. Exiting the application and reloading does.

Dragging one of the broken bend points causes the first and last (the broken ones) to swap and the trace to be connected again.

This is my affected fzz file:
[RGB LED 8x8x8 Cube-h.zip](https://github.com/fritzing/fritzing-app/files/291474/RGB.LED.8x8x8.Cube-h.zip)

Using version 0.9.2 (b8d2d5970658f0bed09c661c9ea9a5)

**Comment by aknoerig** [comment]
Thanks, this is another instance of issue #3115, which is luckily fixed by now. The release is imminent.. :)
