### ISSUE TITLE
Frizting 0.9.3b - Missing MSVCR120.DLL / MSVCP120.DLL

### ISSUE THREAD

**Issue by peter-65** [fritzing/fritzing-app#3222]
![fritzing1](https://cloud.githubusercontent.com/assets/12758431/15836732/1733aadc-2c2e-11e6-9f39-79f02172b15c.PNG)
![fritzing2](https://cloud.githubusercontent.com/assets/12758431/15836736/1bfc230a-2c2e-11e6-9736-48118190cea0.PNG)

Got the above errors while trying to run the 0.9.3b files on windows 10 64Bit. 

Info for the Tech's.

New build of win 10 1115 (no files retained)
Downloaded the zip file and after unzipping tried to run got the errors.

downloaded the 2015 visual studio redistrutabale files as can be seen below. 
retried the program / rebooted and retried.

Downloaded the 2012 version 
retried the program and rebooted and retired again.

Also tried the SFC / scannow (system file correction utility) No Joy 

Anything else I can try to fix ?

![fritzing3](https://cloud.githubusercontent.com/assets/12758431/15836940/05e70e6c-2c2f-11e6-9d56-c7375f039654.PNG)

**Comment by aknoerig** [comment]
Thanks for the detailed report! We just updated the Windows builds so please try downloading a fresh copy of fritzing and try again.
It can sometimes be very confusing to deal with the vc++ libs on Windows. We're actually using the 2013 libraries, so you just didn't get lucky. ;)
