### ISSUE TITLE
"Arduino UNO (Rev3) ICSP" ... pin A4 glitch.

### ISSUE THREAD

**Issue by drawkula** [fritzing/fritzing-app#3225]
"Arduino UNO (Rev3) ICSP" ... pin A4 is double-labled as "A4/SDA" and "ICSP MOSI".
(fritzing-0.93b)

**Comment by el-j** [comment]
thank you.
fixed with:
https://github.com/fritzing/fritzing-parts/commit/983b07b58a39c473c7aea907d98840c482be8768

(fritzing part issues please in the fritzing-parts-repository. ;)

**Comment by drawkula** [comment]
Thanks.

"Arduino UNO (Rev3) - ICSP (w/o Icsp2)" still calls "A4" "ICSP MOSI" in scematics view.
