### ISSUE TITLE
The latest version fritzing.0.9.3b.32.pc crashes when exporting gerber

### ISSUE THREAD

**Issue by gbbickerton** [fritzing/fritzing-app#3226]
The latest version fritzing.0.9.3b.32.pc crashes when exporting gerber while version fritzing.0.9.2b.32.pc does not on this file.
[14 Picaxe Buzzbox.zip](https://github.com/fritzing/fritzing-app/files/304568/14.Picaxe.Buzzbox.zip)

**Comment by aknoerig** [comment]
Sorry, something was seriously borked with the win32 release. I just did a clean new build and uploaded it. Works fine on my machine! Please try downloading a fresh copy.

**Comment by gbbickerton** [comment]
Thanks I wasn't annoyed just giving useful feedback

Barry

**Comment by aknoerig** [comment]
Phew ;)
