### ISSUE TITLE
Mystery part's wire connection display broken after flip or rotation.

### ISSUE THREAD

**Issue by ZeroNullBit** [fritzing/fritzing-app#3235]
Mystery part's wire connection display broken after flip or rotation.

Bug re-trig steps:
1. Drap 3 Mystery part into Schema view and place them.
2. Right click the U2 part, Click "Flip Horizontal" menu item.
3. Right click the U3 part, Click "Rotate 180°".
4. Connect the pins each other.
5. Drag the parts' label "U1","U2","U3" to another position.
6. Save the file and close Fritzing.
7. Launch Fritzing again and reload the file just saved.
8. Switch to Schema View , you'll find that the wires of "U2","U3" part are display broken.

**Comment by ZeroNullBit** [comment]
OS: Windows 7 64Bit Chinese
Fritzing: 0.93b 64bit.

**Comment by KjellMorgenstern** [comment]
Verified the issue
Before:
![image](https://user-images.githubusercontent.com/6494025/73728655-08384b80-4734-11ea-94c5-9048018d0027.png)

After:
![image](https://user-images.githubusercontent.com/6494025/73728801-45044280-4734-11ea-9128-a78457fcd3a4.png)

It seems the mystery parts body is not displayed correctly when loaded from a file.

**Comment by KjellMorgenstern** [comment]
Might be related to #3180
