### ISSUE TITLE
sketches submodule

### ISSUE THREAD

**Issue by paulvollmer** [fritzing/fritzing-app#3237]
hey folk,
what do you think about replacing the [sketches/core](https://github.com/fritzing/fritzing-app/tree/master/sketches/core) directory by a submodule.

after i've create a new repository i realize that it make no sense if i create a submodule linked to my repo (wrong url at the submodule) and send a pull request...

if you're lazy, create a new [fritzing-sketches](https://github.com/fritzing/fritzing-sketches) repo i can fork and setup the submodule to the right directory  and move all the files to the new sketches repository.

**Comment by failiz** [comment]
Is this still in the pipeline?

**Comment by KjellMorgenstern** [comment]
Not planned.
