### ISSUE TITLE
Parts and wires disappearing when placing ground fill

### ISSUE THREAD

**Issue by noisymime** [fritzing/fritzing-app#3255]
About half the time when I place a ground fill, some components and wires simply disappear from the sketch. I have to close the sketch (Without saving) and reopen and then try again. This doesn't happen every time and I make no changes to the sketch in between attempting ground fills. It does seem to happen more frequently when I am zoomed in on a certain part of the board, but this may simply be a red herring as I can't verify it every time. 

Here is a set of gerbers where the problem took place. It's clear to see down the bottom where some wires simply stop dead and aren't placed, yet the ground fill shows where they should be running. 
http://gerblook.org/pcb/XpzhojTMkEok8rfBUhNAQK

**Comment by KjellMorgenstern** [comment]
The link is dead. 
@noisymime Do you still have files or examples available? 
Closing this for now, but will of course reopen for further information or reports.
