### ISSUE TITLE
Autoroute dialog position with multiple displays.

### ISSUE THREAD

**Issue by deggle** [fritzing/fritzing-app#3260]
On a multi monitor setup the autoroute dialog centres itself across all monitors, asnd in my case it's awkwardly split between screens. It's a very minor bug, but hopefully an equally simple fix - just a tweak to centre the dialog on current window dimensions rather than total display dimensions.

**Comment by failiz** [comment]
I cannot replicate this in 0.9.10 (Windows), see:
![image](https://user-images.githubusercontent.com/5708642/183380845-db5be165-3262-489f-99ac-501859447558.png)

The position is as desired in the code:
```
AutorouteProgressDialog progress(tr("Autorouting Progress..."), true, true, true, true, pcbSketchWidget, this);
	progress.setModal(true);
	progress.show();
	QRect pr = progress.frameGeometry();
	QRect wr = this->frameGeometry();
	progress.move(wr.right() - pr.width(), pr.top());
```

**Comment by KjellMorgenstern** [comment]
Using a multi-monitor setup on Linux, I have neither observed this.
