### ISSUE TITLE
Using Fritzing on a Gnome Wayland session lead to global mouse focus issue

### ISSUE THREAD

**Issue by razerraz** [fritzing/fritzing-app#3265]
When using Fritzing on a Gnome Wayland session (using Xwayland indeed), I loose frequently the global mouse focus : I can grab windows focus, but I can't select with the mouse any widgets on it. This affects not only Fritzing windows, but all of them. Keyboard input works.

Getting a shell with Alt-F3 and get back to wayland solve the issue (I exercice that every 10 min or so...)
It seems to occur often when switching focus from fritzing to another Xwayland window.

It's fritzing specific, since I use a lot of Xwayland applications on my system.

fritzing 0.9.3b-2
wayland 1.11.0-1
gtk3 3.20.8-1

**Comment by KjellMorgenstern** [comment]
Does this problem still occur with a recent development build of fritzing? (available via github releases)
