### ISSUE TITLE
Mac crash with 0.9.3b on launching/no pb with 0.9.2b

### ISSUE THREAD

**Issue by fg031956** [fritzing/fritzing-app#3266]
Hello, I have just discovered this fine software.
I have tried to launch the last release of Fritzing 0.9.3b and the software crash on start.
I have no problem with Fritzing 0.9.2b.

I am not a software man but if this can help ...

Here is the configuration :

Nom du modèle: iMac
  Identifiant du modèle:   iMac12,1
  Nom du processeur:    Intel Core i5
  Vitesse du processeur:    2,5 GHz
  Nombre de processeurs:    1
  Nombre total de cœurs:   4
  Cache de niveau 2 (par cœur):    256 Ko
  Cache de niveau 3:    6 Mo
  Mémoire: 4 Go
  Version de la ROM de démarrage:  IM121.0047.B1F
  Version SMC (système):   1.71f22

Vue d’ensemble du logiciel système :

  Version du système:  Mac OS X 10.7.5 (11G63)
  Version du noyau: Darwin 11.4.2
  Volume de démarrage: Macintosh HD
  Mode de démarrage:   Normal
  Nom de l’ordinateur:    xxxx
  Nom de l’utilisateur:   xxxx
  Mémoire virtuelle sécurisée:   activée
  Noyau et extensions 64 bits: Oui
  Temps depuis le démarrage:   121 jours 22:51

**Comment by KjellMorgenstern** [comment]
Sorry, without further information it is not possible to debug this problem in Fritzing. If you still have this issue, it might help to ask in the forum to narrow down the problem. Also, if you can reproduce the problem reliably and have some time to help, please reopen the issue (or a new one).
