### ISSUE TITLE
selecting a part should bring it to the top of its layer?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#327]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 02, 2008 10:19:52_

If, for example, you have a set of wires connected to a single part, and
you want to disconnect a particular wire that's not on top, currently you'd
select the wire, choose the bring-to-front option from the app menu or
context menu, and then you could click and drag on the wire's endpoint.

Brendan suggests combining this all in one operation by having any part
change z-order to the top of its layer when you select it.  

What do you think?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=327_

**Comment by failiz** [comment]
Still not addressed in 0.9.4. Remove imported label.

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
Sounds a bit complicated and may be unpredictable for the user.

**Comment by failiz** [comment]
I am not sure if this is a good idea after reading the others issues. Maybe it is better to focus on improving the selection mechanism.
