### ISSUE TITLE
Can not open file in "special characters path" like this: C:\Users\List02\Desktop\Břink

### ISSUE THREAD

**Issue by Klepeto** [fritzing/fritzing-app#3277]
![image](https://cloud.githubusercontent.com/assets/8652069/18664901/ef2c4478-7f24-11e6-8e0a-da966f2a09c7.png)

Special character is **ř**, but I think there will be more characters causing errors like this..

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using?

**Comment by KjellMorgenstern** [comment]
Note: A quick check on Windows 10 showed no problems with paths that have the character  ř
