### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by donaghan** [fritzing/fritzing-app#3279]
Unable to  install updates. (sorry unable to download new parts)
![problem](https://cloud.githubusercontent.com/assets/22427465/18814975/226bc3ce-831a-11e6-9d73-970c9eaee024.png)

**Comment by Outdoorsman** [comment]
I installed version 0.9.3b, the Windows 64 bit version and am getting this exact same thing. To reproduce do this...

1. Select "Help > Check for updates..."
2. Click "Update parts" from the popup (pic 1)
3. Get the error notice popup (pic 2)

![update-parts](https://cloud.githubusercontent.com/assets/3075533/19981386/f5b8c2e6-a1be-11e6-9b6b-6ec31e3a6b15.png)

![unable-to-download-new-parts](https://cloud.githubusercontent.com/assets/3075533/19981385/f5b4f03a-a1be-11e6-997f-0988510211f2.png)

**Comment by KjellMorgenstern** [comment]
The error message must be improved to give more details about the problem (configuration error, write error, network error...)

**Comment by KjellMorgenstern** [comment]
The error message was improved and a check for writing permissions was added. For now (0.9.7) the feature is disabled. It still caused issues (eg. when the connetion to github is slow). Also it is much easier for us to release new versions of Fritzing and Fritzing parts at once. 
Updating parts via git can still be done manually.
