### ISSUE TITLE
Problems with the download.

### ISSUE THREAD

**Issue by Sever44** [fritzing/fritzing-app#3285]
Please help

![picture1](https://cloud.githubusercontent.com/assets/23387143/20204961/aa255560-a7e5-11e6-9417-877fdbd32ee3.jpg)

**Comment by vanepp** [comment]
While I've not seen this error, I'd check that the platform folder contains qwindows.dll (which it does on my working Win7 system) as that seems to be what it is looking for without success. If its not there on your system as it suggests try a reload of Fritzing (and/or check that that file is in the download that you are using). If it is in the zip file but not on your system check your antivirus program isn't deciding its a virus.

**Comment by np511** [comment]
You need to extract the program fist - you're trying to run it through 7-Zip.

**Comment by vanepp** [comment]
Good catch! I completely missed that that was a 7zip window ...

Peter

**Comment by np511** [comment]
This can be closed right? No need to distract people with a solved issue...
