### ISSUE TITLE
Gerber export is randomly corrupted

### ISSUE THREAD

**Issue by PatrickFranken** [fritzing/fritzing-app#3288]
While exporting a few Fritzing files to Gerber I noticed a bug which occurs from time to time. Below is a valid output (blue) and an invalid output (red)
![screenshot from 2016-11-23 18-39-38](https://cloud.githubusercontent.com/assets/8692465/20572620/7cab5636-b1ac-11e6-9a76-ca23dd8fa8a1.png)
![screenshot from 2016-11-23 18-39-55](https://cloud.githubusercontent.com/assets/8692465/20572619/7ca6e88a-b1ac-11e6-9347-b9a2f9204b22.png)

To reproduce this issue I implemented a tiny Ruby script which is attached to this issue. The resulting probability to run into this issue is about 50%.
Below are the checksums of the copperTop.gtl file which shows valid and invalid files for 20 iterations.

8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
bfb1fbe3fe436db310e1f567ef91f23c
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c
8cd6c97945eec19da2e0f7cfad4bc983
8cd6c97945eec19da2e0f7cfad4bc983
8cd6c97945eec19da2e0f7cfad4bc983
bfb1fbe3fe436db310e1f567ef91f23c

[test_gerber_export.txt](https://github.com/fritzing/fritzing-app/files/609603/test_gerber_export.txt)

**Comment by KjellMorgenstern** [comment]
Retested with version git 74ed0945 , and got the same (correct) top copper:

100 times...
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
6083a063075db637fbb31a70135ed863
...
