### ISSUE TITLE
Resistor Value - GigaOhm Not Working

### ISSUE THREAD

**Issue by freeman892** [fritzing/fritzing-app#3292]
It seems that if I want to place a resistor with an arbitrary value I can manually edit the value while following the format nnn.dP where P is the  unit prefix {umkMG}. I can place the first four prefixes but I cannot create a resistor with a value 1GOhm as the letter g/G is not excepted. Is there another way?

**Comment by HaraldRau** [comment]
I can not retrace the problem. I can set the value of the resistor from the package 1206 [SMD] to 1.2 G [ohm].
Which package is your resistance?

**Comment by DrItanium** [comment]
Actual issue here is that you can not do 2222G or 3.14157G
