### ISSUE TITLE
Ampersand (&) in pin label rendering incorrectly in the schematic view

### ISSUE THREAD

**Issue by IgniparousTempest** [fritzing/fritzing-app#3300]
![fritzing](https://cloud.githubusercontent.com/assets/13403691/21864145/22f0b5b4-d849-11e6-9a5e-6cd566868faf.png)

Inluding an ampersand in a pin label shows up as an HTML entity. Copy and pasting an IC with an ampersand recursively  creates the problem:

![image](https://cloud.githubusercontent.com/assets/13403691/22187564/84036d3a-e111-11e6-9315-a335537ca3cc.png)

To Reproduce:
1. Go to Schematic view
2. Place a generic IC
3. Click "Edit Pin Labels"
4. Include and ampersand in one of the lables

**Comment by failiz** [comment]
Duplicated of #2865? At least they are related.
