### ISSUE TITLE
 api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by deftman2k** [fritzing/fritzing-app#3312]
I can not start fritze because of the error below.

"api-ms-win-crt-runtime-l1-1-0.dll"  not exist.

![dll error](https://cloud.githubusercontent.com/assets/25564073/22625990/366b2024-ebe6-11e6-9dd5-699f8cb71ee0.png)

**Comment by KjellMorgenstern** [comment]
I think the issues is already fixed on the current development version of fritzing.
