### ISSUE TITLE
Gerber output file with wrong dimensions

### ISSUE THREAD

**Issue by Jose60** [fritzing/fritzing-app#3313]
I did a PCB with 80X50 mm and the GBL file have x=3108 and y=1936.
Can someone help me? My knowledge is very poor about this.
Thanks in advance.
Jose

**Comment by Amimaro** [comment]
Hi
I tried to create a 80x50mm pcb and then exported the gerber files. Try to change the unit to mm.

![screenshot from 2017-02-26 03-12-49](https://cloud.githubusercontent.com/assets/6666978/23337586/cdd6b9c8-fbd1-11e6-837f-69414c1d9e32.png)

**Comment by el-j** [comment]
so, there is no problem in the output dimensions? 
can this be closed now?

**Comment by Amimaro** [comment]
I believe so.
