### ISSUE TITLE
Wrong dimensions on Gerber output file

### ISSUE THREAD

**Issue by Jose60** [fritzing/fritzing-app#3314]
I did a PCB with 80X50 mm and the GBL file have x=3108 and y=1936.
Can someone help me? My knowledge is very poor about this.
Thanks in advance.
Jose

**Comment by VeitSanner** [comment]
Seems to be a duplicate with #3313.

Can this be removed?

**Comment by failiz** [comment]
Duplicate of #3313, which has been closed
