### ISSUE TITLE
Ending of a thick copper line in PCB view makes a bad connection

### ISSUE THREAD

**Issue by zjedi** [fritzing/fritzing-app#3316]
Create 72mils thick line and connect it to a component or a hole, it forms a bad connection: it looks like intersection of two disks, while it should be a solid fill reaching towards the center of the hole. See the attached image with red colour highlighting the missing fill.

![bad-connection](https://cloud.githubusercontent.com/assets/15914748/23101725/98e8d106-f69a-11e6-9154-9fdb629a3ce5.png)

**Comment by KjellMorgenstern** [comment]
Issue was fixed with #3379
