### ISSUE TITLE
schematic subpart text cropped

### ISSUE THREAD

**Issue by mMerlin** [fritzing/fritzing-app#3332]
The bounding box for a schematic subpart is not (correctly) determined by ALL of the child elements of the svg subpart group.  Text elements are being clipped at the top, bottom, and right of an example element in the schematic view.  The content DOES get exported to svg, **iff** some other content extends the bounding box far enough.

A work around (not fix), is to include some other invisible graphics in the subparts, to get the bounding box to include the text.  My failing sample has extra text making it easy to see the clipping.  However, if the "relay" text element is removed from the "switch" subpart, then the "8" pin label text gets clipped instead.

[SPST-D31A-Relay-clip.zip](https://github.com/fritzing/fritzing-app/files/926706/SPST-D31A-Relay-clip.zip)

Environment:
Fedora 24
x86_64
Fritzing Version 0.9.2 (b8d2d5970658f0bed09c661c9

I have not upgraded to 0.9.3, since trying to stay with what is provided in the Fedora repos.

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
