### ISSUE TITLE
Breadboard, Schematic and PCB views hangs-up (not responding)        (Version 0.9.3)

### ISSUE THREAD

**Issue by faceter** [fritzing/fritzing-app#3334]
When any activity is started in these views Ffitzing hangs up for a time eventually clearing until the next attempt at use takes place.
This is an upated installation  on a PC running Windows 10.

This makes it impossible for me (a newby to Fritzing) to progress with a project.   Your help would be appreciated.

**Comment by georgielaa** [comment]
hi i have just installed on windows 10 and i get the same issue. If you run the fritzing application with the compatibility troubleshooter and use windows 8 settings, that seems to fix the hanging issue. hope this helps you out :)

**Comment by Gerriko** [comment]
Maybe this is the issue. I had a similar problem on my Windows 10 PC but waited (very) patiently. Eventually responded to tell me there was a fritzing library update available. Maybe some part of the check for updates routine is blocking.

**Comment by KjellMorgenstern** [comment]
Are you able to run Fritzing on a machine that is disconnected from the internet?

**Comment by KjellMorgenstern** [comment]
You could try the development version of Fritzing. Please don't use for production (backup your Fritzing project before download), as it is not yet widely testet. https://github.com/fritzing/fritzing-app/releases/tag/CD-288
As the new build is done on Windows 10, and it seems no other platforms were affected, I am closing this issue. Please reopen if you still observe the issue with latest builds.
