### ISSUE TITLE
White text over light gray background on menus

### ISSUE THREAD

**Issue by pabloab** [fritzing/fritzing-app#3336]
## Ubuntu 16.04.2 LTS, Fritzing v0.9.2 from repos:
![fritz2](https://cloud.githubusercontent.com/assets/657836/25817903/2b3dd2a8-33ff-11e7-8658-bb53765de2d0.gif)

All menus of the UI on Fritzing, the row onmouseover event change font color to white, which makes very difficult to read the selected value with the default light gray background.

**Comment by KY64** [comment]
Not just there, it's also happen on all "Code Window" submenu
![fritzing](https://user-images.githubusercontent.com/31939494/30403225-ce8faa9c-990a-11e7-9728-dcf496c56f38.png)

**Comment by Oozenthor** [comment]
Happens in the Inspector/Properties drop downs as well. Looks like Fritzing does not play nice with Linux dark themes (Titlebar / backgrounds are gray instead of black like my theme is asking for).

**Comment by KjellMorgenstern** [comment]
Could not reproduce on 0.9.5d. Either this is already fixed, or I didn't find the right dark theme for this. If the issue persists, please reopen and provide desktop settings (Windowmanager, Theme...)
