### ISSUE TITLE
Pin numbering of optocoupler PC817 rotates wrong

### ISSUE THREAD

**Issue by JustAGuestWithoutMail** [fritzing/fritzing-app#3338]
When rotating PC817 Pin2 does not rotate correcly with the part.

**Comment by KjellMorgenstern** [comment]
![image](https://user-images.githubusercontent.com/6494025/60896907-73d23d00-a267-11e9-92df-5e59ca7e3bc6.png)

Result after rotating 180 degree in schematics view. Labels for Pin 1 are wrong by 180 degree.
