### ISSUE TITLE
wont load parts on start. ubuntu

### ISSUE THREAD

**Issue by jusrose** [fritzing/fritzing-app#3348]
when loading Fritzing an error report says "sorry we are having problems with the swapping mechanisms. fritzing still works, but you won't be able to change parts properties." then it says
"unable to fin the following parts
'37asdf3c843a2127a0e499f8a0b3ef6aCrystalModuleID' | at | 'resonator-3pin.fzp'
-- | -- | --
'stereo-jack-3_5mm' | at | 'stereo-jack-3_5mm.fzp'
'WireModuleID' | at | ':/resources/parts/core/wire.fzp'
'RaspIO_Duino' | at | 'RaspIO_Duino.fzp'
'alps_stec12e07_fix' | at | 'Rotary_Encoder_fix.fzp'
'AnodeLEDSuperfluxModuleID' | at | 'led_flux_blue_anode.fzp'
'8abf6496b5d466c7a1893c17a296a676' | at | 'piezo sensor.fzp'
'9f2b90fcf9c65c9bc09d570e3442069e' | at | 'solenoid.fzp'
'ADXL335_v13' | at | 'ADXL335_v13.fzp'
'100milTantalumCapacitorModuleID' | at | 'capacitor_tantalum_100mil.fzp'
'SchematicFrameModuleID' | at | ':/resources/parts/core/schematicframe.fzp'
'linino_one_rev1' | at | 'linino_one(rev1).fzp'
'd8f570d723ea4d14f9b61b34575a9699' | at | 'Power plug.fzp'
'ResistorModuleID' | at | ':/resources/parts/core/resistor.fzp'
'arduino_Yun(rev1)_v1' | at | 'arduino_Yun(rev1)_v1.fzp'
'ViaModuleID' | at | ':/resources/parts/core/via.fzp'
'CrystalModuleID' | at | 'crystal.fzp'
'SmallElectrolyticCapacitorModuleID' | at | 'capacitor_electrolytic_small.fzp'
'RevEd_FRM050' | at | ''
'a975d1270bd55d6fc3916947793f1a57' | at | 'rfid-reader.fzp'
'Netduino_plus_2' | at | 'Netduinoplus2.fzp'
'trimmer_3_1_vVariableCapacitorModuleID' | at | 'trimmer_3_1_v.fzp'
'81591c6c31ccf12f0f3ccec5f150df2d' | at | 'usbadapter_wiring.fzp'
'RevEd_24LC01' | at | ''
'NetLabelModuleID' | at | ':/resources/parts/core/netlabel.fzp'
'SparkFun_LSM303C_6_DOF_IMU_Breakout' | at | ''
'raspberry_pi_3_rev-1.2' | at | 'raspberry_pi_3_rev-1.2.fzp'
'intelEdison-HiroseDF40' | at | 'intelEdison-HiroseDF40.fzp'
'RevEd_uM_FPUv2' | at | ''
'proto_shield_v6MEGA' | at | 'proto_shield_v6MEGA.fzp'
'1001AAAB555Timer' | at | '555timer.fzp'
'1099ABDE24_ST_relay' | at | 'basic-relay.fzp'
'20A9BBEE34_ST' | at | 'pushbutton_4_horizontal.fzp'
'71d4db74a3a0ec43d9303ddffee7361b' | at | 'DIP_Relay_D31A.fzp'
'3234DBDC80leg' | at | 'servo.fzp'
'045cef49a96039c64e7363608e127209' | at | 'Dual_VNH2SP30_Motor_Driver.fzp'
'1238DBDC00-toggle-switch' | at | 'basic-toggle-switch.fzp'
'chipkit_WF32' | at | 'chipkit_WF32.fzp'
'RectanglePCBModuleID' | at | ':/resources/parts/core/rectangle_pcb.fzp'
'760832bc79fe1f34e99f420ad872a0b8' | at | 'BASIC_Stamp_2.fzp'
'1238DBDC00-voltage-reg_7805' | at | 'voltage_regulator_7805.fzp'
'a59353bd0db0225dc22770e292c622f3' | at | 'lm358.fzp'
'GroundModuleID' | at | ':/resources/parts/core/ground.fzp'
'15719464aa8d63048081b2444ea6d39c' | at | 'microSD-socket-molex-502774-0891.fzp'
'Bean_revE' | at | 'Bean_revE.fzp'
'raspberry_pi_zero_rev-1.1' | at | 'raspberry_pi_zero_rev-1.1.fzp'
'HoleModuleID' | at | ':/resources/parts/core/hole.fzp'
'a4f38a10-dd92-11dd-a3e2-001f5b3a17a4' | at | 'h-bridge.fzp'
'1001AAACOptocoupler' | at | 'optocoupler.fzp'
'intel-arduino_galileo_gen2-(simple)' | at | 'intel-arduino_galileo_gen2-simple.fzp'
'ad901601e6d29266846fc9e4568504b6' | at | 'Barometric Pressure Sensor.fzp'
'346b613c666d64fc5ac622407ace7130' | at | 'controller_mbed.fzp'
'd30f97b6fbe1asdad59ea7f0d636a7a' | at | 'controller_propeller_d40.fzp'
'PowerLabelModuleID' | at | ':/resources/parts/core/power_label.fzp'
'ti_launchpad-rev1.5' | at | 'TI Launchpad MSP430G2.fzp'
'4d1eb8f243c1aba7afe676122ea516cc_2' | at | 'Textile Pushbutton.fzp'
'udoo_dual' | at | 'udoo_dual.fzp'
'c0e65b2d0c9003507cf4a3222e995a45' | at | 'reedSwitch_500mil.fzp'
'4f6dc41d6d2f66341ea506cdaf0e797e_2' | at | 'Textile Analog Pressure Sensor.fzp'
'jlpcb-104' | at | 'jlpcb-104.fzp'
'c04a5dd707ca537800655cb3aa4b2048' | at | 'din-5_midi_connector.fzp'
'beab33bd7feee277622ef76dd6e79e4d' | at | 'infrared_proximity_sensor.fzp'
'93d4585be720f3982141f4d032f44c8e' | at | 'peltier element.fzp'
'Humidity_and_Temperature_Sensor_RHT03_6' | at | 'Humidity_and_Temperature_Sensor_RHT03.fzp'
'DC2PowerModuleID' | at | ':/resources/parts/core/dcpower2.fzp'
'M5450_LED_Driver' | at | ''
'7d0bc366bcac9395c747f3a92e2ff843leg' | at | 'stepper_motor_bipolar.fzp'
'3234DBDC00PotentiometerModuleID' | at | 'basic_poti.fzp'
'Prolight RGB 3 Watt Star' | at | 'LED_Prolight_RGB.fzp'
'BreadboardLogoTextModuleID' | at | ':/resources/parts/core/breadboardlogotext.fzp'
'1a7828b6466fac9fd042221e931124c4' | at | '74HC595.fzp'
'Copper1BlockerModuleID' | at | ':/resources/parts/core/blocker.fzp'
'Adafruit_Atmega32u4_Breakout' | at | 'Adafruit_Atmega32u4_Breakout.fzp'
'RevEd_DS1302' | at | ''
'blueIOT_Rc1-final' | at | 'blueIOT_Rc1-final.fzp'
'newLogoImageModuleID' | at | ':/resources/parts/core/newlogoimage.fzp'
'Breadboard-RSR03MB102-ModuleID' | at | 'breadboard.fzp'
'fa46ea3312d60697b8e907a5c75db23d_2' | at | 'Textile Stretch Sensor.fzp'
'PadModuleID' | at | ':/resources/parts/core/pad.fzp'
'fuse_with_handler_cff5' | at | 'Fuse_with_Handler.fzp'
'newSchematicLogoImageModuleID' | at | ':/resources/parts/core/newschematiclogoimage.fzp'
'2c9d427b475ef8d07dc752a4362af0ae' | at | 'controller_wiring.fzp'
'2244EBEC21e' | at | 'transistor_signal_PNP_TO92_EBC.fzp'
'RevEd_FRM010' | at | ''
'NPN-to92-ebc' | at | 'transistor_signal_NPN_TO92_EBC.fzp'
'c7acdd26c5e6355cb2e7e05c0aa975c0PotentiometerModuleID' | at | 'AD5206 Digital Potentiometer.fzp'
'415c9d899a1e7de6c023ea0731bab117' | at | 'microphone.fzp'
'jlpcb-089' | at | 'jlpcb-089.fzp'
'fa3e296736059e8c25d88ac262af999a' | at | 'Basic Force Sensing Resistor (FSR).fzp'
'GroundPlaneModuleID' | at | ':/resources/parts/core/groundplane.fzp'
'jlpcb-128' | at | 'jlpcb-128.fzp'
'pinoccio_board' | at | 'pinoccio.fzp'
'RulerModuleID' | at | ':/resources/parts/core/cmRuler.fzp'
'SchematicLogoTextModuleID' | at | ':/resources/parts/core/schematiclogotext.fzp'
'dquidio' | at | 'dquidio.fzp'
'DB25F' | at | 'DB25F.fzp'
'Shield_Eth06-PoE' | at | 'Shield_Eth06-PoE.fzp'
'newBreadboardLogoImageModuleID' | at | ':/resources/parts/core/newbreadboardlogoimage.fzp'
'HEF4094' | at | 'HEF4094.fzp'
'GLCD128x64' | at | 'GLCD 128x64.fzp'
'd206ca0d70364191f0b3fd30d5e53c5d' | at | 'Tilt switch.fzp'
'100milCeramicCapacitorModuleID' | at | 'capacitor_ceramic_100mil.fzp'
'NoteModuleID' | at | ':/resources/parts/core/note.fzp'
'1000ABDD10011' | at | 'basic_fsr.fzp'
'hirose-df13-2p-125h' | at | 'hirose-df13-2p-125h_42.fzp'
'20A9BBEE34_ST-2leadbutton-horizon' | at | 'pushbutton_2_horizontal.fzp'
'5e3b9f7a14a1627168e700bfc9a03b3c' | at | 'USB connector.fzp'
'LCD-GDM1602K' | at | 'lcd-GDM1602K.fzp'
'arduino_Uno_Rev3(fix)' | at | 'Arduino_UNO_R3(fix).fzp'
'LM35_THT' | at | 'lm35.fzp'
'JumperModuleID' | at | ':/resources/parts/core/jumper.fzp'
'hirose-df13-2p-125v' | at | 'hirose-df13-2p-125v_50.fzp'
'8e4b4f3e54f56b3f712afc6a8e6a8a71' | at | 'atmega168.fzp'
'RevEd_PICAXE_08' | at | 'PICAXE_08.fzp'
'5c5090e231dbe30e6bd4b9e2e7949902' | at | 'loudspeaker.fzp'
'LED_Matrix_Kingbright_TA07-11' | at | 'LED_Matrix_Kingbright_TA07-11.fzp'
'teensy_3.1' | at | 'teensy_3.1.fzp'
'Molex-Picoblade-53261-0219_smd-2p-h' | at | 'Molex-Picoblade-53261-0219_smd-2p-h_48.fzp'
'ab15a34dfcf83e23a26e83fe8a5a4dac_2' | at | 'Textile Potentiometer.fzp'
'1000AFDF10011leg' | at | 'battery-AA.fzp'
'sodaq_mbili_rev4 (4)' | at | 'sodaq_mbili_rev4 (4).fzp'
'RevEd_ULN2003A' | at | ''
'1001ABDC27' | at | 'basic_fet_p.fzp'
'7segment10an' | at | '7segment_9,9_an.fzp'
'6d07f5eae4523283f5da4171f9c54e25' | at | 'Antenna.fzp'
'WIZ820io' | at | 'WIZ820io.fzp'
'alps-starter-pot9mm' | at | 'alps-starter-pot9mm.fzp'
'SparkFun_Stepoko' | at | ''
'EDGY_motor_control' | at | 'EDGY_motor_control.fzp'
'56bed03878064b8286b71d5240035138InductorModuleID' | at | 'inductor.fzp'
'5mmColorLEDModuleID' | at | 'LED-generic-5mm.fzp'
'3b1a8578c21940dfe27253a7b57c81f5PotentiometerModuleID' | at | 'pot-slider.fzp'
'2010BBCD20113' | at | 'LDR_photocell_300mil.fzp'
'SPARKCORE_v1_fix' | at | 'SPARKCORE_v1_fix.fzp'
'c4256c251d53ee723058f86aa6d016a2' | at | 'gogoboard 4.0.fzp'
'1000FADF10011leg' | at | 'dc_motor.fzp'
'LogoTextModuleID' | at | ':/resources/parts/core/logotext.fzp'
'bareconductive_touchboard' | at | ''
'd4d5af9700923b8a114f57961f29a8a0' | at | 'led-rgb-4pin-cathode.fzp'
'3254CBFC44diode' | at | 'diode_1N4001_300mil.fzp'
'1a4bfb87a0f0fd2c59be43f3497d72e6' | at | 'xbee.fzp'
'Molex-Picoblade-53398-0271_smd-2p-v' | at | 'Molex-Picoblade-53398-0271_smd-2p-v_18.fzp'"

**Comment by KjellMorgenstern** [comment]
PR #3467 might fix this.
