### ISSUE TITLE
Ui size windows 10

### ISSUE THREAD

**Issue by 25pinjo15** [fritzing/fritzing-app#3353]
The ui is too big on high dpi display. 
Have a 10.2 inch 1920x1200 pixel and the windows scali g set to 150 ( perfect fit for everything) but fritzing is too big. Very not usable. Tryed the disable high dpi thing in the compatibility tab under propriety but nothing work

**Comment by 25pinjo15** [comment]
![capture d ecran 3](https://user-images.githubusercontent.com/23343339/30705928-dbf8b8b2-9ec4-11e7-8f74-b27a47de380f.png)

**Comment by smarbos** [comment]
Im having the same issue on Linux Mint Sarah (18)
fritzing-0.9.3b.linux.AMD64

**Comment by justusenumbers** [comment]
Had the same issue as previously described (Using laptop with Solus Budgie 3.9999). The window size went back to normal once i unplugged the external monitor and restarted Fritzing. It retains proper size even after plugging in the external monitor again. Hope this helps :)

**Comment by KjellMorgenstern** [comment]
There is an issue with detecting the right display size. I could reproduce the problem when using Solus, and switching from an 4k to an FullHD screen. Probably the my screen configuration was set to the wrong dpi in x windows, but other applications don't suffer from this. Disabling retina support in the code solved the issue, but will cause problems on retina displays.

**Comment by KjellMorgenstern** [comment]
No reports on this for 0.9.4 and 0.9.6 anymore, closing. Please open a new issue with exact information about Operating System, Screen setup and Fritzing version if you encounter this.
