### ISSUE TITLE
Windows 7: Display size of Fritzing windows incorrectly tied to text & object control panel setting

### ISSUE THREAD

**Issue by drvomact** [fritzing/fritzing-app#3363]
My vision is poor, so I have set the Windows 7 control panel entry called "Make it easier to read what's on your screen" to "Larger - 150%. This affects the icons and other text in Windows widgets to make them readable. For example, menu items and window titles are larger. However, when I have this set, the entire Fritzing window is too large to fit on my monitor. The window cannot be resized; the panes inside the window also cannot be resized. Objects inside the Fritzing window respond in unexpected ways. No other Windows application acts like this. 

The workaround is to go into the Windows Control Panel, and change the setting to "Medium - 125%". Fritzing then works correctly, but I cannot read anything else on my screen. (If I leave Fritzing.) I suggest that scaling of the Fritzing window should be more flexible--e.g. through a program option that allows me to set the scale of the Fritzing window and its subsidiary widgets.

**Comment by KjellMorgenstern** [comment]
Closing this for now, please reopen if similar issues occur with Window 10 and a recent development build (available via github releases).
