### ISSUE TITLE
Fritzing doesn't show parts

### ISSUE THREAD

**Issue by Abugbilla** [fritzing/fritzing-app#3367]
Whenever I open fritzing it doesn't give me the parts bin. Instead an error occurs. This is the error I'm talking about
![screenshot from 2017-11-17 15-24-40](https://user-images.githubusercontent.com/29587987/32954638-99c8a2d6-cbab-11e7-9634-372edbc8bacb.png)
![screenshot from 2017-11-17 15-24-45](https://user-images.githubusercontent.com/29587987/32954641-99f7db78-cbab-11e7-84f4-520e487af92d.png)
![screenshot from 2017-11-17 15-24-49](https://user-images.githubusercontent.com/29587987/32954642-9a21e80a-cbab-11e7-90f2-c176f9771f05.png)
![screenshot from 2017-11-17 15-24-54](https://user-images.githubusercontent.com/29587987/32954643-9a55d1e2-cbab-11e7-86fb-fe6f3eba0c26.png)

any attempt to update it does not work either

**Comment by sintetico82** [comment]
+1

**Comment by Intrinsically-Sublime** [comment]
Are you running the binary download from Fritzing.org? I know when you guild from source or install from a repository this can happen.

**Comment by sintetico82** [comment]
I installed it from Ubuntu repository. I will try to download the binary.

**Comment by Abugbilla** [comment]
@Intrinsically-Sublime I downloaded it from fritzing.org

**Comment by Intrinsically-Sublime** [comment]
If the parts update is interrupted during download it can corrupt the database which requires a complete reinstall. To do a reinstall you must manually delete the hidden Fritzing directory (make a backup first if you have custom parts and sketches already). Then delete the Fritzing program and redownload it. Once you have started Fritzing you may have to wait a long time while it checks for part updates and downloads them. Fritzing will be unresponsive during that time so you just have to be patient and wait until it completes.

**Comment by Abugbilla** [comment]
I did that and everything now seems to work fine. Thank you so much for your help. Much appreciated
