### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by Acuss** [fritzing/fritzing-app#3374]
Nach Installation der Fritzing Software, startet die Software nicht vollständig. Bauteiledateien lassen sich nicht öffnen

**Comment by Intrinsically-Sublime** [comment]
You need to re-install Fritzing and wait for it to update the parts database. It will become unresponsive during the update and it is important that you do not force the program closed. To re-install Fritzing you need to delete the hidden Fritzing folder.

**Comment by KjellMorgenstern** [comment]
What is a usual time for the parts update? I did not yet see it take more than a few seconds, except when running via valgrind. It would be good to know about the critical configurations that render it unresponsive.
