### ISSUE TITLE
Raspberry Pi Zero Pin spacing is wrong in PCB fiew

### ISSUE THREAD

**Issue by shanebentley** [fritzing/fritzing-app#3380]
The raspberry pi zero component has the incorrect pin spacing in PCB view.
![image](https://user-images.githubusercontent.com/2534059/34070031-680d3460-e2b1-11e7-802e-562378f3604e.png)

**Comment by vanepp** [comment]
Try this one, it was reported as correct (and the pcb spacing was one of my fixes). You are usually better off asking about parts in the forums than here as well ...

http://forum.fritzing.org/t/raspberry-pi-zero-fritzing-part/850/27

Peter

**Comment by KjellMorgenstern** [comment]
Fixed with https://github.com/fritzing/fritzing-parts/pull/127
