### ISSUE TITLE
Using parts editor to make a new part and exporting but not saving it doesn't delete the part as it should.

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3383]
To reproduce:

Clear the directories (note this will destroy all your current sketches and parts if you don't save and 
restore these two directories!) 

F:\Fritzing\My Documents\fritzing\
F:\Fritzing\AppData\Roaming\fritzing

(use the appropriate names for your system)
for a clean start
start fritzing
drag generic ic to breadboard view
edit part in parts editor and save as new part
creates 
prefix0000_d290581c8ba0365c66bddd27b5ec9988_1.fzp in 
F:\Fritzing\My Documents\fritzing\parts\user
and
prefix0000_d290581c8ba0365c66bddd27b5ec9988_0_breadboard.svg
prefix0000_d290581c8ba0365c66bddd27b5ec9988_1_breadboard.svg
in F:\Fritzing\My Documents\fritzing\parts\svg\user\breadboard icon schematic and pcb
creates new part in mine parts bin
close parts editor
right click on the new part in mine parts bin and export part
removes prefix0000_d290581c8ba0365c66bddd27b5ec9988_0_breadboard.svg 
leaving prefix0000_d290581c8ba0365c66bddd27b5ec9988_1_breadboard.svg
and 
prefix0000_d290581c8ba0365c66bddd27b5ec9988_1.fzp
close fritzing 
answer "Don't save" to save sketch
answer "Don't save" to save changes in my parts bin
Fritzing exits 
However prefix0000_d290581c8ba0365c66bddd27b5ec9988_1.fzp
is still in F:\Fritzing\My Documents\fritzing\parts\user
and trying to load the exported part gets a 
there is already a part prefix0000_d290581c8ba0365c66bddd27b5ec9988_1 loaded in to fritzing. Requiring you to either delete that file or clear the user directory to be able to load the new part because the fzp and svgs for the editted part have in fact not been deleted from the mine parts bin although  they also don't show up in the mine parts bin in Fritzing which shows as empty. 

Fix: don't know yet haven't gotten that far but finding out why it doesn't delete those files seems the likely solution. I'll poke at this more as I get time, but if someone familiar with the code wants to make a fix that would be wonderful.

**Comment by KjellMorgenstern** [comment]
This should be fixed by PR #3482
