### ISSUE TITLE
Installation issue on windows 7

### ISSUE THREAD

**Issue by mshane87** [fritzing/fritzing-app#3385]
Fritzing 0.9.3b version does not install on windows 7. Says "The program can't start because api-ms-win-crt-runtime-|1-1-0.dll missing from your computer. Try reinstalling the program to fix this problem" . 
Reinstalled many times and downloaded many times but problem not solved. Please help.

**Comment by Intrinsically-Sublime** [comment]
See this thread http://forum.fritzing.org/t/api-ms-win-crt-runtime-l1-1-0-dll-fix/1636 in the Fritzing forum. It has the solution and multiple ways of achieving it.

**Comment by mshane87** [comment]
Thanks Intrinsically-Sublime
