### ISSUE TITLE
Provide hashsums for releases

### ISSUE THREAD

**Issue by 0xBADCA7** [fritzing/fritzing-app#3402]
Right now there's no safe way of downloading a binary release. Please provide:

- Binary release hashsums (sha256 or even sha512)
- Opportunistically, GPG-sign the releases
- Set up a TLS server on fritzing.org b/c downloads are via HTTP and no hashsums or signatures to be found whether here on GH or on the home page.

**Comment by 0xBADCA7** [comment]
Partially includes #3393

**Comment by advayDev1** [comment]
A few more security requests:
* For the macOS downloads, please use App Signing.  (Also let's the user confidently enable firewall permissions for this app to download parts) 
* Provide the download releases directly via the GitHub release mechanism (at least then the user knows the download is coming securely from GH)

**Comment by KjellMorgenstern** [comment]
Problem with this ticket is that it contains multiple feature requests at once. Setting the focus to hashsums.
