### ISSUE TITLE
Windows 10 -- cannot update parts

### ISSUE THREAD

**Issue by pandelirium** [fritzing/fritzing-app#3405]
Using Fritzing 0.9.3b -- when I select "Check for updates" from the help menu I get the following error:

Fritzing is unable to check for-- and update-- new parts.
If you want this functionality, please enable write permission on this folder:
'C:\Program Files\Fritzing\fritzing-parts'.

I have enabled write permissions and even made sure that C:\Program Files\Fritzing and all its subfolders are not read-only, but the error persists.

**Comment by installfails** [comment]
May be related to #3411

**Comment by KjellMorgenstern** [comment]
PR #3467 might fix this.

**Comment by KjellMorgenstern** [comment]
In case this is still an issue, please try with 0.9.4, as this might be fixed there.
