### ISSUE TITLE
Parts Editor will not load

### ISSUE THREAD

**Issue by CodeZone8** [fritzing/fritzing-app#3407]
On version 0.9.3 (b5c895d327c44a3114e5fcc9d8260daf0) it crashes while loading the parts editor.
It will not load for any part. It says "unable to write svg to breadboard/ 
followed by the name of the file it is trying to write to.

On version 0.9.2 it works fine. No issues at all.

![partseditor](https://user-images.githubusercontent.com/24237608/39101002-66a0675a-4661-11e8-8f44-f3df40e04788.png)

**Comment by KjellMorgenstern** [comment]
In general, the parts editor loads. Maybe the directory you stored the parts in is not writable?
![editor](https://user-images.githubusercontent.com/6494025/57451673-41559500-7262-11e9-8bab-e0234f47a349.png)
