### ISSUE TITLE
Part Search and Mine Parts Collection Area missing

### ISSUE THREAD

**Issue by pekwalker** [fritzing/fritzing-app#3409]
I am using Windows 10 Version 1803 OS Build 17134.81. I am a Windows Insider Build Tester so this may be outside of what you all may be able to address. I am running Fritzing version Version 0.9.3 (b5c895d327c44a3114e5fcc9d8260daf0cbb52806 2016-04-1. I have ran Check for Upgrades via the Help Menu as well as Regenerate Parts Database via the Part Menu. I am unable to see the Search area or the Mine parts collection so I can add my own custom parts.

**Comment by Awaz41** [comment]
same problem here, and i've done exactly what you did (check for updates and regenerate parts)

**Comment by failiz** [comment]
Duplicate of #3270?

**Comment by KjellMorgenstern** [comment]
Closing in favor of #3270 .
