### ISSUE TITLE
Flatpak in Flathub

### ISSUE THREAD

**Issue by Peque** [fritzing/fritzing-app#3410]
Have you considered distributing the Linux application through [Flathub](https://flathub.org/)? In [Flatpak](https://www.flatpak.org/) format, which can be easily installed in all distributions.

**Comment by q2dg** [comment]
It seems this project is pretty dead. What a pity

**Comment by wraybowling** [comment]
Issue belonged to another repository. This can be closed.

For what it's worth, Fritzing was added to Flathub. https://flathub.org/apps/details/org.fritzing.Fritzing

**Comment by failiz** [comment]
It has already been added to go Flatpak. Least close this issue.
