### ISSUE TITLE
swapping failure

### ISSUE THREAD

**Issue by installfails** [fritzing/fritzing-app#3411]
Swapping failure notice on opening the application.  Cannot load parts libraries.
THIS IS AN APPLICATION KILLER!

**Comment by installfails** [comment]
This appears to be a problem in Debian Linux and related Linux distros if using Synaptic to install fritzing.  Due to dependency errors the fritzing-parts library is not being downloaded and installed.  
A work-around is to manually download fritzing-parts from your favorite repository and re-run the install process.  Not many will know how to do this, but it did work for me.

**Comment by KjellMorgenstern** [comment]
PR #3467 might fix this.

**Comment by KjellMorgenstern** [comment]
In case you encounter this via synaptic or other installers, please try the official release 0.9.4 available from https:/fritzing.org .
