### ISSUE TITLE
breadboard components block too many holes and will not flip

### ISSUE THREAD

**Issue by BruceHesher** [fritzing/fritzing-app#3413]
Many component types, transistors, capacitors, etc, need to be shown from directly above so they do not block placement of other components.  Also, components like caps need to be able to be flipped, vertical and horizontal, not just rotated.

**Comment by KjellMorgenstern** [comment]
The flip button is next to the rotate button. Some parts are available as top-view (they don't require flipping in this perspective, and are only rotatable). If you miss parts, you are free to contribute. Please use the forum if you need support.

![screenshot](https://user-images.githubusercontent.com/6494025/57411122-f0f02000-71ec-11e9-831a-6117f14c2719.png)
