### ISSUE TITLE
set board size mixing up wires :D

### ISSUE THREAD

**Issue by virus12** [fritzing/fritzing-app#3414]
when i try to change size of board.

![img1](https://user-images.githubusercontent.com/4078336/41870625-d7ce20c4-78bc-11e8-9b9b-09f18c626b27.PNG)

![img2](https://user-images.githubusercontent.com/4078336/41870633-db491772-78bc-11e8-99e3-63c1bb60a004.PNG)

![img3](https://user-images.githubusercontent.com/4078336/41870638-dd8425a4-78bc-11e8-9f32-f8466e7ae6f5.PNG)

![img4](https://user-images.githubusercontent.com/4078336/41870645-e03cf852-78bc-11e8-8f2a-6941ceb591be.PNG)

🤣

**Comment by KjellMorgenstern** [comment]
Good one :-) Interestingly, parts stay in place.

**Comment by KjellMorgenstern** [comment]
Seems this only happens if decreasing the board size.
