### ISSUE TITLE
Not Responding when launching or updating/cleaning files

### ISSUE THREAD

**Issue by DarkWorld25** [fritzing/fritzing-app#3416]
Just downloaded Fritzing, and on launch it will freeze, displaying not responding, and same when updating. It would get to a place and would just freeze. It's not crashing, so it's nothing program breaking, but its annoying to see it being shown as not responding.

**Comment by undefinedLogic** [comment]
I was having the same problem, where I would open Fritzing, and then it will proceed to crash and I have to close it. I fixed it by changing it's compatibility to Windows 8, and I had to wait a while for some updates to happen, but it ended up working.

**Comment by KjellMorgenstern** [comment]
Looks like an issue with the parts db, but hard to tell. The two problems described might even not be related, not enough details. We are working on more robust parts updating and loading. Closing this for now.
