### ISSUE TITLE
Signing up

### ISSUE THREAD

**Issue by marwanj** [fritzing/fritzing-app#3417]
Recaptcha needs to be updated to allow users to sign up to the fritzing website.

**Comment by undefinedLogic** [comment]
So apparently this is a problem, I thought it was just one of those things that lasts a day or so.

**Comment by lycoch** [comment]
:+1: 

please fix your captcha on http://fritzing.org/account/signup/

we cannot subscribe for asking help on your forum ...

**Comment by ulitiy** [comment]
Apparently it's not that important if they can get new users ever...

**Comment by lycoch** [comment]
it looks like the project is dead
even if we contact them by email, no answer so far

**Comment by HernanA4Q** [comment]
It's a problem since months.

**Comment by KjellMorgenstern** [comment]
The capture has been repaired, sign up and login should be possible.
