### ISSUE TITLE
Problem with swapping mechanism and can't find parts

### ISSUE THREAD

**Issue by jwmurphyjr** [fritzing/fritzing-app#3419]
Upon starting program in Debian 9.5 Stretch AMD 64 bit with fritzing & fritzing-data 0.9.3b+dfsg-4 & fritzing-parts 0.9.3b-1 installed ,  I get this error

![screenshot from 2018-08-24 07-17-11](https://user-images.githubusercontent.com/42672583/44582135-900fdd00-a76e-11e8-8bfe-8052d13ab4b2.png)

also, can't read file screw_terminal_2_3.5mm.fzp
![screenshot from 2018-08-24 07-17-26](https://user-images.githubusercontent.com/42672583/44582499-cf8af900-a76f-11e8-832b-8b603dc40cb2.png)

and unable to find following parts
![screenshot from 2018-08-24 07-16-43](https://user-images.githubusercontent.com/42672583/44582222-d82eff80-a76e-11e8-9b60-4037153445c6.png)

**Comment by jwmurphyjr** [comment]
The program loads after these errors

**Comment by jwmurphyjr** [comment]
Just found issue problem, fritzinf-parts folder is now being created when installing through Synaptic Package Manager and Debian repository. Work around is to download program fritzing-0.9.3b.linux.AMD64.tar.bz2 package from http://fritzing.org/download/ uncompressed and copy the fritzing-parts folder to /usr/share folder and the errors go away

**Comment by ngvjai** [comment]
@jwmurphyjr  Thank you for your sharing. I solved this problem with your method.

**Comment by abbyjgeorge** [comment]
@jwmurphyjr Thanks, that worked!

**Comment by KjellMorgenstern** [comment]
PR #3467 might fix this.

**Comment by akai54** [comment]
Hello i had the same probleme on kali linux so i just compressed the folder from fritzing website then copied the folder "fritzing-parts" to /usr/share/fritzing it solved the probleme.
