### ISSUE TITLE
Fritzing forum signup captcha broken

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3423]
While not a frizting-app flaw, I'm hoping the Fritzing web admin reads these (or someone who does will pass this on to them). The captcha on the fritzing forum signup web page at http://fritzing.org/account/signup/  has gone out of service and thus no new folks can sign up to use the forums. The error message is:

reCAPTCHA V1 IS SHUTDOWN

Direct site owneres to g.co/recaptcha/upgrade

which indicates the web admin needs to register a new key (and I guess possibly change something else as well). 

Peter

**Comment by KjellMorgenstern** [comment]
This issue is closed because it is outdated/solved.
If you think this issue is still important, please reopen.
