### ISSUE TITLE
Generic IC is destroyed displayed in Schaltplan view

### ISSUE THREAD

**Issue by pinout65** [fritzing/fritzing-app#3429]
Hello,
![genericic](https://user-images.githubusercontent.com/45591844/49435165-3c258300-f7b6-11e8-80db-c995537c478d.JPG)

after some changes in view Schaltplan and Leiterplatte the Generic IC is destroyed displayed in Schaltplan view. The 8pin IC-body is displayed at different place as the pin numbering ...

take care - fritzing is great ...

**Comment by KjellMorgenstern** [comment]
This issue was closed due to missing information.
If you think this issue is still important, please provide additional information.
  - Which version of Fritzing have you been using? (0.9.3b?)
  - Which steps reproduce the problem?

**Comment by KjellMorgenstern** [comment]
Note: I tried a few minutes some editing in schematic and pcb view with a generic ic, but did not stumble upon this issue. Did you use the autorouter?
