### ISSUE TITLE
source code for fritzing java version (first release)

### ISSUE THREAD

**Issue by fcampos** [fritzing/fritzing-app#3432]
Hello,
As i understand, the first Fritzing release was coded in java. Does anyone as the source code for it? I would like to integrate a breadboard view in a java circuit simulator and that might be a starting point. Many thanks.

**Comment by KingDarBoja** [comment]
There is no official source code as far as I know on Java. Sorry for the late response but we are currently trying to reactivate the Fritzing Development through Javascript code.

Cheers!
