### ISSUE TITLE
Diode Terminal numbering error in schematic

### ISSUE THREAD

**Issue by godwinhr** [fritzing/fritzing-app#3433]
When rotated the diode terminal numbering 1 and 2 remain on the same terminal.
![screenshot from 2019-01-03 12-12-10](https://user-images.githubusercontent.com/46338920/50625957-728b2500-0f51-11e9-8165-e6d86472a04f.png)

**Comment by HaraldRau** [comment]
Hello, can you load the Sketch here by filname.zip? I can not reproduce the problem in my environment!

**Comment by godwinhr** [comment]
Hi, Please find attached the schematic.

Thanks,
Godwin



*"**If you have the desire and passion to do something, and it’s*

*within God’s will, you will achieve it**"*

**Comment by KjellMorgenstern** [comment]
It seems attaching the file via email did not work?

**Comment by godwinhr** [comment]
[Rectifier Schematic.zip](https://github.com/fritzing/fritzing-app/files/3414522/Rectifier.Schematic.zip)

**Comment by KjellMorgenstern** [comment]
Using Fritzing g2e7bc9f5 , I rotated the Diode D1 multiple times. The result seems correct to me. Is this what you expected? 
![image](https://user-images.githubusercontent.com/6494025/66697937-2805b880-ecda-11e9-9587-eb73fa6bb94e.png)
![image](https://user-images.githubusercontent.com/6494025/66697943-3b188880-ecda-11e9-8e55-2b1141154c23.png)
![image](https://user-images.githubusercontent.com/6494025/66697955-4a97d180-ecda-11e9-86f1-0f30e65120be.png)
![image](https://user-images.githubusercontent.com/6494025/66697963-68653680-ecda-11e9-9360-b0ec16163e7c.png)

**Comment by KjellMorgenstern** [comment]
Closing as probably fixed / can not reproduce.
