### ISSUE TITLE
CLI option for PDF output

### ISSUE THREAD

**Issue by nikeee** [fritzing/fritzing-app#3436]
There already is a cli option called `-svg` which converts all `.fzz` files in a certain directory to `svg` files. 

Due to #1252, I am in the need of a `-pdf` option. Any chances on getting this?

**Comment by KjellMorgenstern** [comment]
Thanks for bringing some attention to #1252 and confirming it for 0.9.3.
Adding such an option is currently not in scope, but it would make perfect sense to fix the original issue of disappearing parts. If you have a reliable way to reproduce this (files, cli calls or step by step instructions) that would be of great help. Please comment on #1252.
