### ISSUE TITLE
local file storage

### ISSUE THREAD

**Issue by CarminKern** [fritzing/fritzing-app#3439]
How can I Change local file storage for fritzing?

**Comment by HaraldRau** [comment]
Do you mean the Storage for the parts? ../fritzing/fritzing-parts/

Which Storage do you want to include? Your local store in C\: or a Git-Repository?

**Comment by CarminKern** [comment]
I mean 
 C:\Documents and Settings\[user name]\Application Data\Fritzing\.

**Comment by HaraldRau** [comment]
Sorry, I do not know, how to change the part storage.

**Comment by vanepp** [comment]
Depends on how you want to change it. The path is hard coded in to the source, so you need to compile from source to make name changes. You can change where it is stored by using symlinks to change which disk the directories will be written to (I used to do that to get them of the Windows system disk) but that is about all without source level changes.

Peter

**Comment by KjellMorgenstern** [comment]
Fritzing part folder structure is discussed in #3454
