### ISSUE TITLE
identical condition

### ISSUE THREAD

**Issue by maddin200** [fritzing/fritzing-app#3451]
[/src/items/resizableboard.cpp: line 400
silk1Layers == 0

**Comment by vanepp** [comment]
I expect one of them should in fact be silk0Layers. We are likely to find that silk0Layers should be the bottom silk and silk1Layers should be the top silk (or visa versa). since silk0Layers is defined and incremented in /src/items/resizableboard.cpp

Peter

**Comment by KjellMorgenstern** [comment]
Added PR #3461 for this
