### ISSUE TITLE
Make sure to use release version of libgit2

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#3466]
In the develop and fix-windows-ci branches, we automatically build the libgit2 on travis and appveyor.
Unexpectedly, git2.dll ends up in build64/Debug folder. Thus, we build a debug version, which we don't need, plus, our scripts are confused about where to find the dll.

Solution might be to add `--config release`
See also
https://stackoverflow.com/questions/49417434/libgit2-is-not-building-in-release-mode-on-windows

**Comment by KjellMorgenstern** [comment]
This should also solve https://github.com/fritzing/fritzing-app/issues/3268

**Comment by ovidiub13** [comment]
Indeed `cmake --build .` when used on Windows with Visual Studio uses the `Debug` target by default and ignores the `CMAKE_BUILD_TYPE` value. It's something to do with how Visual Studio works. I've hit this in the past, and #3473 is the only fix for it.

**Comment by ovidiub13** [comment]
#3268 needs a documentation update, and we plan to do that after we streamline the build process. IMO we can close #3268 and open a new ticket to "don't forget" to update the build docs.
