### ISSUE TITLE
Many pages of the website are still unavailable

### ISSUE THREAD

**Issue by IvanDelsinne** [fritzing/fritzing-app#3481]
Following #2904, I noticed that many pages are still unavailable, especially the homepage ([`http://fritzing.org/`](http://fritzing.org/)).

![Annotation 2019-05-19 192613](https://user-images.githubusercontent.com/23583792/57985691-fe6a9d00-7a6b-11e9-9ecb-2185ecbcd1b4.jpg)

**Comment by bladykast** [comment]
#3418 From what I can tell, this project is dead.

https://hackaday.com/2019/02/14/the-future-of-fritzing-is-murky-at-best/

I can't even access the cached fritzing downloads on Google.

**Comment by KjellMorgenstern** [comment]
We know about the server problems, it’s to old to withstand noise from the internet. 
Please take part in #3443 if you want to discuss future steps.

**Comment by KjellMorgenstern** [comment]
Server was rebooted and is kicking again. Migration is not straightforward, so it needs to hold up a little bit longer.
