### ISSUE TITLE
Rename phoenix.pro to fritzing.pro

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#3507]
Pro
- clear and expected name for the project file makes it a bit easier for new developers

Contra
- breaks existing build environments and development setups

**Comment by Phikimon** [comment]
Does the following commit actually break build environments? Apart from renaming these files it also fixes references to them in build files, isn't it?
https://github.com/fritzing/fritzing-app/pull/3502/commits/af8d6bd6df7451f53bf4c99dcb144c6089dfafde

**Comment by Phikimon** [comment]
However, this is issue seems to be irrelevant concerning #3504  resolved.

**Comment by KjellMorgenstern** [comment]
We won't rename the file for now.
