### ISSUE TITLE
Missing "autoroute"

### ISSUE THREAD

**Issue by WimberleyTech** [fritzing/fritzing-app#3508]
Ï downloaded and ran fritzing-872b5cd4954c9ab41ebe977296eaba35d46734e2-debug-continuous-268.64.pc.  "Autoroute" is missing.

**Comment by KjellMorgenstern** [comment]
Yes, that is intended. The autorouter in its current state was happily writing outside of array bounds. Depending on what memory regions it overwrites, Fritzing would crash sooner or later.

PR #3480 removes the autorouter
PR #3489 is a start to fixing it, by using QVector instead of malloc.

**Comment by KjellMorgenstern** [comment]
A slightly more stable autorouter was re-added.
