### ISSUE TITLE
Subscribing to Fritzing forum is not possible

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#3522]
## Current Behaviour
Fritzing forum signup is not possible

**Steps to reproduce:**
Signup with a new email.
Fritzing forum will tell you to activate via the confirmation email.
- Email does never arrive
- When trying to log in, error message "This account is currently inactive" is shown.

## Expected Behaviour
Email should be sent so the account can be activated.

**Comment by KjellMorgenstern** [comment]
Looking into the database shows that on 2019-07-17, about 4242 accounts had been registered to fritzing.org . To me this looks like someone tricked the signup captacha, and created a kind of DoS for the signup.  For more recent subscriptions, no mail has been sent (yet).

**Comment by KjellMorgenstern** [comment]
There was an error in the DKIM settings, which would explain emails delivered (or better: accepted by other servers) slow or not at all. This is corrected now, fingers crossed it was the only issue.

**Comment by KjellMorgenstern** [comment]
Despite the DKIM fix and successful Mandrill check, emails are still not delivered five days later. Checking again...

**Comment by KjellMorgenstern** [comment]
After learning a lot about the history of Mandrill (and Mailchimp), I think the root cause was that Mailchimp had changed their tariffs in May/June. 
As Mailchimp is overkill for managing a forum, I switched to Mailgun. Main reason to use mailgun: They had good documentation for using a similar smpt configuration, so no code changes on the fritzing.org server needed. 

Signup and Password changes should work again.

**Comment by KjellMorgenstern** [comment]
Just for the records: I have extracted all the accounts that have been created since the email service stopped, and are know sending those mails via a script. There is some careful delay, so it will take some days until all mails are sent (many thousand registrations). Especially if you have a Yahoo account, please check your spamfilter, I see quite some bounces from there.

**Comment by imWACC0** [comment]
Ok, I guess you have to fail a password recovery to join?

I can't find a create account link.
