### ISSUE TITLE
Building with windows does not work (wiki)

### ISSUE THREAD

**Issue by GottfriedSp** [fritzing/fritzing-app#3523]
>c:\Qt\5.6.3\msvc2015\bin\qmake.exe -t vcapp phoenix.pro
Info: creating cache file E:\fritzing-app\.qmake.cache
Project MESSAGE: target arch: x86
Project MESSAGE: Fritzing requires libgit2
Project MESSAGE: Build it from the repo at https://github.com/libgit2
Project MESSAGE: See https://github.com/fritzing/fritzing-app/wiki for details.
Project ERROR: libgit2 include path not found in E:/fritzing-app/../libgit2/include

Windows 7

**Comment by vanepp** [comment]
You need to install both boost and libgit2 before trying the build. From the error message there is something wrong in your libgit2 install (it isn't particularly easy on Windows). 

Peter

**Comment by KjellMorgenstern** [comment]
@GottfriedSp  I updated the wiki page you referred to. Compiling boost is not required, as we currently only use boost header libraries. So, what the error message is saying: Just extract boost next to your fritzing source directory, and it should be fine. In theory, it should also find a boost system installation, but this is currently untested.

**Comment by GottfriedSp** [comment]
This is great!
Ok, i try it again, thank you!

**Comment by vanepp** [comment]
Sorry, because I didn't see the boost error message I assumed you had boost. I didn't know we are only using the headers! I usually copy in the precompiled Windows binaries available on the boost site to fritzing-app/src/lib/boost1.xxx . That is much easier than compiling boost. 

Peter

**Comment by KjellMorgenstern** [comment]
Did it work?

**Comment by Splarkszter** [comment]
> Just extract boost next to your fritzing source directory

I was struggling for like 2 hours so far, I had interpreted `so, the same folder as fritzing-app` from the "install dependencies" instructions as *inside* the `fritzing-app` folder now that I see it, it was a misunderstanding from me. I feel so dumb.

The **next to ... source directory** made me understand it. Lol
