### ISSUE TITLE
Arch package build

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [fritzing/fritzing-app#3524]
## Problem
Would be nice if you could provide also an package for arch based distributions

**Comment by alexws54tk** [comment]
Use [AUR package](https://aur.archlinux.org/packages/fritzing/), bro.

**Comment by DanielMazurkiewicz** [comment]
@alexws54tk I have no idea how did I miss this one :-) Was searching for it, but guess I've misspelled something... Anyway, THX!!!! :-D
