### ISSUE TITLE
Unmet dependencies on Ubuntu 19.04

### ISSUE THREAD

**Issue by marcin-jozwikowski** [fritzing/fritzing-app#3529]
## Current Behaviour
App won't start throwing following errors:
* error while loading shared libraries: libssl.so.1.0.0
* error while loading shared libraries: libQt5SerialPort.so.5
libssl.so.1.0.0 can't be installed - it was dropped from Ubuntu repos. Tried symlinking newer libssl to so.1.0.0 but just got version mismatch error instead.

**Build:**
Version 0.9.4 prerelease (32ab1e863c633bbd6bd926dfcc51f14b9b9d50e6-debug-continuous-346.xenial.linux.AMD64.tar.bz2) 

**Operating System:**
Lubuntu 19.04 (Ubuntu based with LXQt) - freshly installed 

**Steps to reproduce:**
- Download 0.9.4 prerelease binary
- Run install.sh
- Run binary

## Expected Behaviour
Running app.

## Workaround
There is a workaround for this problem but I wouldn't rely on it for too long - you can simply download and install unsupported libssl and install libqtserialport. Run following commands:
- wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6.2_amd64.deb
- wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6.2_i386.deb
- sudo dpkg -i ./libssl*.deb
- sudo apt install libqt5serialport5

**Comment by KjellMorgenstern** [comment]
It is written down in the release notes:

A continuous delivery has been set up for the following targets:

Fedora 30
Ubuntu Bionic
MacOS 14
MacOS 13
Windows 10
Ubuntu Xenial

However you might have more luck trying the Bionic binary on Disco.
