### ISSUE TITLE
Invalid text color for Notes under macOS

### ISSUE THREAD

**Issue by andrivet** [fritzing/fritzing-app#3530]
## Current Behaviour
Under macOS (Mojave, 10.14.6), the color of the text in Notes is white (was black in previous version of Fritzing) and thus hard to read. When you select the text, the background (of the text only) becomes black.

Something that may be important: I am using Dark Mode under macOS.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/981049/65372829-447f7980-dc75-11e9-8563-22ec4070bb1e.png">

**Build:**
Version 0.9.4 (b872b5cd 2019-07-05) Cocoa [Qt 5.12.2]

**Operating System:**
macOS (Mojave, 10.14.6)

**Steps to reproduce:**
- Create a note
- The text color is white
- Select the text
- The background of the text becomes black

## Expected Behaviour
- The text has to be dark with a transparent background

**Comment by 2E0PGS** [comment]
I have a similair issue under Linux. I suspect it's trying to follow my system themeing.

![image](https://user-images.githubusercontent.com/15659301/73122598-be56a500-3f7e-11ea-98c2-256cfdf12a8d.png)

**Comment by KjellMorgenstern** [comment]
@2E0PGS Which theme are you using? Or is it a custom one?

**Comment by KjellMorgenstern** [comment]
Related to #3336
