### ISSUE TITLE
No Windows 10 builds available from latest release

### ISSUE THREAD

**Issue by blobkat** [fritzing/fritzing-app#3550]
Hello, I see that there's CI set up for Windows, however I don't see any Fritzing 0.9.4 binaries for Windows to download anywhere?

It was uploaded to S3 :)
s3://fritzing/415/fritzing-8f47c89054fdb85a098e2c2253e3e37573618628-master-415.windows.64.zip

**Comment by KjellMorgenstern** [comment]
To give a bit more detail:
* The Windows build needed manual afterworks (Windows choked on the long file names, partially unzipped, and then Fritzing simply crashed after the user ignored the warning about not extracting all files... way to get in lots of support requests)
* To minimize the potential risk, I release to a smaller group first. Sorry Linux people for making you guinea pigs. 
* Some further obstacles just vanished, maybe I can finish it today. But I thought that now three days in a row :-)

**Comment by blobkat** [comment]
OK! Superb, no worries, I'm just excited that the Fritzing project is alive again :) Thank you for all the good work you're doing.
