### ISSUE TITLE
Crash when editing connector highlight colors

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#3566]
## Current Behaviour

Segfault when editing colors.
**Build:**
Development branch 0.9.5  (44c26079)

**Operating System:**
At least Ubuntu 19.04, probably all

**Steps to reproduce:**
- Start Fritzing, don' load any project or any parts
- Go to Edit -> Preferences
- Change connected or no connected highlight color
- Confirm

This crash does not occur if any parts are already in the project. This
is also a simple workaround.

## Expected Behaviour
Settings are stored, colors look as expected as soon as parts are added to the schematics view.

**Comment by failiz** [comment]
Yes, I can reproduce it on Windows (0.9.4)
