### ISSUE TITLE
The cost of Fritzing

### ISSUE THREAD

**Issue by OMGdaDPS** [fritzing/fritzing-app#3571]
So, after using the amazing Fritzing program for a while now (for free) on Ubuntu, I decided to use one of my Windows based rigs (as Linux doesn't support Visuino yet) and install Fritzing. Well, I get to the download page and it seems that Fritzing is no longer free. Or at least I cannot find a buttoning which to download the legendary product, that doesn't have a price on it. 
   Is this something that has just recently happened? Or am I experiencing a bug of some sort?

**Comment by KjellMorgenstern** [comment]
Duplicate: #3548

**Comment by xgqfrms** [comment]
# open source, but not free
