### ISSUE TITLE
Support CTRL-F for searching a component

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3582]
## Problem
Many times I am searching for a component I use CTRL-F but the shortcut is not supported in windows.

## Proposed Solution
Add shortcut for searching a component

**Comment by KjellMorgenstern** [comment]
CTRL-S is a typo?

**Comment by NilsRo** [comment]
Yep. CTRL-F. ;-)

**Comment by janclod** [comment]
@NilsRo do you mean a shortcut to "Find part in sketch" from the menu "Part"? Or a shortcut to find a part from the "Search" tab inside the "Parts" dock (usually right side of the window)?

**Comment by NilsRo** [comment]
> @NilsRo do you mean a shortcut to "Find part in sketch" from the menu "Part"? Or a shortcut to find a part from the "Search" tab inside the "Parts" dock (usually right side of the window)?

"Find part in sketch". I have a complex circuit and it would made it faster to work with it searching for the component on the circuit.

**Comment by KjellMorgenstern** [comment]
Indeed, I missed setting the milestone.
