### ISSUE TITLE
Unreadable results in Search pane - white text on light gray

### ISSUE THREAD

**Issue by justinclift** [fritzing/fritzing-app#3600]
## Current Behaviour

Unfortunately, the results in the Search pane are unreadable.  White text on light gray seems an unfortunate choice.  And seems to be hard coded (?). :frowning: 

![Fritzing-unreadable-search-results](https://user-images.githubusercontent.com/406299/73515990-450df500-444b-11ea-8eaf-44ea1a65874f.png)

**Build:**
```
$ rpm -qa|grep -i fritzing
fritzing-parts-0.9.3b-lp151.2.1.noarch
fritzing-0.9.3b-lp151.3.5.x86_64
```
Ironically, guessing there's supposed to be text visible here (?):

![Fritzing-about-dialog](https://user-images.githubusercontent.com/406299/73516012-52c37a80-444b-11ea-9526-9eef3965c7e4.png)

**Operating System:**

SUSE OpenLeap 15.1 x64.

**Steps to reproduce:**
1. Start Fritzing.
2. In the "Search" pane, type in text to search for.  The problem is apparent here.

## Expected Behaviour

Results that are readable.  eg Aren't white text on light gray

**Comment by justinclift** [comment]
Possibly related to #3336

**Comment by justinclift** [comment]
As a workaround, setting my system desktop theme to be `Breeze` instead of `Breeze Dark` (then restarting Fritzing) allows the results to be readable.  eg black text on light gray.

If the background colour is hard coded to light gray, perhaps hard coding the text colour for the results pane would be the correct fix?

**Comment by justinclift** [comment]
Thanks @KjellMorgenstern. :smile:

**Comment by Flavelius** [comment]
in 0.9.10 there still seem to be places where it doesn't match (white on grey):
![grafik](https://github.com/fritzing/fritzing-app/assets/8841352/ca1236ca-8b9b-4667-9df6-d282dfbd9ce0)
Kubuntu 23.04, Plasma-style 'Wings Dark Plasma', application style 'Fluent round dark solid', color set 'Breeze Dracula'
