### ISSUE TITLE
FR: Replace component

### ISSUE THREAD

**Issue by daxliniere** [fritzing/fritzing-app#3604]
If a component has the same pinout and size, you should be able to replace that component with another. This would preserve all wiring and save some time.

For example, replacing a rectifier diode with a zener diode.

Thank you for reading. :)

**Comment by KjellMorgenstern** [comment]
Use delete minus to remove the rectifier diode, add the zener diode and reconnect the loose wires.

In case of the rectifier diode, you can also simply modify the diode to be a zender diode via the Inspector menu.

**Comment by KjellMorgenstern** [comment]
![delete](https://user-images.githubusercontent.com/6494025/74048471-8d409080-49d2-11ea-8658-01430069f42d.gif)

**Comment by daxliniere** [comment]
"...and reconnect the loose wires."
That's the bit I didn't want to have to do. I'm thinking about 16 pin ICs, etc, but from your animation, it looks like it'll automatically connect. I haven't seen that behaviour so far. Does it work in the schematic view? Perhaps that's my real feature request, then.
