### ISSUE TITLE
Enlarging stripboard creates all-joined holes instead of strips

### ISSUE THREAD

**Issue by daxliniere** [fritzing/fritzing-app#3605]
## Current Behaviour
When you enlarge a stripboard (increase rows/columns), all of the newly created holes are joined (into a giant land) instead of creating horizontal/vertical strips.
This is kinda useless as it means you need to manually unlink all the horizontal holes.

**Build:**
Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
Windows 10

**Comment by KjellMorgenstern** [comment]
Could that be related to #3090 ?

**Comment by daxliniere** [comment]
Yes, correct Kjell. Confirmed duplicate of #3090
