### ISSUE TITLE
Two parts connected via breadboard don't route

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3616]
## Current Behaviour

Connecting two parts to each other via the breadboard does not route correctly.

[Two-parts-via-breadboard.fzz.zip](https://github.com/fritzing/fritzing-app/files/4172288/Two-parts-via-breadboard.fzz.zip)

(remove the trailing .zip to recover the .fzz file)

The two Neopixel parts are connected to each other in schematic but show as unrouted in breadboard:

![Capture](https://user-images.githubusercontent.com/16514277/74054388-cfe27880-4992-11ea-98a4-7209b581cdcc.PNG)

Clicking on the unrouted message gets no unrouted nets:

![Capture1](https://user-images.githubusercontent.com/16514277/74054444-ef79a100-4992-11ea-85f9-068cff64c2ed.PNG)

**Build:**
Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
<Windows 7>

**Steps to reproduce:**
- Connect pins on any two parts via a breadboard strip

## Expected Behaviour

Should be a routing complete message instead.

![Capture2](https://user-images.githubusercontent.com/16514277/74054720-63b44480-4993-11ea-8379-93c24e5bfff6.PNG)

**Comment by KjellMorgenstern** [comment]
Straightforward and easy to reproduce
