### ISSUE TITLE
60 Second delay on file open.

### ISSUE THREAD

**Issue by Ajb2k3** [fritzing/fritzing-app#3649]
**OSX 10.14.2
Fritzing 0.9.4**

**Issue:** 
When clicking the file open menu option, it takes 60 seconds for the dialog to be useable and then another 60 second delay if i click on the dropdown box's or the folder list.

**Comment by KjellMorgenstern** [comment]
That seems to be a situation tightly coupled to your system, I would help to get as much information as possible. Also it is important to rule out other possible causes to narrow down the issue.

Possible checks:
Can you repeat this, does it happen each time?
I guess opening the same location in FInder (not with Fritzing) works fine, did you check? If yes, is there an unusual high number of files in that directory?
What does the system status say about CPU usage, is there a process taking a lot of CPU time?
Do you have any backups, indexers or virus scanner running?
Are you using network drives?

**Comment by Ajb2k3** [comment]
**Possible checks:
Can you repeat this, does it happen each time?**

Yes, completely repeatable.

**I guess opening the same location in FInder (not with Fritzing) works fine, did you check? If yes, is there an unusual high number of files in that directory?**

No problem in Finder, Just Fritzing.

**What does the system status say about CPU usage, is there a process taking a lot of CPU time?**

Dunno, will check later but it is possible it is making out as other GUI programs stop working during the delay.

**Do you have any backups, indexers or virus scanner running?**

Nope
**Are you using network drives?**
and nope again.

**Comment by KjellMorgenstern** [comment]
Is there an unusual high number of files in that directory?

**Comment by Ajb2k3** [comment]
What do class as unusual?

**Comment by Ajb2k3** [comment]
It's causing a gui lockup so don't often catch process details but often the TCCD process gets pulled to the top of the process list.

**Comment by KjellMorgenstern** [comment]
About the TCCD process.
Fritzing should not access your contacts. Maybe it helps to remove this access right from Fritzing? See
https://zhuanlan.zhihu.com/p/25164713 for a brief summary , also fits your version of OS i think. 

Anyway this access right should not be there, as Fritzing does not request it. But let’s first check if that’s really what is going on, for now it is just a wild guess.

**Comment by Ajb2k3** [comment]
Fritzing is also trying to access the microphone!

**Comment by KjellMorgenstern** [comment]
How do you get to that conclusion, of course it doesn’t? No matter if it does or not, TCCD should not hog the CPU. 

What happens if you disable that access = remove the access right to contacts?

**Comment by Ajb2k3** [comment]
Ok its gone from microphone but
[https://www.pinterest.co.uk/pin/497295983857290014](url)
[https://www.pinterest.co.uk/pin/497295983857290010/](url)

**Comment by Ajb2k3** [comment]
Update,
Removing the permissions to everything but images has removed the delay.

**Comment by KjellMorgenstern** [comment]
@Ajb2k3 The pintersest links are broken. 

Fritzing doesn't really need access to images either, it is not a mobile app. What it needs is file access to a "Fritzing" folder in the documents location, a place to store its config files and parts, and ideally network access (for projects, blog, updates etc)

**Comment by KjellMorgenstern** [comment]
This doesn't seem happen normally, and a solution has been found. I am going to close this.
