### ISSUE TITLE
Updated Portuguese Portugal translation

### ISSUE THREAD

**Issue by Spectrum256** [fritzing/fritzing-app#3650]
I updated and finished Portuguese translation (pt_PT).

I send the file attached here. Translation is all completed.

Thank you.
Bruno Ramalhete

[fritzing_pt_pt.zip](https://github.com/fritzing/fritzing-app/files/4346063/fritzing_pt_pt.zip)

**Comment by KjellMorgenstern** [comment]
Translation was added to PR 3651

**Comment by Spectrum256** [comment]
Thanks!
