### ISSUE TITLE
Connections between schematic and breadbord differ

### ISSUE THREAD

**Issue by Hamsterjh** [fritzing/fritzing-app#3667]
## Current Behaviour
The alignment of the connections between the circuit schematic and the breadboard view doesn't want to match. schematic is drawn correct, but breadboard connections is wrong. If you correct the breadboard connections, it messes up the schematic connections, and makes them wrong. Same applies to the PCB view.

<please attach screenshot if possible>

![fritzing bb issue](https://user-images.githubusercontent.com/64709031/80891969-da798900-8cc7-11ea-9bea-7d051403a442.PNG)

![fritzing sch issue](https://user-images.githubusercontent.com/64709031/80891971-dcdbe300-8cc7-11ea-9666-4e06f06209d9.PNG)

**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Mismatch of cct drawn in schematic view to the layout in breadboard view,

## Expected Behaviour
Expect the schematic view to match with breadboard and pcb connections, and vice versa.

**Comment by KjellMorgenstern** [comment]
Where is the mismatch?

**Comment by Hamsterjh** [comment]
As an example: 
Schematic - Capacitor C1 positive tied to 7805 positive input
Breadboard - Capacitor C1 positive shows dotted line to negative of 7805

Schematic - Capacitor C2 positive goes to pin 3 of 7805
Breadboard - Capacitor C2 shows no connection to pin 3 of 7805

Schematic - Capacitor C2 negative goes to common negative rail.
Breadboard - Capacitor C2 negative goes to positive input pin 1 of 7805 as well as negative rail, thus creating short circuit.

Thanks,

**Comment by KjellMorgenstern** [comment]
In the schematic pin3 of 7805 is red, which means that it is not connected. 
You can also check by pressing the connection with the mouse, all connections should be highlighted.

7805 is numbered in the wrong order, this is issue https://github.com/fritzing/fritzing-parts/issues/252

The two red wires are not connected, there is no green circle around the connectors on the breadboard where they meet.

**Comment by Hamsterjh** [comment]
Ok, thanks I did fix the unconnected pin 3 of the 7805, it shows green now.

Thanks for pointing out the pins order on the 7805, how come the pins of the 7805 is different to what is in the industry? Is there a fix planned for this?

**Comment by KjellMorgenstern** [comment]
Honestly I don't know why this part is that way, the part was added via a 3rd party, long before I joined the project. As mentioned in https://github.com/fritzing/fritzing-parts/issues/252 , I plan to replace it. Also, with a recent pull request, we will add some more voltage regulators.

**Comment by Hamsterjh** [comment]
Thanks for the feedback on this, much appreciated. Will work around it for the time being. Looking forward to future updates, great software.

**Comment by KjellMorgenstern** [comment]
Wrong numbering of 7805 is tracked in #252 . Closing.
