### ISSUE TITLE
Sorry But I didn't receive the fritzing.exe file, so I can't use it

### ISSUE THREAD

**Issue by reinhard56** [fritzing/fritzing-app#3668]
## Current Behaviour
Text
<please attach screenshot if possible>
**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text

**Comment by KjellMorgenstern** [comment]
This isn't the place for support, please contact via mail or the support page on fritzing.org.
