### ISSUE TITLE
Unable to load fzp from /usr/share/fritzing/pdb/core/sparkfun-connectors-m12-machine-pin_lock.fzp

### ISSUE THREAD

**Issue by jeremyvillalobos** [fritzing/fritzing-app#3670]
Version 0.9.3b

Hello I see this error:

![image](https://user-images.githubusercontent.com/3057618/80927721-a8226700-8d6d-11ea-9557-e8405c3753f6.png)

while trying to edit a part.

Ubuntu 16.04

**Comment by KjellMorgenstern** [comment]
Please update to 0.9.4
