### ISSUE TITLE
Windows 10 64 bits - "git2.dll not found"

### ISSUE THREAD

**Issue by GitMoDu** [fritzing/fritzing-app#3672]
## Current Behaviour
[Screenshot](https://snipboard.io/AIvn1N.jpg)
**Build:**
Version 0.9.4.64 

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1 - Run fritzing on a non-dev computer.

## Expected Behaviour
Run the app.

**Comment by KjellMorgenstern** [comment]
Can not reproduce.

**Comment by GitMoDu** [comment]
I tried another computer and it works. No idea why.
Thank you for the quick response.
