### ISSUE TITLE
About Box does not provide a mechanism to dismiss it on MacOC Catalina

### ISSUE THREAD

**Issue by AndyDoddington** [fritzing/fritzing-app#3675]
## Current Behaviour

Click on the ‘About Fritzing’ menu item and the About box pops up, as expected. Unfortunately, there does not seem to be a way of dismissing the window, apart from terminating the entire application, using Command-Q (I am running on MacOS).

<img width="472" alt="Screenshot 2020-05-05 at 09 24 00" src="https://user-images.githubusercontent.com/62256951/81095079-64aa3300-8efc-11ea-9a0d-8da1fb715591.png">

Note that the box appears on an entirely black screen, rather than in front of the previous window, as is expected.

Normally, on MacOS, a dialog should include a red button in the top left-hand corner, which allows the user to close the window (see later).

**Build:**

Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) Cocoa [Qt 5.13.2]

**Operating System:**

MacOS 10.15.4 Catalina.

**Steps to reproduce:**

Select the 'About Fritzing' option from the 'Fritizing' menu.

## Expected Behaviour

See the About box for the MacOS Safari browse, below:

<img width="307" alt="Screenshot 2020-05-05 at 18 02 54" src="https://user-images.githubusercontent.com/62256951/81095407-e1d5a800-8efc-11ea-86d4-f4cca7d846c4.png">

**Comment by KjellMorgenstern** [comment]
![image](https://github.com/fritzing/fritzing-app/assets/6494025/fb51ab67-94ea-4078-8697-e0dd64b378cd)

This does not seem to affect later versions. Tested a dev build on Monterey. I think we would have noticed during testing for the 1.0.0 release or later. There are no releases planned for Catalina anymore.
