### ISSUE TITLE
Open sketch from url (browser) fails to find some core parts

### ISSUE THREAD

**Issue by mMerlin** [fritzing/fritzing-app#3676]
## Current Behaviour

When using `Open with Fritzing` in a web browser (Firefox 76.0.1 (64-bit) in my case)) a fzz file link, Fritzing fails to find some core parts that do exist. Downloading the file, then opening that from Fritzing works. Fritzing also remembered (in recent) the downloaded and directly opened sketch file. Explicitly opening that also works.

[Forum post for example](https://forum.fritzing.org/t/can-i-export-my-project/9527/5)

EDIT: More research
Same issue if the sketch is opened from the OS file browser. Or even if Fritzing is opened from "Activities", then the downloaded sketch file is opened. The successful path opens Fritzing from a terminal window.

EDIT2: Followup
Opening from Fritzing, which was opened from the command line works. Edit and save as to a new file works. Close Fritzing. Open the new document from the GUI, which opens Fritzing, still fails to find the same 2 core parts, but with messages now pointing to the core library path on my system. Explicitly starting Fritzing from the GUI, then opening the new saved copy of the sketch also still fails. manually unziping the sketch file, and inspecting the fz shows that the path is now correctly pointing to the core part on my system. There are no references in the new file to "C:" The problem is not JUST the stored path. Could be a problem with the parts in library, but still some interaction with whether Fritzing started from command line or GUI.

**Build:**

Version 0.9.3 on some Linux
Version 0.9.4 (CD-498 2019-12-01) 64 [Qt 5.13.2] on Fedora 31
Currently unable to test with 0.9.5 ¦ Environment does not have Fritzing installed, so does not open from browser.

**Operating System:**

- unknown linux
- Fedora 31 5.6.8-200.fc31.x86_64

**Steps to reproduce:**

- Step 1 Click [Door Pi.fzz](https://forum.fritzing.org/uploads/short-url/uMlIle7HDQQBUHxKrnqUCVnZTt5.fzz) link from [Forum Post](https://forum.fritzing.org/t/can-i-export-my-project/9527/5) in web browser (Firefox 76.0.1 (64-bit))
- Step 2 Choose "Open with Fritzing", and click OK
- Step 3 From opens, downloads, then requestor with messages

```t
Unable to find the following 2 parts:

'Camdenboss_CTB0158-8_5_08mm_pitch_90deg_terminals'
at
'C:/Program Files/Fritzing/fritzing-parts/core/Camdenboss_CTB0158-8_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals'
at
'C:/Program Files/Fritzing/fritzing-parts/core/Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals.fzp'
```

- Step 4 Click OK on the message requestor
- Step 5 Document displays but without the terminal parts

## Expected Behaviour

Fritzing should open the sketch, and find the parts, when `Open with` is used from a web browser.

**Comment by mMerlin** [comment]
There is some sort of interaction here with (probably) bad parts. Open Fritzing from the command line, search for "camdenboss" in parts. Shows 11 parts. Close Frtizing. Open fritzing from GUI now throws up requester with:

```t
Unable to find the following 11 parts:

'Camdenboss_CTB0158-3_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-3_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-11_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-11_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-7_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-7_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-12_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-12_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-4_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-4_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-2_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-5_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-5_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-8_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-8_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-10_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-10_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-6_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-6_5_08mm_pitch_90deg_terminals.fzp'
'Camdenboss_CTB0158-9_5_08mm_pitch_90deg_terminals'
at
'/home/phil/Documents/data_files/fritzing-parts/core/Camdenboss_CTB0158-9_5_08mm_pitch_90deg_terminals.fzp'
```

Close that requester, go back to parts search, and no parts are found. Close Fritzing, start from terminal, no requester, and the parts are back in the search results.

**Comment by mMerlin** [comment]
Problem resolved. There were multiple part library repos on the system. The command line run used a script that pointed to one. The GUI startup used the one that came with the Fritzing flatpak app, Due to flatpak rules, and the way Fritzing was packaged, the library is a static snapshot old enough that the parts actually do not exist.

**Comment by KjellMorgenstern** [comment]
Thanks. One of the minor features on my list is a info dialog, that shows the location and some other stats about the database. I guess it would be helpful to identify such issues.

**Comment by mMerlin** [comment]
That would also help for checking the current application state when switching libraries from the command line. When getting my process setup for checking changes to the core parts, while still using Fritzing for other things, I had some problems with Fritzing silently not doing what I wanted. Typos in the command or library path that ended up defaulting to 'base' library, with not enough (noticeable) information that there was a problem. Process has been tweaked, and mostly scripted, so does not happen any more.

Instead of a new dialog, some other applications include those details in the about dialog.
