### ISSUE TITLE
The progress bar for autoroute, save, load, and export should be in a modal progress window

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#368]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on December 11, 2008 16:39:41_

Now the export to DIY is no longer exporting rastered images, but just svg is already much faster. 
Still it is expected that complex sketches will have long saving times and long exporting to pdf / diy 
/ etc time.

If exporting is taking longer than a couple of seconds, a progress bar would be greatly appreciated.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=368_

**Comment by failiz** [comment]
Outdated?

**Comment by KjellMorgenstern** [comment]
I think most are now modal and update. For sometime, there was a issue with "popunders" , like #3304
