### ISSUE TITLE
Wire in schematic view disapears (can be reproduced)

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3681]
## Current Behaviour
If I delete the bendpoint by doubleclick one part of the wire disapears. But you can see that the components are still connected. I can reproduce it every time with that project and can sse that recurrently during building circuits. Please take a look because it is bad in complex circuits if you cannot see the connection.

![2020-05-23 12_49_46-PSU Adapter V2 fzz - Fritzing -  Schaltplanansicht](https://user-images.githubusercontent.com/51311453/82728999-56c62180-9cf4-11ea-86a5-83bfa04f5b77.png)
![2020-05-23 12_50_50-PSU Adapter V2 fzz_ - Fritzing -  Schaltplanansicht](https://user-images.githubusercontent.com/51311453/82729002-59c11200-9cf4-11ea-9a07-464297678051.png)

**Build:**
Version 0.9.4 (CD-498-0-a1ffcea 20-12-01)

**Operating System:**
Windows 10

**Steps to reproduce:**
- Doubleclick the bending point

## Expected Behaviour
Wire should still be visible as compontnets are also still connected.

[PSU Adapter V2.zip](https://github.com/fritzing/fritzing-app/files/4671626/PSU.Adapter.V2.zip)

**Comment by KjellMorgenstern** [comment]
Confirmed with Fritzing 9430027f and the PSU Adapter V2.zip from the report.
