### ISSUE TITLE
Beding point appears in the middle of nowhere without a wire

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3682]
## Current Behaviour
There is a bendpoint in the middle of nowhere in schematic view.

![2020-05-23 13_01_35-PSU Adapter V2 fzz - Fritzing -  Schaltplanansicht](https://user-images.githubusercontent.com/51311453/82729194-d43e6180-9cf5-11ea-92dd-a9f75718aecf.png)

[PSU Adapter V2.zip](https://github.com/fritzing/fritzing-app/files/4671637/PSU.Adapter.V2.zip)

Build:
Version 0.9.4 (CD-498-0-a1ffcea 20-12-01)

Operating System:
Windows 10

Steps to reproduce:
Does not know how ti recreate if happens during building circuits in schematic view but issue is visible in the Fritzing file attached.

## Expected Behaviour
No bending points in the middle of nowhere.

**Comment by KjellMorgenstern** [comment]
This is just a wire with both endpoints at the same position. Can easily reproduced by moving endpoints of a wire to the same grid point, with align to grid enabled so they end up at the exact same spot.
