### ISSUE TITLE
Dashed line is gone in breadboard view after moving the element e.g. LED

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3683]
## Current Behaviour
If I move the connectors of e.g. a LED the dashed line is gone using Perboard in Breadboard view.

![2020-05-24 11_05_13-PSU Adapter V2 fzz_ - Fritzing -  Steckplatinenansicht](https://user-images.githubusercontent.com/51311453/82750245-052e9d00-9daf-11ea-8376-39db8f0b6d6c.png)
![2020-05-24 11_05_56-PSU Adapter V2 fzz_ - Fritzing -  Steckplatinenansicht](https://user-images.githubusercontent.com/51311453/82750248-0790f700-9daf-11ea-893c-06dd03e5974f.png)

Build:
Version 0.9.4 (CD-498-0-a1ffcea 20-12-01)

Operating System:
Windows 10

Steps to reproduce:
Move the connector of the LED in the attached project.
[PSU Adapter V2.zip](https://github.com/fritzing/fritzing-app/files/4673199/PSU.Adapter.V2.zip)

## Expected Behaviour
The dashed line should be still there even if a connector is moved from a LED or other objects.

**Comment by KjellMorgenstern** [comment]
Minimal example: [wire.zip](https://github.com/fritzing/fritzing-app/files/5080425/wire.zip)

After moving the leg, the connection is lost, in schematics and breadboard. 
In the PCB view, R1 and C1 are still connected.
