### ISSUE TITLE
Touchpad gestures for zooming and scrolling

### ISSUE THREAD

**Issue by KjellMorgenstern** [fritzing/fritzing-app#3689]
## Problem
On MacOS, the touchpad is used for zooming and scrolling. Many macbooks are operated without a mouse. Fritzing doesn't support the touchpad in all cases.

## Proposed Solution
Enable touchpad gestures at least for MacOS.

**Comment by failiz** [comment]
Several of my students (macOS users) are finding this issue.

**Comment by failiz** [comment]
Was not this fixed in 1.0.0?
