### ISSUE TITLE
No .exe File

### ISSUE THREAD

**Issue by turrithugger** [fritzing/fritzing-app#3692]
This is a duplicate of #3688, which I think the developers skipped over way too fast. As evidence of this issue, I present:

- both windows and Github can't find it.
![83795374-5cfdbb80-a66d-11ea-826a-6d7036d77d1c](https://user-images.githubusercontent.com/40583173/84180473-8a73ac00-aa55-11ea-93bd-401fed63b657.png)
-A seven minute video of me looking through every file folder manually and finding no .exe files
https://www.dropbox.com/s/uyc7re0kzzre7db/iKaWxbvdN2.mp4?dl=0

**Comment by KjellMorgenstern** [comment]
I think the issue might be that you expect the .exe file to be part of the source code?

**Comment by aallan** [comment]
A .exe file is not part of the source code. There are periodic binary development releases, e.g. https://github.com/fritzing/fritzing-app/releases/tag/CD-548. Production binaries are distributed via the main Fritzing website, see https://fritzing.org/download/ for downloads for Linux, Mac, and Windows.

**Comment by KjellMorgenstern** [comment]
Thanks aallan for explaining.
