### ISSUE TITLE
No.exe

### ISSUE THREAD

**Issue by DKraiser** [fritzing/fritzing-app#3693]
How I can to make fritzing.exe?

**Comment by aallan** [comment]
A .exe file is not part of the source code, instructions for building Fritzing from source can be found at https://github.com/fritzing/fritzing-app/wiki. However there are periodic binary development releases, e.g. https://github.com/fritzing/fritzing-app/releases/tag/CD-548. Production binaries are distributed via the main Fritzing website, see https://fritzing.org/download/ for downloads for Linux, Mac, and Windows.

**Comment by OgreTransporter** [comment]
> Production binaries are distributed via the main Fritzing website, see https://fritzing.org/download/ for downloads for Linux, Mac, and Windows.

Where is the link for download? I can't find one. There seems to be a pay wall which doesn't work for me because PayPal is blocked here. Is it only possible to download the file with PayPal?

**Comment by KjellMorgenstern** [comment]
@OgreTransporter please contact the support at fritzing.org

**Comment by OgreTransporter** [comment]
A simple "yes" to the pay wall would have sufficed. I have seen that the versions are available in the release folder (https://github.com/fritzing/fritzing-app/releases). But unfortunately only since CD-548 for Windows.

**Comment by KjellMorgenstern** [comment]
A simple yes is wrong.

**Comment by OgreTransporter** [comment]
> @OgreTransporter please contact the support at fritzing.org

The support does not respond.

**Comment by KjellMorgenstern** [comment]
We don't have any open tickets or emails regarding that. At what date did you sent the request? I'd like to make sure it is not lost.

**Comment by OgreTransporter** [comment]
> We don't have any open tickets or emails regarding that. At what date did you sent the request? I'd like to make sure it is not lost.

Fr., 26. Juni, 16:53 from Gmail to support at fritzing dot org.

**Comment by OgreTransporter** [comment]
Nothing happened.
