### ISSUE TITLE
No reverse

### ISSUE THREAD

**Issue by Alain81** [fritzing/fritzing-app#3698]
Hello,
Fritzing 0.9.4
After exporting the PCB in PDF format, the text is not reversed on the "copper bottom mirror" file.
cordially
Alain

**Comment by KjellMorgenstern** [comment]
How did you generate the text, can you share an example? Usually text would go to silk, not to copper.

**Comment by KjellMorgenstern** [comment]
Unclear. If you have further information, feel free to reopen.
