### ISSUE TITLE
Icons for fritzing document types (.fz, .fzz, .fzb, .fzp)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#37]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on December 05, 2007 06:58:27_

We need document icons for the different document types that the
application can open and can create:

.fz    fritzing project file
.fzb   fritzing breadboard file
.fzs   fritzing schematic circuit file
.fzp   fritzing pcb (printed circuit board) view file

Those icons should be like the application icon is now, designed for
multiple sizes.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=37_

**Comment by aknoerig** [comment]
Only Linux still to do

**Comment by el-j** [comment]
files are ready as svg and png. we still need to figure out how to set icons for file-extensions in linux (ubuntu). the icons has to be set via the mime. see:
http://stackoverflow.com/questions/30931/register-file-extensions-mime-types-in-linux
