### ISSUE TITLE
Implement IPC Netlist Export to support AISLER Smart Test Infrastructure

### ISSUE THREAD

**Issue by Libermentix** [fritzing/fritzing-app#3701]
## Problem
Fritzing is a great tool for designing PCBs. Yet, it currently does not support the Export of IPC-netlist files. Hence AISLER Smart Test Infrastructure currently cannot be supported. 

See https://aisler.net/blog/electrical-testing-on-steroids

## Proposed Solution
Implement an export function that conforms to IPC Netlist standard (Similar to KiCad).

**Comment by KjellMorgenstern** [comment]
Is there a preferred version? 
IPC-D-356A has been superseded by IPC-D-356B 
https://www.ipc.org/TOC/IPC-D-356B.pdf

**Comment by Libermentix** [comment]
@KjellMorgenstern IPC-D-356B is preferred

**Comment by KjellMorgenstern** [comment]
IPC export works with 1.0.0

This should be helpful for evaluating PCBs, both for automatic checks, but also for manual reviews or even 3rd party renderers: 
![image](https://github.com/fritzing/fritzing-app/assets/6494025/6a5b5116-b91a-4dbb-a7bb-416b52de6007)
