### ISSUE TITLE
Version 0.9.3 is broken from ubuntu repos.

### ISSUE THREAD

**Issue by abr4xas** [fritzing/fritzing-app#3707]
## Current Behaviour
With a fresh install:

![1](https://user-images.githubusercontent.com/405484/90651202-20c10c80-e213-11ea-8a55-55f259821455.png)
![2](https://user-images.githubusercontent.com/405484/90651207-21f23980-e213-11ea-9b32-7f3e9b9a94c5.png)
![3](https://user-images.githubusercontent.com/405484/90651208-228ad000-e213-11ea-8473-77cf9e577392.png)
![4](https://user-images.githubusercontent.com/405484/90651213-23236680-e213-11ea-9394-7ddb22c7e69d.png)
![5](https://user-images.githubusercontent.com/405484/90651217-23bbfd00-e213-11ea-828d-00a68667ce8d.png)
![6](https://user-images.githubusercontent.com/405484/90651218-24549380-e213-11ea-9c68-716fb4aa07e6.png)
<please attach screenshot if possible>
**Build:**
Version 0.9.3 (b5c895d327c44a3114e5fcc9d8260daf0cbb52806 2016-04-19) 64 [Qt 5.9.1]

**Operating System:**
Ubuntu 18.04.5 LTS

**Steps to reproduce:**
- apt install fritzing

## Expected Behaviour
work without problems or errors (?)

**Comment by KjellMorgenstern** [comment]
This looks like an issue with the Ubuntu package of 0.9.3, which is not maintained here.

**Comment by abr4xas** [comment]
Hey @KjellMorgenstern thanks.
