### ISSUE TITLE
Free or not free? Confused..

### ISSUE THREAD

**Issue by Rick-van-Dam** [fritzing/fritzing-app#3709]
## Problem
On the home page it clearly states that you can download the free fritzing app and start building immediately

![image](https://user-images.githubusercontent.com/19387223/90957929-f8464600-e490-11ea-9ba1-d07f9662bb3c.png)

Then I proceed to click on this to go to the downloads and I see this:
![image](https://user-images.githubusercontent.com/19387223/90957958-3479a680-e491-11ea-9819-f7aca77499ee.png)

Is the free option simply missing or is the home page wrong?

**Comment by einarpersson** [comment]
So it is not free?

(I'm an educator and was looking forward to letting my students use fritzing for their course)

**Comment by kaveenr** [comment]
This is a tad saddening, I do understand it's not easy to keep such OSS projects afloat. But not allowing to try out the program before kicking back some cash is cruel!

Yes, I do understand that I can build it myself. But hey, I just want to see if it can get the job done.

**Comment by KjellMorgenstern** [comment]
Those trial periods are usually used as a sales strategy for software which is very expensive, is new on the market, has a less then trivial tariff structure, or any combination of that. And it usually comes with an obligatory registration and login for using the application. Does this fit for Fritzing?

What we could do to improve, and which is on my wishlist, is to update the videos about how to use Fritzing, and what it can do.

**Comment by kaveenr** [comment]
What I meant is trialling out in the sense of trying it out before tipping in. It must be really tough getting cash into the development team, I do sympathize. 

But gate-keeping for an entry-level piece of software that can help a lot of people getting into electronics is a bit of a downer.

Isn't monetization possible in other aspects like cloud part libraries and workspaces possible instead?

**Comment by el-j** [comment]
Sadly it has become that unfree software. I do not like it as well, but money for dev is very important. I would love as well getting a free option back. Maybe "export" could be reduced in free version? So with free u can just use the aisler fab? This could be an idea or?

**Comment by syardumi** [comment]
This is really unfortunate. Would love to see a "donate" strategy employed instead since this tool is a huge gateway for students in circuit design.
