### ISSUE TITLE
2.2mF capacitor

### ISSUE THREAD

**Issue by thomasw-mitutoyo-ctl** [fritzing/fritzing-app#3713]
## Problem
We have 1mF and 4.7mF capacitors, but not the 2.2mF capacitor.
IMHO 2200µF capacitors are also common

## Proposed Solution
Add another value to the dropdown list

**Comment by KjellMorgenstern** [comment]
PR #3717 could be a fix, however it adds more values than just 2.2mF ( = 2200µF ) .
