### ISSUE TITLE
IC pin labels lost on any change to part properties. Undo doesn't work.

### ISSUE THREAD

**Issue by marcin-jozwikowski** [fritzing/fritzing-app#3720]
## Current Behaviour
When a generic IC has custom-names pins they get lost on any change of that part properties. 
I've tested it with properties such as _Hole Size_; _Pin Spacing_; _Number of Pins_ and _Package Type_.
That wouldn't be so much of a problem if I could revert that with Ctrl+Z but it reverts only the change made but doesn't bring back the labels.

![Screenshot from 2020-09-20 13-51-02](https://user-images.githubusercontent.com/5331237/93710687-dfd95200-fb48-11ea-873a-bc60c6440251.png)

After changing _Hole Size_ to _Large_ all labels are gone

![Screenshot from 2020-09-20 13-51-42](https://user-images.githubusercontent.com/5331237/93710838-cb498980-fb49-11ea-87e7-fd779bf07e86.png)

**Build:**
Version 0.9.5 (dCD-548-0-3d61c58 2020-02-07) 64 [Qt 5.9.5]

**Operating System:**
Ubuntu 20.04.1 LTS

**Steps to reproduce:**
- Add an IC part
- Edit pin labels
- Make any change to the part like _Pin Spacing_
- Try to _Undo_ the change with menu action on _Ctrl+Z_

## Expected Behaviour
Most of all I'd expect Undo to work properly.
I'd also like for the labels to stay untouched on any change when pin count stays the same. 
When lowering the count (from 32 to 16 for example) label over the pin count could be deleted but it would be better for them to stay as well. That sort of change could be accidental.

**Comment by KjellMorgenstern** [comment]
Fix for Undo is in the pipeline. 
Fix to remember pin labels after certain operations will be implemented as issue #2336

**Comment by KjellMorgenstern** [comment]
Just retested to be sure it works now. Pin labels now persist when other properties change.
Even changing the number of pins works, unless you reduce it, then the labels for pins that have been removed will not persist, even if you increase the number again.
