### ISSUE TITLE
moving a parts leg in breadboard view breaks connection in schematic view

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3740]
## Current Behaviour
The connection between the components is dropped but it should not. 

[2020-10-31 21-48-05.zip](https://github.com/fritzing/fritzing-app/files/5469788/2020-10-31.21-48-05.zip)
[Raspberry Schaltung.zip](https://github.com/fritzing/fritzing-app/files/5469789/Raspberry.Schaltung.zip)

**Build:**
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
Windows 10

**Steps to reproduce:**
- Move a leg in breadboard view in example (see video)

## Expected Behaviour
Connection should not be dropped

**Comment by KjellMorgenstern** [comment]
When moving a leg in breadboard view, the net line should follow, not disconnect.
