### ISSUE TITLE
CD-625 not found libm.so.6 and libQt5Core.so.5

### ISSUE THREAD

**Issue by HaraldRau** [fritzing/fritzing-app#3744]
I can not open ./Firzing
Fritzing CD-625 has tow Errors:

`./Fritzing
/home/hara/Downloads/Fritzing/fritzing-0.9.5.linux.AMD64/lib/Fritzing: /lib/x86_64-linux-gnu/libm.so.6: version "GLIBC_2.29" not found (required by /home/hara/Downloads/Fritzing/fritzing-0.9.5.linux.AMD64/lib/Fritzing)`

`/home/hara/Downloads/Fritzing/fritzing-0.9.5.linux.AMD64/lib/Fritzing: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version "Qt_5.12" not found (required by /home/hara/Downloads/Fritzing/fritzing-0.9.5.linux.AMD64/lib/Fritzing)`

I found on my System (Xubuntu 18.04):
/lib/x86_64-linux-gnu/libm.so.6
and:
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5

Fritzing 0.9.4 run without Problems

**Comment by KjellMorgenstern** [comment]
That is a first try to build for Linux Mint 20, it is not supposed to run on Xubuntu 18.04 (and probably all other < 19.04 variants)
