### ISSUE TITLE
Text size of the connection pins of the ESP32 too large - text overlap

### ISSUE THREAD

**Issue by Gekla** [fritzing/fritzing-app#3748]
## Current Behaviour
Text
<please attach screenshot if possible>
**Build:**
<e.g. Version 0.9.4 (CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
<Windows 10>

Hello fritzing team,
I am a teacher at a vocational school and we have various projects that we implement with the ESP32 microcontroller. I imported the ESP32 into the component list using the "ESP32-38PinWide.fzpz" file using the import function. However, the font size of the pin labeling of the ESP in the breadboard view is too large and text overlaps. The connection designations are therefore hardly legible.
![figure 1](https://user-images.githubusercontent.com/74313755/98837823-b69bba80-2443-11eb-8763-cfbddcb7cd43.png)

Interestingly, the font size is displayed correctly in the accompanying SVG file and there are no overlaps. 
![figure 2](https://user-images.githubusercontent.com/74313755/98838015-f662a200-2443-11eb-9efb-305417d7ce34.png)

Even after installing the Fritzing fonts, the error persisted.
Can you give me a hint as to what is causing this error and how to fix it?
regards
Gekla

**Comment by HaraldRau** [comment]
Hallo,

kannst Du mal das Paket "ESP32-38PinWide.fzpz" hier einfügen. Dann sehe ich mir es an und versuche zu helfen.

Gruß Harald!

**Comment by HaraldRau** [comment]
Hallo noch mal,

welche Schriftarten hast Du installiert und mit welchen Programm hast Du das Teil bearbeitet oder angezeigt?

**Comment by HaraldRau** [comment]
Um das Paket "ESP32-38PinWide.fzpz" hier einzufügen, musst Du den Dateinamen in "ESP32-38PinWide.fzpz.zip" ändern.

**Comment by HaraldRau** [comment]
The font is arial, not OCRA. I will change the font.

**Comment by HaraldRau** [comment]
I've converted the font into paths. Certainly not the best solution, but it works for now.

[ESP32-38_Pin_V_01.fzpz.zip](https://github.com/fritzing/fritzing-app/files/5532055/ESP32-38_Pin_V_01.fzpz.zip)

Download the file and remove the extension *.zip

**Comment by KjellMorgenstern** [comment]
Instead of Arial, why not use OpenSans?

**Comment by HaraldRau** [comment]
I can't say, but "arial" was used in the svg-file - whatever reason. I changed the font to OCRA. But I still exported the font in paths. So the Part is working.

**Comment by KjellMorgenstern** [comment]
The recommendation is to use OCR-A or OpenSans, Fritzing includes those fonts so the text don't need to be vectorized in paths or embedded to the svg files. Don't use "px" values in svg documents (the font-size attribute uses them here). Since svg are scaled with the viewBox, the px value would loose its meaning, specifically, it will not correspond to a screen pixel. 

The pcb view of the part seems to have the same issue.

**Comment by HaraldRau** [comment]
O.K., I see I have to learn more about the part editor and the Fritzing part file system.
Is this documentation up to date?
[https://fritzing.org/learning/tutorials/creating-custom-parts](https://fritzing.org/learning/tutorials/creating-custom-parts)
Can the part be used as a reference?
[https://fritzing.org/media/uploads/learning/graphic_standards/fontsandtemplates.zip](https://fritzing.org/media/uploads/learning/graphic_standards/fontsandtemplates.zip)
Is there another part that can be used as a reference?

**Comment by HaraldRau** [comment]
Is it possible to move this issue to fritzing-parts?

**Comment by KjellMorgenstern** [comment]
It's a request about 3rd party part, not a core part, and there is no response yet from @Gekla . Should be closed.

**Comment by KjellMorgenstern** [comment]
Closing due to inactivty
