### ISSUE TITLE
Scroll should zoom to cursor

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#375]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on December 14, 2008 15:57:15_

When you scroll with your scroll wheel, scroll slider, and of course –most significant– with two 
fingers on your multi-touch macbook trackpad, this should result in scrolling (panning).

Using the scroll wheel/slider/trackpad in combination with the alt-modifier should zoom.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=375_

**Comment by failiz** [comment]
This can be configured in edit->preferences
