### ISSUE TITLE
Build failed. Missing file phoenix.pro

### ISSUE THREAD

**Issue by marcoratto** [fritzing/fritzing-app#3751]
## Current Behaviour

fritzing-app/docker
$./build-linux.sh 
+ mkdir build
++ pwd
+ docker run -v /home/rattom/RepositoryGit/fritzing-app/docker:/home/conan/fritzing -w /home/conan/fritzing/build fritzing/build:bionic qmake ../phoenix.pro
Unable to find image 'fritzing/build:bionic' locally
bionic: Pulling from fritzing/build
7413c47ba209: Pull complete 
0fe7e7cbb2e8: Pull complete 
1d425c982345: Pull complete 
344da5c95cec: Pull complete 
eeb2c00a4a27: Pull complete 
296287cc51b0: Pull complete 
ad58473653cd: Pull complete 
c7b51c5bc300: Pull complete 
273a7c575ad9: Pull complete 
Digest: sha256:96636eefd7790136a0341906a32d911b1c10125b08bb799d05abf72b8b256337
Status: Downloaded newer image for fritzing/build:bionic
**Cannot find file: ../phoenix.pro.**

**Build:**
Latest on GitHub

**Operating System:**
Ubuntu 18.04

**Steps to reproduce:**
git clone https://github.com/fritzing/fritzing-app
cd fritzing-app/
cd docker/
./build-linux.sh 

## Expected Behaviour
Compile the App.

**Comment by KjellMorgenstern** [comment]
The docker build is intended for the CI. To build locally, better open the phoenix.pro file in Qt Creator
