### ISSUE TITLE
"schematic frame" component is not scaling

### ISSUE THREAD

**Issue by NilsRo** [fritzing/fritzing-app#3761]
## Current Behaviour
The "schematic frame" component does not scale with its size. So e.g. long filenames does not fit.
![2020-11-23 07_01_53-Window](https://user-images.githubusercontent.com/51311453/99932998-03dc2e00-2d5a-11eb-9774-3b6d990de434.png)
 

**Build:**
Version 0.9.4 
(CD-498-0-a1ffcea 2019-12-01) 64 [Qt 5.12.3]

**Operating System:**
Windows 10

**Steps to reproduce:**
- scale a "schematic frame" component

## Expected Behaviour
The size excluding the text should scale also.

**Comment by KjellMorgenstern** [comment]
Reviewing this again, it also looks like the fix doesn't exactly resolve the issue.

The frame is now literally scaling. However, I guess what actually was needed, was a resize of the text area, and better wrapping or multi line text support, not scaling.
