### ISSUE TITLE
My Fritzing is so laggy and sometimes I cannot even open it up.

### ISSUE THREAD

**Issue by AziziAmiruddin** [fritzing/fritzing-app#3766]
## Current Behaviour
Text
<please attach screenshot if possible>
**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text

**Comment by KjellMorgenstern** [comment]
Sorry, we need further information. Please give steps to reproduce as suggested in the template.

Closing this issue until relevant information is provided.
