### ISSUE TITLE
Arduino pro mini se se cale pas sur la grille de la strip board

### ISSUE THREAD

**Issue by Claude-Pierre** [fritzing/fritzing-app#3779]
## Current Behaviour
Les pins principales de Arduino Pro mini ne se verrouillent pas sur sur la grille de la strip board.
Seules les 6 pins de programmation sont verrouillées (BLK GND VCC TX0 RX1  GRN °
<please attach screenshot if possible>
**Build:**
0.9.4

**Operating System:**
<Windows 7
![ArduinoProMini](https://user-images.githubusercontent.com/60773670/105484912-64311280-5cac-11eb-823c-2210aa9938dd.JPG)
>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text

**Comment by KjellMorgenstern** [comment]
Usually, the the header PINs should automatically align. If they don't, you can disable "align to grid" in the "View" menu.

**Comment by Claude-Pierre** [comment]
I tanks you for you answer..

CHOULET-PARPILLON Claude
