### ISSUE TITLE
INSTALL.txt says, to install "double-click fritzing.exe". however, no file "fritzing.exe" exists in repo.

### ISSUE THREAD

**Issue by Monsoonexe** [fritzing/fritzing-app#3783]
Installation instructions are incomplete.  After unzipping, the file "fritzing.exe" does not exist. It's not a problem with 7zip, because there isn't even a "fritzing.exe" file in the git repo.

**Comment by KjellMorgenstern** [comment]
You are looking at the source code. Github is for application development.  The website https://fritzing.org has an executable version.
