### ISSUE TITLE
Silkscreen SVG image not shown on PCB after PDF or Gerber exports

### ISSUE THREAD

**Issue by steliosm** [fritzing/fritzing-app#3790]
## Current Behavior
Some SVG images for Silkscreen logo fail to be generated during a PDF or Gerber export while they show fine on the PCB view at the editor. Using the previous version of Fritzing (0.9.4) the SVG images are generated fine during PDF or Gerber export.

Relevant forum thread: https://forum.fritzing.org/t/trying-to-figure-out-why-a-pcb-logo-is-not-generated/12197/8

**Build:** 0.9.6

**Operating System:** Ubuntu Linux 20.04 / Windows 10 64bit

**Steps to reproduce:**
- Prepare an SVG image for the silkscreen to be added on the PCB
- Import the on the PCB
- Generate PDF or Gerber files

## Expected Behaviour
Get the Silkscreen logo generated on the exported files (pdf/gerber)

**Comment by KjellMorgenstern** [comment]
Can not reproduced in 0.9.9.
This was probably cause by a bug when parsing EXP numbers, which was introduced in 0.9.6 and fixed later on.
