### ISSUE TITLE
Building on Mageia Linux

### ISSUE THREAD

**Issue by Morganlej** [fritzing/fritzing-app#3796]
I am an occasional QA at Mageia, and an occasional Fritzing user.
Our packager have problems packaging Fritzing.
Specifically problems with creating parts.db
https://bugs.mageia.org/show_bug.cgi?id=18689#c32

Any hint?

Maybe https://github.com/fritzing/fritzing-app/wiki/1.3-Linux-notes can be enhanced.

Thank you for this fun and educating program!
Now lets get it out to more users :)

**Comment by david-geiger** [comment]
Hi,

I'm the mageia packager for fritzing package, some help is needed as I can't create/build the parts database (parts.db file) which is needed. I get the following error during build:

> ./Fritzing -platform minimal -f ./parts -db ./parts/parts.db
/home/iurt/rpmbuild/tmp/rpm-tmp.FO9JLJ: line 43: 23315 Aborted                 (core dumped) ./Fritzing -platform -f ./parts -db ./parts/parts.db
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.FO9JLJ (%build)

And this one on my own system:

> ./Fritzing -platform minimal -f ./parts -db ./parts/parts.db
This plugin does not support propagateSizeHints()


Regards,
David

**Comment by Morganlej** [comment]
Reason for closure?

Should we simply skip building it and instead tell users to download the parts library to a folder and tell fritzing to use that?

( Like described at end of https://github.com/fritzing/fritzing-app/wiki/1.3-Linux-notes )

**Comment by KjellMorgenstern** [comment]
Sorry, i thought you have already solved it, but maybe i mixed something up. 
To ensure a wide support on Linux systems, we are currently testing an AppImage.

**Comment by david-geiger** [comment]
Please re-open this bug as long as it is not fixed!

**Comment by Morganlej** [comment]
Yes please reopen.

Meanwhile, i could help test if the Appimage works on Mageia 8-64 bit, if available.
Same, if you try to make a Flatpak.
(btw my user experience is that Flatpak programs in general have less problems than Appimages, but that may be just bad luck)

**Comment by Morganlej** [comment]
Kjell?

**Comment by Morganlej** [comment]
Ping...

**Comment by Morganlej** [comment]
Anything?

**Comment by Morganlej** [comment]
OK with this level of interest, we drop it from our distro.

**Comment by Morganlej** [comment]
Sorry our issue tracker had not been updated.
Fritzing 0.9.10 is built and works in upcoming Mageia 9 :)

As a backup/support, I bought 0.9.10 and verified that the Appimage works on Mageia 8 :)
