### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by zn59** [fritzing/fritzing-app#3798]
## Current Behaviour
I don't manage to print the whole PCB, a small bit on the left side is always missing. Tried both with or without margins but a bit of left side is always missing.

![IMG_1929](https://user-images.githubusercontent.com/80244604/111819182-5aa8dd00-88e0-11eb-82ff-fd6a28b4cfb1.jpeg)

**Build:**
Version 0.9.6 
(bCD-175-0-8a1e0682 2021-02-21) Cocoa [Qt 5.15.2]

**Operating System:**
<OS X BigSur>

**Steps to reproduce:**
- Printing with different settings

## Expected Behaviour
Would like to se the whole PCB on paper.

**Comment by KjellMorgenstern** [comment]
"Printing with different settings"

I am sorry, what should i do to reproduce this? Prints come out in original resolution, a 5cm wire will be 5cm on paper

**Comment by zn59** [comment]
Hi Kjell,
The resolution is fine! What I’m complaining about is that i bit of the side is always  missing.
The two holes visible at the right side are there on the left side too...
I have tried with different settings, with or whithout margins but some bit to the left and top are not printed.

**Comment by KjellMorgenstern** [comment]
![image](https://user-images.githubusercontent.com/6494025/111867239-0995f900-8973-11eb-88d8-ee639c143e64.jpeg)

**Comment by KjellMorgenstern** [comment]
Can not reproduce

**Comment by zn59** [comment]
Windows or Mac? Which settings?
