### ISSUE TITLE
regression: Images on copper layers missing from gerbers

### ISSUE THREAD

**Issue by deshipu** [fritzing/fritzing-app#3807]
## Current Behaviour
In Fritzing 0.9.6 and 0.9.5, images placed on the copper layer do not appear in generated Gerbers:
![fritzing096](https://user-images.githubusercontent.com/1181357/113941455-690f5800-97ff-11eb-8f3e-1d0a84553cea.png)

In earlier versions (0.9.3 is what I tested), the images appear correctly:
![fritzing093](https://user-images.githubusercontent.com/1181357/113941495-7af0fb00-97ff-11eb-83bb-0fc2e1b0716c.png)

<please attach screenshot if possible>
**Build:**
Version 0.9.6

**Operating System:**
Linux

**Steps to reproduce:**
Create a PCB with an image on a copper layer.
Export the PCB as gerbers.
See the image missing from the exported gerbers.

## Expected Behaviour
The image should be included in the exported gerbers.

**Comment by KjellMorgenstern** [comment]
Confirmed. 
I tested by exporting a production PDF of the Ocarina v1 on hackaday, which users similar images.
0.9.4 has the pattern on copper top
0.9.6 does not have the pattern

**Comment by deshipu** [comment]
If that helps, I also noticed that if you re-do the ground fills, it ignores the images in 0.9.5 and 6, while it goes around them in 0.9.3.

**Comment by KjellMorgenstern** [comment]
This is resolved by adding 'e' and 'E' to svg token list. It is not a svg path command, but it is used (and valid svg) in scientific notation of numbers. Pathc upcoming.
