### ISSUE TITLE
Trying to build Fritzing but issue: "Fritzing does not build with Qt 5.8 or earlier. 5.12 is recommended."

### ISSUE THREAD

**Issue by t-scale** [fritzing/fritzing-app#3812]
## Current Behaviour

I'm trying to build Fritizing after this guide:
https://github.com/fritzing/fritzing-app/wiki/1.-Building-Fritzing
Qt version is higher than 5.12 but i get the above error.

<img width="928" alt="Screenshot 2021-04-21 at 14 41 15" src="https://user-images.githubusercontent.com/4723347/115555436-cac7cb80-a2af-11eb-8c72-a15297381c9d.png">
<img width="928" alt="Screenshot 2021-04-21 at 14 41 25" src="https://user-images.githubusercontent.com/4723347/115555449-ce5b5280-a2af-11eb-8282-2ddfe4da727f.png">

**Build:**
Qt Creator 4.14.2
Based on Qt 5.15.2 (Clang 11.0 (Apple), 64 bit)

Built on Mar 19 2021 09:03:22

**Operating System:**
MacOS 10.14.6 (Mojave)

**Steps to reproduce:**
- Install Qt Creator with installer
- load phoenix.pro from fritzing-app into Qt Creator

## Expected Behaviour
It should build Fritzing.

**Comment by t-scale** [comment]
why is this invalid?

**Comment by t-scale** [comment]
my bad i'd just missed one step...

**Comment by leao-nardo** [comment]
> my bad i'd just missed one step...

im having the same error how did you fixed ?

**Comment by leao-nardo** [comment]
i got this error when using qt 6.1.1 and 6.1.2 when i installed the version Qt 5.15.2 it didnt gave the error

**Comment by WeepingRaven** [comment]
> my bad i'd just missed one step...

what step?

**Comment by StevenLovell** [comment]
There's a special place in hell for people who fix there own problem then don't post the fix.

**Comment by KjellMorgenstern** [comment]
@StevenLovell There isn't anything to fix. I think the problem might be sitting in front of your screen.

**Comment by StevenLovell** [comment]
> @StevenLovell There isn't anything to fix. I think the problem might be sitting in front of your screen.

Probably.

> i got this error when using qt 6.1.1 and 6.1.2 when i installed the version Qt 5.15.2 it didnt gave the error

This sorted it for me.

**Comment by fanatic007** [comment]
@leao-nardo @StevenLovell How do I use the extract to run the installer? Or better, how can I get a .dmg ..?
