### ISSUE TITLE
Bad Fritzing settings path on Ubuntu

### ISSUE THREAD

**Issue by frederikheld** [fritzing/fritzing-app#3815]
## Current Behaviour
I just installed Fritzing via "Ubuntu Software" and it created the settings path in `~/Documents/Fritzing`. This is bad. No app should write settings into the user's Documents directory (more than ever without even asking)! It is intended for the user's very own documents, not for anything apps want to store.

**Build:**
Version 0.9.3

**Operating System:**
Ubuntu 20.10

**Steps to reproduce:**
Install Fritzing via "Ubuntu Software"

## Expected Behaviour
If you want to store user-specific settings in the user's profile, the path should be `~/.fritzing`.

**Comment by KjellMorgenstern** [comment]
5 year old version, and not our official release. Settings are stored according OS guidelines.
