### ISSUE TITLE
Parts when dragged in get random orientation in schematic or pcb views.

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3825]
## Current Behaviour

Dragging a part in to either schematic or pcb has a constant orientation in that view and in breadboard but in  schematic or pcb (depending on which view the part is dragged in to) the orientation varies. It appears the orientation parameter isn't being passed in the IPC call to do the rendering of the other views (except in breadboard.)

**Build:**
Version 0.9.6 
(bCD-175-0-8a1e0682 2021-02-21) 64 [Qt 5.12.10]

**Operating System:**
Windows 10

**Steps to reproduce:**

- Drag 10 copies of the Pchannel mosfet in to pcb view

![capture](https://user-images.githubusercontent.com/16514277/117576172-a20a4900-b099-11eb-9810-b1a94b0cdcaa.jpg)

- change to schematic and one  of them is misaligned

![capture1](https://user-images.githubusercontent.com/16514277/117576197-c7975280-b099-11eb-9bd3-21399f09de87.jpg)

- breadboard is correct (AFAIK always!)

![capture2](https://user-images.githubusercontent.com/16514277/117576233-fdd4d200-b099-11eb-961b-197852ff908b.jpg)

- Delete them all and drag 10 copies in to schematic

![capture3](https://user-images.githubusercontent.com/16514277/117576264-1f35be00-b09a-11eb-8105-2ba9892b618a.jpg)

- pcb has two misaligned

![capture4](https://user-images.githubusercontent.com/16514277/117576293-38d70580-b09a-11eb-83d4-df499d9df7bd.jpg)

- breadboard is correct

![capture5](https://user-images.githubusercontent.com/16514277/117576318-5f953c00-b09a-11eb-84ed-1e208f794227.jpg)

-  again delete all then drag 10 in to breadboard
 
![capture6](https://user-images.githubusercontent.com/16514277/117576339-7b98dd80-b09a-11eb-885e-14e9430c1449.jpg)

- schematic has most wrong

![capture7](https://user-images.githubusercontent.com/16514277/117576358-910e0780-b09a-11eb-8aca-87c6a082a2d2.jpg)

- pcb has two wrong
 
![capture8](https://user-images.githubusercontent.com/16514277/117576377-a5520480-b09a-11eb-8dc1-0f547266e8b6.jpg)

## Expected Behaviour

All parts in all views should have the same orientation.

**Comment by KjellMorgenstern** [comment]
This also happens when inserting parts via the breadboard view.
The automatic placement in the PCB view will try to keep the parts inside the board area. However, i don't think that this modifies the orientation of the part. It would also not apply to the orientation in the schematic view. So indeed, this looks like an uninitialized variable or similar bug.
