### ISSUE TITLE
impractical behaviour (known from the first ever version)

### ISSUE THREAD

**Issue by bieblsoft** [fritzing/fritzing-app#3828]
Working with Fritzing still is a menace due to some illogical and impractical design behaviour in every mode (breadboard as well as schematic and pcb views) due to a number of problems:

- it is nearly impossible to select a number of components using mouse drag selection since in every case the breadboard or pcb will be selected, too (which is nonsense). Background items like breadboard or pcb should only be selectable on demand, e.g. using a dedicated shift-click on them. This makes copying a group of items very hard and frustrating.
- Moving or rotating items often misplaces item labels to strange positions 
- Having selected a component (or a group of Components), e.g. trying to copy them using the context menu, a right-click to display the context menu instantly unselects everything.
- In schematic view, Component pins connected to either Ground or Vcc are shown as unconnected, making it somehow difficult to check if all connections are correct. In this case it would be good to display some information about these connections, plus distinguishing between upper and lower power/ground rails, since sometimes you would need 2 different voltages in your project.

I am aware that Fritzing is not a full-fledged design tool like e.g. DesignSpark, but it could be a handy little tool for small projects which it presently is only partially.

**Comment by KjellMorgenstern** [comment]
Thank you for the input. As you stated, those behaviours are mostly known. I think separate issues already exist for them. For example, to select a PCB, I think there is a ticket to pin the PCB by default, so it can not get selected. It is easy to miss that possibility.
Closing as duplicate.
