### ISSUE TITLE
macOS, building against qt 5.15.2, Preferences Menu is not enabled

### ISSUE THREAD

**Issue by kencu** [fritzing/fritzing-app#3829]
## Current Behaviour
When I build Fritzing on MacOS (10.13 and 10.14 tried) against qt 5.15.2, the Preferences Menu is not enabled. 

![Screen Shot 2021-05-15 at 12 25 07 PM](https://user-images.githubusercontent.com/21211439/118375958-020d5d80-b57a-11eb-9bdb-f31600a43335.png)

![Screen Shot 2021-05-15 at 12 24 34 PM](https://user-images.githubusercontent.com/21211439/118375954-f752c880-b579-11eb-87ce-b0df115277f5.png)

<please attach screenshot if possible>

Version 0.9.6 (8a1e0682d7846f6384ae45373961ed693b4c55d2 20210221) Cocoa [Qt 5.15.2]

**Operating System:**
macOS 10.13 and macOS 10.14

Downloading the prebuilt version <fritzing-3d61c58421bdb63ca903bb5d11310a257f1ec0ed-develop-548.mojave.10.2.dmg> shows a normally-working Preferences menu.

![Screen Shot 2021-05-15 at 12 28 16 PM](https://user-images.githubusercontent.com/21211439/118375975-1b160e80-b57a-11eb-9bbb-3a0a6ecaec4c.png)

**Steps to reproduce:**
- checkout fritzing-app 0.9.6. build against qt 5.15.2 on macOS 10.13 or 10.14.

## Expected Behaviour
The Preferences menu will be enabled, and function.

**Comment by kencu** [comment]
I tried building the current tip of the development branch a3d8cab74c48a67795d71c199c378317fe3aa633 and I see the same greyed-out Preferences menu doing that as well.

**Comment by kencu** [comment]
building against qt 5.11 gives a working Preferences menu.

**Comment by KjellMorgenstern** [comment]
Preferences menu works fine with 5.15.2 , see our official 0.9.6 build.

**Comment by kencu** [comment]
cool. I must just have a bad download of qt 5.15.2 on those systems.

I'll reinstall it I guess.

My error.

**Comment by kencu** [comment]
As a MacPorts maintainer who has built and installed a great many qt4 and qt5 applications, I would like to deploy this application on MacPorts, where there are many thousands of users, however this issue prevents that from happening.

MacPorts has a "policy" of requiring source builds rather than installing prebuilt official builds, so I can just copy in your build from the dmg.

This same error happens on multiple machines, so either all the qt installs on MacPorts are broken somehow (possible -- I did the last set of qt5 updates on MacPorts, and I don't have certificate of perfection on my driver's license), or there is some issue that only shows up here. No other qt5 software appears to show this issue that I have seen so far.

If I do sort it out, I'll report back here what the eventual fix was.
