### ISSUE TITLE
When you move a component (part), the connected wires in it are lost

### ISSUE THREAD

**Issue by edson-acordi** [fritzing/fritzing-app#3832]
## Problem
Hi, I would like to know if there is the possibility to configure the Fritzing to move together with the component (part), all the existing connections. It is frustrating when you have a project and need to do some modifications, but the connections between the parts and the wires are lost when you move the parts on the breadboard.

## Proposed Solution
It would be very helpful to have an option to change the way a component (part) moves. For example, having an option to move only the part and other option to move the part and all the connected wires in it in a way that you do not lose the connections.

**Comment by edson-acordi** [comment]
Selecting the IC to move:
![image](https://user-images.githubusercontent.com/60040866/120084170-8268ae00-c0a4-11eb-9be9-f6fdf1696ef1.png)

After the part was moved (the wires connected to the IC was lost):
![image](https://user-images.githubusercontent.com/60040866/120084205-c3f95900-c0a4-11eb-9006-c5d83eeb4329.png)

**Comment by KjellMorgenstern** [comment]
Not a bug. That is exactly how the IC is intended to move.

**Comment by edson-acordi** [comment]
Ok, but this behaviour of Fritzing is terrible when you need to do some modifications to an existing project. When the part is moved, you lose the connections!

**Comment by KjellMorgenstern** [comment]
The part is connected to the breadboard. I don't think you want do move the breadboard along with it.
Rerouting the wires which you have manually placed before would be a different feature, and would be at least equally surprising or annoying to other users.

As mentioned before, the logical connection (aka ratsnest line) is kept if the part was connected or even routed in the pcb or schematic layer.
