### ISSUE TITLE
Platform, Board and Port menus are a barely readable white on grey on Macos

### ISSUE THREAD

**Issue by BruceH2020** [fritzing/fritzing-app#3833]
Macos Big Sur 11.3; Fritzing 0.9.6 downloaded from the Fritzing website.

The selection menus for choosing platform, board and port are a very hard to read white text on light grey background. Please see attached screenshot.

<img width="1253" alt="Screenshot 2021-05-29 at 12 51 19" src="https://user-images.githubusercontent.com/80216982/120069285-07d86800-c07d-11eb-9fbc-b98efec0f032.png">

(I don't see a way to select a severity when submitting this to Github but "cosmetic" is fine - would be nice to get something more legible, but the world won't end.) :-)

**Comment by KjellMorgenstern** [comment]
Which color scheme do you have configured on MacOS?

**Comment by BruceH2020** [comment]
I'm using light. But changing to dark and restarting Fritzing made no difference.

**Comment by KjellMorgenstern** [comment]
Not really fixed. It seems we have now a problem with dark letters on dark background in some Windows configurations.
