### ISSUE TITLE
Mouse click on the parts search does not start the search only the return key.

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3850]
## Problem

When doing ng a parts search mouse clicking on the search icon will not start the search, only hitting the return key will start the search. 

## Proposed Solution
Make a mouse click on the search icon act the same as the enter key. So a mouse click on the search icon (circled in red) will start the search. 

![capture](https://user-images.githubusercontent.com/16514277/123184654-f8182d80-d448-11eb-8b2f-51a6cddc110f.jpg)

**Comment by KjellMorgenstern** [comment]
![image](https://user-images.githubusercontent.com/6494025/127689225-cfe2b3c1-5df6-4e02-a1ca-f02de03fb669.png)

![image](https://user-images.githubusercontent.com/6494025/127689300-92e5d57c-5b06-4694-ae35-3b8957675256.png)

Proposed improvement:
1. Search updates while typing
2. Replaced search icon with a clear button

Currently, rendering the icons for the search result is what slows the search. There are two possible solutions.
a. update the icons with a thread pool, in the background
b. store the icons as blobs in sqlite, which should load them almost instant.

Generating the icons is burried quite some levels deep, the same functionality also delays Fritzing when starting up.

**Comment by KjellMorgenstern** [comment]
The searching glass issue has been resolved by replacing it with a "x" button for clearing the search for now.
We are working on further improvements to the search function.
