### ISSUE TITLE
Improve Perf board workflow

### ISSUE THREAD

**Issue by Djeez2** [fritzing/fritzing-app#3854]
When designing a perf board a couple of issues prevent a good experience.

1. In perf board, you cannot layout tracks as you can in strip board. The only way I found is to take a Vero board and delete all track connections. Suggestion is to allow track manipulation on perf boards like on strip boards

2. When resizing a board many of the connections go wrong, especially wires placed on the board. In practice this means you have to decide on the board size before placing all components. This severely limits an iterative workflow.

3. It is not possible to view the bottom of the board. You need this if you want to solder the tracks. My current workaround is to hide the parts layer, take a screenshot and flip the image in a graphics program and then print. This is cumbersome.

4. After placing components it is very hard to connect the dots. Even when the parts layer is hidden, you cannot click the track because the (invisible) component gets selected. The only workaround I found is temporarily move the component aside to connect the track. Suggestion is to disable the parts layer (i.e. not selectable), not only make it invisible.

**Comment by KjellMorgenstern** [comment]
Sorry, those are mostly duplicated issues, and to many different topics to track in one issue. It is also partially solved for 0.9.8. Closing this for now.
