### ISSUE TITLE
Generic IC broken on 0.9.7

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3859]
## Current Behaviour

Upgraded to 0.9.7 from 0.9.6 (without removing 0.9.6 first)

Drag a generic IC in to the sketch and try and resize it. 

![capture](https://user-images.githubusercontent.com/16514277/127585625-85e55d0d-48d7-4359-95e4-16f24b186038.jpg)

resize fails

![capture1](https://user-images.githubusercontent.com/16514277/127585670-f9cbfc19-5bbf-43b1-b040-a5899952eab4.jpg)

instead of the expected 10 pin dip, the 8 pin remains (in all views) 

![capture2](https://user-images.githubusercontent.com/16514277/127585782-b07f55d4-f274-46ac-b9b7-8339a7d951bc.jpg)

trying to change to an so package also fails, package remains 8pin dip. 

![capture3](https://user-images.githubusercontent.com/16514277/127585851-9dfa8ae3-9c19-412b-8abb-8ae34ffea69e.jpg)

Import a generic 20 pin dip created with 0.9.3b probably. Attempting to modify it also fails. 

![capture4](https://user-images.githubusercontent.com/16514277/127585986-3f20b26d-bb13-485d-b28d-1dcdc9a2611f.jpg)

switch to schematic and try editing pin labels set new tab editable pin labels from false to true to enable pin labels (presumably!) 

![capture5](https://user-images.githubusercontent.com/16514277/127586086-0a04b922-c149-457a-84cc-bbb0ddcd0874.jpg)

works (but doesn't allow you to go back to non editable pin labels!) but changes the IC from 20pins to 8

![capture6](https://user-images.githubusercontent.com/16514277/127586104-e3155a40-5733-426f-a425-6ab9890cca26.jpg)

running back the undo may indicate the problem. Here it is going to undo Swapped IC2 (which was a 20 pin dip) with generic 8 pin DIP which is likely the problem

![capture7](https://user-images.githubusercontent.com/16514277/127586541-1cefdfc4-31b2-415f-a1da-d76b11d88005.jpg)

which indeed restores the 20 pin dip as expected. 

![capture8](https://user-images.githubusercontent.com/16514277/127586653-efee63a6-7d93-4a95-8855-ea2272a390ed.jpg)

I also tried uninstalling Fritzing 0.9.7, rebooted the machine and then reinstalled 0.9.7 (without having the previous copy of 0.9.6 in the mix) but there was no change so it doesn't appear to be an upgrade related issue.

In addition, trying to change the 20pin to a 10 pin (which used to be legal) gets this message;

![capture9](https://user-images.githubusercontent.com/16514277/127587173-524d080a-1827-4bc8-957f-c108441a32d9.jpg)

which seems to also be incorrect. 

**Build:**

Version 0.9.7 
(bCD-534-0-120da230 2021-07-12) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Steps to reproduce:**
- Step 1 see current behaviour
- Step 2

## Expected Behaviour
Expected to be able to modify the generic IC as in previous versions.

**Comment by KjellMorgenstern** [comment]
Confirmed.
Is using the mystery part ("?") instead of the generic ic ("IC") an alternative?

**Comment by vanepp** [comment]
"Confirmed.
Is using the mystery part ("?") instead of the generic ic ("IC") an alternative?"

The mystery part will do some of it, but schematic (mystery part on the left)is single side not double.

![capture](https://user-images.githubusercontent.com/16514277/127749116-5ae5ff56-9b41-4a77-a48a-e1e1a4a75bb7.jpg)

so the result is quite different. I think the best thing would be to move the fix in to a replaced 0.9.7, otherwise the likely workaround will be to down grade to 0.9.6 where it works (this is what the original poster in the forums ended up doing). The generic IC is a quite important part!

**Comment by vanepp** [comment]
Fixed in 0.9.8, thanks Kjell!
