### ISSUE TITLE
Fritzing crashes when swapping a superflux led

### ISSUE THREAD

**Issue by failiz** [fritzing/fritzing-app#3863]
## Current Behaviour
1. Add a superflux Blue Led in the breadboard like in the picture:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZXXBytz/Capture.png" alt="Capture" border="0"></a>

2. Change the property polarrity to "common cathode"
3. Fritzing crashes
 
<Windows 10>, Fritzing 0.9.8

**Comment by KjellMorgenstern** [comment]
Could reproduce this also with Fritzing 0.9.6 on Ubuntu 20.04

**Comment by failiz** [comment]
Not sure if it is the same bug, could you check this in the development branch:
Add an Arduino Nano (3.0)  to the breadboard view
Change it to Arduino Nano (3.0) with ICSP 
Rotate it 90 degrees
Place it on the breadboard
Change it to Arduino Mini (Rev5)
Fritzing crashes in 0.9.9...
