### ISSUE TITLE
Build fails on macOS

### ISSUE THREAD

**Issue by rothn** [fritzing/fritzing-app#3877]
## Current Behaviour
The latest master build fails on macOS when trying to link frameworks, with linker errors.

## Expected Behaviour
The macOS build should complete successfully with the latest XCode

PR to fix this: https://github.com/fritzing/fritzing-app/pull/3870

**Comment by KjellMorgenstern** [comment]
This is a valid fix (actually we did the same when playing around with M1 builds). We probably will update it when we drop High Sierra support, but for now it has to wait.
