### ISSUE TITLE
[Minor, Installer] Some installer text truncated on high dpi displays

### ISSUE THREAD

**Issue by JC3** [fritzing/fritzing-app#3879]
Windows 10, 64-bit, Installer

On a display with system scaling set to 250%:

![image](https://user-images.githubusercontent.com/5651184/132954022-c8159ceb-74fa-48a8-9172-583b9b45b1dc.png)

As you can see, that text is truncated.

**THIS IS A MAJOR, SHOW-STOPPING, CRITICAL ISSUE AND WE REALLY NEED A HOTFIX IMMEDIATELY. I CAN'T BELIEVE I PAID ACTUAL MONEY FOR THIS!!!**

Just kidding, lol. This is so ridiculously minor but... ya know.

PS Worth every penny plus some. 😸❤

**Comment by KjellMorgenstern** [comment]
The glitch appears at 250% scaling first. 225% is ok. Won't fix.
