### ISSUE TITLE
core parts schematic view power nets all connect together.

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3882]
## Current Behaviour

From

https://forum.fritzing.org/t/power-symbol-connection-error/13887

On Fritzing 0.9.3b and 0.9.6 this works as expected (only 0.9.3b shown here!):

![capture](https://user-images.githubusercontent.com/16514277/133893783-b1439740-ff0a-404c-91fa-bb3660ebfe07.jpg)

![capture1](https://user-images.githubusercontent.com/16514277/133893786-b08601f8-54f6-4a6b-8289-2cd2c44f4ccf.jpg)

on 0.9.8 the 3V3 and 5V nets are connected together which is incorrect.

![capture2](https://user-images.githubusercontent.com/16514277/133893816-acb60cfc-16b9-4441-b528-cc3b7631e273.jpg)

![capture3](https://user-images.githubusercontent.com/16514277/133893819-0009c91c-3463-4a9e-ab8c-dc5f45ba2446.jpg)

**Build:**

Version 0.9.8 
(bCD-92-0-b3d4fefa 2021-08-03) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Steps to reproduce:**
- Drag a 4001 subpart IC in to the sketch
- in schematic drag a 5V power connector in to the sketch 
- then drag a 3.3V power connector in to the sketch (or dup and change the 5V one) 
- drag a 2 pin header in to be the power source and connect the 3.3V to one pin and 5V to the other
- dup the 5V power net and attach it to pin 14
- dup the 3.3V power net and attach it to pin 2
- in pcb both headers and pins 14 and 2 all connect together which is incorrect. 

## Expected Behaviour
The 5V power pin should connect to pin 14 and the 3.3V power connector should connect to pin 2.

**Comment by failiz** [comment]
My fault. My fix of the net labels broke the power symbols...
I made a pull request that fixes it.
