### ISSUE TITLE
custom wire width in schematic

### ISSUE THREAD

**Issue by spassignat** [fritzing/fritzing-app#3891]
When the schema become rich with a lot of wires, colors are not enough to identify wires easily.

Could it be possible to choose the wire width? example: to have bold wires twice larger ?
If possible, it would be nice to have stripped wires, where we can choose the two colors.

thanks

**Comment by failiz** [comment]
I do not think this is a good idea. Implementation should not be difficult (in fact, it could be that it is just disabled in the code, see #2734 ), but it is not common used in schematics. 
Schematics need to be easy to read and you should try to avoid too many different kinds of wires. I would suggest that you use power symbols (GND and power symbols) and netlists to reduce the number of wires in your schematic.

**Comment by KjellMorgenstern** [comment]
I also agree, the schematic view should not rely on colors too much. There are many other improvements we could look into, like half-automatic net and power symbols, grouping schematic elements, splitting across pages, alternative symbols ...

**Comment by spassignat** [comment]
I understand your points and I kind of agree on the general idea. Let's go back to the need and not focus too much on this color or width solutions.
My current system requires 3 boards linked together with flat cables carrying I2C, several powers level, Serial, inputs outputs... When I want to check wires are well placed, I use colors and that great but not always enough and as a developer I imagined wire width would be 'simple'.
What would be a better solution ?

**Comment by KjellMorgenstern** [comment]
Not sure if i understand your use case completely. Does this help?: If you just want to check a connection, you can press a mouse button on one end, and the complete subnet should highlight in yellow. On small zoom levels, the highlights can be hard to see. 

In general, open connections are red, and connections are green. Those colors can be changed in the preferences (eg red and blue)

**Comment by failiz** [comment]
In schematics, you just represent the logic connections. Use netlabels to reduce the number of wires. 

In breadboards, we already have an issue to be able to change the wire width, see #3594.

Maybe add a picture of your board, so we can see what the problem is.
