### ISSUE TITLE
PCB positioning in Inspector is inaccurate

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3902]
## Current Behaviour

Someone is trying to set holes in pcb view at exact coordinates but can not do so. First make sure snap to grid is disabled, so grid snapping isn't the problem:

![capture](https://user-images.githubusercontent.com/16514277/140554808-259fed2c-126b-4456-ba91-5a5ed10e1bba.jpg)

place 4 holes in pcb and try and set the top left one's X coordinate to 50mm via Inspector:

![capture1](https://user-images.githubusercontent.com/16514277/140555152-b46e72fe-940d-416b-b386-daebc7b29f59.jpg)

when the change takes place, the x coordinate is wrong:

![capture2](https://user-images.githubusercontent.com/16514277/140555362-e71e9556-dbd7-46a7-b16c-a9b69792467d.jpg)

instead of 50mm we get 49.972mm. When I do the same to the bottom left hole (set the x coord to 50mm) we get 49.985mm (same input, two different outputs!)

![capture3](https://user-images.githubusercontent.com/16514277/140555827-c9cd0d13-58d9-45de-aa85-62db72cdce2b.jpg)

entering 129 (50mm + 79mm) and 10mm on the right top hole results in 128.987mm and 10.016mm.
It would be desirable (but perhaps not possible due to floating point roundoff) to have the numbers be exact. As well it would be desirable that incrementing the value via the up and down arrows in Inspector moved in even increments (such as 1mm or .1in) which they don't at present:

![capture4](https://user-images.githubusercontent.com/16514277/140556966-e3eb2ded-3db9-4729-a04b-a363af4656d7.jpg)

1 click of the up arrow went from 128.987 to 130.009 instead of an even increment (although this is less important if exact values can be manually set!) 

![capture5](https://user-images.githubusercontent.com/16514277/140557410-deeae47e-7dfa-46b1-8a7b-680987a47644.jpg)

**Build:**

Version 0.9.9 
(bCD-348-0-f0af53a9 2021-09-22) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Steps to reproduce:**

See behaviour

## Expected Behaviour

The exact value set in to Inspector becomes the coordinate

**Comment by failiz** [comment]
Duplicate of  #3639.

**Comment by failiz** [comment]
@vanepp or @KjellMorgenstern , if you think that this is a duplicate of #3639, please, close the issue. If not, please, highlight the differences (or me, they are identical).

**Comment by vanepp** [comment]
Yes it appears to be a dup of #3639. I'll close this one.
