### ISSUE TITLE
cannot be switched between Chinese and English

### ISSUE THREAD

**Issue by shg18511968707** [fritzing/fritzing-app#3921]
## Current Behaviour
Text
<please attach screenshot if possible>
**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text
鼠标进入编辑窗口，电脑右下角输入方式中英文无法切换。

**Comment by KjellMorgenstern** [comment]
No enough information.
