### ISSUE TITLE
Ratsnest lines appearing from nowhere

### ISSUE THREAD

**Issue by civitareale** [fritzing/fritzing-app#3930]
## Current Behaviour
When deleting/moving wires on Breadboard, Ratsnest seems to appear from nowhere
https://user-images.githubusercontent.com/24688044/152539305-bf95ba8b-e9e8-4885-bd4b-2e1e9f2b8ff8.mov
https://user-images.githubusercontent.com/24688044/152539284-ea0a4dff-8609-41a1-af9b-8183f9035d8c.mov

**Build:**
Version 0.9.9 
(bCD-348-0-f0af53a9 2021-09-22) Cocoa [Qt 5.15.2]

**Operating System:**
  System Version:	macOS 12.1 (21C52)
  Kernel Version:	Darwin 21.2.0

**Steps to reproduce:**
When deleting/moving wires on Breadboard, Ratsnest seems to appear from nowhere

## Expected Behaviour
Not having lots of ratsnest lines when changing the Breadboard wires

**Comment by RadioFlakes** [comment]
I have the same problem! If I move a component on the breadboard it creates an erroneous ratsnest line on the schematic that cannot be deleted, if I delete the erroneous ratsnest on the schematic, then the component on the breadboard jumps out of position and when you place the component back into position on the breadboard, the erroneous ratsnest on the schematic reappears! It cannot be deleted for it recreates itself on the other environment, ad infinitum!!!

**The schematic is: TO BE UNTOUCHABLE! A CHISELED IN STONE REFERENCE THAT IS NEVER EVER TO BE TOUCHED BY THE SOFTWARE ALGORITHM! IT SHOULD ONLY CAN BE EDITED MANUALLY BE THE CREATOR!!! WHY WOULD ANYONE CREATE A PROGRAM THAT EDITS THE SCHEMATIC AUTOMATICALLY FROM THE BREADBOARD ENVIRONMENT? THAT IS BATSHIT CRAZY!!!**
