### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Djeremaille** [fritzing/fritzing-app#3934]
## Current Behaviour
I'm unable to launch Fritzing. It only works with sudo.
Segmentation fault error

**Build:**
Version 0.9.9 (bCD-348-0-f0af53a9 2021-09-22) 64 [Qt 5.15.2]

**Operating System:**
Kde Neon 5.24 64bits (based on ubuntu 20.04)

**Steps to reproduce:**
Start Fritzing

## Expected Behaviour
Fritzing working without sudo.

**Comment by failiz** [comment]
Could you specify if this is the official build and how you are starting Fritzing?

**Comment by KjellMorgenstern** [comment]
Fritzing does not need admin or sudo rights to run. Of course, it might need, if the system is messed up (eg. some important files and directories can only accessed by root).
