### ISSUE TITLE
accelerator keys for menu items (&...) need cleaning up

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#395]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 20, 2008 11:59:08_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=395_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
