### ISSUE TITLE
Opensuse-Installation of Fritzing not working out of the box

### ISSUE THREAD

**Issue by hp4** [fritzing/fritzing-app#3951]
## Current Behaviour
Problem : parts.db does not exist => Fritzing starts but complains about missing parts
**Build:**
Version 0.9.4 
( ) 64 [Qt 5.15.2]

**Operating System:**
Opensuse Tumbleweed

**Steps to reproduce:**
- install via yast
- click Fritzing icon

## Expected Behaviour
Startup without errors

concept questions:
- where should the parts be installed ? /usr/share/fritzing ? /home/user/Documents/fritzing..... ?
  own parts for every user or central parts by root? Should be reflected somehow in the startup-icon. 
  Description?
  
- trying to build the parts.db by using the -db option complains about missing git and missing SHA-value.
  is that an opensuse-package-problem or a fritzing-problem? can a fritzing release be build without git?
  
- copying a parts.db from offical git-repository to ~/Documents/fritzing.... can read the parts db, but
  online update is not possible and complains about missing access rights although user has access to his own directory

**Comment by KjellMorgenstern** [comment]
Fritzing is funded via the support for the official build on https://fritzing.org/download
Our official AppImage will work fine on OpenSuse Tumbleweed (64bit).

**Comment by hp4** [comment]
ok, thanks (maybe I should write a bug report to opensuse to remove the yast-package from the official repository)
