### ISSUE TITLE
Error 500 in the Fritzing Discussion Board

### ISSUE THREAD

**Issue by BastianFie** [fritzing/fritzing-app#3952]
I´m sorry for posting this here into the Fritzing GitHub section but I do not found another option to report that: Since some days I couldn´t post anything into the Forum. All I get is an error 500:

![temp](https://user-images.githubusercontent.com/5032669/172702174-8b66c05a-eb4c-4994-8c75-b978ffa29114.jpg)

I already tried multiple browsers, reboot, deletion from cache, ... could that be fixed?

**Comment by KjellMorgenstern** [comment]
Thank you for reporting, I have fixed the forum server, and posts should work again. Also, I updated discourse from 2.8 to 2.9.

**Comment by BastianFie** [comment]
> Thank you for reporting, I have fixed the forum server, and posts should work again. Also, I updated discourse from 2.8 to 2.9.

thanks for the quick fix!
