### ISSUE TITLE
Schematic view will no longer increase the scroll area when adding new parts. 

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3959]
## Current Behaviour

This is actually the .fzz file, so just remove the trailing .zip to get the .fzz file.

[EC-PH System Wire-PCB Diograme V7.fzz.zip](https://github.com/fritzing/fritzing-app/files/8969939/EC-PH.System.Wire-PCB.Diograme.V7.fzz.zip)

On 0.9.3b and 0.9.6 the default schematic looks like this on initial load:

![capture](https://user-images.githubusercontent.com/16514277/175369189-93d4a7de-a345-4ada-955e-d03442b62852.jpg)

then I added a part near the bottom edge (this is on 0.9.3b)

![capture1](https://user-images.githubusercontent.com/16514277/175369413-a1b501d0-1d15-49b3-9011-fc9f03eadfa2.jpg)

then I clicked on the part and dragged it down, the window scrolls up (as desired) and adds more scroll room to schematic window as long as the mouse is near the bottom edge of the schematic window. 

![capture2](https://user-images.githubusercontent.com/16514277/175369930-cdc2632f-2ca3-4e23-ab4b-ea85d22ff5a9.jpg)

The downwards green arrow is me dragging the part downwards. The up green arrow is Fritzing increasing the size of the schematic scroll window automatically (which no longer happens on 0.9.10!)

Then I switched to 0.9.10 (0.9.9 acts the same as 0.9.10)

doing the same thing (adding the part and dragging it down) gets a circle with a diagonal line through it and the scrolling window does not increase.

![capture3](https://user-images.githubusercontent.com/16514277/175370992-4882e689-a46a-4b47-b0e6-c92435347b81.jpg)

 clicking on the part and dragging it down will move it off the screen like this, but then I can't find a way to scroll down to it (as happens automatically in 0.9.3b) 

![capture4](https://user-images.githubusercontent.com/16514277/175372092-75632c49-f66f-4226-aa13-be8b60a29bbf.jpg)

even scrolling in and out doesn't change the boundaries of the scroll window and thus I can't add parts to the sketch. 

![capture5](https://user-images.githubusercontent.com/16514277/175372361-4cd8395b-dcd5-47d0-83af-e3272b17a857.jpg)

**Build:**

Version 0.9.10 
(bCD-1801-0-29c2cede 2022-05-14) 64 [Qt 5.15.2]

**Operating System:**

Windows 10

**Steps to reproduce:**

in Current Behaviour section

## Expected Behaviour

That the size of the schematic scroll window increases (and preferably keeps increasing as long as the mouse is at the bottom of the window) as happens in 0.9.3b.

**Comment by KjellMorgenstern** [comment]
This was a regression introduced in 0.9.10, build 1801 (windows and linux) and build 1807 (macos).
Reverting 87c19ea86 fixes this. I created a new build, 0.9.10 build 2134 (windows, linux and mac). 

If you are affected by this, and have 0.9.10 build 180x, you can download build 2134 from https://fritzing.org/download . The new build is the default.
Windows users: When you install build 2134 over build 1801, the installer will ask how you want to proceed. Choose "repair".
