### ISSUE TITLE
Setting a pin as a ground seed in pcb adds the connection to the ground fill but not the ground net

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#3961]
## Current Behaviour

More info in 

https://forum.fritzing.org/t/parts-apart-from-the-pcb/16552/

the sketch fritzing-beispiel.fzz which created the images below is available there.

The user looks to have added ground seeds for two header pins in pcb view. The ground fill connected both pins to ground, but doesn't appear to have added them to the ground net. The result is  the rats nest lines don't appear in pcb, schematic and breadboard for the pins connected to ground in pcb. Selecting each ground fill seed should (I think anyway!) light all the ground connections, but it does not:

![capture](https://user-images.githubusercontent.com/16514277/178824202-47db5aba-e338-40ca-8938-a01d5e79b229.jpg)

![capture1](https://user-images.githubusercontent.com/16514277/178824230-dab17fff-dcfe-479d-b0eb-2251996b9005.jpg)

![capture2](https://user-images.githubusercontent.com/16514277/178824259-ca3abee6-7440-4f8e-8059-e43f90ca9de4.jpg)

the red arrows on the last two images show where I believe there should be rats nest lines.  To verify that I made a connection to the currently unconnected header pin in breadboard:

![capture3](https://user-images.githubusercontent.com/16514277/178824574-df7024bb-dd88-43c3-8e5f-d75373fad1cd.jpg)

which indeed causes the rats nest line to appear as expected in pcb

![capture4](https://user-images.githubusercontent.com/16514277/178824656-b426ad4e-378a-476d-9d91-8a91b450fe49.jpg)

**Build:**

Version 0.9.10 
(bCD-1801-0-29c2cede 2022-05-14) 64 [Qt 5.15.2]

**Operating System:**
Windows 10

**Steps to reproduce:**

see Current Behaviour

## Expected Behaviour

Adding the ground seeds should add the pins to the ground net causing rats nest lines to appear in schematic and breadboard views.

**Comment by KjellMorgenstern** [comment]
Related: https://github.com/fritzing/fritzing-app/issues/2304

Problem underneath both tickets: Ground fill seeds are not treated as connections. Both issues should be solved by my suggested solution to #3794 , see 'Mini feature spec'

**Comment by vanepp** [comment]
"Problem underneath both tickets: Ground fill seeds are not treated as connections. Both issues should be solved by my suggested solution to https://github.com/fritzing/fritzing-app/issues/3794 , see 'Mini feature spec'"

I agree, I'll close this ticket as a duplicate.
