### ISSUE TITLE
Icon of custom bins are lost after restart

### ISSUE THREAD

**Issue by spassignat** [fritzing/fritzing-app#3969]
Hello,

I created several bins with parts inside and produce the related fzbz files. Import works well, parts works, ... and the bin icons are properly displayed.

When I shutdown Fritzing, I save everything (bins, parts, ...). Then when I restart Fritzing, the bin are still present but their icons are lost. 
To keep icons I need to add them along side other bin icons (Arduino.png...)

thanks

**Comment by failiz** [comment]
Related to #1702

**Comment by KjellMorgenstern** [comment]
Closing in favor of #1702
