### ISSUE TITLE
Arduino pcb image improvement

### ISSUE THREAD

**Issue by spassignat** [fritzing/fritzing-app#3970]
## Problem
When I layout a card, I always need to look at arduino pinout to know where are the usb,usart connector.

## Proposed Solution
Could it be possible to enhance the pcb image adding a symbol for these connectors ? (simple square is fine)

thanks

**Comment by KjellMorgenstern** [comment]
Something like this? 
![image](https://user-images.githubusercontent.com/6494025/185798181-452f1bf6-cf71-433a-bb02-2a61cb247a7d.png)

**Comment by spassignat** [comment]
I was thinking more about something like this:
![image](https://user-images.githubusercontent.com/6451374/185808410-b87f1490-c326-4367-a225-1e1d3f42007e.png)

**Comment by KjellMorgenstern** [comment]
I don't understand, why don't you add the labels then? Or is the request about changing a fritzing part file? Then it would help to move this issue to the fritzing-part repo, and name the exact file that should be improved.

**Comment by spassignat** [comment]
Hello,
You're right. It should move this to fritzing-part repo. I'm not sure I can move cases from repo to repo. 
Can you do this, for me ?

thanks
