### ISSUE TITLE
[Bug or not?] Errors on export (empty layers)

### ISSUE THREAD

**Issue by Tornix242** [fritzing/fritzing-app#3986]
Hi there!

My first project was nice and great, PCBs export and manufacturing/delivery went great with 3 different versions. So thanks a lot about it!

Today, I'm trying to export (Gerber files) a second project but Fritzing seems to encounter errors. Those errors mention empty layers (copper0, copper1, masks, holes, silks, etc...).

It can't figure out why. Perhaps I did something wrong while I thought I made this design the very same way the first that did great.

Here is the file : https://www.swisstransfer.com/d/ead62de7-7494-4124-a5a2-cb0d8775361c

All the best,
Tornix

**Comment by KjellMorgenstern** [comment]
Can you please upload the file here?
Also, please explain why you think it is a bug, empty layers are possible. Without looking, I would guess you have multiple boards in your project, one of them empty.
