### ISSUE TITLE
Edit Wiki file “1.-Building-Fritzing.md”

### ISSUE THREAD

**Issue by buscacomponentes** [fritzing/fritzing-app#3992]
## Problem
Wiki file “1.-Building-Fritzing.md” is outdated in libgit2 version and I suggest some improvements in it via a patch.

## Proposed Solution
Apply the patch at https://pastebin.com/raw/fqJ5cMQn

**Comment by KjellMorgenstern** [comment]
Latest libgit2 version will cause problems. We don't recommed using boost from system, but to install your own version.
