### ISSUE TITLE
Documentation Update - Software Download

### ISSUE THREAD

**Issue by ThePieMonster** [fritzing/fritzing-app#3997]
Update the [Wiki - Download Qt](https://github.com/fritzing/fritzing-app/wiki/1.-Building-Fritzing#download-and-install-qt) page to have the direct download links below:

https://www.qt.io/offline-installers

https://download.qt.io/archive/qt/5.12/5.12.12/qt-opensource-windows-x86-5.12.12.exe

**Comment by KjellMorgenstern** [comment]
The official qt download link is already on the wiki page.
