### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by mitko-kamburow** [fritzing/fritzing-app#3998]
Hello,
I decided to build fritzing 0.9.10 from source and I got to this point: 

![Screenshot from 2023-01-29 21-08-47](https://user-images.githubusercontent.com/99120262/215350001-ffddedb8-beeb-4d99-827d-862449da5f4c.png)

**OS: Ubuntu 22.04**

I have quazip-1.4 and libquazip5-dev installed.
I'm not very sure what to do, so please help me.

Regards,
Mitko Kamburow

**Comment by jsrobson10** [comment]
could you please post what you did to solve this issue? i am experiencing this. i am on arch and have quazip-qt6 installed but I am getting `quazip could not be found` in the issues tab. 

edit: this fixed it for me. i was actually using qt5. 
1. download https://github.com/stachenov/quazip/releases/ (i used v1.4)
2. extract it to the same directory that the fritzing-app directory is in
3. make a build folder in quazip, enter it, run `cmake ..` and `make`
4. rename the `quazip-x` folder to `quazip_qt5`
5. build with `qmake "INCLUDEPATH+=../quazip_qt5/quazip/"` and then `make`
