### ISSUE TITLE
Mouse pointer strange behaviour

### ISSUE THREAD

**Issue by Motomanual** [fritzing/fritzing-app#4037]
Hello, just installed version 1.0.0-1457Win64 but found a strange behaviour of the mouse pointer when focused on a component on breadboard and drawing sections (pointer looks like two orizontal lines).
Already sent a mail to 'support@fritzing.org' with a short video showing the issue, that was not present on previous versions and make complex connect wires to components.
Additionally in the Code section the drop down menu used to select platform/card/port, words appear in black color on dark gray background (almost unreadable).
The mouse problem appear on a specific laptop below ireported and just in the indicated sections, color problem appeared on all pc I have tested.
O.S. - Windows 10 V19045.3086
PC Lenovo Ideapad Ryzen 7
Thanks and best regards

**Comment by Motomanual** [comment]
https://github.com/fritzing/fritzing-app/assets/137813515/13baee7c-2e8e-45e0-b2f6-30d5cf43f2b5

**Comment by KjellMorgenstern** [comment]
Can you check the integrity of Fritzing? Reachable by right clicking, ( https://chat.openai.com/share/ce4247fa-e95c-4188-b612-21fc64c1f7a1 ) . Certificate should be to Fritzing GmbH.

Were there any error messages when installing on the Ideapad?

**Comment by Motomanual** [comment]
Hello, thanks for Your answer!
I checked the integrity as requested and the certificate is correct (I download the file from the link supplied by Fritzing several times).
During installation any error message appeared (checked several times), previous versions don't have this problem.
Thanks and best regards.

**Comment by failiz** [comment]
I have seen this bug in a few computers from my students (all running 1.0.0).

**Comment by KjellMorgenstern** [comment]
Unfortunately I have never seen it yet. Were all the students using Windows? And can you check if it was Windows 10, maybe even build 19045 like in the first post?

**Comment by failiz** [comment]
I think all of them were on Windows. I took some pictures of one of them. I will try to find more tomorrow.
![IMG_20230717_144855](https://github.com/fritzing/fritzing-app/assets/5708642/330b5730-3fea-46b4-a656-956639dad38f)
![IMG_20230717_144904](https://github.com/fritzing/fritzing-app/assets/5708642/7ebaabe0-0ad1-4c49-a501-2b74a19e2ca8)
![IMG_20230717_144921](https://github.com/fritzing/fritzing-app/assets/5708642/115f9c3e-852e-43ef-8fe7-6c059c8eada3)

**Comment by failiz** [comment]
Another computer with the same problem.
![IMG_20230718_115539](https://github.com/fritzing/fritzing-app/assets/5708642/1e759d8d-5f43-4603-abef-17a863cdedae)
![IMG_20230718_115549](https://github.com/fritzing/fritzing-app/assets/5708642/c6632c44-8d27-4e1d-b781-9da2acd1288a)
![IMG_20230718_115619](https://github.com/fritzing/fritzing-app/assets/5708642/84c152a7-2615-424c-aa5d-48fd5a7b8322)

Let me know if you need more info.

**Comment by KjellMorgenstern** [comment]
Are there any Windows PC where it does work? 

One thing suspicious is that the cursors are encoded as binary bitmap
`make_wire.bmp: PC bitmap, Windows 3.x format, 32 x 32 x 1, image size 130, resolution 2834 x 2834 px/m, cbSize 192, bits offset 62`
Maybe that is too outdated for some graphics drivers, but just pure speculation here.

**Comment by Motomanual** [comment]
Hello, in my case there are other 3 (older) laptops with same Windows version that don't have any problem.
In the newest laptop the problem appear just with Fritzing version 1.0.0, older versions (included 0.9.10 that's Im actually using) dont have any problem and suppose the cursor bitmap is the same...
What about the QT version?

**Comment by KjellMorgenstern** [comment]
Indeed, no changes for the bitmaps. Qt docs warn that QGuiApplication must be created before the Cursor, but this also did not change from Qt5 to Qt6. Fritzing is build with qt6 since 1.0.0

Another guess could be that upscaling the cursor does not work, which would then show mostly on notebooks with HiRes displays.

**Comment by Motomanual** [comment]
It could be, are there any test to be done?
Thanks.

**Comment by failiz** [comment]
> Are there any Windows PC where it does work?

I have 23 students and around half of them (or 40%) are MacOS users. From the around 12 or 14 Windows users, I have seen this bug in two or maybe three computers. In the other ones, it works correctly.

**Comment by jfmorgenstern** [comment]
I was able to reproduce the bug by adjusting the display scaling to a non-integer scaling factor of 100%, such as 175%.

![grafik](https://github.com/fritzing/fritzing-app/assets/18153740/e4dc916f-1e5f-40bb-88dc-c99da229e38b)

Tested on Windows 11, multi-monitor setup. One Monitor was set to 100% scaling, the other to 175%
![grafik](https://github.com/fritzing/fritzing-app/assets/18153740/34c12f70-b8d1-48b2-a1e6-d30c0b408296)

**Comment by Motomanual** [comment]
You're right, the suggested scaling setting of my monitor is 125% but changing to 100% the problem disappear, unfortunately with this scaling setting there are reading problem with other programs..
An additional issue that forgot to report is that, after installation, the resolution of version 0.9.10 and 1.0.0 is quite different as shown on below pictures (scaling 125%, 1.0.0 is bigger).
![Fritzing 1 0 0](https://github.com/fritzing/fritzing-app/assets/137813515/9cc313eb-a06e-48f6-acf1-99de5c8e2e1e)
![Fritzing 0 9 10](https://github.com/fritzing/fritzing-app/assets/137813515/c55b5910-dc2b-469e-bd6a-abf603947a6e)

**Comment by jfmorgenstern** [comment]
This could be related to the switch to QT6.

As a workaround until we fix this, you could try to change the high DPI settings in the compatibility tab.

1. Right click on Fritzing shortcut
2. Select Properties
3. Select Compatibility tab
![grafik](https://github.com/fritzing/fritzing-app/assets/18153740/08a4a0ae-6b61-48c3-bf68-0b13bdb7e033)
4. Set High DPI scaling override to "Sytem" or "System Enhanced"
![grafik](https://github.com/fritzing/fritzing-app/assets/18153740/16b10423-72e5-437b-97de-71d3a1874dab)

This fixes the cursor for me.

**Comment by Motomanual** [comment]
With this setting the cursor probem is fixed also for me, the resolution of this version remain bigger compared to 0.9.10 but now is possible to use it.
Thanks for your support!

**Comment by Motomanual** [comment]
Hello, in my first post I mention another problem 'Additionally in the Code section the drop down menu used to select platform/card/port, words appear in black color on dark gray background (almost unreadable).' and don't know if is necessary open a new issue, here a picture showing it.
![Fritzing 1 0 0](https://github.com/fritzing/fritzing-app/assets/137813515/1dfa590d-e178-4ada-8eca-2b15f5891a83)

**Comment by KjellMorgenstern** [comment]
Of course it is, split the problems. Thats what the issues are for.

**Comment by failiz** [comment]
Probably, it would be a good idea to add this bug and the workaround to the list of known issues.

**Comment by KjellMorgenstern** [comment]
I added it: https://fritzing.org/download/known-issues/

**Comment by KjellMorgenstern** [comment]
Switched the cursor from Bitmap to Pixmap representation. Pixmap can be scaled correctly. It looks like the issue does not occur on other systems because they don't try to scale the cursor, it just stays at 100%

**Comment by Spinky1001** [comment]
I started using Fritzing yesterday and I also  have this problem with the cursor.
Tried all the suggestions above but still not working properly.
Not sure what last comment means - how do you switch the cursor from Bitmap to Pixmap?
Any further ideas?
Windows 10 home edition.
