### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by bsbhro** [fritzing/fritzing-app#4044]
## Current Behaviour
Hello, my attempt to compile ends with this error. I do not have c++ skills.
---snip
src/sketch/sketchwidget.cpp: In member function ‘virtual long int SketchWidget::setUpSwap(SwapThing&, bool)’:
src/sketch/sketchwidget.cpp:5962:12: error: ‘partLabel’ was not declared in this scope; did you mean ‘PartLabel’?
 5962 |         if(partLabel != nullptr) {
      |            ^~~~~~~~~
      |            PartLabel
---/snip
**Build:**
latest code
**Operating System:**
Ubuntu 23.04
**Steps to reproduce:**
- Step 1: git pull, qmake
- Step 2: make

Thank you for this software and any help.

**Comment by DJManas** [comment]
Workaround, until solved.

Renamed partLabel to oldPartLabel on this line. It compiles, but dunno if it is needed (don't have time to get into whole code). App seems to be working.

**Comment by supercairos** [comment]
I have the same issue.

**Comment by bsbhro** [comment]
I cloned new and the error is gone. Thank you very much!
