### ISSUE TITLE
Low Code menu readability

### ISSUE THREAD

**Issue by Motomanual** [fritzing/fritzing-app#4045]
## Current Behaviour
In the CODE section the drop down menu used to select platform/card/port, options appear in black color on dark gray background (almost unreadable).
**Build:**
<Version 1.0.0 (rcCD-4157-0-6b14cfe 2023-06-02) 64 (Qt6.4.3)

**Operating System:**
<Windows 10 V19045.3086>

![Fritzing 1 0 0](https://github.com/fritzing/fritzing-app/assets/137813515/7aa327ca-db37-45a6-9650-6fe5364876ea)
Problem appear with dark and light theme and was not present on previous versions.

**Comment by jfmorgenstern** [comment]
I could reproduce this on Windows 11.

**Comment by Motomanual** [comment]
Are there any settings to improve the readability?

**Comment by KjellMorgenstern** [comment]
It should look like this in dark mode, tested with 1.0.2, but on Linux:

![image](https://github.com/fritzing/fritzing-app/assets/6494025/8ee6d638-03c9-467d-8e1e-f51af349c5c0)
