### ISSUE TITLE
Icon Changes to Garbage when active

### ISSUE THREAD

**Issue by robodoc24** [fritzing/fritzing-app#4054]
## Current Behaviour
Whenever an action is possible, the mouse pointer turns into a bunch of random lines. See attached picture of what it looks like.

**Build:**
Version 1.0.0 (rcCD-4157-0-6b14cfe9 2023-06-02) 64 [Qt 6.4.3]

**Operating System:**
<Windows 11>

**Steps to reproduce:**
It seems to always happen

## Expected Behaviour
Pointer changes to lines
![20230820_163500](https://github.com/fritzing/fritzing-app/assets/24609047/4c61df95-4932-46e1-85c0-47a6bdc01b32)

**Comment by KjellMorgenstern** [comment]
This looks like a duplicate of #4037 . Can you try the solution suggested there?

**Comment by robodoc24** [comment]
Worked like a charm.
