### ISSUE TITLE
PNP (Pick-and-Place) file is not a common Format (XLS,XLSX,CSV, etc.)

### ISSUE THREAD

**Issue by brdane** [fritzing/fritzing-app#4056]
## Problem
PCB manufacturers like JLCPCB cannot accept the .xy file format that Fritzing exports.

## Proposed Solution
Implement exporting of the PNP file to XLS, XLSX and CSV... along with the existing .xy format

**Comment by KjellMorgenstern** [comment]
The xy file is in csv format.

**Comment by brdane** [comment]
Even if JLCPCB is unable to load it?

**Comment by KjellMorgenstern** [comment]
Why can't they load our CSV?

**Comment by brdane** [comment]
I am not sure why. All I know is that I took the .xy file, changed the extension to CSV since that is what they accept, but it still does not upload for some reason. 

![Unbenannt](https://github.com/fritzing/fritzing-app/assets/67879478/27e277c6-a0e6-40c7-842e-fd94205952f5)

**Comment by KjellMorgenstern** [comment]
From the screenshots, it looks like you tried to upload the bill of materials, not the pick and place file.

**Comment by brdane** [comment]
The one on the left is indeed the bill of materials but there is another upload on the right for the PNP file, which you see I uploaded too.

**Comment by KjellMorgenstern** [comment]
From the error message I can see as much information as you. Maybe contact jlcpcb support about it?

**Comment by brdane** [comment]
Contacted their support and they said that both BOM and PNP files are a different format/layout than what fritzing generates. In the screenshots below I have the BOM/PNP on one side and JLCPCB's example BOM/PNP that they accept. Labels are different, there seems to be a lot of information that they, in-particular, do not need.



![bomcompare](https://github.com/fritzing/fritzing-app/assets/67879478/edec4496-5af0-4cdb-be19-5dbcfcb9c290)
![pnpcompare](https://github.com/fritzing/fritzing-app/assets/67879478/a3c840ac-70b3-416a-99eb-6136db47cbce)

**Comment by brdane** [comment]
For the PNP screenshot, my version of Excel (for some reason) opens its incorrectly, but it does show correctly in LibreOffice Calc. Regardless, JLC can't upload it. Their support member even made modifications to it as well and asked me to upload, but it also did not work.

**Comment by brdane** [comment]
Would it help your team if I uploaded JLC's example BOM/PNP files as well as other ones?
