### ISSUE TITLE
Realtime PCB Shape Modification

### ISSUE THREAD

**Issue by brdane** [fritzing/fritzing-app#4060]
## Problem
The process for having a custom printed circuit board in fritzing requires at least one addition piece of software to create the needed SVG file to import into fritzing.

## Proposed Solution
Have fritzing's PCB designer be able to allow the user to edit the PCB's shape, add points on edges, drag them to change the shape, enter in measurements for how long certain edges can be, import pictures to be able to easily trace a shape, from said picture, etc.

**Comment by KjellMorgenstern** [comment]
Scope of this issue is too wide. Implementing inkscape or something like https://yqnn.github.io/svg-path-editor/ comes to mind. Closing in favor of #2027 and #3320
