### ISSUE TITLE
Unreadable popup menus. 

### ISSUE THREAD

**Issue by def1149** [fritzing/fritzing-app#4072]
## Current Behaviour
Unreadable popup menu. 
This is the first time I've ever used fritzing. The UI is atrocious

![image](https://github.com/fritzing/fritzing-app/assets/3155291/9cc3d2d6-9bbe-44fd-9b8a-da96d4c7c13f)
**Build:**
Version 1.0.1 
(rcCD-1654-0-8f5f1373 2023-09-06) 64 [Qt 6.4.3]

**Operating System:**
Windows 11

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Readable menus

**Comment by KjellMorgenstern** [comment]
Duplicate
