### ISSUE TITLE
Question: Which version of Qt should I use to compile fritzing?

### ISSUE THREAD

**Issue by lshqqytiger** [fritzing/fritzing-app#4074]
I initially tried to compile using Qt 6.5.3. However, a few minutes later, it failed with a specification compatibility error with Qt. And I followed Wiki and tried to compile using Qt 5.12.2. This time, it failed with another specification compatibility error with Qt in less than a minute. I think the Qt version this requires will be at least 6.x and I'm installing 6.4.3 now. Where is the appropriate Qt version specified for compiling fritzing?

**Comment by lshqqytiger** [comment]
I was able to compile fritzing with Qt 6.4.3.

**Comment by pizzapi2012** [comment]
how did you compile
