### ISSUE TITLE
my parts not showing

### ISSUE THREAD

**Issue by xamenoss** [fritzing/fritzing-app#4080]
## Current Behaviour 
my parts not showing
when i re-open .fzpz files i get reply:
there is already a part with id ....... loaded into Fritzing.
Text
<please attach screenshot if possible>
![20231110_185209](https://github.com/fritzing/fritzing-app/assets/74813350/dfbf152c-53ad-4d19-838b-7a441252042c)

**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text

**Comment by vanepp** [comment]
That means you have a copy of the fzpz file already loaded. If it isn't in your mine parts bin (which is the default place for loaded parts) try a search like this:

![capture](https://github.com/fritzing/fritzing-app/assets/16514277/f7f59e2b-a06b-4032-a1ed-9c9396759cf4)

that will find parts that were saved but not to the mine parts bin. Note I am assuming Fritzing 1.0.1 here (as you didn't change the default build version and OS fields in your post) although older versions should act the same.
