### ISSUE TITLE
A sch wire does not snap to grid for existing wires

### ISSUE THREAD

**Issue by failiz** [fritzing/fritzing-app#4091]
## Current Behaviour
Prepare this circuit and try to snap the sch wire to the bendpoint between the resistors:
![image](https://github.com/fritzing/fritzing-app/assets/5708642/c8b1f4ca-7259-411a-8e8b-2bebf2ffca89)
![image](https://github.com/fritzing/fritzing-app/assets/5708642/72383ca6-87dd-49c4-9b36-1f65b1c7cf47)
![image](https://github.com/fritzing/fritzing-app/assets/5708642/6543d65f-dfb7-4c31-a60f-8ce5c6205f92)

After the connection, the bendpoint moves out of the grid.

This is related to the https://github.com/fritzing/fritzing-app/issues/3738 and https://github.com/fritzing/fritzing-app/issues/3602 
Note that if the wire is created, then the bug does not happen

**Build:**
Fritzing 1.01, Windows 

## Expected Behaviour
The bendpoint remains on the grid

**Comment by KjellMorgenstern** [comment]
Found a fix, looks like we can even still add this to 1.0.2.
Problem was similar to the other mentioned issues ("from" and "to" need to be swapped) , but a different place in the code.
