### ISSUE TITLE
Linux side scrolling no longer works on Fritzing 1.0.1

### ISSUE THREAD

**Issue by benreu** [fritzing/fritzing-app#4096]
## Current Behaviour
side scrolling on mice no longer works

**Build:**
fritzing-1.0.1-l1653-8d480a18-qt6

**Operating System:**
Linux Mint 21 Cinnamon

**Steps to reproduce:**
Push the mouse scroll wheel sideways

## Expected Behaviour
The view will scroll left and right

**Comment by benreu** [comment]
Side scroll worked on 0.9.10 and no longer works in 1.0.0

**Comment by KjellMorgenstern** [comment]
Which setting do you use for scrolling / zooming? 

`Preferences -> General -> Mouse Wheel Behavior`

**Comment by benreu** [comment]
That did it. I was using the default, and wasn't aware that could even be changed. I may have tried it way back, and forgot it again.
![Screenshot from 2023-12-23 06-31-09](https://github.com/fritzing/fritzing-app/assets/24444193/8e792f7a-8d0b-4a08-ba1f-2ffc73c7cf35)

This setting now removes one of the gripes I had with Fritzing. That it scrolled way too slow.

![Screenshot from 2023-12-23 06-30-04](https://github.com/fritzing/fritzing-app/assets/24444193/60b896d1-ec6f-4798-b471-fda1af2409ec)

Thanks for the quick response.

**Comment by benreu** [comment]
Out of curiosity I went back to 0.9.10, and I see there are only 2 mouse options. 1.0.0 has 4 options.

**Comment by KjellMorgenstern** [comment]
We added the other two options in 1.0.0 , along with support for pinch gestures on MacBooks and other touchpads.
