### ISSUE TITLE
-1: error: LNK1104: cannot open file 'quazip1-qt6.lib'

### ISSUE THREAD

**Issue by axelklaudedelgado** [fritzing/fritzing-app#4105]
When trying to build using Qt Creator, I get this error. I do have the file and its library is there

-1: error: LNK1104: cannot open file 'quazip1-qt6.lib'

**Comment by MKK4559** [comment]
How did you solve this issue?

Edit: I solved the issue by adding "LIBS +=" then the directory of my quazip1-qt6.lib file in quotation marks into the .pro file.

**Comment by AnasDorgham11** [comment]
> How did you solve this issue?
> 
> Edit: I solved the issue by adding "LIBS +=" then the directory of my quazip1-qt6.lib file in quotation marks into the .pro file.

Where could I find this file, please? Sorry, I am totally new to the world of Qt.
