### ISSUE TITLE
Debug Assertion Failed!

### ISSUE THREAD

**Issue by kaamburoow** [fritzing/fritzing-app#4106]
## Current Behaviour
It spits this error when loading a sketch: 
Debug Assertion Failed!

Program: C:\Users\Mitko\Desktop\fritzing\release64\Fritzing.exe
File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp
Line: 904

Expression: _CrtIsValidHeapPointer(block)

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
![image](https://github.com/fritzing/fritzing-app/assets/132601893/c52ad37b-d433-4a72-81de-b583be5b9c46)

**Build:**
Version 1.0.2 (b0.9.6-1875-gdbdbe34c 2023-12-20) 64 [Qt 6.5.3]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
- Build fritzing release
- Open a fritzing sketch(even example would work)

## Expected Behaviour
Open the sketch without any errors.

**Comment by KjellMorgenstern** [comment]
Can you reproduce this with the official build? 

Does it happen with any sketch, or a specific one?

**Comment by kaamburoow** [comment]
@KjellMorgenstern I don't have the official build, but it happens with every sketch.

**Comment by KjellMorgenstern** [comment]
Can not reproduce.
