### ISSUE TITLE
tooltip colors are so similar

### ISSUE THREAD

**Issue by andreruz** [fritzing/fritzing-app#4109]
## Current Behaviour
Tooltip colors are dificult to read. im on windows 11, background are black and font is dark gray.
![Captura de tela 2024-01-27 204130](https://github.com/fritzing/fritzing-app/assets/833239/5853d3fb-2774-4ff9-86f5-62a7eb7427bc)

**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>

**Steps to reproduce:**
add any component
mouse hover any connector.

## Expected Behaviour
the tooltip is with better contrast, or any place to customize this.

**Comment by KjellMorgenstern** [comment]
Version 0.9.3 is 8 years old, please try a recent version

**Comment by failiz** [comment]
Looks like ir happens in dark mode on Windows 11 with 1.0.2
https://forum.fritzing.org/t/font-colour-and-background-colour-of-the-tooltip-so-similar-that-the-text-is-not-visible/22178

**Comment by KjellMorgenstern** [comment]
Affects tooltip of connectors

While on it, TOTD has a very dark shadow. Happens when window is resized so that scrollbars disapear.

![image](https://github.com/fritzing/fritzing-app/assets/6494025/2c85e764-6019-4ac7-b8ed-b11110e0f303)

**Comment by KjellMorgenstern** [comment]
Related #4093

**Comment by tyeth** [comment]
Makes it totally unusable. Had to switch off dark mode in Windows.
