### ISSUE TITLE
What version of Qt is required? 

### ISSUE THREAD

**Issue by rcarteraz** [fritzing/fritzing-app#4121]
What version of Qt is required to build from source? Your instructions say 5.5.12, however after installing that version I get an error that it requires at minimum 6.4.3. So, I install 6 via brew which they currently have as 6.6.2_1. I try to build again and it comes back saying I can't use a higher than 5.5.12, the version I just had. 

What gives? Which version? Why are your instructions so out of date? 

It would appear you all make it considerably harder than it should be to build from source... I wonder why that is?

**Comment by KjellMorgenstern** [comment]
Required Qt version at time of this writing is Qt 6.5.3 , please see the .pro file.

**Comment by bunnypranav** [comment]
> Required Qt version at time of this writing is Qt 6.5.3 , please see the .pro file.

Then why is that in the documentation for [https://github.com/fritzing/fritzing-app/wiki/1.3-Linux-notes](linux) you have this:
```
sudo apt-get install build-essential git cmake libssl-dev libudev-dev qt5-default libqt5serialport5-dev libqt5svg5-dev
```
which suggests to install qt 5 libraries?
