### ISSUE TITLE
Unable to place components in list mode

### ISSUE THREAD

**Issue by Clavdiv** [fritzing/fritzing-app#4123]
![Fritz mode](https://github.com/fritzing/fritzing-app/assets/161802568/6da36f68-3b90-4bbc-bcb9-87cf1ef7c616)
Please let me know - me - beginner level ....
Only way to capture this was with a photographic camera - mobile phone

**Comment by KjellMorgenstern** [comment]
Bug template was ignored, exact version of Fritzing and also the exact OS version are missing.

**Comment by KjellMorgenstern** [comment]
Can reproduce it on Ubuntu 22.04, current development branch. 
The mouse cursor in the screen photo looks different, so at least one more configuration is affected.

**Comment by Clavdiv** [comment]
Peter Van Epp VANEPP suggested I forward this problem on to you - it is real and unfortunate - hope you have a fix - Fritzing ver 1.0.2 - OS Windows 10 Professional ver 10.0.1945 Build 19045 -  Cheers

**Comment by Clavdiv** [comment]
Component placement would be much enhanced if working in LIST mode
