### ISSUE TITLE
Darkmode with Windows 11

### ISSUE THREAD

**Issue by Maro-Mau** [fritzing/fritzing-app#4133]
## Current Behaviour
Text
If you have selected a dark design under Windows 11, the info boxes are displayed in a very dark window when you skim through pins and the like (see screenshot).

**Build:**
(bCD-1901-0-dbdbe34c 2023-12-20) 64 [Qt 6.5.3]

**Operating System:**
<Windows 11>

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
![Bugreport](https://github.com/fritzing/fritzing-app/assets/124598631/823e85fe-8f3b-42a5-a6ec-dd433acc456a)

Text

**Comment by KjellMorgenstern** [comment]
Duplicate of #4109
