### ISSUE TITLE
fritzing-1.0.2-l1901-dbdbe34c-win64_qt6.msi unable to install in Windows 10 64bit

### ISSUE THREAD

**Issue by Gabriele1974** [fritzing/fritzing-app#4134]
## Current Behaviour
Unable to install Fritzing app on Windows 10 64bit

![image](https://github.com/fritzing/fritzing-app/assets/57966306/93fe204c-920a-4341-9aad-cbe1dd8dfd8a)
![image](https://github.com/fritzing/fritzing-app/assets/57966306/484fadd0-4fa0-4a34-b6e6-d28884cb1114)

**Build:**
fritzing-1.0.2-l1901-dbdbe34c-win64_qt6.msi

**Operating System:**
Windows 10 64bit

**Steps to reproduce:**
- Double click on the installer file

## Expected Behaviour
To run installation

**Comment by KjellMorgenstern** [comment]
Can you please add the exact version of Windows?
Many old Windows 10 versions don't get service anymore by Microsoft, and especially older versions (<2016) are problematic. See https://learn.microsoft.com/en-us/windows/release-health/release-information

Also, can you add which architecture you are using (intel or arm?)

**Comment by KjellMorgenstern** [comment]
Not enough information to reproduce this issue. Closing
