### ISSUE TITLE
expand range of electrolytic capacitor capacitance and voltage

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#4142]
## Problem
The capacitance field in Inspector will only accept 4 characters. Someone wanted a 1000uf capacitor (not an unreasonable request!) but you can't create that with this limitation. The pulldown menu is fairly limited but that doesn't really matter if you can manually set larger values, the problem is currently you can't. For instance it wouldn't be unreasonable to want a 40,000 uf capacitor but you can't currently set that. 

![capture](https://github.com/fritzing/fritzing-app/assets/16514277/1017b4c0-8528-4d29-9c8c-41710248690f)

the most you can set is 999u (I actually typed 999uf but the 'f' appears to truncate!) 

![capture1](https://github.com/fritzing/fritzing-app/assets/16514277/00feb231-9181-4140-8840-8dbb5f2bb26b)

you can set the voltage to 100V but again there are apparently only 3 characters available (I typed in 100V but only got100 in schematic) so you can't set 1000V for instance (although you could set 1KV I expect).

![capture2](https://github.com/fritzing/fritzing-app/assets/16514277/0d1be3f9-ae20-42c6-98f5-e163b5d0a430)

I note there is a range limitation that appears when you click on the capacitance value, this (and the number of characters available) are probably what wants to change. A 999,999uf top end would be better in my opinion as 40,000 uf caps are available and should be settable.

![capture3](https://github.com/fritzing/fritzing-app/assets/16514277/64e1f117-8ce7-460c-8cb5-e0a09f3afb31)

voltage has a similar limitation in number of characters and values although the listed range is much higher. Again more available characters would in my view be desirable to allow larger values. 

![capture4](https://github.com/fritzing/fritzing-app/assets/16514277/368320d4-8ac5-4efd-96ee-8177184e136a)

## Proposed Solution

Is inline with the current state above.

**Comment by failiz** [comment]
Duplicate of https://github.com/fritzing/fritzing-app/issues/1943

**Comment by failiz** [comment]
Workaround is to use engineering notation: e.g. 10m

**Comment by vanepp** [comment]
Issue #1943 covers this better so I will close this in favor of that.
