### ISSUE TITLE
La carga falló con el código de salida -1, 0

### ISSUE THREAD

**Issue by ILordC** [fritzing/fritzing-app#4145]
Es primera vez usando este programa fritzing y quería simular el Arduino para encender un let pero al momento d ejecutar el código me sale el siguiente error. "Ejecutando D:/Programas/Arduino IDE/Arduino IDE.exe --board arduino:avr:uno --port \\.\COM4 --upload C:\Users\Usuario\Downloads\prueba xxxx_TMP\prueba xxxx_TMP.ino
La carga falló con el código de salida -1, 0". No se a que se deba, Acepto todo tipo de ayuda .
![Captura de pantalla 2024-05-12 222817](https://github.com/fritzing/fritzing-app/assets/169631715/a304f07d-23b5-4d6c-a1d3-867274ab691a)

**Comment by failiz** [comment]
Duplicate of #4010.

Usa Arduino 1.8 en vez de arduino 2.x. Si estas en Windows, selectiona arduino_debug.exe mejor que arduino.exe. Mira  #4011

**Comment by KjellMorgenstern** [comment]
Closing in favor of #4010
