### ISSUE TITLE
label text unreadable in breadboard view

### ISSUE THREAD

**Issue by itsmeyaboi-debug** [fritzing/fritzing-app#4152]
## Current Behaviour
the label text is almost unreadable when dark mode is turned on

![image](https://github.com/fritzing/fritzing-app/assets/72557785/a5b083ea-b9f5-42fb-8163-6fe7b9631f43)

**Build:**
Version 1.0.2  (bCD-1901-0-dbdbe34c 2023-12-20) 64 [Qt 6.5.3]

**Operating System:**
Windows 11

**Steps to reproduce:**
windows is set to dark mode
## Expected Behaviour
text should maybe be white instead of black when dark mode is enabled

**Comment by failiz** [comment]
I think this was fixed in 1.0.3. could you try that version?

**Comment by itsmeyaboi-debug** [comment]
you're right! i missed that new update
