### ISSUE TITLE
ERROR WITH THE SIMULATOR

### ISSUE THREAD

**Issue by AlexVital3** [fritzing/fritzing-app#4159]
## Current Behaviour
Text
<please attach a screenshot if possible>
<please attach a Fritzing file if possible. To attach it, change the extension of the file from fzz to zip (e.g., bug.zip instead of bug.fzz)>

**Build:**
<e.g. Version 0.9.3 (b5c895d32 2016-04-19) Cocoa [Qt 5.12.2]

**Operating System:**
<Windows 10>
![SIMULADOR NO ESTA](https://github.com/user-attachments/assets/4876bc18-8fc3-4834-9478-079a8bdd3c96)

**Steps to reproduce:**
- Step 1
- Step 2

## Expected Behaviour
Text

**Comment by failiz** [comment]
Please, state what's the problem and the version that you are using. There is no enough information in this bug report and we will close the issue if you don't add more info soon.
