### ISSUE TITLE
User can't find his login

### ISSUE THREAD

**Issue by DJLAWOLF** [fritzing/fritzing-app#4168]
the reason is that if I paid for the 2023 version of fritzing why do i have to pay for the app again and there is a update option to and dose not work stop scamming us u will be hearing from my lawyer and im being for real here is my email xxx

Edit: redacted private information

**Comment by KjellMorgenstern** [comment]
Thank you for your feedback. We take all user concerns seriously. However, GitHub Issues is not the appropriate channel for customer support or legal matters. We've reached out to you directly via email to address your concerns.

For all users: If you experience any issues with Fritzing, please contact us through our official support channel at fritzing.org/contact. We're here to help.

This issue will be closed as it's not related to Fritzing's codebase or documentation.
