### ISSUE TITLE
Error (Bad Function Call)

### ISSUE THREAD

**Issue by cwison56** [fritzing/fritzing-app#4176]
## Current error_ Fritzing caught an exception from simulationButton in event 3: bad_function_call.

screenshot
![image](https://github.com/user-attachments/assets/9a4ce323-ebd5-4924-91e6-7ec00bda4459)

All files crash when given command to simulate and program then exit/close

**Build:**
Fritzing 1.0.1

**Operating System:**
Linux OS - Ubuntu 24.01 1 LTS

**Steps to reproduce:**
- Step 1 goto open example; select file to open xxx.fzz (Potentiometer)
- Step 2 select file to run; press simulate

## Expected Behavior
Run simulator without crashing

**Comment by KjellMorgenstern** [comment]
Please try our latest official version, Fritzing 1.0.3 from https://fritzing.org .

**Comment by cwison56** [comment]
Thanks for the suggestion.
________________________________

**Comment by cwison56** [comment]
Now, Fritizing 1.0.3 is running, why won't it run the simulation? When I press simulate button nothing happens! Help.

**Comment by failiz** [comment]
Try one of the examples of the simulator. Examples->simulator. 
The simulator is quite basic at the moment. See it's current capabilities here: 
https://blog.fritzing.org/2022/06/27/Simulating-Circuits-with-Fritzing

**Comment by cwison56** [comment]
Thanks for the information. I have reviewed some of the tutorials only to find "sim" doesn't run/operate beyond its basic programming as you stated. Thank you.

**Comment by failiz** [comment]
From 1.0.3, you can try transitory simulations if you start Fritzing from the command line with the -d argument.
If you do that, you can try these examples:
https://github.com/fritzing/fritzing-app/tree/develop/sketches/core/Simulator/EN/trans

**Comment by cwison56** [comment]
I'm trying build a smart robot car using Uno, L298n, HC 05, with servo for ultrasonic sensor. I will just manually test all components to learn these Arduino programming. Thank you for your suggestions and ideas.

**Comment by yanlenner** [comment]
Hi there
