### ISSUE TITLE
pcb view fabricate icon no longer displays cost

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#4183]
## Current Behaviour

The  pcb view fabricate button no longer displays the cost of the board in a window.

See forum post for the issue. Looks to have stopped working (which may be intentional!) with version 1.0.0

(https://forum.fritzing.org/t/fabricate-costs/25160)

**Build:**
Version 1.0.3 
(bCD-1995-0-a7811ba0 2024-05-30) 64 [Qt 6.5.3]

**Operating System:**
Windows 10

**Steps to reproduce:**

see Current Behaviour

## Expected Behaviour

Display cost as 10.2 did unless the deletion was intentional.

**Comment by KjellMorgenstern** [comment]
This might be a problem with the configuration. 
If you press the button sub-menu, see if any Fab is selected. I just observed that no Fab was selected.

![image](https://github.com/user-attachments/assets/016c1195-b17a-45ff-8c11-d8abf01ffc2f)

The price estimation currently only works with the Aisler Fab.

Related to this:
Once you upload a project, Fritzing will remember the link it was uploaded to, and with that, it will also remember which fab you used, so you can easily update your project. This is stored in the "recently opened" list, not in the project itself. A symbol and the Fab name next to the sketch name indicate this in the Welcome View. The Fab name there is a link to your uploaded project:
![image](https://github.com/user-attachments/assets/8d78526c-a5b2-40fa-b313-b20f0de4b84e)

**Comment by vanepp** [comment]
That indeed resolves the issue, I'll close this ticket. Thanks!
