### ISSUE TITLE
Only parts in the selected layer can be select

### ISSUE THREAD

**Issue by tiramisu376** [fritzing/fritzing-app#4186]
## Problem
For example, if want to change the position of a part label while the lower layer is displayed, dragging the part label will select the part placed on the upper layer and drag it, resulting in unintended part movement.

## Proposed Solution
Would like to be able to select only the parts in the selected layer.

**Comment by KjellMorgenstern** [comment]
View from above and below
![image](https://github.com/user-attachments/assets/e3781857-2f16-4fd1-baa9-b05e1ee2e3a2)

already is independent from clickable layer.
![image](https://github.com/user-attachments/assets/b3684ab0-40e5-4c5f-9868-2722eb251def)
