### ISSUE TITLE
1.0.4 release on Win 10 appears broken.

### ISSUE THREAD

**Issue by vanepp** [fritzing/fritzing-app#4187]
## Current Behaviour

I installed the released version of 1.0.4 over 1.0.4B1 and the release version doesn't create a Fritzing icon on the Desktop (which is easily fixable) and doesn't associate the .fzpz of .fzz files with Fritzing (which as far as I can see isn't user fixable!) 

This is the file associations with 1.0.4B1 loaded (where they are correct) 

![bug1](https://github.com/user-attachments/assets/6e71207b-265a-4bcb-9bf1-5f8cd8121884)

and the desktop with the Fritzing icon

![bug2](https://github.com/user-attachments/assets/bc378ab1-d24e-4506-b2f9-420b448deaf3)

so uninstall 1.0.4 release

![bug3](https://github.com/user-attachments/assets/8c80ed70-cf7c-45bd-8fd2-d0d125a4349c)

and reinstall 1.0.4 release (with installer logging enabled)

![bug4](https://github.com/user-attachments/assets/c4e9f092-7e45-4deb-a078-a14de3a6d43c)

accept the defaults (as I usually do) 

![bug5](https://github.com/user-attachments/assets/28854468-270a-4a4a-bf77-2f51ef9bfff0)

![bug6](https://github.com/user-attachments/assets/32b58962-194f-4b20-b209-75a0c47f7ea3)

![bug7](https://github.com/user-attachments/assets/4d6b10f9-545e-4044-82db-d3f893ff1e3e)

![bug8](https://github.com/user-attachments/assets/70034aab-e329-4da4-abf1-d1a87f9ab483)

![bug9](https://github.com/user-attachments/assets/50dbee11-5bb0-4fdc-8ada-efdd524a18ec)

![bug10](https://github.com/user-attachments/assets/2ff4451f-c6a4-4ed4-b725-76210f54b4f9)

![bug11](https://github.com/user-attachments/assets/6ee86d08-6974-4deb-9d3d-5c8d6e7e8d7e)

![bug12](https://github.com/user-attachments/assets/ad297484-29ff-48a5-b826-95f2ae481991)

![bug13](https://github.com/user-attachments/assets/bcfc64e8-c09f-47ee-a3ba-a19aebd19ccd)

![bug15](https://github.com/user-attachments/assets/a5e65c45-6c47-4a86-8f24-6bc47b6b0366)

![bug16](https://github.com/user-attachments/assets/b89338bf-ff09-4b70-84b1-1ba5222bf211)

It loads and works correctly (except for the lack of the desktop icon and the file associations.
reloading 1.0.4B1 restores correct operation as far as I can see (as does falling back to 1.0.3)

![bug17](https://github.com/user-attachments/assets/bd27de17-0275-4611-854e-41e343f0557a)

Here are the installer log files from a 1.0.3 install both in a zip file in case that helps.

[install-logs.zip](https://github.com/user-attachments/files/17358825/install-logs.zip)

**Build:**
Version 1.0.4 
(CD-2065-0-a8c6ef7c 2024-10-07) 64 [Qt 6.5.3]
**Operating System:**
Windows 10

**Steps to reproduce:**

See  ## Current Behaviour

## Expected Behaviour

Adds the desktop icon and associates the Fritzing files.

**Comment by failiz** [comment]
I also just noticed that Fritzing 1.0.4 cannot be found when I click the start windows button and type Fritzing. This used to work before, and it is probably caused by not adding a shortcut in the start menu.
![{37FE5E5D-59B1-4B53-B82D-56ECE68D971E}](https://github.com/user-attachments/assets/53903d4b-b08e-4f61-b2e8-02abbd7398bf)

**Comment by KjellMorgenstern** [comment]
The only difference between build 2051 and 2065 is that they are bundled with a different version of the installer:
fritzing-1.0.4-l2051-a8c6ef7c-win64_qt6.msi
fritzing-1.0.4-l2065-a8c6ef7c-win64_qt6.msi

You mentioned 1.0.4b1 . That version is not increased for each build, but it likely is
build 2049 ( fritzing-1.0.4rc2-l2049-904f8559-win64_qt6.msi ) or 
build 2046 ( fritzing-1.0.4rc1-l2046-1717c0a0-win64_qt6.msi )

Can you try again if installing build 2051 works? It should show up as Fritzing 1.0.4, too (not beta or release candidate).

I would then replace the current public build 2065 with the 2051 build. 

Edit: Also, of course, I'll see if I can fix the configuration for the the new installer version, and then upload another build to staging.

**Comment by vanepp** [comment]
I had reinstalled 1.0.4 release (The rc I am using looks to be build 2049 as the about box calls it rc1CD-2049-904f8559 2024-10-02 rather than fritzing-1.0.4rc2-l2049-904f8559-win64_qt6.msi but I assume the commit number is the important part.) After unistalling 1.0.3 and reinstalling 1.0.4 last night, it acted the same. I just now started the install again (with Version 1.0.4 (CD-2065-0-a8c6ef7c 2024-10-07) 64 [Qt 6.5.3] already loaded) and selected repair, but it didn't add the shortcut or the file associations.

**Comment by KjellMorgenstern** [comment]
I have replaced build 2065 with build 2088.  This should fix creating the shortcuts and file associations on windows.

If directly installed over an existing 2065 build, it will not replace the executable (it will still report as 2065 in the About dialog). But this second install should add shortcuts and, after the first start of Fritzing, the associations.

If you don't want to have this kind of "repaired" installation, you can uninstall Fritzing 1.0.4 build 2065 first, and then install Fritzing 1.0.4 build 2088.

**Comment by failiz** [comment]
With the new version, I can find the Fritzing when typing Frit... in the start button.

**Comment by vanepp** [comment]
Looks like the new release fixes the problem. I just installed and tested it and everything now appears to work fine in terms of file associations:

![capture](https://github.com/user-attachments/assets/9a7f0848-5a50-43d3-8079-e30f4d567958)

and .fzpz and .fzz files load in Fritizng when double clicked on so I will close this ticket as resolved. Thank you!
