### ISSUE TITLE
Version branch for 1.0.4?

### ISSUE THREAD

**Issue by knyipab** [fritzing/fritzing-app#4190]
I believe that it would be necessary to have at least branch for version (e.g. 1.0.4 this time), if not a tag. Otherwise users will need to go through your commit history to find a specific a version.  

You know... There are #4047 and #4086 to request tag. That is particularly relevant for platform that cannot use the binary file on your official website, including Termux, MinGW, etc. Otherwise some linux distro will always stuck in the old 0.9.6 (your latest tag). See this on repology: https://repology.org/project/fritzing/versions.

**Comment by knyipab** [comment]
Unlikely to be fixed under the fritzing's current policy.

**Comment by Kreijstal** [comment]
Nooooo
