### ISSUE TITLE
Search typing not visible

### ISSUE THREAD

**Issue by IshitBhargava** [fritzing/fritzing-app#4193]
## Current Behaviour
Text
<please attach a screenshot if possible>
<please attach a Fritzing file if possible. To attach it, change the extension of the file from fzz to zip (e.g., bug.zip instead of bug.fzz)>

**Build:**
<e.g. Version 0.9.3>

**Operating System:**
<Windows 11>

## Expected Behaviour
The typing box doesn't work because it is not visible

**Comment by KjellMorgenstern** [comment]
Fritzing 0.9.3 is outdated. If the issue persists with the most recent official build from https://fritzing.org, please reopen the issue.
