### ISSUE TITLE
Horizontal scrolling via horizontal mouse wheel not supported

### ISSUE THREAD

**Issue by git4-me** [fritzing/fritzing-app#4199]
## Problem
I can use the normal (vertical) mouse wheel to scroll up and down. When turning the horizontal wheel on the mouse, nothing happens.

## Proposed Solution
Have the horizontal scroll wheel scroll left-right would be good. I'm using the Logitech MX Master 3S on a Mac.

**Comment by KjellMorgenstern** [comment]
In the preferences, there are four different options to interpret wheel and gestures. Can you check which one you are using, and if one of the other options works?

**Comment by KjellMorgenstern** [comment]
I got a mouse with horizontal scrolling and tried this. It works in "pure" and in "guess" mode out of the box.
Since there is no further information about the Fritzing version and configuration, I'll close the issue.
