### ISSUE TITLE
Unable to open the Inspector panel

### ISSUE THREAD

**Issue by JonSearle120** [fritzing/fritzing-app#4201]
Hello, I am a new user, still trying to find my way around the application.  I have created a simple design on a stripboard with a corresponding schematic, when I started I could see and use the Inspector panel at the bottom of the parts panel but now it has disappeared. I cannot find anything in the help sections to advise how to get it back, I have shut down and reopened the app and closed and reloaded my design, both with no success.  I'm afraid I may have deleted it by accident, I moved it off the screen using the mouse thinking I could find it and move it back, but its gone.  How can I regain my access to the Inspector panel?  This situation arose because I wanted to resize the stripboard but without access to the Inspector panel this is not possible.

Thankyou in anticipation of your help.

**Comment by failiz** [comment]
Try to use the view or window menu. You can enable the Inspector view there. You probably closed it accidentally.

**Comment by KjellMorgenstern** [comment]
![image](https://github.com/user-attachments/assets/f7a4422c-978d-4a39-a047-e7c9273ae27d)


Besides the Window menu, a less known option is the context menu of the menu bar. Just right click anywhere on it:

![image](https://github.com/user-attachments/assets/19907c04-a6f6-455e-b70c-301c20c7b9c9)

**Comment by JonSearle120** [comment]
Thankyou for your prompt reply.  Is the Context menu the drop-down list that appears when I select the Window tile in the menu bar?  If it is, I have done that and I see a drop down menu in which I can select; Minimize, Parts, Inspector, Undo History, and Layers.  Below is a link to a picture of my screen, you can see that I have selected Parts and Inspector, and the untitled sketch showing the problem.  I can see the Parts panel but not the Inspector panel which used to appear below the parts panel.  I have scrolled to the bottom of the Parts panel to  illutrate this.  Sorry to have to ask for further help, being a very new user I am very grateful for any advice.

Thankyou.
![Fritzing problem](https://github.com/user-attachments/assets/bb585f32-baaa-408a-9668-67d977013f1d)

**Comment by JonSearle120** [comment]
Further to my last post,  I've got it back!  Whatever I did I've now undone and so far it all seems to be working again.  Onward and upward, thankyou for your help.

Kind regards
