### ISSUE TITLE
algorithm for sorting values in part properties

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#427]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 29, 2008 09:37:44_

The resistors are sorted not by value, but alphabetic. This means that a
220 Ohm Resistor is under a 1k Resistor.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=427_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
