### ISSUE TITLE
"tidy up wires" function for schematic view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#439]
_From [brendan....@gmail.com](https://code.google.com/u/110718573451811856532/) on January 05, 2009 14:19:43_

would be really nice to have a "tidy up wires" function in the schematic
view.  This would go through each wire and attempt to re-position the bend
points so that all wires are at 90-degree angles.  If this is not possible,
add an additional bend point (or two?).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=439_

**Comment by failiz** [comment]
I think that we should change how to add wires in order to produce better schematics from the beginning, instead of tidying up after they are placed. There is an issue to create 90 degrees bends, I would recommend to close this issue
