### ISSUE TITLE
swapping a part with a different leg span should disconnect it from the breadboard

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#450]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 07, 2009 10:55:16_

have to pop the part out of the breadboard and reconnect it with wires, or
if the part has bendable legs...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=450_

**Comment by failiz** [comment]
I only found an issue with when changing from a bipolar to a unipolar stepper motor. Then, two of the wires are connected together.
Remove imported label.

**Comment by KjellMorgenstern** [comment]
Closing in favor of #3922
