### ISSUE TITLE
"Made with Fritzing" badge

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#479]
_From [brendan....@gmail.com](https://code.google.com/u/110718573451811856532/) on January 15, 2009 13:36:27_

We need some nice PNG and SVG badges that users can put on their own web
sites and project docs to link back to fritzing.org.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=479_

**Comment by failiz** [comment]
Not code related. And the logo is in the exported images.

**Comment by failiz** [comment]
Ping
