### ISSUE TITLE
The author of a part should have a url

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#483]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on January 16, 2009 12:05:08_

The author tag in the part file should have a url property. The url should point to the makers home 
page or the makers page on fritzing,org.
This information should be displayed in the inspector.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=483_

**Comment by KjellMorgenstern** [comment]
Won't fix.
