### ISSUE TITLE
In the inspector it should show the modification date of the part, instead the version

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#486]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on January 16, 2009 12:18:20_

Since there is not an active system in place to keep incrementing the part version numbers, we can 
better display the modification date there.

On a similar topic, two other suggestions. If we think they are relevant, we should make separate 
issues out of these:
- update the version numbers of all parts (since we changed them so much over the last revisions)
- have the parts editor automatically up the version number by a minor when you save the part (or 
  ask the user specifically, which will be annoying)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=486_

**Comment by failiz** [comment]
Still not implemented, but not sure if this is the right way. Versions sound more friendly that modification date. Maybe, we should tag the versions of the parts with the release? Or increase the version number automatically when pushed to the repository?

**Comment by KjellMorgenstern** [comment]
I agree, automatically increasing versions could be a good feature.
This is mitigated by parts in a git repo. 
I think the date inside the part is also not automatically set. The file modification date on the other hand is quite unreliable.
