### ISSUE TITLE
Support Arduino shields

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#488]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on January 19, 2009 10:46:59_

We need a simple system to support all kinds of Arduino shields, as asked 
for in the mailing list: http://groups.google.com/group/fritzing/browse_thread/thread/44542b1da20584 dd

Some implications to keep in mind:
- some shields can be stacked on top of each other
- the surface of a shield might have to be accessible

Example shields can be found here:
- http://www.arduino.cc/playground/Main/SimilarBoards - http://www.libelium.com/tienda/catalog/index.php?cPath=21 - http://www.liquidware.com/shop The implementation could be held rather simple: We could make them behave 
  like the Arduino itself, and for PCB view they could also show up as 
  separate boards, but without a copper layer.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=488_

**Comment by failiz** [comment]
This has been implemented. Close it?
