### ISSUE TITLE
all qobjects emit a "destroyed" signal...might be nice to use this as a way to clean up cached references

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#516]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on January 21, 2009 10:39:37_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=516_

**Comment by failiz** [comment]
This was set to PartlyDone. Is it still relevant?
