### ISSUE TITLE
Some nice way to turn off and on all labels.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#547]
_From [brendan....@gmail.com](https://code.google.com/u/110718573451811856532/) on February 03, 2009 10:11:41_

Labels are nice but sometimes they get in the way.  Sometimes you just need
a quick switch to turn the global label visibility on or off.  Turning them
on and off individually is annoying.  Doing select all and then turning it
on is less intuitive and you end up cluttering up the screen with labels
for wires (which normally don't need labels).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=547_

**Comment by failiz** [comment]
The labels of the wires are not shown and the part labels can be toggle on/off in the view menu and layers menu. Outdated?
