### ISSUE TITLE
z-order problem with arduino in pcb view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#562]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 07, 2009 17:26:11_

drag an led onto the sketch
drag an arduino onto the sketch
drag another led onto the sketch

go to pcb view and, if they're not already there, position the leds on the
arduino

now move the mouse over the two leds.  the second led responds to hover
events; the first led does not.

this is because the arduino's copper layer svg is actually above the first
led in the z-order, even though the arduino's copper layer svg is mostly
invisible.  

the workaround is to select the arduino, and then use the send-to-back menu
item.

afix could choose one of several approaches:
1. figure out the real clickable shape of the ardiuno (and all the other
   parts, for that matter).  This would involve parsing the part svgs and
   converting them to QPainterPaths (something we have also discussed as one
   approach to pouring ground planes-- issue #58 ).  We know how to do this with
   a certain subset of SVG elements, but it gets tricky when anyone can add a
   part.
2. always slam parts that are boards to the lowest z value in their layer
   (though this gets tricky if there are multiple boards, or when someone
   chooses "send to back" on a non-board part). 
3. have a special sub-copper layer for boards--it counts as a copper layer
   when exporting, or hiding/showing layers, but has its own separate range of
   z-values.  the label layer in pcb view already works this way.  This
   prrobably requires a change to the arduino fzp file.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=562_

**Comment by failiz** [comment]
I cannot replicate this in 0.9.4 (Windows)

**Comment by KjellMorgenstern** [comment]
r2379 is not available anymore to check if something is missing. Seems to work, so we can close it.
