### ISSUE TITLE
Fritzing mailing list

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#567]
_From [jenn...@gmail.com](https://code.google.com/u/118211363250187816324/) on February 09, 2009 11:46:52_

we should implement a mailing list to send out information about major
releases, other news and events

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=567_

**Comment by failiz** [comment]
Is this in the pipeline? If so, remove the imported label.
