### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#584]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 17, 2009 13:09:23_

We've been meaning to check the codebase for memory leaks pretty much from
the beginning of the project.  Our original plan was to use Valgrind under
Linux. But it turns out visual studio offers a reasonable (if obscure)
toolset for finding memory leaks, and I've set it up so that if you're
running fritzing from Windows Visual Studio, Debug mode, it will generate a
memory leak log when you quit fritzing.

Most of the biggest "memory leaks" in Fritzing were benign--that is, we
create a whole bunch of objects at startup, and those remain with the
program until the end--so it was never really necessary to directly delete
them.  However, in order to use the windows toolset, those benign objects
had to be deleted, because the toolset couldn't tell the difference (and it
made the log too big to wade through).   

Since then, Mariano and I have already plugged a number of leaks, but we
haven't gone through the entire program yet, so this issue is a reminder to
finish the process.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=584_

**Comment by KjellMorgenstern** [comment]
To generic, quite some leaks have been fixed since 2009, time to close this.
