### ISSUE TITLE
grouping

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#586]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on February 19, 2009 01:48:44_

There have been several requests for this feature, and it looks like nearly
all grouping behavior would have to be implemented for modules, so adding
this as an issue at low priority

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=586_

**Comment by KjellMorgenstern** [comment]
Original description not available anymore
