### ISSUE TITLE
selecting more than one part and then right clicking deselects parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#598]
_From [jenn...@gmail.com](https://code.google.com/u/118211363250187816324/) on February 25, 2009 10:31:34_

What steps will reproduce the problem? 1. I selected 3 leds
2. Then i tried a "right click" to rotate them
3. Only one remained selected What is the expected output? What do you see instead? I would expect all the parts to stay selected so that i could use the right
click menu to perform actions on them.  I thought that i was able to do
this previously, but maybe not.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=598_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
