### ISSUE TITLE
Notes - cursor should NOT change into cross hairs when note is moused over 

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#602]
_From [jenn...@gmail.com](https://code.google.com/u/118211363250187816324/) on February 26, 2009 10:10:56_

Currently the cursor changes to the cross hairs when you mouse over a note,
but it should remain a pointer.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=602_

**Comment by KjellMorgenstern** [comment]
No problem in 0.9.4 with ubuntu 18.04 or MacOS Catalina
