### ISSUE TITLE
More options for Notes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#620]
_From [jenn...@gmail.com](https://code.google.com/u/118211363250187816324/) on March 11, 2009 08:23:41_

This is low priority, but it would be nice if i had more options for Notes
- perhaps bold, italic text, but also the ability to make text hyperlinked
  as i've been using the notes to point to pages on the web.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=620_

**Comment by MikeMitterer** [comment]
Can you please reopen this issue.
I just tried it on Mac - it doesn't work anymore. It's also a bit strange that you mark a hidden feature as "solved". In my opinion it would be very! useful to have e.g. links in notes so that I can link to data-sheets or so.
