### ISSUE TITLE
connector names not consistent for some parts

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#629]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on March 22, 2009 12:35:33_

Electrolytic and ceramic capacitor use different names for connectors, so
connections are disconnected when swapping between instances of these two
types.  There are probably other cases of mismatching names, but this is
all I've found so far.  Transistors, resistors, and LEDs seem ok.  

BTW, is it correct that when swapping transistors there are three choices
"NPN", "pnp" and "npn"?

And when matching connector names for swapping, should the match be case
sensitive or case-insensitive? Currently it's case-insensitive.

I've attached a text file that lists all the parts and their connector names.

**Attachment:** [connectorNames.txt](http://code.google.com/p/fritzing/issues/detail?id=629)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=629_

**Comment by KjellMorgenstern** [comment]
NPN and PNP seem now in upper case
Switching from electrolytic to ceramic is not possible, classes differ : unidirectional / bidirectional
