### ISSUE TITLE
if you drag a wire end onto the breadboard, always connect to something

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#641]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on May 04, 2009 14:19:09_

In other words, don't allow a wire end to be unconnected when you release
it on a breadboard.  Is there a more general idea here, or does it only
apply to the breadboard.  Could this be a grid alignment function, or could
we add a notion of 'gravity' to connectors?

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=641_

**Comment by KjellMorgenstern** [comment]
As of version 0.9.4 it is not possible to drag a wire onto the breadboard in between holes, without it snapping. Gravity is there, and the corresponding hole is highlighted before. 
It is possible to drop on the wider areas, but there it is easily visble as dangling wire -> Closing
