### ISSUE TITLE
Redesign inspector panel

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#666]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 22, 2009 06:38:43_

The inspector panel currently wastes a lot of space due to its information 
architecture and also its visual design. There are already sketches and ideas 
for this, but they need to be finalized.

(This probably goes hand in hand with a need for re-implementation, since the 
WebKit approach proved too cumbersome to maintain.)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=666_

**Comment by failiz** [comment]
This issue was partly done nine years ago, the specification is not available now and it could be outdated (are we still using WebKit?).
