### ISSUE TITLE
Integrate Octopart Search API

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#675]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on May 26, 2009 06:04:58_

In the online parts reference, it would be nice to integrate this search for 
vendors: http://octopart.com/api/ A datasheet search like http://www.datasheetarchive.com would also be 
convenient.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=675_

**Comment by failiz** [comment]
Not sure what is the "online parts reference". Maybe it is outdated as it's marked as a website related.
If this is in the pipeline, remove imported label. If not, close it.
