### ISSUE TITLE
rotating a part doesn't rotate its label

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#684]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 01, 2009 10:58:20_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=684_

**Comment by failiz** [comment]
The labels still not rotate in the BB view when moving a part in 0.9.4. I think the labels should rotate when moving the part. However, the label should be always readable (the text should be horizontal and be able to read it from left to right or vertical and from bottom to top). Kicad labels are always horizontal, when you rotate a part. I think that having this as an option in the preferences menu is a lot of overhead for a minimal improvement. I would try to implement a good behaviour that works for most of us and not try to make everybody happy as the labels can still be changed manually. 
As a side note, I think that implementing hotkeys for rotating (parts or labels) could save a lot of time. Implementing the same ones as Kicad will make them easy to use for the users.

**Comment by failiz** [comment]
My PR #3874 fixes this issue

**Comment by KjellMorgenstern** [comment]
Now, with #3874, it will be so easy to rotate the label, that we don't need to rotate it along and keep Fritzings behavior, that the orientation stays readable by default?

**Comment by failiz** [comment]
I am not following you...
#3874 has a couple of fixes. Add shortcuts to rotate and flip a part and keeps the labels readable. 
Regarding the shortcuts, they rotate a part. It is not possible to rotate just the label. That needs to be done with the right click contextual menu. 
One option would be not to rotate the label when rotating a part, but this would break the current behavior (except in bb view, but the labels are hidden by default in bb view). In Fritzing, when rotating a part, it rotates the label.

**Comment by KjellMorgenstern** [comment]
So, you did not change the default rotation behavior in BB nor in the other views?

**Comment by failiz** [comment]
I changed the behavior of the BB view to have the same behavior as the sch and PCB. I thought that it was odd to have different behaviors. And I took the sch and PCB one as the default as it is where you see the labels by default.

**Comment by failiz** [comment]
This is the current behaviour in Firtzing 0.9.9 when rotating a part.

Schematics:
![Untitled Sketch_schem0](https://user-images.githubusercontent.com/5708642/145779235-f0eec301-98ee-4c4c-930e-070c829acb5f.png) ![Untitled Sketch_schem45](https://user-images.githubusercontent.com/5708642/145779237-aeaf0b9c-0c0d-4dc6-a9fe-7a0f7541d073.png) ![Untitled Sketch_schem90](https://user-images.githubusercontent.com/5708642/145779238-8c717da6-641f-40bc-9e10-ce11c6c90ef1.png) ![Untitled Sketch_schem135](https://user-images.githubusercontent.com/5708642/145779240-25bcdf09-ebaf-4f87-af92-ef0b59509076.png) 

![Untitled Sketch_schem180](https://user-images.githubusercontent.com/5708642/145779245-144b4ed6-f604-4d4d-94ce-20f02d43b611.png)![Untitled Sketch_schem225](https://user-images.githubusercontent.com/5708642/145779248-b6b73a8a-4131-43c6-a9a3-292873f8107c.png) ![Untitled Sketch_schem270](https://user-images.githubusercontent.com/5708642/145779250-65d1bf6a-37b9-49df-8cf3-5ed78bb3ac44.png) ![Untitled Sketch_schem315](https://user-images.githubusercontent.com/5708642/145779252-02cc95d9-7dec-4fcf-b4c9-d5cf568f27f3.png)

Breadboard:
![Untitled Sketch_bb90](https://user-images.githubusercontent.com/5708642/145779583-17e5233e-401e-427f-9055-7b2cce441e43.png) ![Untitled Sketch_bb135](https://user-images.githubusercontent.com/5708642/145779589-79965124-2031-48d0-9ec6-c2d128f379d1.png) ![Untitled Sketch_bb0](https://user-images.githubusercontent.com/5708642/145779590-3f7253b8-7d0f-49b4-9e40-8d898bb95163.png) ![Untitled Sketch_bb45](https://user-images.githubusercontent.com/5708642/145779591-59051bf7-107c-4c5a-a566-b5bb3c1879f8.png)

PCB:
![Untitled Sketch_pcb180](https://user-images.githubusercontent.com/5708642/145779657-a94bddc8-dbad-4fa9-a244-4b1381509d03.png) ![Untitled Sketch_pcb0](https://user-images.githubusercontent.com/5708642/145779660-d0f7711c-c441-416f-be73-ebe781de2d98.png) ![Untitled Sketch_pcb45](https://user-images.githubusercontent.com/5708642/145779661-e78a0c29-d96a-4800-9e15-8aa348a8ac42.png) ![Untitled Sketch_pcb90](https://user-images.githubusercontent.com/5708642/145779663-79077e9e-c733-47b5-bf22-042f9e516dd3.png)
![Untitled Sketch_pcb135](https://user-images.githubusercontent.com/5708642/145779664-17726813-8fcb-440f-8e31-fe9e0f40ca16.png)

**Comment by failiz** [comment]
From the previous pictures I see a big issue in the schematics. The labels are not readable. When you rotate 180 degrees the part, the label is upside down. And when they are rotated 90 or 270 degrees, the text direction is down to up and up to down. For me, this does not make sense at all as the schematics are supposed to be read with the same orienation always. In fact, when I create schematics in Fritzing, most of my time is spent in rotating the labels after rotating the part. I think that this needs to be fixed and there are two options: (a) Acept my pull request that keeps the labels readable and (b) do not rotate the lables when rotating a part. Both options are ok with me.

A minor issue is that the behaviour of the labels is not constistent across the views. In SCH and PCB, labels are rotated with the parts. In BB view, they are not. I think it would be nice to fix this too, but it is not as important as fixing the label issue in the sch view.

**Comment by KjellMorgenstern** [comment]
I agree with above comment from wapcaplet88 on January 24, 2014 11:20:17:
- it makes sense to rotate the label in PCB (I guess it is about 50/50 there, so we should just keep the current behavior)
- it makes sense to keep the label horizontal in schematic view

**Comment by KjellMorgenstern** [comment]
Also, please note that pin label behavior is again a little different. Pin labels will rotate along with the part, but they will flip before turning upside down. You can see this in failiz schematics example of the resistor rotation in Fritzing 0.9.9 above.

**Comment by failiz** [comment]
Regarding:
 Minor: When rotating a complete breadboard, should labels be rotated along?
 Should label rotation behavior be made an option in the preferences? (I tend towards not doing this)
I do not think that they should be implemented, at least for now. My main issue was the schematic view behaviour.
