### ISSUE TITLE
vector based ground plane extraction method?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#702]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 08, 2009 01:36:10_

There may be a way to stay in vector space:
1. convert the board outline SVG to a filled QPainterPath
2. use renderSVG() to make a single svg from all the parts inside the board  
   (one issue would be clipping parts that aren't all the way inside the board 
   outline, butI would say ignore these)
3. subtract 2 from 1 to get a new painter path

It would be nice if we could go directly from the subtracted painterpath to 
a new groundplane part without first saving it as an fzp/svg and reloading 
it--it would save two conversion steps: painterpath to svg to save and svg 
back to painterpath to reload.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=702_

**Comment by failiz** [comment]
Is this still in the pipeline?

**Comment by KjellMorgenstern** [comment]
The issue description is quite implementation specific... and the implementation has changed a lot since 2009. I think we can close this "stay in vector space" issue in favor of #3185 .
