### ISSUE TITLE
interesting stuff happens when you paste formatted stuff into notes

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#711]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 10, 2009 09:25:40_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=711_

**Comment by KjellMorgenstern** [comment]
Still an issue 0.9.5dev g29b8f5d3
![image](https://user-images.githubusercontent.com/6494025/73532096-3c51fa80-441c-11ea-99c0-920b467df4b4.png)

**Comment by failiz** [comment]
Remove imported label

**Comment by KjellMorgenstern** [comment]
This looks much more sane now. Tested on macOS 11.4:

![image](https://user-images.githubusercontent.com/6494025/125401490-867e3000-e3b3-11eb-94ee-68c2b0dfae10.png)
