### ISSUE TITLE
From the forum: export issues (mostly with illustrator)

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#713]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 12, 2009 17:22:29_

I have been trying to draw diagrams of a simple circuit, but I have 
problems about exporting as follows:

PDF: Looks fine with Preview.app and Adobe Reader 9.1.0, but looks garbaged 
when opened with Illustrator CS3
SVG: Wires looks too thick when opened with Illustrator CS3
PS: Mysterious black rectangles appear with Preview.app and Illustrator CS3 http://dl.getdropbox.com/u/36239/fritzing_report_2009-06-11.zip I'm sorry if my data is wrong, but I'd like to report here just to make 
sure.

Fritzing 2009.06.02 Mac OS X 10.5.7 Illustrator CS3

Best, Shigeru

Posted 7 hours

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=713_

**Comment by KjellMorgenstern** [comment]
Original information is not available anymore. There have been quite a number of changes to SVG handling and PDF export. Closing.
