### ISSUE TITLE
undo after a note is resized doesn't work consistently

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#722]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on June 17, 2009 10:39:09_

This happens after a plain resize operation, or after a text input that 
results in a resize.  In some but not all cases, the undo doesn't restore the 
note to its previous size.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=722_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
