### ISSUE TITLE
website - relative image source path does not work

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#733]
_From [cont...@airpiano.de](https://code.google.com/u/115638533122043274614/) on June 24, 2009 09:39:52_

the photos on these pages does not show up: http://fritzing.org/learning/tutorials/creating-custom-parts/parts-editor/using-svg-images-new-parts/ http://fritzing.org/learning/tutorials/creating-custom-parts/parts-editor/fritzings-graphic-standards/ this problem is actually not new, it just happens once in a while...

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=733_

**Comment by failiz** [comment]
From the old website, I doubt that this is relevant now.
