### ISSUE TITLE
Change part properties through context menu

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#754]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on July 02, 2009 07:06:04_

We have this now for changing the color of a wire (right-click a wire), but 
for consistency and convenience it would of course be nice to also get this 
for all other properties, i.e. for part swapping.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=754_

**Comment by failiz** [comment]
If this worth it? You change the colour of the wires very often. Not so much for parts. And there are some with lots of properties

**Comment by KjellMorgenstern** [comment]
I think that can only be decided for each property and part.
