### ISSUE TITLE
Revise color preferences UI

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#777]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on August 24, 2009 06:51:17_

Fritzing now has preference settings for background colors and selection 
highlight colors.
Their UI needs to be improved..

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=777_

**Comment by failiz** [comment]
The issue does not specify how the UI should be improved and the link is gone.
