### ISSUE TITLE
store user name and password in the preferences.

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#782]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on August 25, 2009 10:10:31_

marking this low priority until the infrastructure is ready for it.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=782_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
