### ISSUE TITLE
convert trace or ratsnest to jumper item or via

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#796]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 02, 2009 08:17:34_

unexpected result if the trace has a bendpoint that connects to multiple 
other traces (i.e. you get one jumper and you probably need n - 1 jumpers, 
where n is the number of endpoints which connect to parts).  

Maybe the answer is that you should get a connected set of jumpers (i.e. one 
per wire segment).

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=796_

**Comment by failiz** [comment]
The convert bendpoint to via works well in 0.9.4 (Windows) in junctions of 3 traces. The convert to jumper has been removed from the program. Can someone still replicate this?

**Comment by failiz** [comment]
Ping

**Comment by KjellMorgenstern** [comment]
There are some problems when multiple wires connect at one point. I think this issue might be valid

**Comment by KjellMorgenstern** [comment]
There are no issues converting to via, or connecting many traces to a via.
Big Dots in the schematic still have issues, when multiple wires connect pins from the same part.
However, this is a bug that will be handled in a separate issue.
https://github.com/fritzing/fritzing-app/issues/4178
