### ISSUE TITLE
parts bin search ui needed

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#828]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on September 19, 2009 02:19:31_

We now have enough parts that inspection by eye is no longer sufficient--especially since there are 
multiple bins.  Here's my proposal for a search UI which I think would both be decent for users and 
reasonable to implement, and which could grow eventually into searching our archives on the net.

To access the search, have a type-in search field at the base of the parts bin dock window, between the 
list/icon view icons at the left and the folder/part icons at the right.  For a first pass, the search 
could simply match against anything in all the fzp files (second pass, we could restrict it to certain 
fields like title, properties, tags; third pass could allow AND, OR and other search modifiers in some 
kind of advanced search).  

Search results would appear in a new bin, the Search Results bin, the contents of which could remain 
stable until they were replaced by the next search.  So users could drag parts from the Search Results 
bin just like any other bin, and the contents would be retained when the user quit Fritzing.

What would be nice is if the search ran in the background.  In other words, the search runs while the 
user is free to do other things, and as an individual match is found, it is immediately added to the 
Search Results bin.  So I think we'd need to add an icon to the Search Results bin that would show that 
the search was still under way, and which would give you a way to stop the search.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=828_

**Comment by failiz** [comment]
Old issue that has already been implemented. Close?
