### ISSUE TITLE
mystery part special swapping

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#848]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on October 05, 2009 07:30:20_

mystery part can be swapped for any part with an equal number of pins.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=848_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
