### ISSUE TITLE
Project editing is broken

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#851]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on October 06, 2009 05:13:28_

It seems that people cannot replace an attachment properly.
See http://fritzing.org/projects/motorcycle-computer-based-on-arduino

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=851_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
