### ISSUE TITLE
Make language listing (etc.) easily editable through the web

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#855]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on October 08, 2009 09:58:08_

We've got so many language translations, but don't tell anywhere yet.
The download page would be a good place: Beneath the Download links, above 
history of changes, enter this text:

"Includes these languages: Deutsch, English, Español, Français, Italiano, 
Português (eu), Русский."

By the way, the HTML for these and all other upcoming languages can be found 
here: http://www.mozilla.com/en-US/firefox/all.html

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=855_

**Comment by failiz** [comment]
Is this still an issue? The issue is from 2010 and translations appear in the downloads page...

**Comment by KjellMorgenstern** [comment]
And also in the About dialog in Fritzing, this issue is solved.
