### ISSUE TITLE
Dock Panel doesn't want to go back into the main window when its too wide

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#858]
_From [dirk.van...@gmail.com](https://code.google.com/u/102845219688896911239/) on October 11, 2009 12:57:42_

What steps will reproduce the problem? 1.Drag the parts panel out of the main window
2.Quit Fritzing
3.(Maybe do an update of Fritzing. I don't remember if I had the parts panel outside the main 
window before I upgraded Fritzing ...)
4. Start Fritzing. (The parts panel is not loaded in the main window)
5. Go Window -> Parts to show the parts panel
6. Try to drag the panel back into the main window What is the expected output? What do you see instead? It is expected to see the panels inside the main window make room for the dragged panel from 
outside. Instead the main window does not 'accept' the external parts panel. The panel just stays 
floated above the main window. Please use labels and text to provide additional information. I tried the same with other panels, e.g. the undo panel:
1. drag the undo panel outside the main window
2. quit Fritzing
3. reopen Fritzing (and see the external panels loaded properly)
4. drag the undo panel inside the main window
This _did_ work. Just the parts panel seems not be accepted by the main window

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=858_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
