### ISSUE TITLE
weird selection behavior in bb view

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#914]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on November 16, 2009 12:34:37_

try dragging a selection rect over the lower pair of wires in the attached bb 
view. Why do the wire selections keep toggling on and off?  It happens even 
when you delete one of the wires.

**Attachment:** [energy_remote_v2.fz](http://code.google.com/p/fritzing/issues/detail?id=914)

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=914_

**Comment by failiz** [comment]
Duplicated of 991, which has been fixed. And the file is not available.
