### ISSUE TITLE
since we're adding aspect ratio preservation to logo parts, should it also be added to resizable boards?

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#955]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 05, 2009 18:32:01_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=955_

**Comment by failiz** [comment]
Still not implemented in 0.9.6

**Comment by KjellMorgenstern** [comment]
Is this a demanded feature? I think we can close this.

**Comment by failiz** [comment]
I think it is minor feature and does not look very demanded. I am ok with closing it for now. We can always implement it later if it requested.
