### ISSUE TITLE
fritzing is a memory hog

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#963]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 10, 2009 05:27:41_

my uninformed guess is that fritzing caches every svg it renders.  If so, 
making it an LRU cache might cut memory usage way down without adversely 
affecting performance

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=963_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
