### ISSUE TITLE
when you open a sketch that has obsolete parts, fritzing should offer to replace them

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#971]
_From [irasc...@gmail.com](https://code.google.com/u/104729248032245122687/) on December 18, 2009 07:29:16_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=971_

**Comment by KjellMorgenstern** [comment]
This issue was closed because it is outdated.
If you think this issue is still important for a reason, please open.
