### ISSUE TITLE
Add ability to delete subnets

### ISSUE THREAD

**Issue by davidperrenoud** [fritzing/fritzing-app#989]
_From [andre.knoerig@gmail.com](https://code.google.com/u/andre.knoerig@gmail.com/) on January 29, 2010 11:45:56_

In the case of a multi-wire connection, it currently isn't possible to
split up nets, i.e. detach a subnet from a net.
Add a right-click menu option underneath "Delete": "Delet subnet (Ctrl+Del)"

_Original issue: http://code.google.com/p/fritzing/issues/detail?id=989_

**Comment by failiz** [comment]
I am not sure what is the difference between subnet and net. The definition provided "Subnets are parts of the ratsnest that show up in pcb and schematic view. Each subnet has its own color and shows all the potential/implied connections resulting from a
concrete connection made in any of the views." looks like a net to me...
